libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-features-feature/step-features-feature.spec.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-features/step-features.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/card-cluster-feature/card-cluster-feature.tsx
- Update doc links
- Update default value for `STATIC_IP` 
---
=> chore(cluster-feature): update links

libs/domains/clusters/feature/src/lib/cluster-action-toolbar/__snapshots__/cluster-action-toolbar.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-action-toolbar/__snapshots__/environment-action-toolbar.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-list/__snapshots__/environment-list.spec.tsx.snap, libs/domains/organizations/feature/src/lib/git-token-list/__snapshots__/git-token-list.spec.tsx.snap, libs/domains/service-helm/feature/src/lib/networking-setting/__snapshots__/networking-setting.spec.tsx.snap, libs/domains/service-helm/feature/src/lib/values-override-arguments-setting/__snapshots__/values-override-arguments-setting.spec.tsx.snap, libs/domains/service-helm/feature/src/lib/values-override-files-setting/__snapshots__/values-override-files-setting.spec.tsx.snap, libs/domains/service-helm/feature/src/lib/values-override-yaml-setting/__snapshots__/values-override-yaml-setting.spec.tsx.snap, libs/domains/services/feature/src/lib/last-commit/__snapshots__/last-commit.spec.tsx.snap, libs/domains/services/feature/src/lib/pod-details/__snapshots__/pod-details.spec.tsx.snap, libs/domains/services/feature/src/lib/pods-metrics/__snapshots__/pods-metrics.spec.tsx.snap, libs/domains/services/feature/src/lib/select-commit-modal/__snapshots__/select-commit-modal.spec.tsx.snap, libs/domains/services/feature/src/lib/select-version-modal/__snapshots__/select-version-modal.spec.tsx.snap, libs/domains/services/feature/src/lib/service-action-toolbar/__snapshots__/service-action-toolbar.spec.tsx.snap, libs/domains/services/feature/src/lib/service-list/__snapshots__/service-list-action-bar.spec.tsx.snap, libs/domains/services/feature/src/lib/service-list/__snapshots__/service-list.spec.tsx.snap, libs/domains/services/feature/src/lib/update-all-modal/__snapshots__/update-all-modal.spec.tsx.snap, libs/pages/application/src/lib/ui/page-settings-resources/__snapshots__/page-settings-resources.spec.tsx.snap, libs/pages/cluster/src/lib/ui/page-settings-kubeconfig/__snapshots__/page-settings-kubeconfig.spec.tsx.snap, libs/pages/clusters/src/lib/ui/page-clusters-create/step-features/button-popover-subnets/__snapshots__/button-popover-subnets.spec.tsx.snap, libs/pages/clusters/src/lib/ui/page-clusters-create/step-features/button-popover-subnets/button-popover-subnets.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-kubeconfig/__snapshots__/step-kubeconfig.spec.tsx.snap, libs/pages/services/src/lib/feature/page-helm-create-feature/step-general-feature/__snapshots__/step-general-feature.spec.tsx.snap, libs/pages/services/src/lib/feature/page-helm-create-feature/step-values-override-files-feature/__snapshots__/step-values-override-files-feature.spec.tsx.snap, libs/shared/ui/.storybook/preview.tsx, libs/shared/ui/src/lib/components/button-primitive/__snapshots__/button-primitive.spec.tsx.snap, libs/shared/ui/src/lib/components/button-primitive/button-primitive.tsx, libs/shared/ui/src/lib/components/button/__snapshots__/button.spec.tsx.snap
https://qovery.atlassian.net/browse/FRT-1043
=> feat(ui) add button style plain

libs/domains/services/feature/src/lib/update-all-modal/__snapshots__/update-all-modal.spec.tsx.snap, libs/shared/ui/src/lib/components/inputs/input-checkbox/input-checkbox.tsx, libs/shared/ui/src/lib/styles/components/input.scss
=> fix(input-checkbox): check icon

libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-summary-feature/step-summary-feature.tsx
- Fix Scaleway creation flow
---
=> fix(cluster): remove features from SCW creation

libs/domains/environments/feature/src/lib/environment-list/__snapshots__/environment-list.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-list/environment-list.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1709655659413629
---
=> fix(cluster-badge): add height for icon

libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-summary-feature/step-summary-feature.tsx
https://qovery.slack.com/archives/C02NLAJEYP6/p1709892443078949
---
=> fix(cluster): creation flow K3S

libs/domains/environments/feature/src/lib/environment-list/__snapshots__/environment-list.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-list/environment-list.tsx, libs/domains/services/feature/src/lib/service-list/__snapshots__/service-list.spec.tsx.snap, libs/domains/services/feature/src/lib/service-list/service-list.tsx
=> feat(button-status): update size 14px

libs/pages/settings/src/lib/feature/page-organization-billing-summary-feature/show-usage-modal-feature/show-usage-modal-feature.tsx, libs/pages/settings/src/lib/ui/page-organization-billing-summary/page-organization-billing-summary.tsx, libs/pages/settings/src/lib/ui/page-organization-billing-summary/show-usage-modal/show-usage-modal.tsx
=> refactor(billing): refactor report periods

libs/pages/settings/src/lib/ui/page-organization-members/row-member/row-member.spec.tsx
=> test: fix flaky test

libs/pages/settings/src/lib/ui/page-organization-billing-summary/page-organization-billing-summary.tsx, libs/pages/settings/src/lib/ui/page-organization-billing-summary/show-usage-modal/show-usage-modal.tsx
https://qovery.atlassian.net/browse/FRT-1049
=> fix(billing): fix billing report

libs/pages/cluster/src/lib/feature/page-settings-feature/page-settings-feature.tsx, libs/pages/cluster/src/lib/ui/page-settings-features/aws-existing-vpc/aws-existing-vpc.spec.tsx, libs/pages/cluster/src/lib/ui/page-settings-features/aws-existing-vpc/aws-existing-vpc.tsx, libs/pages/cluster/src/lib/ui/page-settings-features/gcp-existing-vpc/__snapshots__/gcp-existing-vpc.spec.tsx.snap, libs/pages/cluster/src/lib/ui/page-settings-features/gcp-existing-vpc/gcp-existing-vpc.spec.tsx, libs/pages/cluster/src/lib/ui/page-settings-features/gcp-existing-vpc/gcp-existing-vpc.tsx, libs/pages/cluster/src/lib/ui/page-settings-features/page-settings-features.tsx, libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-features-feature/step-features-feature.tsx, libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-summary-feature/step-summary-feature.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-features/gcp-vpc-feature/__snapshots__/gcp-vpc-feature.spec.tsx.snap, libs/pages/clusters/src/lib/ui/page-clusters-create/step-features/gcp-vpc-feature/gcp-vpc-feature.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-summary/step-summary.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1015
---
=> feat(cluster): VPC GCP settings page

.github/workflows/semantic-release.yml, .github/workflows/test-build-and-deploy.yml, libs/pages/settings/src/lib/ui/page-organization-billing-summary/page-organization-billing-summary.tsx
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> ci: bump github actions

libs/domains/organizations/data-access/src/lib/domains-organizations-data-access.ts, libs/domains/organizations/feature/src/lib/git-token-list/__snapshots__/git-token-list.spec.tsx.snap, libs/domains/organizations/feature/src/lib/git-token-list/git-token-list.spec.tsx, libs/domains/organizations/feature/src/lib/git-token-list/git-token-list.tsx, libs/domains/organizations/feature/src/lib/git-token-services-list-modal/__snapshots__/git-token-services-list-modal.spec.tsx.snap, libs/domains/organizations/feature/src/lib/git-token-services-list-modal/git-token-services-list-modal.spec.tsx, libs/domains/organizations/feature/src/lib/git-token-services-list-modal/git-token-services-list-modal.tsx, libs/domains/organizations/feature/src/lib/hooks/use-git-token-associated-services/use-git-token-associated-services.ts, libs/domains/services/feature/src/lib/select-commit-modal/__snapshots__/select-commit-modal.spec.tsx.snap, libs/shared/ui/src/lib/components/accordion/accordion.stories.tsx, libs/shared/ui/src/lib/components/accordion/accordion.tsx, libs/shared/ui/src/lib/components/inputs/input-search/input-search.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-896
---
=> feat(git-token): add services count

apps/console/src/app/app.tsx
https://qovery.atlassian.net/browse/FRT-1052
=> feat(user): add intercom user hash

libs/pages/clusters/src/lib/ui/page-clusters-create/step-features/aws-vpc-feature/aws-vpc-feature.spec.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-features/aws-vpc-feature/aws-vpc-feature.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-features/button-popover-subnets/__snapshots__/button-popover-subnets.spec.tsx.snap, libs/pages/clusters/src/lib/ui/page-clusters-create/step-features/button-popover-subnets/button-popover-subnets.spec.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-features/button-popover-subnets/button-popover-subnets.tsx
https://qovery.atlassian.net/browse/FRT-1028
=> feat(clusters): add form validation to vpc configuration

libs/pages/settings/src/lib/feature/page-organization-billing-summary-feature/show-usage-modal-feature/show-usage-modal-feature.tsx, libs/pages/settings/src/lib/ui/page-organization-billing-summary/show-usage-modal/show-usage-modal.tsx
If "now" is 20th of march and "renewal date" is 24th of the month, you can have in periods a futur date.
We need to prevent it by limiting periods to now.
https://qovery.atlassian.net/browse/FRT-1056
=> fix(billing): fix report usage interval

libs/domains/organizations/feature/src/index.ts, libs/domains/organizations/feature/src/lib/container-registry-create-edit-modal/container-registry-create-edit-modal.tsx, libs/domains/organizations/feature/src/lib/git-provider-setting/git-provider-setting.tsx, libs/domains/organizations/feature/src/lib/git-public-repository-settings/__snapshots__/git-public-repository-settings.spec.tsx.snap, libs/domains/organizations/feature/src/lib/git-public-repository-settings/git-public-repository-settings.spec.tsx, libs/domains/organizations/feature/src/lib/git-public-repository-settings/git-public-repository-settings.tsx, libs/domains/organizations/feature/src/lib/git-repository-setting/git-repository-setting.tsx, libs/domains/organizations/feature/src/lib/helm-repository-create-edit-modal/helm-repository-create-edit-modal.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/page-helm-create-feature.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/step-general-feature/__snapshots__/step-general-feature.spec.tsx.snap, libs/pages/services/src/lib/feature/page-helm-create-feature/step-general-feature/step-general-feature.spec.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/step-general-feature/step-general-feature.tsx, libs/shared/console-shared/src/lib/git-repository-settings/ui/git-repository-settings/git-repository-settings.tsx, libs/shared/interfaces/src/lib/domain/application-creation-flow.interface.ts, libs/shared/interfaces/src/lib/domain/job-creation-flow.interface.ts, libs/shared/util-js/src/lib/build-git-repo-url.ts
https://qovery.atlassian.net/browse/FRT-798
Fixes:
Features:
=> feat(services): add public git repo support

apps/console/src/app/app.tsx, package.json, yarn.lock
- Update Logrocket version
- Add some [sanitize DOM options](https://docs.logrocket.com/reference/dom#sanitize-all-user-input-fields)
---
=> chore(logrocket): update version

libs/domains/cloud-providers/data-access/src/lib/domains-cloud-providers-data-access.ts, libs/domains/clusters/feature/src/lib/cluster-type/cluster-type.tsx, libs/domains/environments/feature/src/lib/create-clone-environment-modal/create-clone-environment-modal.tsx, libs/shared/console-shared/src/lib/cluster-settings/feature/cluster-resources-settings-feature/cluster-resources-settings-feature.tsx, libs/shared/console-shared/src/lib/cluster-settings/feature/create-edit-credentials-modal-feature/create-edit-credentials-modal-feature.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/create-edit-credentials-modal/create-edit-credentials-modal.tsx, libs/shared/console-shared/src/lib/database-settings-resources/feature/settings-resources-instance-types-feature/setting-resources-instance-types-feature.tsx, package.json, yarn.lock
https://qovery.slack.com/archives/C02P2JB4SEM/p1711470746888259
---
=> chore(cluster): add new ON_PREMISE cloud provider type

libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-general-feature/step-general-feature.tsx, libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-summary-feature/step-summary-feature.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/card-cluster-feature/card-cluster-feature.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1711361258278359
https://qovery.slack.com/archives/C02P2JB4SEM/p1711463240242349
---
=> fix(card-cluster-feature): specific case for STATIC_IP

libs/domains/environments/feature/src/lib/environment-list/__snapshots__/environment-list.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-list/environment-list.tsx, libs/domains/services/feature/src/lib/advanced-settings/advanced-settings.tsx, libs/domains/services/feature/src/lib/pods-metrics/__snapshots__/pods-metrics.spec.tsx.snap, libs/domains/services/feature/src/lib/pods-metrics/pods-metrics.tsx, libs/domains/services/feature/src/lib/service-details/service-details.tsx, libs/domains/services/feature/src/lib/service-list/__snapshots__/service-list.spec.tsx.snap, libs/domains/services/feature/src/lib/service-list/service-list.tsx, libs/domains/variables/feature/src/lib/output-variables/__snapshots__/output-variables.spec.tsx.snap, libs/domains/variables/feature/src/lib/output-variables/output-variables.tsx, libs/shared/ui/src/lib/components/table-primitives/table-primitives.tsx, package.json, yarn.lock
https://qovery.atlassian.net/browse/FRT-1059
=> fix(ui): fix text wrap issues

libs/domains/services/feature/src/lib/select-commit-modal/__snapshots__/select-commit-modal.spec.tsx.snap, libs/shared/util-js/src/lib/compute-available-environment-variable-scope.ts
https://qovery.atlassian.net/browse/FRT-1061
=> fix(services): fix default variable scope for job

libs/domains/services/feature/src/lib/select-commit-modal/__snapshots__/select-commit-modal.spec.tsx.snap, libs/pages/settings/src/lib/feature/page-organization-container-registries-feature/page-organization-container-registries-feature.tsx
https://qovery.atlassian.net/browse/FRT-1062
=> fix(ui): fix mislabeled edit container registry button

libs/pages/services/src/lib/feature/page-helm-create-feature/step-general-feature/step-general-feature.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/step-summary-feature/step-summary-feature.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/step-values-override-arguments-feature/step-values-override-arguments-feature.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/step-values-override-files-feature/step-values-override-files-feature.tsx
=> fix(services): fix react state warning

libs/pages/application/src/lib/ui/container/container.tsx, libs/pages/cluster/src/lib/ui/container/container.tsx, libs/pages/database/src/lib/ui/container/container.tsx, libs/pages/services/src/lib/ui/container/container.tsx
https://qovery.atlassian.net/browse/FRT-1057
=> feat(ui): update header UI

libs/pages/services/src/lib/ui/container/container.tsx
https://qovery.atlassian.net/browse/FRT-1036
=> feat(environments): add cancel ongoing banner

libs/domains/services/feature/src/lib/service-terminal/__snapshots__/service-terminal.spec.tsx.snap, libs/domains/services/feature/src/lib/service-terminal/input-search/__snapshots__/input-search.spec.tsx.snap, libs/domains/services/feature/src/lib/service-terminal/input-search/input-search.spec.tsx, libs/domains/services/feature/src/lib/service-terminal/input-search/input-search.tsx, libs/domains/services/feature/src/lib/service-terminal/service-terminal.tsx, libs/shared/ui/src/lib/components/dropdown-menu/dropdown-menu.tsx, package.json, yarn.lock
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1034
---
=> feat(service-terminal): add pod and container select

libs/domains/services/feature/src/lib/service-terminal/service-terminal.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1712214014382269
---
=> fix(service-terminal): select pod errors

libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-features-feature/step-features-feature.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/card-cluster-feature/card-cluster-feature.tsx
https://qovery.atlassian.net/browse/FRT-1078
=> fix(clusters): fix static ip feature value in creation flow

libs/pages/services/src/lib/feature/page-database-create-feature/step-summary-feature/step-summary-feature.tsx, libs/pages/services/src/lib/ui/page-database-create/step-summary/step-summary.tsx
https://qovery.slack.com/archives/C02NQ0LC8M9/p1712817361924969
---
=> fix(database-creation-flow): submit button type

libs/pages/services/src/lib/feature/page-helm-create-feature/step-summary-feature/step-summary-feature.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1712820073576829
=> fix(helm): fix creation

libs/pages/services/src/lib/ui/page-job-create/step-resources/step-resources.tsx, libs/shared/console-shared/src/lib/application-settings/ui/application-settings-resources/application-settings-resources.tsx
https://qovery.atlassian.net/browse/FRT-1080
=> fix(job): remove instance limits for job

apps/console/src/app/router/main.router.tsx, libs/pages/clusters/src/lib/ui/container/container.tsx, libs/pages/clusters/src/lib/ui/page-clusters-general/page-clusters-general.tsx, libs/pages/events/src/lib/page-events.tsx, libs/pages/events/src/lib/ui/page-general/page-general.tsx, libs/pages/layout/src/lib/ui/breadcrumb/breadcrumb.tsx, libs/pages/settings/src/lib/ui/container/container.tsx, libs/shared/spotlight/feature/src/lib/spotlight/spotlight.tsx, libs/shared/ui/src/lib/components/inputs/input-file/input-file.tsx, libs/shared/ui/src/lib/components/navigation-left/navigation-left-sub-link/navigation-left-sub-link.tsx
https://qovery.atlassian.net/browse/FRT-1068
=> feat(ui): add the top bar on missing screens (clusters, org settings, audit logs)

libs/shared/spotlight/feature/src/lib/spotlight/spotlight.tsx
https://qovery.atlassian.net/browse/FRT-1082
=> fix(spotlight): update roadmap link

libs/pages/cluster/src/lib/ui/page-settings-features/page-settings-features.tsx, libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-features-feature/step-features-feature.tsx, libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-summary-feature/step-summary-feature.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-features/step-features.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-summary/step-summary.tsx
=> feat(GCP): allow static IP

libs/domains/services/feature/src/lib/update-all-modal/__snapshots__/update-all-modal.spec.tsx.snap, libs/pages/logs/environment/src/lib/ui/pod-logs/pod-logs.tsx, libs/shared/ui/src/lib/components/inputs/input-checkbox/input-checkbox.tsx
https://qovery.atlassian.net/browse/FRT-1075
=> feat(services): add nginx logs button for helm charts

libs/domains/services/feature/src/lib/last-commit/last-commit.tsx
- Linked to the second label with the branch size
Before:
Now:
---
=> fix(last-commit): position delta

libs/domains/environments/data-access/src/lib/domains-environments-data-access.ts, libs/domains/service-helm/feature/src/lib/networking-port-setting-modal/networking-port-setting-modal.spec.tsx, libs/domains/service-helm/feature/src/lib/networking-setting/networking-setting.spec.tsx, libs/domains/services/data-access/src/lib/domains-services-data-access.ts, libs/domains/services/feature/src/lib/pods-metrics/pods-metrics.tsx, libs/domains/services/feature/src/lib/service-list/service-list-action-bar.spec.tsx, libs/domains/services/feature/src/lib/service-terminal/service-terminal-provider.tsx, libs/pages/application/src/lib/feature/page-settings-feature/page-settings-feature.spec.tsx, libs/pages/application/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx, libs/pages/application/src/lib/ui/container/container.tsx, libs/pages/application/src/lib/ui/page-variables/page-variables.spec.tsx, libs/pages/cluster/src/lib/ui/page-settings-kubeconfig/page-settings-kubeconfig.spec.tsx, libs/pages/database/src/lib/feature/page-settings-feature/page-settings-feature.spec.tsx, libs/pages/events/src/lib/feature/custom-filter-feature/custom-filter-feature.tsx, libs/pages/logs/environment/src/lib/feature/service-stage-ids-context/service-stage-ids-context.tsx, libs/pages/logs/environment/src/lib/ui/pod-logs/pod-logs.spec.tsx, libs/pages/services/src/lib/feature/page-application-create-feature/step-port-feature/crud-modal-feature/crud-modal-feature.spec.tsx, libs/pages/services/src/lib/feature/page-settings-feature/page-settings-feature.spec.tsx, libs/shared/auth/src/lib/use-invite-member/use-invite-member.spec.tsx, libs/shared/console-shared/src/lib/github-application-callback/github-application-callback-feature/github-application-callback-feature.spec.tsx, libs/shared/console-shared/src/lib/layout-logs/buttons-actions-logs/buttons-actions-logs.spec.tsx, libs/shared/ui/src/lib/components/inputs/input-filter/input-filter.spec.tsx, libs/shared/ui/src/lib/components/modal/modal-root.tsx, libs/shared/ui/src/lib/components/sticky-action-form-toaster/sticky-action-form-toaster.stories.tsx, libs/shared/util-js/src/lib/compute-available-environment-variable-scope.ts, libs/state/util-queries/src/lib/use-react-query-ws-subscription/use-react-query-ws-subscription.spec.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1038
---
=> chore(linter): fix all errors

libs/domains/organizations/feature/src/lib/annotation-create-edit-modal/__snapshots__/annotation-create-edit-modal.spec.tsx.snap, libs/domains/organizations/feature/src/lib/annotation-create-edit-modal/annotation-create-edit-modal.spec.tsx, libs/domains/organizations/feature/src/lib/annotation-create-edit-modal/annotation-create-edit-modal.tsx
=> chore: test ci node_modules

.github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml, .github/workflows/pull-request.yml, .github/workflows/test-build-and-deploy.yml, nx.json
https://qovery.atlassian.net/browse/FRT-1089
=> chore: update nx cloud access token

libs/domains/services/feature/src/lib/service-terminal/__snapshots__/service-terminal.spec.tsx.snap, libs/domains/services/feature/src/lib/service-terminal/input-search/__snapshots__/input-search.spec.tsx.snap, libs/domains/services/feature/src/lib/service-terminal/input-search/input-search.tsx, libs/domains/services/feature/src/lib/service-terminal/service-terminal.tsx, libs/shared/ui/src/lib/components/xterm/xterm.tsx, package.json, yarn.lock
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1074
---
=> feat(service-terminal): resize behavior

libs/domains/services/feature/src/lib/service-terminal/service-terminal.tsx
=> fix(service-terminal): set addons after ws open

apps/console/src/app/app.tsx, libs/pages/logs/environment/src/lib/feature/deployment-logs-feature/deployment-logs-feature.tsx, libs/pages/logs/environment/src/lib/page-environment-logs.tsx, libs/state/util-queries/src/lib/use-react-query-ws-subscription/use-react-query-ws-subscription.spec.tsx, libs/state/util-queries/src/lib/use-react-query-ws-subscription/use-react-query-ws-subscription.ts, package.json, yarn.lock
https://qovery.atlassian.net/browse/FRT-1076
=> fix: ensure no sensible information are leak with logrocket

libs/pages/application/src/lib/feature/page-settings-configure-job-feature/page-settings-configure-job-feature.tsx, libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx, libs/pages/application/src/lib/ui/page-settings-configure-job/page-settings-configure-job.tsx, libs/shared/console-shared/src/lib/job-configure-settings/ui/job-configure-settings.spec.tsx, libs/shared/console-shared/src/lib/job-configure-settings/ui/job-configure-settings.tsx, package.json, yarn.lock
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1073
---
=> feat(cron-general-settings): entrypoint and cmd

libs/domains/clusters/feature/src/lib/cluster-action-toolbar/cluster-action-toolbar.tsx, libs/domains/environments/feature/src/lib/environment-action-toolbar/environment-action-toolbar.tsx, libs/domains/environments/feature/src/lib/environment-list/environment-list-filter.tsx, libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx, libs/domains/services/feature/src/lib/service-list/service-list-filter.tsx, libs/domains/variables/feature/src/lib/variables-action-toolbar/variables-action-toolbar.tsx, libs/pages/login/src/lib/ui/login/login.tsx
Replace `onClick` with `onSelect` to accessibility issues
https://www.radix-ui.com/primitives/docs/components/dropdown-menu#item
=> fix: use onSelect instead of onClick for DropdownMenu.Item

apps/console/src/app/app.tsx, libs/shared/assistant/feature/src/index.ts, libs/shared/assistant/feature/src/lib/assistant-context/assistant-context.ts, libs/shared/assistant/feature/src/lib/assistant-trigger/assistant-trigger.tsx, libs/shared/spotlight/feature/src/lib/spotlight/spotlight.tsx
https://qovery.atlassian.net/browse/FRT-1091
=> fix(ui): turn spotlight "Get Help" into assistant

libs/pages/cluster/src/lib/ui/page-settings-features/aws-existing-vpc/aws-existing-vpc.tsx
https://qovery.slack.com/archives/C02NPSG2HBL/p1713780043962809
---
=> fix(cluster-feature-vpc): AWS VPC condition

libs/pages/layout/src/lib/feature/dark-mode-enabler/dark-mode-enabler.tsx
The goal of this PR is to hide transition when we navigate between dark and light pages, should be more smooth.
---
=> feat(dark-mode): hide transition during navigation

libs/domains/environments/feature/src/lib/create-clone-environment-modal/__snapshots__/create-clone-environment-modal.spec.tsx.snap, libs/domains/environments/feature/src/lib/terraform-export-modal/__snapshots__/terraform-export-modal.spec.tsx.snap, libs/domains/organizations/feature/src/lib/annotation-create-edit-modal/__snapshots__/annotation-create-edit-modal.spec.tsx.snap, libs/domains/service-helm/feature/src/lib/networking-port-setting-modal/__snapshots__/networking-port-setting-modal.spec.tsx.snap, libs/domains/service-helm/feature/src/lib/values-override-yaml-modal/__snapshots__/values-override-yaml-modal.spec.tsx.snap, libs/domains/services/feature/src/lib/redeploy-modal/__snapshots__/redeploy-modal.spec.tsx.snap, libs/domains/services/feature/src/lib/redeploy-modal/redeploy-modal.spec.tsx, libs/domains/services/feature/src/lib/redeploy-modal/redeploy-modal.tsx, libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx, libs/domains/services/feature/src/lib/service-clone-modal/__snapshots__/service-clone-modal.spec.tsx.snap, libs/pages/application/src/lib/feature/page-settings-deployment-restrictions-feature/page-settings-deployment-restrictions-feature.tsx, libs/shared/ui/src/lib/components/modals/modal-crud/modal-crud.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1081
- And, I removed all ButtonLegacy for ModalCRUD 
---
=> feat(redeploy): add modal

apps/console/src/app/app.tsx
=> fix: prevent js error on requestSanitizer / responseSanitizer

libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
=> fix(jobs): jobs schedule general settings

libs/domains/organizations/feature/src/lib/git-token-services-list-modal/__snapshots__/git-token-services-list-modal.spec.tsx.snap, libs/domains/services/feature/src/lib/select-commit-modal/__snapshots__/select-commit-modal.spec.tsx.snap, libs/shared/assistant/feature/src/lib/assistant-panel/assistant-panel.tsx, libs/shared/ui/src/lib/components/inputs/input-search/input-search.tsx
https://qovery.slack.com/archives/C02PGRVRMD2/p1713773558175449
---
=> feat(assistant-panel): dark version

libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1098
---
=> fix(service-action-toolbar): remove yellow color for stopped status

libs/shared/console-shared/src/lib/flow-create-port/ui/crud-modal/crud-modal.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1713978726603569
---
=> feat(port): allow ON_PREMISE cluster

libs/domains/organizations/feature/src/lib/annotation-create-edit-modal/annotation-create-edit-modal.tsx, libs/domains/organizations/feature/src/lib/annotation-setting/annotation-setting.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1097
---
=> feat(annotation-setting): add modal create

libs/shared/assistant/feature/src/lib/assistant-panel/assistant-panel.tsx
=> fix(assistant): feedback dark color

libs/shared/assistant/feature/src/lib/hooks/use-contextual-doc-links/use-contextual-doc-links.ts
Add annotation doc link in services creation flows
Add annotation doc link in services creation flows
---
=> chore: add annotation doc links in services creation flows

libs/pages/settings/src/lib/ui/page-organization-roles-edit/table/table.tsx
=> fix(ui): avoid z-index conflict

libs/domains/services/feature/src/lib/need-redeploy-flag/need-redeploy-flag.spec.tsx, libs/domains/services/feature/src/lib/need-redeploy-flag/need-redeploy-flag.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1104
---
=> fix(need-redeploy-service): not deploy service message

libs/domains/clusters/feature/src/lib/cluster-delete-modal/__snapshots__/cluster-delete-modal.spec.tsx.snap, libs/pages/logs/environment/src/lib/ui/sidebar-history/sidebar-history.spec.tsx, libs/pages/logs/environment/src/lib/ui/sidebar-history/sidebar-history.tsx, libs/pages/onboarding/src/lib/ui/plan-card/plan-card.tsx, libs/pages/onboarding/src/lib/ui/step-company/step-company.tsx, libs/pages/onboarding/src/lib/ui/step-more/step-more.tsx, libs/pages/onboarding/src/lib/ui/step-personalize/step-personalize.tsx, libs/pages/onboarding/src/lib/ui/step-pricing/step-pricing.tsx, libs/pages/onboarding/src/lib/ui/step-project/step-project.tsx, libs/pages/onboarding/src/lib/ui/step-thanks/step-thanks.tsx, libs/pages/services/src/lib/ui/page-settings-deployment-pipeline/page-settings-deployment-pipeline.tsx, libs/pages/services/src/lib/ui/page-settings-deployment-pipeline/stage-order-modal/stage-order-modal.tsx, libs/pages/services/src/lib/ui/page-settings-deployment-rules/page-settings-deployment-rules.tsx, libs/pages/services/src/lib/ui/page-settings-general/page-settings-general.tsx, libs/pages/settings/src/lib/ui/page-organization-api/value-modal/value-modal.tsx, libs/pages/settings/src/lib/ui/page-organization-billing-summary/promo-code-modal/promo-code-modal.tsx, libs/pages/settings/src/lib/ui/page-organization-billing/billing-details/billing-details.tsx, libs/pages/settings/src/lib/ui/page-organization-github-repository-access/disconnection-confirm-modal/disconnection-confirm-modal.tsx, libs/pages/settings/src/lib/ui/page-organization-github-repository-access/page-organization-github-repository-access.tsx, libs/pages/settings/src/lib/ui/page-organization-roles-edit/page-organization-roles-edit.tsx, libs/shared/console-shared/src/lib/layout-logs/tabs-cluster-logs/tabs-cluster-logs.tsx, libs/shared/ui/src/lib/components/modal-alert/modal-alert.tsx, libs/shared/ui/src/lib/components/modals/modal-confirmation/__snapshots__/modal-confirmation.spec.tsx.snap, libs/shared/ui/src/lib/components/modals/modal-confirmation/modal-confirmation.tsx, libs/shared/ui/src/lib/components/sticky-action-form-toaster/sticky-action-form-toaster.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1071
---
=> chore(button-legacy): diverse components and pages part2

libs/domains/clusters/feature/src/lib/cluster-delete-modal/cluster-delete-modal.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1088
---
=> feat(cluster-delete-modal): hide warning for self managed

libs/domains/organizations/feature/src/lib/annotation-create-edit-modal/annotation-create-edit-modal.tsx, libs/domains/organizations/feature/src/lib/container-registry-create-edit-modal/container-registry-create-edit-modal.tsx, libs/domains/organizations/feature/src/lib/git-token-create-edit-modal/git-token-create-edit-modal.tsx, libs/domains/organizations/feature/src/lib/helm-repository-create-edit-modal/helm-repository-create-edit-modal.tsx, libs/pages/settings/src/lib/feature/page-organization-api-feature/crud-modal-feature/crud-modal-feature.tsx, libs/pages/settings/src/lib/feature/page-organization-webhooks-feature/webhook-crud-modal-feature/webhook-crud-modal-feature.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1099
---
=> feat(modals): add click outside confirmation

libs/domains/organizations/feature/src/lib/hooks/use-delete-annotations-group/use-delete-annotations-group.ts, libs/domains/organizations/feature/src/lib/hooks/use-edit-annotations-group/use-edit-annotations-group.ts
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1103
---
=> chore(annotations): toast delete and edit wording

libs/domains/clusters/feature/src/lib/cluster-action-toolbar/__snapshots__/cluster-action-toolbar.spec.tsx.snap, libs/domains/clusters/feature/src/lib/cluster-action-toolbar/cluster-action-toolbar.spec.tsx, libs/domains/clusters/feature/src/lib/cluster-action-toolbar/cluster-action-toolbar.tsx
https://qovery.atlassian.net/browse/FRT-849
=> feat(clusters): add yellow update button actions cluster

libs/domains/projects/feature/src/lib/hooks/use-delete-project/use-delete-project.ts
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-723
---
=> chore(use-delete-project): update toast wording

libs/domains/services/feature/src/lib/pods-metrics/empty-state.tsx
https://qovery.atlassian.net/browse/FRT-1090
Here is an impacted service:
http://localhost:4200/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/cf021d82-2c5e-41de-96eb-eb69c022eddc/environment/55867c71-56f9-4b4f-ab22-5904c9dbafda/application/ebd8be35-d7a2-4d4f-ad82-de4378a83ef4/general
=> feat(services): improve empty state for cron job

libs/pages/application/src/lib/ui/container/container.tsx, libs/pages/database/src/lib/ui/container/container.tsx, libs/pages/services/src/lib/ui/container/container.tsx
https://qovery.atlassian.net/browse/FRT-1108
=> feat(clusters): add missing icon for self-managed cluster

libs/domains/clusters/feature/src/lib/cluster-action-toolbar/cluster-action-toolbar.tsx
https://qovery.atlassian.net/browse/FRT-1102
=> feat(clusters): update action toolbar for self-managed

libs/domains/organizations/feature/src/lib/git-public-repository-settings/__snapshots__/git-public-repository-settings.spec.tsx.snap, libs/domains/organizations/feature/src/lib/git-public-repository-settings/git-public-repository-settings.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/step-general-feature/__snapshots__/step-general-feature.spec.tsx.snap
https://qovery.slack.com/archives/C02P2JB4SEM/p1714556054691099
---
=> chore(git-public-repository): update application wording to service

libs/pages/layout/src/lib/ui/navigation/navigation.tsx
=> fix(navigation): dark buttons

libs/domains/organizations/feature/src/lib/annotation-setting/annotation-setting.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx, libs/shared/interfaces/src/lib/common/value.interface.ts, libs/shared/ui/src/lib/components/inputs/input-radio-box/input-radio-box.tsx, libs/shared/ui/src/lib/components/inputs/input-radio/input-radio.tsx, libs/shared/ui/src/lib/components/tooltip/tooltip.tsx
https://qovery.atlassian.net/browse/FRT-1106
=> feat(annotations): Add tooltip on annotation groups list

libs/pages/clusters/src/lib/ui/card-cluster/card-cluster.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1714738206339089
---
=> fix(card-cluster): title max-width

libs/shared/ui/src/lib/components/sticky-action-form-toaster/sticky-action-form-toaster.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1714994575558079
---
=> fix(sticky-action-form-toaster): submit button

libs/pages/application/src/lib/feature/page-general-feature/page-general-feature.tsx, libs/pages/application/src/lib/ui/page-general/page-general.tsx
https://qovery.atlassian.net/browse/FRT-1113
=> fix(services): limit output-variables component to lifecycle jobs

libs/domains/organizations/data-access/src/lib/domains-organizations-data-access.ts, libs/domains/organizations/feature/src/index.ts, libs/domains/organizations/feature/src/lib/annotation-items-list-modal/__snapshots__/annotation-items-list-modal.spec.tsx.snap, libs/domains/organizations/feature/src/lib/annotation-items-list-modal/annotation-items-list-modal.spec.tsx, libs/domains/organizations/feature/src/lib/annotation-items-list-modal/annotation-items-list-modal.tsx, libs/domains/organizations/feature/src/lib/hooks/use-annotations-group-associated-items/use-annotations-group-associated-items.ts, libs/pages/settings/src/lib/feature/page-organization-labels-annotations-feature/__snapshots__/page-organization-labels-annotations-feature.spec.tsx.snap, libs/pages/settings/src/lib/feature/page-organization-labels-annotations-feature/page-organization-labels-annotations-feature.tsx, package.json, yarn.lock
https://qovery.atlassian.net/browse/FRT-1093
=> feat(annotations): add annotation associated items

libs/domains/services/feature/src/lib/service-list/service-list.tsx, libs/domains/variables/feature/src/lib/variable-list/__snapshots__/variable-list.spec.tsx.snap, libs/domains/variables/feature/src/lib/variable-list/variable-list-action-bar.tsx, libs/domains/variables/feature/src/lib/variable-list/variable-list-skeleton.tsx, libs/domains/variables/feature/src/lib/variable-list/variable-list.tsx, libs/pages/application/src/lib/feature/page-variables-feature/page-variables-feature.tsx, libs/pages/environments/src/lib/feature/page-variables-feature/page-variables-feature.tsx
https://qovery.atlassian.net/browse/FRT-693
=> feat(variables): add variable bulk actions

libs/shared/console-shared/src/lib/cluster-settings/feature/create-edit-credentials-modal-feature/create-edit-credentials-modal-feature.spec.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/create-edit-credentials-modal/create-edit-credentials-modal.tsx
GCP credentials JSON string to be sent as base64 encoded string.
ENG-1749
---
=> feat(clusters): GCP credentials as base64 string

libs/pages/clusters/src/lib/ui/page-clusters-create/step-general/copy-button/copy-button.spec.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-general/copy-button/copy-button.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-general/step-general.spec.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-general/step-general.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-summary/step-summary.tsx, libs/shared/interfaces/src/lib/domain/cluster-creation-flow.interface.ts, tailwind-workspace-preset.js
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1121
---
=> feat(cluster): update creation flow general step

libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-general-feature/step-general-feature.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-general/step-general.tsx
https://qovery.slack.com/archives/C071PR1HGP8/p1715757092438479
---
=> feat(cluster): update UI type creation flow general step

libs/domains/services/feature/src/lib/service-list/service-list.tsx, libs/pages/database/src/lib/page-database.tsx, libs/pages/database/src/lib/ui/container/container.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1715693552091669
---
=> feat(shell): add database container

libs/pages/cluster/src/lib/feature/page-settings-feature/page-settings-feature.spec.tsx, libs/pages/cluster/src/lib/feature/page-settings-feature/page-settings-feature.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1117
---
=> feat(cluster): self-managed advanced settings

libs/pages/onboarding/src/lib/ui/step-thanks/step-thanks.tsx
…EO video link on Loom
I changed the Youtube link at the end of the sign-up with a more useful one 👯‍♂️ 
---
=> chore(page-onboarding-step-thanks): replace youtube video link on sign up

libs/pages/services/src/lib/feature/page-helm-create-feature/page-helm-create-feature.tsx
=> fix(helm): route path

libs/domains/services/feature/src/lib/service-details/service-details.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1716188406138199
---
=> feat(jobs-overview): resources CPU unit

libs/pages/services/src/lib/feature/page-application-create-feature/page-application-create-feature.tsx, libs/pages/services/src/lib/feature/page-application-create-feature/step-general-feature/step-general-feature.tsx, libs/pages/services/src/lib/feature/page-application-create-feature/step-healthchecks-feature/step-healthchecks-feature.tsx, libs/pages/services/src/lib/feature/page-application-create-feature/step-port-feature/step-port-feature.tsx, libs/pages/services/src/lib/feature/page-application-create-feature/step-resources-feature/step-resources-feature.tsx, libs/pages/services/src/lib/feature/page-application-create-feature/step-summary-feature/step-summary-feature.tsx, libs/pages/services/src/lib/feature/page-database-create-feature/page-database-create-feature.tsx, libs/pages/services/src/lib/feature/page-database-create-feature/step-general-feature/step-general-feature.spec.tsx, libs/pages/services/src/lib/feature/page-database-create-feature/step-general-feature/step-general-feature.tsx, libs/pages/services/src/lib/feature/page-database-create-feature/step-resources-feature/step-resources-feature.spec.tsx, libs/pages/services/src/lib/feature/page-database-create-feature/step-resources-feature/step-resources-feature.tsx, libs/pages/services/src/lib/feature/page-database-create-feature/step-summary-feature/step-summary-feature.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/page-helm-create-feature.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/step-general-feature/step-general-feature.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/step-summary-feature/step-summary-feature.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/step-values-override-arguments-feature/step-values-override-arguments-feature.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/step-values-override-files-feature/step-values-override-files-feature.tsx, libs/shared/ui/src/lib/components/inputs/input-select/input-select.tsx
- Fix navigation for all Services with new template behavior
---
=> fix(service-creation-flow): navigation with template url

libs/pages/logs/environment/src/lib/page-environment-logs.tsx
https://qovery.atlassian.net/browse/FRT-1130
=> fix(logs): reset logs when switching version

libs/domains/variables/feature/src/lib/create-update-variable-modal/create-update-variable-modal.tsx
https://qovery.atlassian.net/browse/FRT-1125
=> feat(variables): add default scope

libs/domains/services/feature/src/lib/service-list/service-list.tsx, libs/pages/services/src/lib/feature/page-application-create-feature/page-application-create-feature.tsx, libs/pages/services/src/lib/feature/page-database-create-feature/page-database-create-feature.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/page-helm-create-feature.tsx, libs/pages/services/src/lib/feature/page-job-create-feature/page-job-create-feature.tsx, libs/pages/services/src/lib/feature/page-new-feature/page-new-feature.tsx, libs/pages/services/src/lib/feature/page-new-feature/service-templates.ts, libs/pages/services/src/lib/ui/container/container.tsx
https://qovery.slack.com/archives/C071PR1HGP8/p1716304622858699
+ Add new feature flag to reverse the logic
---
=> feat(service-creation-list): add first version with groups

libs/shared/console-shared/src/lib/layout-logs/tabs-cluster-logs/tabs-cluster-logs.tsx
https://qovery.atlassian.net/browse/FRT-1131
=> fix(ui): show assistant button in cluster logs

libs/domains/clusters/feature/src/lib/cluster-delete-modal/__snapshots__/cluster-delete-modal.spec.tsx.snap, libs/domains/clusters/feature/src/lib/cluster-delete-modal/cluster-delete-modal.tsx
https://qovery.atlassian.net/browse/FRT-1129
=> feat(clusters): update delete modal wording

libs/domains/organizations/feature/src/lib/container-registry-create-edit-modal/container-registry-create-edit-modal.tsx, libs/domains/organizations/feature/src/lib/hooks/use-available-container-registries/use-available-container-registries.ts, package.json, yarn.lock
Allow to create GCP artifact registries in an organization.
https://qovery.atlassian.net/browse/COR-898
---
=> feat(container-registry): allow to create GCP registry

libs/domains/services/feature/src/lib/pod-statuses-callout/pod-statuses-callout.spec.tsx, libs/domains/services/feature/src/lib/pod-statuses-callout/pod-statuses-callout.tsx
https://qovery.atlassian.net/browse/FRT-1128
=> fix(services): fix job banners appearance

libs/domains/clusters/feature/src/lib/cluster-setup/__snapshots__/cluster-setup.spec.tsx.snap, libs/domains/clusters/feature/src/lib/cluster-setup/cluster-setup.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-general/step-general.spec.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1716793212734219
---
=> chore(cluster): self-managed typo

libs/pages/application/src/lib/page-application.tsx, libs/pages/application/src/lib/router/router.tsx, libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-summary-feature/step-summary-feature.spec.tsx, libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-summary-feature/step-summary-feature.tsx, libs/pages/environments/src/lib/page-environments.tsx, libs/pages/services/src/lib/feature/page-new-feature/page-new-feature.tsx, libs/pages/services/src/lib/page-services.tsx, package.json, yarn.lock
- Fix 404 for services list
---
=> fix(page-services): 404page

libs/pages/application/src/lib/ui/container/container.tsx
https://qovery.atlassian.net/browse/FRT-1109
=> feat(services): add auto-deploy badge

libs/pages/cluster/src/lib/page-cluster.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1716985521232759
---
=> fix(page-cluster): 404 redirect

libs/domains/variables/feature/src/lib/variable-list/variable-list.tsx
https://qovery.atlassian.net/browse/FRT-916
=> fix(variables): disable override if one already exists

libs/pages/services/src/lib/feature/page-application-create-feature/step-port-feature/crud-modal-feature/crud-modal-feature.tsx, libs/pages/services/src/lib/feature/page-application-create-feature/step-port-feature/step-port-feature.tsx, libs/pages/services/src/lib/ui/page-application-create/step-summary/step-summary.tsx, libs/shared/console-shared/src/lib/flow-create-port/ui/crud-modal/crud-modal.tsx, libs/shared/console-shared/src/lib/flow-create-port/ui/flow-create-port/flow-create-port.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1133
---
=> feat(service-creation-flow): step ports hide name input

libs/domains/environments/feature/src/lib/create-clone-environment-modal/create-clone-environment-modal.tsx, libs/domains/environments/feature/src/lib/environment-list/__snapshots__/environment-list.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-list/environment-list.tsx, libs/domains/environments/feature/src/lib/environment-mode/environment-mode.tsx, libs/pages/layout/src/lib/ui/breadcrumb/breadcrumb.tsx
https://qovery.atlassian.net/browse/FRT-1110
=> feat(environments): revamp environment breadcrumb

libs/domains/environments/feature/src/lib/create-clone-environment-modal/create-clone-environment-modal.tsx
https://qovery.atlassian.net/browse/FRT-1138
=> feat(clusters): add self-managed in cluster selection

libs/domains/environments/feature/src/lib/hooks/use-environments/use-environments.ts, libs/domains/services/feature/src/lib/hooks/use-services/use-services.ts
https://qovery.atlassian.net/browse/FRT-1141
=> fix(services): remove deleted services/environments from listing

libs/pages/services/src/lib/feature/page-new-feature/page-new-feature.tsx, libs/pages/services/src/lib/feature/page-new-feature/service-templates.ts
- Filter by service template cloud provider
---
=> feat(page-new-services): filter by cloud provider

libs/shared/console-shared/src/lib/layout-logs/layout-logs.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1717441564814169
---
=> fix(cluster-logs): add max-width to avoid long log gap

libs/pages/services/src/lib/feature/page-new-feature/page-new-feature.tsx, libs/shared/console-shared/src/lib/general-container-settings/ui/general-container-settings.tsx
https://qovery.slack.com/archives/C02NPSG2HBL/p1717492142573819?thread_ts=1716381234.909459&cid=C02NPSG2HBL
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1136
---
=> feat(general-settings): hide registries linked to cluster

libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1111
---
=> fix(service-redeploy-modal): condition for running and error state

libs/domains/organizations/feature/src/lib/container-registry-form/container-registry-form.tsx, libs/pages/cluster/src/lib/feature/page-settings-image-registry-feature/page-settings-image-registry-feature.tsx
https://qovery.slack.com/archives/C02NPSG2HBL/p1717514863514019?thread_ts=1716381234.909459&cid=C02NPSG2HBL
---
=> fix(cluster-registry): disabled url and region field if cluster managed

libs/domains/environments/feature/src/lib/environment-mode/environment-mode.tsx
https://qovery.atlassian.net/browse/FRT-1159
Fix the following error
=> fix(ui): add forwardRef to EnvironmentMode component

libs/domains/cloud-providers/feature/src/lib/hooks/use-cloud-provider-features/use-cloud-provider-features.ts, libs/pages/cluster/src/lib/ui/page-settings-features/page-settings-features.tsx
- We need to hide the cluster feature `KARPENTER` on the front-end side  
---
=> fix(cluster-feature): hide karpenter item

libs/shared/ui/src/lib/components/status-chip/__snapshots__/status-chip.spec.tsx.snap, libs/shared/ui/src/lib/components/status-chip/status-chip.tsx, tailwind-workspace-preset.js
https://qovery.atlassian.net/browse/FRT-1123
=> feat(ui): add ripple effect on service error

libs/pages/application/src/lib/ui/page-settings-general/page-settings-general.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1717688658973509
---
=> fix(job-settings): container hide docker section

libs/domains/variables/feature/src/lib/variable-list/__snapshots__/variable-list.spec.tsx.snap, libs/domains/variables/feature/src/lib/variable-list/variable-list.spec.tsx, libs/domains/variables/feature/src/lib/variable-list/variable-list.tsx
https://qovery.atlassian.net/browse/FRT-1160
=> feat(variables): display parent variable when searching

libs/domains/variables/feature/src/lib/variable-list/__snapshots__/variable-list.spec.tsx.snap, libs/domains/variables/feature/src/lib/variable-list/variable-list.spec.tsx, libs/domains/variables/feature/src/lib/variable-list/variable-list.tsx
https://qovery.atlassian.net/browse/FRT-1161
=> feat(variables): improve variable count display

libs/domains/services/feature/src/lib/service-list/service-list.tsx, libs/shared/factories/src/lib/job-factory.mock.ts, package.json, yarn.lock
- Update open-api package to 1.1.433
---
=> chore: fix open api update

libs/pages/environments/src/lib/ui/container/container.spec.tsx, libs/pages/environments/src/lib/ui/container/container.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1154
---
=> feat(btn-new-environment): add hint if no cluster

libs/pages/services/src/lib/feature/page-database-create-feature/step-general-feature/step-general-feature.tsx, libs/pages/services/src/lib/ui/page-database-create/step-general/step-general.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1155
---
=> feat(database-creation-flow): default container value

libs/domains/clusters/feature/src/lib/cluster-action-toolbar/cluster-action-toolbar.tsx, libs/pages/cluster/src/lib/feature/page-settings-feature/page-settings-feature.tsx
https://qovery.atlassian.net/browse/FRT-1156
=> feat(clusters): hide unnecessary features for self managed cluster

libs/domains/services/feature/src/lib/service-details/service-details.tsx
https://qovery.atlassian.net/browse/FRT-1157
=> fix(services): hide cpu & ram for managed db

libs/pages/logs/environment/src/lib/feature/pod-logs-feature/pod-logs-feature.tsx, libs/state/util-queries/src/lib/use-react-query-ws-subscription/use-react-query-ws-subscription.ts, package.json, yarn.lock
https://qovery.atlassian.net/browse/FRT-1142
=> feat(logs): filter by pod use new endpoint

libs/pages/services/src/lib/feature/page-new-feature/page-new-feature.tsx
https://qovery.slack.com/archives/C071PR1HGP8/p1718262000535169
---
=> chore(select-service): add search capture posthog event

libs/pages/layout/src/lib/ui/breadcrumb/breadcrumb.tsx
https://qovery.atlassian.net/browse/FRT-1147
=> fix(ui): fix service icons

libs/pages/database/src/lib/ui/page-settings-general/page-settings-general.tsx, libs/pages/services/src/lib/ui/page-database-create/step-general/step-general.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1167
---
=> fix(annotations-labels): database settings

libs/pages/settings/src/lib/feature/page-organization-labels-annotations-feature/page-organization-labels-annotations-feature.tsx
=> fix(labels-settings): change delete tooltip wording

libs/shared/ui/src/lib/components/modals/modal-confirmation/modal-confirmation.tsx
https://qovery.atlassian.net/browse/FRT-1146
=> feat(ui): place confirm modal warning at the bottom

libs/shared/ui/src/lib/components/date-picker/date-picker.tsx, libs/shared/ui/src/lib/components/inputs/input-text/input-text.tsx
Small improvement to tend to the following end goal (it still not working but this is a first step):
```ts
import type { FieldValues, UseFormReturn, SubmitHandler } from "react-hook-form"
import React from "react"
import { useForm } from "react-hook-form"
type InputProps = React.DetailedHTMLProps<
React.InputHTMLAttributes<HTMLInputElement>,
HTMLInputElement
>
const Input = React.forwardRef<HTMLInputElement, InputProps>((props, ref) => (
<input ref={ref} {...props} />
))
type Option = {
label: React.ReactNode
value: string | number | string[]
}
type SelectProps = React.DetailedHTMLProps<
React.SelectHTMLAttributes<HTMLSelectElement>,
HTMLSelectElement
> & { options: Option[] }
const Select = React.forwardRef<HTMLSelectElement, SelectProps>(
({ options, ...props }, ref) => (
<select …
```
=> refacto(ui): use forwardRef for input-text

libs/pages/cluster/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.spec.tsx, libs/pages/cluster/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx, libs/pages/cluster/src/lib/ui/page-settings-resources/page-settings-resources.tsx, libs/pages/clusters/src/lib/feature/page-clusters-create-feature/page-clusters-create-feature.tsx, libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-features-feature/step-features-feature.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-features/step-features.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/karpenter-image.tsx
Cluster creation flow
- Add warning
- Update wording
- Add default values
---
=> feat(karpenter): feedback

libs/domains/environments/feature/src/lib/environment-list/__snapshots__/environment-list.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-list/environment-list.tsx, libs/domains/services/feature/src/lib/service-list/__snapshots__/service-list.spec.tsx.snap, libs/domains/services/feature/src/lib/service-list/service-list.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1170
---
=> feat(service-environment-list): truncate name

.github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml, .github/workflows/pull-request.yml, .github/workflows/test-build-and-deploy.yml
Add codecov token for the CI + update codecov action 4
https://docs.codecov.com/docs/quick-start#step-2-get-the-repository-upload-token
They want us to pass a token even we have an open-source repository
---
=> chore: update Codecov CI

libs/domains/environments/data-access/src/lib/domains-environments-data-access.ts, libs/domains/services/data-access/src/lib/domains-services-data-access.ts, package.json, yarn.lock
- Need to add an payload to simplify test for back-end teeam
---
=> feat(cancel-deployment): add payload force_cancel

libs/pages/cluster/src/lib/ui/page-settings-advanced/page-settings-advanced.spec.tsx
=> tests: move page-settings-advanced to new format

libs/shared/util-js/src/lib/parse-dotenv.spec.ts, libs/shared/util-js/src/lib/parse-dotenv.ts
https://qovery.atlassian.net/browse/FRT-1175
=> fix(variables): file parsing with double equal sign

libs/pages/layout/src/lib/feature/layout/layout.tsx
https://qovery.atlassian.net/browse/FRT-1145
=> feat: add posthog organization_id

libs/domains/services/feature/src/lib/service-details/service-details.tsx
https://qovery.atlassian.net/browse/FRT-1175
=> fix(ui): truncate container registry

libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx
=> fix(karpenter): doc link

libs/domains/services/feature/src/lib/select-version-modal/select-version-modal.tsx, libs/shared/console-shared/src/lib/general-container-settings/ui/general-container-settings.tsx, libs/shared/ui/src/lib/styles/components/select.scss
Note: I didn't strictly follow figma design due to inconsistency https://www.figma.com/design/L3T54WTTm9rZQwLQHCkcZg?node-id=19431-384696#847826013
=> feat: add tooltip info on disabled container tag

libs/domains/service-helm/feature/src/lib/source-setting/source-setting.tsx, libs/domains/services/feature/src/lib/select-version-modal/__snapshots__/select-version-modal.spec.tsx.snap, libs/domains/services/feature/src/lib/select-version-modal/select-version-modal.tsx, libs/shared/console-shared/src/lib/general-container-settings/ui/general-container-settings.tsx
=> feat(services): add input text fallback on container tag and helm chart versions

libs/domains/service-helm/feature/src/lib/networking-port-setting-modal/networking-port-setting-modal.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1180
https://www.loom.com/share/dd4457fb5f9f43a1bf0c21cbcbe6cc84
---
=> fix(helm-port): add input name length/regex rules

libs/pages/events/src/lib/feature/custom-filter-feature/custom-filter-feature.tsx, libs/pages/events/src/lib/feature/page-general-feature/page-general-feature.tsx, libs/pages/events/src/lib/ui/custom-filter/custom-filter.tsx, libs/pages/events/src/lib/ui/page-general/page-general.tsx
https://qovery.atlassian.net/browse/FRT-1152
=> feat(audit): fix min date according to organization plan

libs/pages/settings/src/lib/feature/page-organization-labels-annotations-feature/__snapshots__/page-organization-labels-annotations-feature.spec.tsx.snap, libs/pages/settings/src/lib/feature/page-organization-labels-annotations-feature/page-organization-labels-annotations-feature.tsx, libs/pages/settings/src/lib/ui/page-organization-api/page-organization-api.tsx, libs/pages/settings/src/lib/ui/page-organization-container-registries/page-organization-container-registries.tsx, libs/pages/settings/src/lib/ui/page-organization-general/page-organization-general.tsx, libs/pages/settings/src/lib/ui/page-organization-github-repository-access/page-organization-github-repository-access.tsx, libs/pages/settings/src/lib/ui/page-organization-helm-repositories/page-organization-helm-repositories.tsx, libs/pages/settings/src/lib/ui/page-organization-members/page-organization-members.tsx, libs/pages/settings/src/lib/ui/page-organization-roles/page-organization-roles.tsx, libs/pages/settings/src/lib/ui/page-organization-webhooks/page-organization-webhooks.tsx, libs/pages/settings/src/lib/ui/page-project-general/page-project-general.tsx
https://qovery.atlassian.net/browse/FRT-1148
=> feat(organization): add need help button in organization settings

libs/pages/logs/environment/src/lib/feature/pod-logs-feature/pod-logs-feature.tsx
https://qovery.atlassian.net/browse/FRT-1166
=> feat(logs): display 20 last logs

libs/pages/events/src/lib/ui/page-general/page-general.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1173
---
=> feat(audit-logs): add filter by user

libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx
- Allow Qovery mobile view for debug
---
=> feat(qovery-debug-mode): allow mobile view

libs/domains/services/data-access/src/lib/domains-services-data-access.ts, libs/domains/services/feature/src/lib/hooks/use-clean-failed-jobs/use-clean-failed-jobs.ts, libs/domains/services/feature/src/lib/pod-statuses-callout/__snapshots__/pod-statuses-callout.spec.tsx.snap, libs/domains/services/feature/src/lib/pod-statuses-callout/pod-statuses-callout.tsx, package.json, yarn.lock
https://qovery.atlassian.net/browse/FRT-1124
=> feat(services): add clear warning button for job cronjob execution fails

libs/pages/logs/environment/src/lib/ui/pod-logs/pod-logs.tsx, libs/pages/logs/environment/src/lib/ui/row-pod/__snapshots__/row-pod.spec.tsx.snap, libs/pages/logs/environment/src/lib/ui/row-pod/row-pod.tsx, libs/shared/util-js/src/lib/trim-id.spec.ts, libs/shared/util-js/src/lib/trim-id.ts
https://qovery.atlassian.net/browse/FRT-1168
=> fix(logs): align pod name truncation

libs/pages/services/src/lib/feature/page-new-feature/service-templates.ts
https://qovery.atlassian.net/browse/FRT-1183
=> feat(services): add docker templates

libs/domains/services/feature/src/lib/dockerfile-raw-modal/dockerfile-raw-modal.tsx, libs/domains/services/feature/src/lib/dockerfile-settings/dockerfile-settings.spec.tsx, libs/domains/services/feature/src/lib/dockerfile-settings/dockerfile-settings.tsx, libs/pages/application/src/lib/feature/page-settings-dockerfile-feature/page-settings-dockerfile-feature.tsx, libs/pages/services/src/lib/feature/page-job-create-feature/page-job-create-feature.tsx, libs/pages/services/src/lib/feature/page-job-create-feature/step-dockerfile-feature/step-dockerfile-feature.spec.tsx, libs/pages/services/src/lib/feature/page-job-create-feature/step-dockerfile-feature/step-dockerfile-feature.tsx, libs/pages/services/src/lib/ui/page-application-create/step-summary/step-summary.tsx, libs/pages/services/src/lib/ui/page-job-create/step-summary/step-summary.tsx, libs/shared/factories/src/lib/job-factory.mock.ts
https://qovery.atlassian.net/browse/FRT-1194
=> fix(services): fix dockerfile validation

libs/shared/ui/src/lib/components/indicator/__snapshots__/indicator.spec.tsx.snap, libs/shared/ui/src/lib/components/indicator/indicator.spec.tsx, libs/shared/ui/src/lib/components/indicator/indicator.stories.tsx, libs/shared/ui/src/lib/components/indicator/indicator.tsx
=> feat(indicator): add new wrapper component

libs/pages/application/src/lib/ui/page-settings-general/page-settings-general.tsx
https://qovery.atlassian.net/browse/FRT-1199
=> fix(services): add missing arguments field cronjob settings

libs/domains/environments/feature/src/lib/hooks/use-deployment-history/use-deployment-history.ts, libs/domains/services/feature/src/lib/hooks/use-deployment-history/use-deployment-history.ts, libs/pages/application/src/lib/ui/page-deployments/page-deployments.tsx, libs/pages/database/src/lib/ui/page-deployments/page-deployments.tsx, libs/pages/services/src/lib/ui/page-deployments/page-deployments.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1720168178762849
- Reduce refetch interval + fix memo for deployments pages
---
=> fix(page-deployment): status memoized

libs/domains/variables/feature/src/lib/create-update-variable-modal/create-update-variable-modal.tsx, libs/domains/variables/feature/src/lib/variable-list/__snapshots__/variable-list.spec.tsx.snap, libs/domains/variables/feature/src/lib/variable-list/variable-list.spec.tsx, libs/domains/variables/feature/src/lib/variable-list/variable-list.tsx, package.json, yarn.lock
Peer programming @fabienfleureau 
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-725
---
=> feat(variable): add description field

libs/shared/ui/src/lib/components/inputs/input-text-area/input-text-area.tsx, libs/shared/ui/src/lib/components/inputs/input-text/input-text.tsx
Follows https://github.com/Qovery/console/pull/1426 but for `InputTextArea`
=> refactor(ui): forwardRef to input textarea

libs/domains/environments/feature/src/lib/environment-action-toolbar/__snapshots__/environment-action-toolbar.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-action-toolbar/environment-action-toolbar.tsx, libs/domains/environments/feature/src/lib/environment-list/__snapshots__/environment-list.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-list/environment-list.tsx, libs/domains/services/feature/src/lib/service-action-toolbar/__snapshots__/service-action-toolbar.spec.tsx.snap, libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx, libs/domains/services/feature/src/lib/service-list/__snapshots__/service-list.spec.tsx.snap, libs/domains/services/feature/src/lib/service-list/service-list.tsx, libs/pages/logs/environment/src/lib/ui/sidebar-history/sidebar-history.spec.tsx, libs/shared/ui/src/lib/components/link/link.tsx, libs/shared/ui/src/lib/components/menu/menu-item/menu-item.tsx
=> feat(ui): ensure links when possible

libs/pages/clusters/src/lib/feature/page-clusters-create-feature/page-clusters-create-feature.tsx, libs/pages/services/src/lib/feature/page-application-create-feature/page-application-create-feature.tsx, libs/pages/services/src/lib/feature/page-database-create-feature/page-database-create-feature.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/page-helm-create-feature.tsx, libs/pages/services/src/lib/feature/page-job-create-feature/page-job-create-feature.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1205
---
=> feat(creation-flow): add confirmation modal to close flow

libs/domains/variables/feature/src/lib/output-variables/__snapshots__/output-variables.spec.tsx.snap, libs/domains/variables/feature/src/lib/output-variables/output-variables.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1720626699229189
---
=> feat(output-variables): add description

libs/pages/application/src/lib/feature/page-settings-configure-job-feature/page-settings-configure-job-feature.tsx, libs/shared/util-services/src/lib/build-edit-service-payload.ts
https://qovery.slack.com/archives/C02P2JB4SEM/p1720646033406489
---
=> fix(settings-configure-job): edit service payload

libs/pages/application/src/lib/feature/page-settings-storage-feature/page-settings-storage-feature.spec.tsx, libs/pages/application/src/lib/feature/page-settings-storage-feature/page-settings-storage-feature.tsx, libs/pages/application/src/lib/ui/page-settings-storage/page-settings-storage.spec.tsx, libs/pages/application/src/lib/ui/page-settings-storage/page-settings-storage.tsx
https://qovery.atlassian.net/browse/FRT-561
=> feat(services): improvements on storage settings

libs/domains/service-helm/feature/src/lib/source-setting/source-setting.tsx
https://qovery.atlassian.net/browse/FRT-1212
=> fix(helm): fix source settings

libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx, libs/shared/iam/feature/src/index.ts, libs/shared/iam/feature/src/lib/use-user-role/use-user-role.ts, package.json, yarn.lock
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1201
---
=> feat(layout): add qovery admin banner

libs/domains/environments/feature/src/lib/environment-list/__snapshots__/environment-list.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-list/environment-list.tsx, libs/domains/services/feature/src/lib/service-list/__snapshots__/service-list.spec.tsx.snap, libs/domains/services/feature/src/lib/service-list/service-list.tsx, libs/shared/ui/src/lib/components/menu/menu-item/menu-item.tsx
https://qovery.atlassian.net/browse/FRT-1202
=> fix(ui): fix breadcrumb and link truncation

libs/pages/events/src/lib/ui/row-event/row-event.tsx, package.json, yarn.lock
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1213
---
=> feat(audit-logs): add new events

libs/pages/application/src/lib/feature/page-settings-configure-job-feature/page-settings-configure-job-feature.tsx
https://qovery.slack.com/archives/C038JMN9GUE/p1721226286045219
---
=> fix(settings-configure-job): return lifecycle_type

libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx, libs/domains/services/feature/src/lib/service-clone-modal/__snapshots__/service-clone-modal.spec.tsx.snap, libs/domains/services/feature/src/lib/service-clone-modal/service-clone-modal.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1721146378805379
---
=> fix(clone-service-modal):  fakeModal option and searchable selects 

libs/domains/clusters/feature/src/lib/cluster-delete-modal/__snapshots__/cluster-delete-modal.spec.tsx.snap, libs/domains/clusters/feature/src/lib/cluster-delete-modal/cluster-delete-modal.tsx, libs/domains/organizations/feature/src/lib/annotation-create-edit-modal/__snapshots__/annotation-create-edit-modal.spec.tsx.snap, libs/domains/services/feature/src/lib/confirmation-cancel-lifecycle-modal/__snapshots__/confirmation-cancel-lifecycle-modal.spec.tsx.snap, libs/domains/services/feature/src/lib/service-list/__snapshots__/service-list.spec.tsx.snap, libs/domains/variables/feature/src/lib/variable-list/__snapshots__/variable-list.spec.tsx.snap, libs/shared/ui/src/lib/components/checkbox/checkbox.tsx, libs/shared/ui/src/lib/components/modals/modal-confirmation/modal-confirmation.tsx
https://qovery.atlassian.net/browse/FRT-1198
=> feat(clusters): update cluster delete modal with checkboxes

libs/pages/services/src/lib/feature/page-job-create-feature/step-summary-feature/step-summary-feature.tsx
https://qovery.atlassian.net/browse/FRT-1216
---
=> fix(creation-flow): jobs auto_preview false by default

libs/domains/services/feature/src/lib/service-access-modal/service-access-modal.tsx, libs/pages/layout/src/lib/ui/breadcrumb/breadcrumb.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1721631607759309
---
=> fix(modal-access): local machine cmd

libs/pages/services/src/lib/feature/page-job-create-feature/step-introduction-feature/step-introduction-feature.tsx
Fixed wording for generic lifecycle jobs
=> fix(lifecycle-intro): use the right wording for generic lifecycle jobs

libs/domains/clusters/feature/src/lib/cluster-action-toolbar/cluster-action-toolbar.tsx, libs/domains/clusters/feature/src/lib/cluster-installation-guide-modal/cluster-installation-guide-modal.tsx, libs/domains/clusters/feature/src/lib/cluster-setup/__snapshots__/cluster-setup.spec.tsx.snap, libs/domains/clusters/feature/src/lib/cluster-setup/cluster-setup.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1215
---
=> feat(cluster-install-guide-modal):  update demo command

libs/domains/services/feature/src/lib/pods-metrics/__snapshots__/pods-metrics.spec.tsx.snap, libs/domains/services/feature/src/lib/pods-metrics/pods-metrics-skeleton.tsx, libs/domains/services/feature/src/lib/pods-metrics/pods-metrics.tsx, libs/domains/variables/feature/src/lib/output-variables/__snapshots__/output-variables.spec.tsx.snap, libs/domains/variables/feature/src/lib/output-variables/output-variables.tsx, libs/pages/application/src/lib/ui/page-general/page-general.tsx, libs/pages/database/src/lib/ui/page-general/page-general.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1214
---
=> fix(service-overview): responsive

libs/domains/service-helm/feature/src/lib/networking-port-setting-modal/__snapshots__/networking-port-setting-modal.spec.tsx.snap, libs/domains/service-helm/feature/src/lib/networking-port-setting-modal/networking-port-setting-modal.spec.tsx, libs/domains/service-helm/feature/src/lib/networking-port-setting-modal/networking-port-setting-modal.tsx, libs/domains/service-helm/feature/src/lib/networking-setting/networking-setting.spec.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1218
---
=> fix(modal-port): regex form

libs/pages/layout/src/lib/ui/breadcrumb/breadcrumb.tsx
- Bug with "close" button in the navbar level
---
=> fix(breadcrumb): full width responsive

libs/pages/logs/environment/src/lib/ui/pod-logs/pod-logs.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1721631720710649
---
=> feat(pod-name-dropdown): add pod_name tooltip

libs/pages/cluster/src/lib/ui/container/container.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1217
---
=> fix(page-cluster): remove useless badge for self managed

libs/domains/service-helm/feature/src/lib/values-override-yaml-modal/__snapshots__/values-override-yaml-modal.spec.tsx.snap, libs/domains/service-helm/feature/src/lib/values-override-yaml-modal/values-override-yaml-modal.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1210
---
=> feat(chart-raw-values-modal): add wording

libs/domains/clusters/feature/src/lib/cluster-delete-modal/__snapshots__/cluster-delete-modal.spec.tsx.snap, libs/domains/clusters/feature/src/lib/cluster-delete-modal/cluster-delete-modal.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1211
---
=> feat(clusters): update cluster delete modal

libs/pages/application/src/lib/feature/page-settings-domains-feature/crud-modal-feature/crud-modal-feature.spec.tsx, libs/pages/application/src/lib/feature/page-settings-domains-feature/crud-modal-feature/crud-modal-feature.tsx, libs/pages/application/src/lib/ui/page-settings-domains/crud-modal/crud-modal.spec.tsx, libs/pages/application/src/lib/ui/page-settings-domains/crud-modal/crud-modal.tsx
https://qovery.atlassian.net/browse/FRT-1222
=> feat(services): add use CDN flag

apps/console/src/app/app.tsx, package.json, yarn.lock
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1041
- Setup [Sentry](https://qovery.sentry.io/projects/console/?project=4507661194625024) + added notification in the **#frontend-alert** slack channel
- I didn't setup "release" feature but asking Github organization permission for Sentry
---
=> chore(sentry): init setup

libs/pages/cluster/src/lib/ui/page-settings-general/page-settings-general.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-summary/step-summary.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1209
---
=> fix(cluster): page settings general warning

libs/shared/console-shared/src/lib/cluster-settings/ui/card-cluster-feature/card-cluster-feature.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1229
---
=> fix(cluster-feature): card link stop event propagation

package.json, yarn.lock
- Update `react-xtermjs` with `peerDependencies`
---
=> chore(deps): bump react-xtermjs 1.0.9

libs/pages/application/src/lib/feature/page-settings-configure-job-feature/page-settings-configure-job-feature.tsx, libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
https://qovery.slack.com/archives/C038JMN9GUE/p1720532811750659?thread_ts=1720513590.483949&cid=C038JMN9GUE
---
=> fix(cmd): add joinArgsWithQuotes lifecycle cron

libs/domains/organizations/feature/src/lib/container-registry-services-list-modal/container-registry-services-list-modal.spec.tsx, libs/domains/organizations/feature/src/lib/container-registry-services-list-modal/container-registry-services-list-modal.tsx, package.json, yarn.lock
- Add real icons for LIFECYCLE or CRON service
---
=> fix(container-registries-services-list-modal): display CRON and LIFECYCLE icons

libs/pages/application/src/lib/feature/page-settings-domains-feature/crud-modal-feature/crud-modal-feature.tsx
https://qovery.atlassian.net/browse/FRT-1233
=> fix(services): add missing use_cdn default value

libs/domains/organizations/data-access/src/lib/domains-organizations-data-access.ts
https://qovery.atlassian.net/browse/FRT-1234
=> fix(organizations): add missing cache key

libs/shared/ui/src/lib/components/table/table-row-deployment/table-row-deployment.spec.tsx, libs/shared/ui/src/lib/components/table/table-row-deployment/table-row-deployment.tsx
https://qovery.atlassian.net/browse/FRT-1228
=> fix(services): fix links to deployment logs

libs/pages/events/src/lib/ui/row-event/row-event.tsx, libs/shared/factories/src/lib/organizations-factory.mock.ts, package.json, yarn.lock
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1231
---
=> feat(audit-logs): events icons

libs/pages/login/src/lib/ui/login/login.tsx
=> chore(login): updated messaging

libs/pages/services/src/lib/feature/page-job-create-feature/template-form-sync.tsx, package.json, yarn.lock
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1239
---
=> fix(lifecycle): update max duration minutes to seconds

libs/domains/organizations/feature/src/lib/git-branch-settings/__snapshots__/git-branch-settings.spec.tsx.snap, libs/domains/organizations/feature/src/lib/git-branch-settings/git-branch-settings.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/step-general-feature/step-general-feature.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1223
---
=> fix(root-path-field): update label and hint depending services

libs/domains/organizations/feature/src/lib/git-public-repository-settings/__snapshots__/git-public-repository-settings.spec.tsx.snap, libs/domains/organizations/feature/src/lib/git-public-repository-settings/git-public-repository-settings.spec.tsx, libs/domains/organizations/feature/src/lib/git-public-repository-settings/git-public-repository-settings.tsx, libs/domains/organizations/feature/src/lib/git-repository-setting/__snapshots__/git-repository-setting.spec.tsx.snap, libs/domains/organizations/feature/src/lib/git-repository-setting/git-repository-setting.spec.tsx, libs/domains/organizations/feature/src/lib/git-repository-setting/git-repository-setting.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/step-general-feature/__snapshots__/step-general-feature.spec.tsx.snap, libs/shared/console-shared/src/lib/git-repository-settings/feature/edit-git-repository-settings-feature/edit-git-repository-settings-feature.tsx, libs/shared/console-shared/src/lib/git-repository-settings/ui/git-repository-settings/git-repository-settings.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1238
---
=> feat(git-repository): add external link url

libs/domains/services/feature/src/lib/service-details/service-details.tsx, libs/domains/services/feature/src/lib/service-list/__snapshots__/service-list.spec.tsx.snap, libs/domains/services/feature/src/lib/service-list/service-list.tsx, libs/pages/application/src/lib/feature/page-settings-feature/page-settings-feature.tsx, libs/pages/application/src/lib/ui/page-settings-configure-job/page-settings-configure-job.tsx, libs/pages/services/src/lib/feature/page-job-create-feature/page-job-create-feature.tsx, libs/pages/services/src/lib/ui/page-job-create/step-configure/step-configure.spec.tsx, libs/pages/services/src/lib/ui/page-job-create/step-configure/step-configure.tsx, libs/shared/console-shared/src/lib/force-run-modal/ui/force-run-modal.tsx, libs/shared/console-shared/src/lib/job-configure-settings/ui/job-configure-settings.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1219
---
=> feat(job-configuration): rename to triggers section

libs/pages/database/src/lib/ui/page-settings-general/page-settings-general.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1243
---
=> fix(page-settings-database): display version callout if new version

libs/pages/services/src/lib/feature/page-new-feature/page-new-feature.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1723123407211229
---
=> fix(page-new-services): remove filter for terraform and cloudformation

libs/pages/services/src/lib/feature/page-new-feature/page-new-feature.tsx, libs/pages/services/src/lib/feature/page-new-feature/service-templates.ts
- added the IAC section
- updated the wording (first section + added info that the resource will be managed via a lifecycle job)
---
=> chore(service-list): update wording and add IAC section

libs/pages/services/src/lib/ui/page-job-create/step-summary/step-summary.tsx, libs/shared/console-shared/src/lib/force-run-modal/feature/force-run-modal-feature.spec.tsx, libs/shared/console-shared/src/lib/force-run-modal/ui/force-run-modal.tsx, libs/shared/console-shared/src/lib/job-configure-settings/ui/job-configure-settings.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1723187814403979?thread_ts=1723184754.601109&cid=C02P2JB4SEM
---
=> chore(job-configure): feedback wording

libs/pages/layout/src/lib/feature/not-found-page/not-found-page.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1241
---
=> fix(not-found-page): redirect link and status

libs/pages/events/src/lib/ui/row-event/row-event.tsx, package.json, yarn.lock
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1249
---
=> feat(audit-logs): add field user_agent

libs/pages/services/src/lib/feature/page-database-create-feature/step-general-feature/step-general-feature.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1245
---
=> fix(creation-flow-database): default mode for ON_PREMISE cloud provider

libs/domains/organizations/feature/src/lib/git-public-repository-settings/git-public-repository-settings.tsx, libs/domains/service-helm/feature/src/lib/source-setting/source-setting.tsx, libs/shared/console-shared/src/lib/general-container-settings/ui/general-container-settings.tsx
https://qovery.atlassian.net/browse/FRT-1254
=> feat(services): trim some input fields

libs/domains/variables/feature/src/lib/create-update-variable-modal/create-update-variable-modal.tsx, libs/pages/services/src/lib/feature/page-job-create-feature/step-summary-feature/step-summary-feature.tsx, package.json, yarn.lock
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1257
---
=> feat(variables): add toggle enable_interpolation_in_file

libs/pages/layout/src/lib/feature/layout/layout.tsx
https://qovery.atlassian.net/browse/FRT-1244
=> feat: add company info for intercom

libs/shared/console-shared/src/lib/layout-logs/placeholder-logs/live-placeholder/live-placeholder.spec.tsx, libs/shared/console-shared/src/lib/layout-logs/placeholder-logs/live-placeholder/live-placeholder.tsx, libs/shared/console-shared/src/lib/layout-logs/placeholder-logs/loader-placeholder/loader-placeholder.tsx, libs/shared/console-shared/src/lib/layout-logs/placeholder-logs/placeholder-logs.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1258
---
=> feat(live-logs): add placeholder if service not deployed

libs/pages/events/src/lib/ui/row-event/row-event.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1724250737683599
---
=> fix(audit-logs): display user_agent with tooltip

libs/domains/services/feature/src/lib/pod-statuses-callout/pod-statuses-callout.spec.tsx, libs/domains/services/feature/src/lib/pod-statuses-callout/pod-statuses-callout.tsx
https://qovery.atlassian.net/browse/FRT-1247
=> feat(services): update certificate error banner

libs/domains/services/feature/src/lib/service-avatar-switcher/service-avatar-switcher.tsx
https://qovery.atlassian.net/browse/FRT-1256
Note: this is not fully aligned with the designs due to several issues in the designs
- https://www.figma.com/design/L3T54WTTm9rZQwLQHCkcZg?node-id=19431-384664&m=dev#923167214
- https://www.figma.com/design/L3T54WTTm9rZQwLQHCkcZg?node-id=19431-384664&m=dev#923170219
=> feat(services): improve service icons

libs/domains/service-helm/feature/src/lib/deployment-setting/deployment-setting.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/step-general-feature/__snapshots__/step-general-feature.spec.tsx.snap
https://qovery.atlassian.net/browse/FRT-1273
=> fix(services): fix Helm install format w/ git repo

libs/domains/clusters/feature/src/lib/cluster-delete-modal/__snapshots__/cluster-delete-modal.spec.tsx.snap, libs/domains/organizations/feature/src/lib/annotation-create-edit-modal/__snapshots__/annotation-create-edit-modal.spec.tsx.snap, libs/domains/services/feature/src/lib/confirmation-cancel-lifecycle-modal/__snapshots__/confirmation-cancel-lifecycle-modal.spec.tsx.snap, libs/domains/services/feature/src/lib/service-list/__snapshots__/service-list.spec.tsx.snap, libs/domains/variables/feature/src/lib/variable-list/__snapshots__/variable-list.spec.tsx.snap, libs/pages/logs/environment/src/lib/feature/deployment-logs-feature/deployment-logs-feature.tsx, libs/pages/logs/environment/src/lib/feature/pod-logs-feature/pod-logs-feature.tsx, libs/pages/logs/environment/src/lib/ui/deployment-logs/deployment-logs.tsx, libs/pages/logs/environment/src/lib/ui/pod-logs/pod-logs.tsx, libs/shared/console-shared/src/lib/layout-logs/buttons-actions-logs/buttons-actions-logs.tsx, libs/shared/console-shared/src/lib/layout-logs/layout-logs.tsx, libs/shared/ui/src/lib/components/checkbox/checkbox.tsx
https://qovery.atlassian.net/browse/FRT-1260
=> feat(logs): remove play logs button in console logs

libs/pages/services/src/lib/feature/page-application-create-feature/step-port-feature/crud-modal-feature/crud-modal-feature.tsx, libs/pages/services/src/lib/feature/page-application-create-feature/step-port-feature/step-port-feature.tsx, libs/shared/console-shared/src/lib/flow-create-port/ui/flow-create-port/flow-create-port.tsx
https://qovery.atlassian.net/browse/FRT-1272
=> fix(ports): fix port editing

libs/domains/services/feature/src/lib/service-icon/service-icon.tsx, libs/pages/services/src/lib/feature/page-new-feature/service-templates.ts
https://qovery.atlassian.net/browse/FRT-1246
=> feat(services): add more service templates

libs/domains/clusters/feature/src/lib/cluster-type/__snapshots__/cluster-type.spec.tsx.snap, libs/domains/environments/feature/src/lib/create-clone-environment-modal/__snapshots__/create-clone-environment-modal.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-list/__snapshots__/environment-list.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-mode/__snapshots__/environment-mode.spec.tsx.snap, libs/domains/services/feature/src/lib/last-commit/__snapshots__/last-commit.spec.tsx.snap, libs/domains/services/feature/src/lib/pods-metrics/__snapshots__/pods-metrics.spec.tsx.snap, libs/domains/services/feature/src/lib/pods-metrics/pods-metrics.tsx, libs/domains/services/feature/src/lib/service-details/service-details.tsx, libs/domains/services/feature/src/lib/service-list/__snapshots__/service-list.spec.tsx.snap, libs/domains/services/feature/src/lib/service-list/service-list.tsx, libs/pages/application/src/lib/feature/page-settings-dockerfile-feature/__snapshots__/page-settings-dockerfile-feature.spec.tsx.snap, libs/pages/application/src/lib/ui/container/container.tsx, libs/pages/application/src/lib/ui/page-settings-resources/__snapshots__/page-settings-resources.spec.tsx.snap, libs/pages/cluster/src/lib/ui/container/container.tsx, libs/pages/cluster/src/lib/ui/page-settings-kubeconfig/__snapshots__/page-settings-kubeconfig.spec.tsx.snap, libs/pages/clusters/src/lib/ui/card-cluster/card-cluster.tsx, libs/pages/database/src/lib/ui/container/container.tsx, libs/pages/events/src/lib/ui/row-event/row-event.tsx, libs/pages/logs/environment/src/lib/ui/sidebar-history/sidebar-history.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/step-values-override-files-feature/__snapshots__/step-values-override-files-feature.spec.tsx.snap, libs/pages/services/src/lib/feature/page-job-create-feature/step-dockerfile-feature/__snapshots__/step-dockerfile-feature.spec.tsx.snap, libs/pages/services/src/lib/ui/container/container.tsx, libs/pages/settings/src/lib/feature/page-organization-labels-annotations-feature/__snapshots__/page-organization-labels-annotations-feature.spec.tsx.snap, libs/pages/settings/src/lib/ui/page-organization-billing-summary/invoices-list/table-row-invoice/table-row-invoice.tsx, libs/shared/ui/src/lib/components/badge/__snapshots__/badge.spec.tsx.snap, libs/shared/ui/src/lib/components/badge/badge.spec.tsx, libs/shared/ui/src/lib/components/badge/badge.tsx, libs/shared/ui/src/lib/components/button-primitive/button-primitive.tsx, libs/shared/ui/src/lib/components/table/table-row-deployment/table-row-deployment.tsx
Here’s a list of the differences (was added by Yael, but we never implemented these changes) between design and front-end that I corrected:
- Badge: Removed all sizes to avoid mistakes, as we only have one height in the design `24px`.
- Button: Fixed the height for the `xs` size to `24px`, aligning it with the design system.
- Services list: Updated the row height from `64px` to `68px`.
I navigated through all the pages to check for potential bugs but didn’t find anything 
If you could double-check, that would be great
Thanks!
---
=> fix(ui): remove badge height and update xs button height

libs/pages/services/src/lib/feature/page-job-create-feature/step-summary-feature/step-summary-feature.tsx, libs/pages/services/src/lib/feature/page-job-create-feature/template-form-sync.tsx, package.json, yarn.lock
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1274
---
=> feat(lifecycle-template): add flag enable interpolation creation flow

libs/domains/organizations/feature/src/lib/container-registry-create-edit-modal/container-registry-create-edit-modal.spec.tsx, libs/domains/organizations/feature/src/lib/container-registry-create-edit-modal/container-registry-create-edit-modal.tsx, libs/domains/organizations/feature/src/lib/container-registry-form/container-registry-form.spec.tsx, libs/domains/organizations/feature/src/lib/container-registry-form/container-registry-form.tsx, libs/domains/organizations/feature/src/lib/helm-repository-create-edit-modal/helm-repository-create-edit-modal.spec.tsx, libs/domains/organizations/feature/src/lib/helm-repository-create-edit-modal/helm-repository-create-edit-modal.tsx, libs/pages/settings/src/lib/feature/page-organization-helm-repositories-feature/page-organization-helm-repositories-feature.tsx, libs/pages/settings/src/lib/ui/page-organization-container-registries/page-organization-container-registries.tsx, libs/pages/settings/src/lib/ui/page-organization-helm-repositories/page-organization-helm-repositories.tsx, libs/shared/console-shared/src/lib/cluster-settings/feature/create-edit-credentials-modal-feature/create-edit-credentials-modal-feature.spec.tsx, libs/shared/console-shared/src/lib/cluster-settings/feature/create-edit-credentials-modal-feature/create-edit-credentials-modal-feature.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-credentials-settings/cluster-credentials-settings.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/create-edit-credentials-modal/create-edit-credentials-modal.tsx, libs/shared/ui/src/lib/components/modals/modal-crud/modal-crud.tsx
https://qovery.atlassian.net/browse/FRT-1237
=> feat(settings): cluster/helm/container credentials

libs/domains/environments/feature/src/lib/environment-list/__snapshots__/environment-list.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-list/environment-list.tsx
=> fix(environment-list): add skeleton for deployment status

libs/pages/services/src/lib/feature/page-job-create-feature/page-job-create-feature.tsx, libs/pages/services/src/lib/feature/page-job-create-feature/step-configure-feature/step-configure-feature.tsx, libs/pages/services/src/lib/feature/page-job-create-feature/step-resources-feature/step-resources-feature.tsx, libs/pages/services/src/lib/feature/page-job-create-feature/step-summary-feature/step-summary-feature.tsx, libs/pages/services/src/lib/feature/page-job-create-feature/step-variable-feature/step-variable-feature.tsx
https://qovery.atlassian.net/browse/FRT-1250
=> fix(services): fix steps names

libs/domains/service-helm/feature/src/lib/deployment-setting/deployment-setting.tsx
https://qovery.atlassian.net/browse/FRT-1250
=> fix(services): fix exception with unexisting `root_path`

libs/domains/service-helm/feature/src/lib/networking-port-setting-modal/networking-port-setting-modal.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1285
---
=> fix(networking-port-modal): slice max value length condition for port name

libs/pages/layout/src/lib/feature/spotlight-trigger/spotlight-trigger.tsx, libs/shared/util-hooks/src/lib/use-format-hotkeys/use-format-hotkeys.ts
+ Update wording ISO with Figma
**Before:**
https://github.com/user-attachments/assets/bcbb5027-db7b-4da7-8eaa-d1a2d9a6a310
**After:**
https://github.com/user-attachments/assets/8f4a533e-80f5-4ef1-b3b8-b1555f9d26b7
---
=> fix(spotlight-trigger): reload glitch macOS

libs/domains/services/feature/src/lib/service-list/__snapshots__/service-list.spec.tsx.snap, libs/domains/services/feature/src/lib/service-list/service-list.tsx
- Improve loading state for Service list
---
=> fix(service-list): add skeleton for deployment status

libs/domains/clusters/feature/src/lib/cluster-card/__snapshots__/cluster-card.spec.tsx.snap, libs/domains/clusters/feature/src/lib/cluster-card/cluster-card.spec.tsx, libs/domains/clusters/feature/src/lib/cluster-card/cluster-card.tsx, libs/pages/clusters/src/lib/feature/page-clusters-general-feature/page-clusters-general-feature.spec.tsx, libs/pages/clusters/src/lib/feature/page-clusters-general-feature/page-clusters-general-feature.tsx, libs/pages/clusters/src/lib/ui/page-clusters-general/page-clusters-general.spec.tsx, libs/pages/clusters/src/lib/ui/page-clusters-general/page-clusters-general.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1286
---
=> fix(cluster-card): prefers call `useClusterStatuses` instead of `useClusterStatus`

libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.tsx, libs/shared/console-shared/src/lib/flow-create-port/ui/crud-modal/crud-modal.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1725284704103839
---
=> fix(port-modal): callout if demo cluster only

libs/domains/service-helm/feature/src/lib/values-override-yaml-modal/values-override-yaml-modal.tsx, libs/domains/variables/feature/src/lib/code-editor-variable/code-editor-variable.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1725262195991039?thread_ts=1725034227.280149&cid=C02P2JB4SEM
---
=> fix(code-editor-variable): return YAML format for variable suggestion

libs/shared/console-shared/src/lib/general-container-settings/ui/general-container-settings.tsx
https://qovery.atlassian.net/browse/FRT-1284
=> fix(services): improve image tag fallback

libs/domains/services/feature/.eslintrc.json
Part of https://qovery.atlassian.net/browse/FRT-1230
=> chore: rename legacy plugins

README.md, pull_request_template.md
- Update some outdate paragraphes with correct content
---
=> chore: update README content

.github/workflows/test-build-and-deploy.yml
Part of https://qovery.atlassian.net/browse/FRT-1230
https://github.com/nrwl/ci/issues/104
=> ci: fix wrong coverage option

libs/domains/services/feature/src/lib/service-avatar/service-avatar.tsx, libs/domains/services/feature/src/lib/service-list/service-list.tsx
=> fix(service-list): filter service name avatar resize

libs/pages/cluster/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1292
---
=> feat(cluster-resources-settings): karpenter modal wording and set default values

libs/domains/organizations/feature/src/lib/container-registry-form/container-registry-form.tsx, libs/domains/organizations/feature/src/lib/helm-repository-create-edit-modal/helm-repository-create-edit-modal.tsx
https://qovery.atlassian.net/browse/FRT-1264
=> feat(ui): add hint to CR-HR URL configuration

libs/domains/services/feature/src/lib/service-access-modal/service-access-modal.tsx
https://qovery.atlassian.net/browse/FRT-1265
=> feat(ui): update access info wording

libs/pages/cluster/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx, libs/pages/cluster/src/lib/ui/page-settings-resources/page-settings-resources.spec.tsx, libs/pages/cluster/src/lib/ui/page-settings-resources/page-settings-resources.tsx, libs/shared/console-shared/src/lib/cluster-settings/feature/cluster-resources-settings-feature/cluster-resources-settings-feature.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx, libs/shared/ui/src/lib/components/modals/modal-confirmation/__snapshots__/modal-confirmation.spec.tsx.snap, libs/shared/ui/src/lib/components/modals/modal-confirmation/modal-confirmation.tsx, libs/shared/ui/src/lib/components/modals/modal-confirmation/use-modal-confirmation/use-modal-confirmation.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1270
https://qovery.slack.com/archives/C02NPSG2HBL/p1725375326599479
---
=> feat(cluster-resources-settings): enable karpenter option

libs/domains/organizations/feature/src/lib/hooks/use-available-container-registries/use-available-container-registries.ts
https://qovery.atlassian.net/browse/FRT-1263
=> feat(ui): sort container registries

libs/domains/organizations/feature/src/lib/git-provider-setting/__snapshots__/git-provider-setting.spec.tsx.snap, libs/domains/organizations/feature/src/lib/git-provider-setting/git-provider-setting.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/step-general-feature/__snapshots__/step-general-feature.spec.tsx.snap, libs/pages/services/src/lib/feature/page-helm-create-feature/step-values-override-files-feature/__snapshots__/step-values-override-files-feature.spec.tsx.snap
https://qovery.atlassian.net/browse/FRT-1280
=> fix(ui): rename git account select

libs/shared/console-shared/src/lib/job-configure-settings/ui/job-configure-settings.tsx
https://qovery.atlassian.net/browse/FRT-1276
=> feat(ui): add job max duration warning

libs/domains/clusters/feature/src/lib/cluster-card/cluster-card.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1288
https://qovery.slack.com/archives/C02P2JB4SEM/p1725286143834669?thread_ts=1725284704.103839&cid=C02P2JB4SEM
---
=> feat(cluster-card): add demo tag

libs/domains/organizations/feature/src/lib/git-provider-setting/git-provider-setting.spec.tsx, libs/domains/organizations/feature/src/lib/git-provider-setting/git-provider-setting.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1279
---
=> feat(select-git-token): add label and icon

libs/domains/service-helm/feature/src/lib/values-override-arguments-setting/__snapshots__/values-override-arguments-setting.spec.tsx.snap, libs/domains/service-helm/feature/src/lib/values-override-yaml-modal/__snapshots__/values-override-yaml-modal.spec.tsx.snap, libs/domains/service-helm/feature/src/lib/values-override-yaml-modal/values-override-yaml-modal.tsx, libs/domains/variables/feature/src/lib/code-editor-variable/code-editor-variable.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1287
---
=> fix(helm-raw-modal): btn suggestion position and modal height

libs/domains/clusters/feature/src/lib/cluster-access-modal/__snapshots__/cluster-access-modal.spec.tsx.snap, libs/domains/clusters/feature/src/lib/cluster-access-modal/cluster-access-modal.spec.tsx, libs/domains/clusters/feature/src/lib/cluster-access-modal/cluster-access-modal.tsx, libs/domains/clusters/feature/src/lib/cluster-action-toolbar/__snapshots__/cluster-action-toolbar.spec.tsx.snap, libs/domains/clusters/feature/src/lib/cluster-action-toolbar/cluster-action-toolbar.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1290
---
=> feat(cluster-access-modal): add new modal

libs/domains/organizations/feature/src/lib/git-public-repository-settings/git-public-repository-settings.tsx, libs/domains/service-helm/feature/src/lib/source-setting/source-setting.tsx
Unregister field "repository"
---
=> fix(repository-field): add shouldUnregister props

libs/domains/organizations/feature/src/lib/git-public-repository-settings/__snapshots__/git-public-repository-settings.spec.tsx.snap, libs/domains/organizations/feature/src/lib/git-public-repository-settings/git-public-repository-settings.tsx, libs/domains/service-helm/feature/src/lib/source-setting/source-setting.tsx, libs/domains/service-helm/feature/src/lib/values-override-files-setting/values-override-files-setting.tsx, libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx, libs/pages/application/src/lib/feature/page-settings-values-override-file-feature/page-settings-values-override-file-feature.tsx, libs/pages/services/src/lib/feature/page-application-create-feature/step-general-feature/step-general-feature.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/step-general-feature/__snapshots__/step-general-feature.spec.tsx.snap, libs/pages/services/src/lib/feature/page-helm-create-feature/step-general-feature/step-general-feature.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/step-values-override-files-feature/__snapshots__/step-values-override-files-feature.spec.tsx.snap, libs/pages/services/src/lib/feature/page-helm-create-feature/step-values-override-files-feature/step-values-override-files-feature.tsx, libs/pages/services/src/lib/feature/page-job-create-feature/step-general-feature/step-general-feature.tsx, libs/pages/services/src/lib/ui/page-application-create/step-general/step-general.tsx, libs/pages/services/src/lib/ui/page-job-create/step-general/step-general.tsx, libs/shared/console-shared/src/lib/git-repository-settings/ui/git-repository-settings/git-repository-settings.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1295
---
=> fix(helm-values-override): add missing field for git public repo

libs/shared/console-shared/src/lib/job-configure-settings/ui/job-configure-settings.tsx
https://qovery.atlassian.net/browse/FRT-1276
=> fix(services): adjust max duration warning time

libs/pages/events/src/lib/ui/custom-filter/custom-filter.tsx, libs/shared/ui/src/lib/components/date-picker/date-picker.tsx, libs/shared/ui/src/lib/components/inputs/input-select/input-select.tsx
https://qovery.atlassian.net/browse/FRT-1293
=> fix(ui): handle clickOutside for filters

libs/pages/clusters/src/lib/feature/page-clusters-create-feature/page-clusters-create-feature.tsx, libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-general-feature/step-general-feature.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx
Fix missing pieces of https://qovery.atlassian.net/browse/FRT-1270
https://qovery.atlassian.net/browse/FRT-1294
=> fix(clusters): prevent Karpenter on a prod cluster

libs/pages/application/src/lib/feature/page-settings-feature/page-settings-feature.tsx, libs/pages/application/src/lib/feature/tabs-feature/tabs-feature.tsx, libs/pages/application/src/lib/ui/container/container.tsx, libs/pages/cluster/src/lib/feature/page-settings-feature/page-settings-feature.tsx, libs/pages/database/src/lib/feature/page-settings-feature/page-settings-feature.tsx, libs/pages/database/src/lib/ui/container/container.tsx, libs/pages/environments/src/lib/ui/container/container.tsx, libs/pages/services/src/lib/feature/page-settings-feature/page-settings-feature.tsx, libs/pages/services/src/lib/ui/container/container.tsx, libs/pages/settings/src/lib/page-settings.tsx, libs/shared/ui/src/lib/components/error-boundary/error-boundary.tsx, libs/shared/ui/src/lib/components/navigation-left/navigation-left-sub-link/navigation-left-sub-link.spec.tsx, libs/shared/ui/src/lib/components/navigation-left/navigation-left-sub-link/navigation-left-sub-link.tsx, libs/shared/ui/src/lib/components/navigation-left/navigation-left.spec.tsx, libs/shared/ui/src/lib/components/navigation-left/navigation-left.stories.tsx, libs/shared/ui/src/lib/components/navigation-left/navigation-left.tsx, package.json, yarn.lock
https://qovery.atlassian.net/browse/FRT-1291
=> fix(ui): fix navigation glitch

libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
https://qovery.slack.com/archives/C038JMN9GUE/p1726475223669909
---
=> fix(job-container-settings): send correct data to edit labels

libs/pages/services/src/lib/feature/page-database-create-feature/page-database-create-feature.tsx
https://qovery.atlassian.net/browse/FRT-1308
=> fix(databases): auto select db type from template

libs/domains/organizations/feature/src/lib/container-registry-form/container-registry-form.tsx
https://qovery.atlassian.net/browse/FRT-1314
=> fix(settings): loosen generic container registry validation

libs/pages/services/src/lib/ui/page-application-create/step-general/step-general.tsx, package.json, yarn.lock
https://qovery.atlassian.net/browse/FRT-1309
=> feat(services): add show hide extra labels annotations in creation flows

libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-general-settings/cluster-general-settings.tsx
https://qovery.atlassian.net/browse/FRT-1312
=> feat(clusters): automatically set production flag for cluster depending on its name

libs/shared/console-shared/src/lib/general-container-settings/ui/general-container-settings.tsx
https://qovery.atlassian.net/browse/FRT-1315
=> fix(services): fix container image tags selection

libs/domains/organizations/feature/src/lib/container-registry-form/container-registry-form.tsx, libs/pages/cluster/src/lib/feature/page-settings-image-registry-feature/page-settings-image-registry-feature.tsx
https://qovery.atlassian.net/browse/FRT-1313
=> feat(clusters): allows self-managed cluster to change image registry

libs/domains/services/feature/src/lib/select-version-modal/select-version-modal.tsx, libs/shared/console-shared/src/lib/general-container-settings/ui/general-container-settings.tsx, libs/shared/ui/src/lib/components/inputs/input-select/input-select.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1318
https://www.loom.com/share/883e08bc1f42453090bedea01cf1e6e4
---
=> fix(input-tag): allow creatable option

libs/domains/organizations/feature/src/lib/container-registry-form/container-registry-form.tsx
https://qovery.atlassian.net/browse/FRT-1313?focusedCommentId=13216
=> feat(clusters): match new conditions to change mirroring registry

libs/domains/service-helm/feature/src/lib/source-setting/source-setting.tsx
https://qovery.atlassian.net/browse/FRT-1298
=> fix(services): fix remaining errors across helm source types

libs/domains/clusters/feature/src/lib/cluster-card/__snapshots__/cluster-card.spec.tsx.snap, libs/domains/clusters/feature/src/lib/cluster-type/__snapshots__/cluster-type.spec.tsx.snap, libs/domains/environments/feature/src/lib/create-clone-environment-modal/__snapshots__/create-clone-environment-modal.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-list/__snapshots__/environment-list.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-mode/__snapshots__/environment-mode.spec.tsx.snap, libs/domains/service-logs/feature/src/lib/list-service-logs/row-service-logs/row-service-logs.tsx, libs/domains/services/feature/src/lib/pods-metrics/__snapshots__/pods-metrics.spec.tsx.snap, libs/shared/ui/src/lib/components/badge/__snapshots__/badge.spec.tsx.snap, libs/shared/ui/src/lib/components/badge/badge.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1317
---
=> feat(row-infra-log): align badge color with design

libs/domains/services/feature/src/lib/pods-metrics/__snapshots__/pods-metrics.spec.tsx.snap, libs/domains/services/feature/src/lib/pods-metrics/pods-metrics.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1325
---
=> feat(pods-metrics): add count pods header

libs/pages/services/src/lib/ui/page-deployments/page-deployments.tsx, libs/shared/ui/src/lib/components/table/table.tsx, libs/shared/util-js/src/lib/merge-deployment-services.spec.ts, libs/shared/util-js/src/lib/merge-deployment-services.ts
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1255
---
=> fix(deployment-history-environment): sort by name and updated date

libs/shared/ui/src/lib/components/icon/icons-status/index.ts, libs/shared/ui/src/lib/components/icon/icons-status/skip.tsx, libs/shared/ui/src/lib/components/status-chip/status-chip.stories.tsx, libs/shared/ui/src/lib/components/status-chip/status-chip.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1328
---
=> feat(status-chip): add skip icon

libs/domains/environments/feature/src/lib/create-clone-environment-modal/create-clone-environment-modal.tsx, libs/domains/service-logs/feature/src/lib/breadcrumb-deployment-history/breadcrumb-deployment-history.spec.tsx, libs/domains/service-logs/feature/src/lib/breadcrumb-deployment-history/breadcrumb-deployment-history.tsx, libs/domains/service-logs/feature/src/lib/breadcrumb-deployment-logs/breadcrumb-deployment-logs.spec.tsx, libs/domains/service-logs/feature/src/lib/breadcrumb-deployment-logs/breadcrumb-deployment-logs.tsx, libs/domains/service-logs/feature/src/lib/breadcrumb-deployment-logs/stage-item/stage-item.spec.tsx, libs/domains/service-logs/feature/src/lib/header-logs/header-logs.spec.tsx, libs/domains/service-logs/feature/src/lib/header-logs/header-logs.tsx, libs/domains/service-logs/feature/src/lib/list-deployment-logs/list-deployment-logs.spec.tsx, libs/domains/service-logs/feature/src/lib/list-deployment-logs/list-deployment-logs.tsx, libs/domains/service-logs/feature/src/lib/list-deployment-logs/row-deployment-logs/row-deployment-logs.spec.tsx, libs/domains/service-logs/feature/src/lib/list-deployment-logs/row-deployment-logs/row-deployment-logs.tsx, libs/domains/service-logs/feature/src/lib/list-service-logs/list-service-logs.tsx, libs/pages/application/src/lib/ui/page-general/page-general.tsx, libs/pages/layout/src/lib/ui/breadcrumb/breadcrumb.tsx, libs/pages/logs/environment/src/lib/feature/deployment-logs-feature/deployment-logs-feature.tsx, libs/pages/logs/environment/src/lib/feature/pod-logs-feature/pod-logs-feature.tsx, libs/pages/logs/environment/src/lib/page-environment-logs.tsx, libs/shared/ui/src/lib/components/menu/menu-group/menu-group.tsx, libs/shared/ui/src/lib/components/menu/menu-item/menu-item.tsx
=> feat(logs): add header navigation

libs/domains/organizations/feature/src/lib/container-registry-create-edit-modal/container-registry-create-edit-modal.tsx, libs/domains/organizations/feature/src/lib/container-registry-form/container-registry-form.spec.tsx, libs/domains/organizations/feature/src/lib/container-registry-form/container-registry-form.tsx, libs/domains/organizations/feature/src/lib/helm-repository-create-edit-modal/helm-repository-create-edit-modal.spec.tsx, libs/domains/organizations/feature/src/lib/helm-repository-create-edit-modal/helm-repository-create-edit-modal.tsx, libs/domains/services/data-access/src/lib/domains-services-data-access.ts, package.json, yarn.lock
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1332
---
=> fix(registry): add project_id field for scaleway

libs/domains/environments/feature/src/lib/environment-action-toolbar/environment-action-toolbar.tsx, libs/domains/environments/feature/src/lib/environment-list/environment-list.tsx, libs/pages/environments/src/lib/ui/container/container.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1728460126943419
---
=> fix(create-clone-environment-modal): add fakeModal option

libs/domains/services/feature/src/lib/pods-metrics/pods-metrics.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1728553171266389
---
=> fix(pods-metrics): use ws for container version

libs/domains/clusters/feature/src/lib/cluster-action-toolbar/__snapshots__/cluster-action-toolbar.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-action-toolbar/__snapshots__/environment-action-toolbar.spec.tsx.snap, libs/domains/services/feature/src/lib/service-action-toolbar/__snapshots__/service-action-toolbar.spec.tsx.snap, libs/domains/services/feature/src/lib/service-links-popover/__snapshots__/service-links-popover.spec.tsx.snap, libs/domains/variables/feature/src/lib/dropdown-variable/__snapshots__/dropdown-variable.spec.tsx.snap, libs/domains/variables/feature/src/lib/field-variable-suggestion/__snapshots__/field-variable-suggestion.spec.tsx.snap, libs/pages/clusters/src/lib/ui/page-clusters-create/step-features/button-popover-subnets/__snapshots__/button-popover-subnets.spec.tsx.snap, libs/shared/ui/src/lib/components/dropdown-menu/dropdown-menu.tsx, libs/shared/ui/src/lib/components/menu/menu.tsx, libs/shared/ui/src/lib/components/popover/popover.tsx, libs/shared/ui/src/lib/styles/components/menu.scss
- Add border for dark version
---
=> fix(ui): update dark version popover menu and dropdown

libs/domains/clusters/feature/src/lib/cluster-action-toolbar/cluster-action-toolbar.tsx
just update the text on info and entry in list
---
=> chore: update wording on available upgrade

libs/domains/variables/feature/src/lib/create-update-variable-modal/create-update-variable-modal.tsx, libs/shared/ui/src/lib/components/inputs/input-text-area/input-text-area.tsx, package.json, yarn.lock
https://qovery.slack.com/archives/C038JMN9GUE/p1728918966738059
---
=> fix(create-update-variable-modal): allow null value during edition

libs/domains/service-logs/feature/src/lib/list-deployment-logs/filters-stage-step/filters-stage-step.tsx, libs/domains/service-logs/feature/src/lib/list-deployment-logs/list-deployment-logs.spec.tsx, libs/domains/service-logs/feature/src/lib/list-deployment-logs/list-deployment-logs.tsx, libs/shared/ui/src/lib/components/tooltip/tooltip.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1330
And adding feedback for https://qovery.slack.com/archives/C02NPSG2HBL/p1728487593457479?thread_ts=1727785723.481289&cid=C02NPSG2HBL
---
=> feat(deployment-logs): add details tooltip for filter stage

package.json, yarn.lock
=> chore: update open-api 1.1.492

libs/domains/service-logs/feature/src/lib/list-deployment-logs/list-deployment-logs.spec.tsx, libs/domains/service-logs/feature/src/lib/list-deployment-logs/list-deployment-logs.tsx, libs/domains/service-logs/feature/src/lib/list-service-logs/list-service-logs.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1729580761228409
---
=> fix(service-logs): scrolling height

libs/domains/clusters/feature/src/lib/cluster-setup/__snapshots__/cluster-setup.spec.tsx.snap, libs/domains/clusters/feature/src/lib/cluster-setup/cluster-setup.tsx
- Adding callout with information for SELF_MANAGED creation flow
---
=> feat(cluster-setup): callout for self managed

libs/domains/environment-logs/feature/src/lib/environment-stages/environment-stages.tsx, libs/domains/service-logs/feature/src/lib/header-logs/header-logs.tsx, libs/pages/layout/src/lib/feature/dark-mode-enabler/dark-mode-enabler.tsx, libs/pages/logs/environment/src/lib/feature/environment-stages-feature/environment-stages-feature.tsx, libs/shared/ui/src/lib/styles/main.scss
- Improve UI for OS with scrollbar by default
---
=> fix(scrollbar): ui accessibility

libs/domains/organizations/feature/src/lib/container-registry-form/container-registry-form.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1333
---
=> fix(container-registry): disabled demo cluster

libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx, libs/pages/layout/src/lib/ui/navigation/navigation.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1335
---
=> feat(navigation): cluster error icon statuses

libs/domains/environment-logs/feature/src/lib/header-pre-check-logs/header-pre-check-logs.tsx, libs/domains/variables/feature/src/lib/create-update-variable-modal/create-update-variable-modal.tsx, package.json, yarn.lock
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1345
---
=> fix(edit-variable-modal): add missing enable_interpolation_in_file field

libs/domains/clusters/feature/src/lib/cluster-card/__snapshots__/cluster-card.spec.tsx.snap, libs/domains/clusters/feature/src/lib/cluster-card/cluster-card.tsx, libs/domains/clusters/feature/src/lib/cluster-installation-guide-modal/cluster-installation-guide-modal.tsx, libs/pages/clusters/src/lib/feature/page-clusters-create-feature/page-clusters-create-feature.tsx, libs/pages/clusters/src/lib/feature/page-new-feature/page-new-feature.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-general/step-general.spec.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-general/step-general.tsx, libs/shared/ui/src/lib/styles/main.scss
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1341
---
=> feat(page-new-cluster): update grid cards

libs/domains/environments/data-access/src/lib/domains-environments-data-access.ts
https://qovery.slack.com/archives/C02P2JB4SEM/p1730285259191339
---
=> fix(environment-deployment-status): remove rest call cause glitch with ws

libs/pages/clusters/src/lib/feature/page-new-feature/page-new-feature.tsx
- Fix responsive for small screen
---
=> fix(new-cluster-page): responsive alignment

__tests__/mocks.ts, libs/domains/service-logs/feature/src/lib/list-service-logs/list-service-logs.tsx, libs/domains/service-logs/feature/src/lib/service-logs-placeholder/service-logs-placeholder.tsx, libs/shared/util-hooks/src/index.ts
https://qovery.slack.com/archives/C02P2JB4SEM/p1730363016647679
---
=> fix(service-logs): display header during loading and add placeholder msg

libs/shared/console-shared/src/lib/cluster-settings/feature/cluster-resources-settings-feature/cluster-resources-settings-feature.spec.tsx, libs/shared/console-shared/src/lib/cluster-settings/feature/cluster-resources-settings-feature/cluster-resources-settings-feature.tsx
https://qovery.slack.com/archives/C02NPSG2HBL/p1730551911538659
---
=> fix(cluster-creation-flow): remove EC2 cluster type

libs/domains/services/feature/src/lib/pod-statuses-callout/__snapshots__/pod-statuses-callout.spec.tsx.snap, libs/domains/services/feature/src/lib/pod-statuses-callout/pod-statuses-callout.tsx
https://qovery.slack.com/archives/C038JMN9GUE/p1731074145056389
---
=> fix(pod-statuses-callout): add certificate callout if runningState is error

libs/domains/service-logs/feature/src/lib/list-service-logs/list-service-logs.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1343
---
=> feat(nginx-button): add external link with tooltip

libs/pages/application/src/lib/ui/container/container.tsx, libs/pages/database/src/lib/ui/container/container.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1340
---
=> fix(services): update wording deployment history tab

libs/domains/environments/feature/src/lib/environment-action-toolbar/__snapshots__/environment-action-toolbar.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-action-toolbar/environment-action-toolbar.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1344
---
=> feat(environment-action-toolbar): update log icon

libs/pages/services/src/lib/ui/page-application-create/step-general/step-general.tsx, libs/pages/services/src/lib/ui/page-database-create/step-general/step-general.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1329
---
=> fix(service-creation-flow): labels/annotations if source selected

libs/pages/database/src/lib/ui/page-settings-resources/page-settings-resources.tsx, libs/pages/services/src/lib/feature/page-database-create-feature/step-general-feature/step-general-feature.tsx, libs/pages/services/src/lib/feature/page-database-create-feature/step-resources-feature/step-resources-feature.spec.tsx, libs/pages/services/src/lib/feature/page-database-create-feature/step-resources-feature/step-resources-feature.tsx, libs/pages/services/src/lib/ui/page-database-create/step-general/step-general.tsx, libs/pages/services/src/lib/ui/page-database-create/step-resources/step-resources.tsx, libs/shared/console-shared/src/lib/database-settings-resources/feature/settings-resources-instance-types-feature/setting-resources-instance-types-feature.tsx, libs/shared/console-shared/src/lib/database-settings-resources/ui/database-settings-resources/database-settings-resources.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1346
---
=> feat(database-creation-flow): add default instance type for managed

libs/domains/cloud-providers/feature/src/lib/karpenter-instance-filter-modal/instance-category/instance-category.spec.tsx, libs/domains/cloud-providers/feature/src/lib/karpenter-instance-filter-modal/instance-category/instance-category.tsx, libs/domains/cloud-providers/feature/src/lib/karpenter-instance-filter-modal/karpenter-instance-filter-modal.tsx
https://qovery.slack.com/archives/C02NPSG2HBL/p1731679616161079?thread_ts=1730898724.878129&cid=C02NPSG2HBL
---
=> feat(karpenter-instance-modal): add tooltip for disabled cat and families

libs/domains/cloud-providers/feature/src/lib/karpenter-instance-filter-modal/karpenter-instance-filter-modal.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1732198155660069
---
=> fix(karpenter-instance-filter-modal): add overflow selected instance section

libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1366
---
=> feat(cluster-slider-nodes): allow minimum 3 instance

libs/domains/service-logs/feature/src/lib/header-logs/header-logs.tsx, libs/domains/service-logs/feature/src/lib/list-deployment-logs/list-deployment-logs.tsx, libs/domains/service-logs/feature/src/lib/list-service-logs/list-service-logs.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1348
* [`libs/domains/service-logs/feature/src/lib/header-logs/header-logs.tsx`](diffhunk://#diff-476b9ba8aca95449c76dde0e11538ae8448454669039d5a329b47ef9d8a70b92L4-R4): Removed unnecessary imports of `ENVIRONMENT_LOGS_URL` and `ENVIRONMENT_STAGES_URL`.
* [`libs/domains/service-logs/feature/src/lib/header-logs/header-logs.tsx`](diffhunk://#diff-476b9ba8aca95449c76dde0e11538ae8448454669039d5a329b47ef9d8a70b92L60-L79): Removed the conditional rendering of the environment stages link for 'DEPLOYMENT' type.
* [`libs/domains/service-logs/feature/src/lib/list-deployment-logs/list-deployment-logs.tsx`](diffhunk://#diff-831d814aa77dded52f2a26bfd224104a6b8aa6046966020eb0f864207598c7d4L295-R374): Added an …
=> feat(deployment-logs): update pipeline button

libs/shared/ui/src/lib/styles/components/input.scss
- Update padding to be iso with refactoring from 16px to 12px
---
=> fix(input-select): padding value

libs/domains/organizations/feature/src/lib/hooks/use-container-images/use-container-images.ts, libs/domains/organizations/feature/src/lib/hooks/use-container-versions/use-container-versions.ts, libs/shared/console-shared/src/lib/general-container-settings/ui/general-container-settings.spec.tsx, libs/shared/console-shared/src/lib/general-container-settings/ui/image-name.tsx, libs/shared/ui/src/lib/components/inputs/input-select/input-select.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1307
---
=> fix(general-container-settings): debounce every 500ms image searching

libs/shared/console-shared/src/lib/general-container-settings/ui/image-name.tsx
https://qovery.slack.com/archives/C038JMN9GUE/p1732808878417559
---
=> fix(input-image-name): no images fetching if GCR anonymous

libs/domains/environment-logs/feature/src/lib/environment-stages/environment-stages.tsx, libs/domains/environment-logs/feature/src/lib/header-pre-check-logs/header-pre-check-logs.tsx, libs/domains/environment-logs/feature/src/lib/list-pre-check-logs/list-pre-check-logs.tsx, libs/domains/service-logs/feature/src/lib/header-logs/header-logs.tsx, libs/domains/service-logs/feature/src/lib/list-deployment-logs/list-deployment-logs.tsx, libs/pages/logs/environment/src/lib/page-environment-logs.tsx
https://qovery.slack.com/archives/C02NPSG2HBL/p1732742115728479
---
=> fix(list-pre-check): allow version id for statuses

libs/shared/util-js/src/lib/format-metric.ts
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1355
---
=> fix(format-metric): return value if current_metric is 0

libs/domains/services/feature/src/lib/service-template-indicator/service-template-indicator.tsx
- Fix position service avatar indicator
---
=> fix(service-template-indicator): add background rounded

libs/domains/services/feature/src/lib/pod-details/__snapshots__/pod-details.spec.tsx.snap, libs/domains/services/feature/src/lib/pod-details/pod-details.tsx, libs/domains/services/feature/src/lib/pods-metrics/empty-state.tsx, libs/domains/services/feature/src/lib/pods-metrics/pods-metrics.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1391
---
=> fix(service-overview): memoized metrics table

libs/domains/services/feature/src/lib/pod-statuses-callout/__snapshots__/pod-statuses-callout.spec.tsx.snap, libs/domains/services/feature/src/lib/pod-statuses-callout/pod-statuses-callout.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1733737317687109
---
=> fix(pod-statuses-callout): clear status btn for jobs warning

libs/domains/environments/feature/src/lib/create-clone-environment-modal/create-clone-environment-modal.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1399
---
=> fix(environment-modal): remove regex name field

libs/domains/services/feature/src/lib/advanced-settings/advanced-settings.spec.tsx, libs/domains/services/feature/src/lib/advanced-settings/advanced-settings.tsx, libs/pages/cluster/src/lib/feature/page-settings-advanced-feature/page-settings-advanced-feature.spec.tsx, libs/pages/cluster/src/lib/ui/page-settings-advanced/page-settings-advanced.spec.tsx, libs/pages/cluster/src/lib/ui/page-settings-advanced/page-settings-advanced.tsx
https://qovery.slack.com/archives/C02NQ0LC8M9/p1734343388956569
---
=> feat(advanced-settings): replace input-text to textarea

libs/domains/cloud-providers/feature/src/lib/karpenter-instance-filter-modal/instance-category/instance-category.spec.tsx, libs/domains/cloud-providers/feature/src/lib/karpenter-instance-filter-modal/karpenter-instance-filter-modal.tsx, libs/pages/settings/src/lib/ui/page-organization-members/page-organization-members.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1373
---
=> fix(karpenter-selection-modal): add some improvements

libs/pages/cluster/src/lib/ui/page-settings-advanced/page-settings-advanced.tsx, libs/shared/ui/src/lib/components/table-edition/table-edition.tsx
- Fix height of the row with Firefox
---
=> fix(cluster-advanced-settings): row height

libs/domains/service-logs/feature/src/lib/list-deployment-logs/filters-stage-step/filters-stage-step.tsx, libs/domains/service-logs/feature/src/lib/list-deployment-logs/list-deployment-logs.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1372
---
=> feat(deployment-logs): hide build step for container services and helm charts

libs/domains/services/data-access/src/lib/domains-services-data-access.ts, libs/domains/services/feature/src/lib/last-commit/__snapshots__/last-commit.spec.tsx.snap, libs/domains/services/feature/src/lib/last-commit/last-commit.tsx, libs/domains/services/feature/src/lib/last-version/__snapshots__/last-version.spec.tsx.snap, libs/domains/services/feature/src/lib/last-version/last-version.spec.tsx, libs/domains/services/feature/src/lib/last-version/last-version.tsx, libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx, libs/domains/services/feature/src/lib/service-list/__snapshots__/service-list.spec.tsx.snap, libs/domains/services/feature/src/lib/service-list/service-list.spec.tsx, libs/domains/services/feature/src/lib/service-list/service-list.tsx, libs/domains/services/feature/src/lib/service-template-indicator/service-template-indicator.tsx, libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.spec.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/step-general-feature/step-general-feature.tsx, libs/pages/services/src/lib/feature/page-new-feature/service-templates.ts, libs/pages/services/src/lib/ui/page-application-create/step-general/step-general.tsx, libs/pages/services/src/lib/ui/page-database-create/step-general/step-general.tsx, libs/pages/services/src/lib/ui/page-job-create/step-general/step-general.tsx, libs/shared/factories/src/lib/application-factory.mock.ts, libs/shared/factories/src/lib/container-factory.mock.ts, libs/shared/factories/src/lib/database-factory.mock.ts, libs/shared/factories/src/lib/helm-factory.mock.ts, libs/shared/factories/src/lib/job-factory.mock.ts, libs/shared/ui/src/lib/components/copy-to-clipboard/copy-to-clipboard.tsx, libs/shared/ui/src/lib/components/link/link.tsx, libs/shared/util-services/src/lib/build-edit-service-payload.spec.ts, package.json, yarn.lock
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1301
---
=> feat(service-list): add new design

README.md
Revised the main header in the README to "Web Console" for better alignment with the content and purpose. This change enhances the document's readability and focus.
---
=> Update README header to "Web Console"

libs/domains/services/feature/src/lib/last-version/last-version.tsx, libs/domains/services/feature/src/lib/service-list/service-list.tsx
https://qovery.slack.com/archives/C038JMN9GUE/p1737018722450679
---
=> fix(service-list): container info truncate commit id and container name

libs/domains/service-logs/feature/src/lib/deployment-logs-placeholder/deployment-logs-placeholder.spec.tsx, libs/domains/service-logs/feature/src/lib/deployment-logs-placeholder/deployment-logs-placeholder.tsx, libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx, libs/domains/services/feature/src/lib/service-clone-modal/service-clone-modal.tsx, libs/domains/services/feature/src/lib/service-list/service-list.tsx
* https://qovery.atlassian.net/browse/FRT-1416
* https://qovery.atlassian.net/browse/FRT-1414
* https://qovery.atlassian.net/browse/FRT-1411
* https://qovery.atlassian.net/browse/FRT-1413
---
=> chore: wording updates

libs/domains/clusters/feature/src/lib/nodepools-resources-settings/nodepools-resources-settings.spec.tsx, libs/domains/clusters/feature/src/lib/nodepools-resources-settings/nodepools-resources-settings.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1409
---
=> fix(karpenter): consolidation setting detail ui

libs/domains/environments/feature/src/lib/hooks/use-cancel-deployment-environment/use-cancel-deployment-environment.ts, libs/domains/environments/feature/src/lib/hooks/use-delete-environment/use-delete-environment.ts, libs/domains/environments/feature/src/lib/hooks/use-deploy-all-services/use-deploy-all-services.ts, libs/domains/environments/feature/src/lib/hooks/use-deploy-environment/use-deploy-environment.ts, libs/domains/environments/feature/src/lib/hooks/use-stop-environment/use-stop-environment.ts, libs/domains/services/feature/src/lib/hooks/use-cancel-deployment-service/use-cancel-deployment-service.ts, libs/domains/services/feature/src/lib/hooks/use-delete-all-services/use-delete-all-services.ts, libs/domains/services/feature/src/lib/hooks/use-deploy-service/use-deploy-service.ts, libs/domains/services/feature/src/lib/hooks/use-restart-all-services/use-restart-all-services.ts, libs/domains/services/feature/src/lib/hooks/use-restart-service/use-restart-service.ts, libs/domains/services/feature/src/lib/hooks/use-stop-all-services/use-stop-all-services.ts, libs/domains/services/feature/src/lib/hooks/use-stop-service/use-stop-service.ts
- Replace `See Deployment Logs` to `See deployment logs`
---
=> chore(toast): update deployment logs text

libs/domains/clusters/feature/src/lib/nodepools-resources-settings/nodepool-modal/nodepool-modal.spec.tsx, libs/domains/clusters/feature/src/lib/nodepools-resources-settings/nodepool-modal/nodepool-modal.tsx, libs/domains/clusters/feature/src/lib/nodepools-resources-settings/nodepools-resources-settings.tsx, libs/pages/cluster/src/lib/ui/page-settings-resources/page-settings-resources.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1422
---
=> feat(cluster-resources): update Karpenter UI

libs/domains/service-logs/feature/src/lib/list-service-logs/list-service-logs.tsx, libs/domains/services/feature/src/lib/pods-metrics/pods-metrics.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1737381617795729
https://qovery.slack.com/archives/C02P2JB4SEM/p1737627119739149
---
=> fix(service-metrics): truncate version

.github/workflows/test-build-and-deploy.yml
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
---
=> chore: update download-artifact version

.github/workflows/test-build-and-deploy.yml, jest.preset.js
=> chore: CI update workflow upload-artificat@v4 and nx-cloud-agents.yml@v0.15.0

libs/domains/clusters/feature/src/lib/nodepools-resources-settings/nodepool-modal/nodepool-modal.tsx, libs/pages/cluster/src/lib/ui/page-settings-resources/page-settings-resources.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-resources/step-resources.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1738076078438759
https://qovery.atlassian.net/browse/FRT-1429
---
=> fix(cluster-creation-flow): show SCW resources configuration section

libs/domains/clusters/feature/src/lib/cluster-access-modal/__snapshots__/cluster-access-modal.spec.tsx.snap, libs/domains/clusters/feature/src/lib/cluster-access-modal/cluster-access-modal.spec.tsx, libs/domains/clusters/feature/src/lib/cluster-access-modal/cluster-access-modal.tsx, libs/domains/clusters/feature/src/lib/cluster-action-toolbar/cluster-action-toolbar.tsx, libs/domains/services/feature/src/lib/service-access-modal/service-access-modal.tsx
https://qovery.atlassian.net/browse/FRT-1426
https://qovery.atlassian.net/browse/FRT-1431
---
=> feat(cluster-access-modal): add custom content for SELF_MANAGED cluster

libs/domains/environments/feature/src/lib/hooks/use-deployment-history/use-deployment-history.ts, libs/domains/environments/feature/src/lib/hooks/use-deployment-queue/use-deployment-queue.ts, libs/pages/environments/src/lib/feature/page-deployment-rules-feature/page-deployment-rules-feature.tsx, libs/pages/environments/src/lib/ui/container/container.tsx, libs/pages/services/src/lib/feature/page-deployments-feature/page-deployments-feature.tsx, libs/pages/services/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx, libs/pages/services/src/lib/feature/page-variables-feature/page-variables-feature.tsx, libs/pages/services/src/lib/ui/page-general/page-general.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1418
---
=> fix(deployment-history): add notifyOnChangeProps to avoid useless re-rendering

libs/domains/services/feature/src/lib/service-access-modal/service-access-modal.tsx
https://qovery.atlassian.net/browse/FRT-1436
---
=> feat(service-access-modal): add qovery shell command in access info

libs/domains/services/feature/src/lib/service-list/service-list.tsx, libs/pages/services/src/lib/feature/page-application-create-feature/page-application-create-feature.tsx, libs/pages/services/src/lib/feature/page-database-create-feature/page-database-create-feature.tsx, libs/pages/services/src/lib/feature/page-helm-create-feature/page-helm-create-feature.tsx, libs/pages/services/src/lib/feature/page-job-create-feature/page-job-create-feature.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1425
---
=> chore(feature-flag): remove service-dropdown-list

libs/domains/service-logs/feature/src/lib/breadcrumb-deployment-history/breadcrumb-deployment-history.spec.tsx, libs/domains/service-logs/feature/src/lib/breadcrumb-deployment-history/breadcrumb-deployment-history.tsx, libs/domains/services/feature/src/lib/hooks/use-deploy-service/use-deploy-service.ts, libs/domains/services/feature/src/lib/hooks/use-restart-service/use-restart-service.ts, libs/domains/services/feature/src/lib/hooks/use-stop-service/use-stop-service.ts, libs/pages/logs/environment/src/lib/page-environment-logs.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1430
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1362
---
=> feat(page-environment-logs): add placeholder out of date logs

libs/pages/application/src/lib/feature/page-settings-feature/page-settings-feature.tsx, libs/pages/application/src/lib/ui/page-settings-configure-job/page-settings-configure-job.tsx, libs/pages/services/src/lib/feature/page-job-create-feature/page-job-create-feature.tsx, libs/pages/services/src/lib/ui/page-job-create/step-configure/step-configure.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1402
---
=> chore(cronjob-settings): update wording

libs/pages/application/src/lib/feature/page-settings-feature/page-settings-feature.tsx, libs/pages/application/src/lib/ui/page-settings-configure-job/page-settings-configure-job.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1739203941280809
---
=> fix(service-settings): CRON condition matching

libs/domains/environments/feature/src/lib/environment-deployment-list/dropdown-services/dropdown-services.spec.tsx, libs/domains/environments/feature/src/lib/environment-deployment-list/dropdown-services/dropdown-services.tsx, libs/domains/environments/feature/src/lib/environment-deployment-list/environment-deployment-list.tsx, libs/domains/services/feature/src/lib/service-deployment-list/service-deployment-list.tsx, libs/shared/ui/src/lib/components/action-trigger-status-chip/action-trigger-status-chip.tsx
https://qovery.slack.com/archives/C02NPSG2HBL/p1739344454009619
---
=> fix(deployment-history): add stage pagination and logs link for error statuses

libs/pages/clusters/src/lib/ui/page-clusters-create/step-summary/step-summary.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1739788212818339
---
=> fix(cluster-creation-flow): remove create and install condition for Karpenter

libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx
https://qovery.atlassian.net/browse/FRT-1447
---
=> fix(cluster-resources): condition existing VPC popover

libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx
- Disabled Karpenter migration for production cluster
---
=> fix(cluster): disabled migration managed to karpenter production

libs/pages/clusters/src/lib/ui/container/container.spec.tsx
=> chore: trigger new deployment

libs/pages/clusters/src/lib/ui/page-clusters-create/step-features/step-features.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1442
---
=> fix(cluster-creation-flow): add stop propagation for feature card

libs/domains/clusters/feature/src/lib/cluster-action-toolbar/cluster-action-toolbar.tsx, libs/domains/environments/feature/src/lib/environment-action-toolbar/environment-action-toolbar.tsx, libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1416
---
=> feat(db-stopping-modal): add warning time for mysql and postresql

libs/domains/services/feature/src/lib/pods-metrics/empty-state.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1412
---
=> fix(cronjob-overview): empty state never executed service

libs/shared/console-shared/src/lib/cluster-settings/feature/cluster-credentials-settings-feature/cluster-credentials-settings-feature.tsx, libs/shared/console-shared/src/lib/cluster-settings/feature/create-edit-credentials-modal-feature/create-edit-credentials-modal-feature.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/create-edit-credentials-modal/create-edit-credentials-modal.tsx
https://qovery.atlassian.net/browse/FRT-1334
---
=> chore(credentials-warning): add a warning while editing cluster credentials

libs/pages/application/src/lib/feature/page-settings-dockerfile-feature/page-settings-dockerfile-feature.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1741159981368409
---
=> fix(settings-dockerfile): remove validate state buggy form

libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx
- Enabled Karpenter migration for production
---
=> fix(cluster): enabled migration karpenter production

libs/domains/organizations/feature/src/lib/git-token-create-edit-modal/git-token-create-edit-modal.spec.tsx, libs/domains/organizations/feature/src/lib/git-token-create-edit-modal/git-token-create-edit-modal.tsx
add the token id in the token edit modal
https://qovery.atlassian.net/browse/FRT-1456
---
=> feat(FRT-1456): add id in token edit modal

libs/domains/organizations/feature/src/lib/helm-repository-create-edit-modal/helm-repository-create-edit-modal.spec.tsx, libs/domains/organizations/feature/src/lib/helm-repository-create-edit-modal/helm-repository-create-edit-modal.tsx
add the ID in the edit modal for helm charts 
FRT-1456
---
=> feat(FRT-1456): add id in edit modal for helm repositories

libs/domains/organizations/feature/src/lib/container-registry-create-edit-modal/container-registry-create-edit-modal.tsx, libs/domains/organizations/feature/src/lib/container-registry-form/container-registry-form.tsx
add the registry id into the edit modal
FRT-1456
---
=> feat(FRT-1456): add id to container registry modal

libs/domains/services/feature/src/lib/service-deployment-list/service-deployment-list.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1459
---
=> fix(service-deployment-history): show container version

libs/shared/console-shared/src/lib/cluster-settings/ui/create-edit-credentials-modal/create-edit-credentials-modal.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1334
---
=> fix(cluster-credential-modal): display warning edit modal only

libs/domains/service-helm/feature/src/lib/source-setting/source-setting.tsx, libs/pages/settings/src/lib/feature/page-organization-helm-repositories-feature/page-organization-helm-repositories-feature.tsx, libs/shared/ui/src/lib/components/modal/modal.tsx
https://qovery.atlassian.net/jira/software/c/projects/QOV/boards/56?selectedIssue=QOV-108
---
=> fix(modal): fakeModal props not working with alert modal

libs/pages/settings/src/lib/feature/page-organization-billing-feature/page-organization-billing-feature.tsx
https://qovery.atlassian.net/jira/software/c/projects/QOV/boards/56?selectedIssue=QOV-553
---
=> chore: remove custom placeholder credit card modal

libs/pages/logs/environment/src/lib/feature/environment-stages-feature/environment-stages-feature.spec.tsx, libs/pages/logs/environment/src/lib/feature/environment-stages-feature/environment-stages-feature.tsx
https://qovery.atlassian.net/browse/QOV-116
---
=> feat: hide skipped services by default in pipeline view

libs/domains/clusters/feature/src/lib/cluster-card/cluster-card.tsx
https://qovery.atlassian.net/jira/software/c/projects/QOV/boards/56?selectedIssue=QOV-71
---
=> fix(cluster-card): add missing statuses deployment failed

libs/domains/environments/feature/src/lib/create-clone-environment-modal/__snapshots__/create-clone-environment-modal.spec.tsx.snap, libs/domains/environments/feature/src/lib/create-clone-environment-modal/create-clone-environment-modal.spec.tsx, libs/domains/environments/feature/src/lib/create-clone-environment-modal/create-clone-environment-modal.tsx, package.json, yarn.lock
https://qovery.atlassian.net/browse/QOV-65
---
=> feat(environment-clone-modal): add project_id field

libs/pages/layout/src/lib/feature/spotlight-trigger/spotlight-trigger.tsx, libs/shared/spotlight/feature/src/lib/sub-command/sub-command.tsx
- Added cmd k case insensitive
https://qovery.slack.com/archives/C02NPSG2HBL/p1744202540743999?thread_ts=1744170459.679139&cid=C02NPSG2HBL
---
=> fix(spotlight): cmd+k case insensitive

libs/pages/onboarding/src/lib/feature/container/container.tsx, libs/pages/onboarding/src/lib/feature/onboarding-pricing/onboarding-pricing.tsx, libs/pages/onboarding/src/lib/ui/step-pricing/step-pricing.tsx
https://qovery.atlassian.net/browse/QOV-622
---
=> chore(onboarding): remove free plan

libs/domains/clusters/feature/src/lib/cluster-card/__snapshots__/cluster-card.spec.tsx.snap, libs/domains/clusters/feature/src/lib/cluster-card/cluster-card.tsx, libs/domains/clusters/feature/src/lib/cluster-running-status-badge/cluster-running-status-badge.tsx
https://qovery.atlassian.net/jira/software/c/projects/QOV/boards/56?selectedIssue=QOV-617
---
=> fix(cluster-card): add missing queued label

libs/shared/spotlight/feature/src/lib/spotlight/spotlight.tsx, libs/shared/ui/src/lib/components/command-menu/command-menu.tsx
https://qovery.slack.com/archives/C02PGRVRMD2/p1745330706274349
---
=> fix(spotlight): update width and weight

libs/domains/clusters/feature/src/lib/cluster-card/__snapshots__/cluster-card.spec.tsx.snap, libs/domains/clusters/feature/src/lib/cluster-card/cluster-card.tsx, libs/pages/clusters/src/lib/ui/page-clusters-general/page-clusters-general.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1745394555065269
---
=> fix(clusters): update responsive behavior

libs/state/util-queries/src/lib/use-react-query-ws-subscription/use-react-query-ws-subscription.ts
- `shouldReconnect` allow `boolean` or `number` to set maximum of reconnection
---
=> fix(ws-subscription): simplify max attempts shouldReconnect props

libs/domains/environments/feature/src/lib/environment-deployment-list/environment-deployment-list.tsx, libs/pages/services/src/lib/feature/page-database-create-feature/step-resources-feature/step-resources-feature.spec.tsx
https://qovery.atlassian.net/jira/software/c/projects/QOV/boards/56?selectedIssue=QOV-90
---
=> fix(environment-deployment-list): dropdown cancel deployment with queue status

libs/domains/clusters/feature/src/lib/cluster-card/cluster-card.tsx, libs/shared/ui/src/lib/components/status-chip/status-chip.tsx, package.json, yarn.lock
https://qovery.atlassian.net/browse/QOV-625
https://qovery.slack.com/archives/C02P2JB4SEM/p1745589574914349
---
=> fix(cluster-status): support DRY_RUN

package.json, yarn.lock
- Update last version of react-xtermjs
---
=> chore: bump react-xtermjs 1.0.10

libs/shared/console-shared/src/lib/general-container-settings/ui/image-name.tsx
[QOV-80](https://qovery.atlassian.net/browse/QOV-80)
This PR makes sure the custom image name inputted by the user is lowercase.
https://github.com/user-attachments/assets/7841196f-0134-4f34-8494-37923a4a7aa1
---
[QOV-80]: https://qovery.atlassian.net/browse/QOV-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(containers): image name should be lowercase

libs/shared/util-js/src/lib/parse-cmd.spec.ts, libs/shared/util-js/src/lib/parse-cmd.ts
https://qovery.slack.com/archives/C02P2JB4SEM/p1746428425575539
- Modified parseCmd function to support parsing commands with placeholders, ensuring proper extraction and restoration of variables
- Updated tests to cover handling of environment variables in both and formats
---
=> fix(parse-cmd): enhance arguments handling with new formats

libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-credentials-settings/cluster-credentials-settings.tsx
https://qovery.atlassian.net/browse/QOV-805
---
=> feat(cluster): add warning if credentials switch

libs/domains/users-sign-up/feature/src/lib/hooks/use-create-user-sign-up/use-create-user-sign-up.ts, libs/domains/users-sign-up/feature/src/lib/hooks/use-signup-cargo/use-signup-cargo.ts, libs/shared/util-node-env/src/lib/shared-util-node-env.ts
https://qovery.slack.com/archives/C08M2RT8T29/p1746543979992499
- Added useSignUpCargo hook to handle posting user sign-up data to Cargo API.
- Updated useCreateUserSignUp to format and send data to Cargo upon successful user sign-up.
- Implemented error handling for data formatting and API requests.
---
=> chore(users-sign-up): integrate Cargo API for user sign-up data submission

libs/domains/services/feature/src/lib/hooks/use-delete-all-services/use-delete-all-services.ts
https://qovery.atlassian.net/jira/software/c/projects/QOV/boards/56?selectedIssue=QOV-612
---
=> fix(use-delete-all-services): invalidate services list query and toast

libs/shared/ui/src/lib/components/inputs/input-select/input-select.tsx
[> Link to the JIRA ticket](https://qovery.atlassian.net/browse/QOV-80)
This PR improves the input-select by making it non-sensitive to case.
---
=> fix(input-select): made the search not case-sensitive

libs/domains/cloud-providers/feature/src/index.ts, libs/domains/cloud-providers/feature/src/lib/cluster-scw-control-plane-feature/cluster-scw-control-plane-feature.spec.tsx, libs/domains/cloud-providers/feature/src/lib/cluster-scw-control-plane-feature/cluster-scw-control-plane-feature.tsx, libs/pages/cluster/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx, libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-resources-feature/step-resources-feature.tsx, libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-summary-feature/step-summary-feature.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-summary/step-summary.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx, libs/shared/interfaces/src/lib/domain/cluster-creation-flow.interface.ts
https://qovery.atlassian.net/jira/software/c/projects/QOV/boards/56?selectedIssue=QOV-46
- Introduced `ClusterSCWControlPlaneFeature` component to manage Scaleway control plane options.
- Update creation flow and settings pages
---
=> feat(cloud-providers): add SCW control plane feature and related tests

libs/domains/variables/feature/src/lib/create-update-variable-modal/create-update-variable-modal.tsx
https://qovery.atlassian.net/jira/software/c/projects/QOV/boards/56?selectedIssue=QOV-100
---
=> feat(create-update-variable-modal): asFile default environment scope if service

libs/domains/organizations/feature/src/lib/container-registry-form/container-registry-form.tsx, libs/shared/util-js/src/lib/container-registry-kind-to-icon.ts
https://qovery.slack.com/archives/C02P2JB4SEM/p1747292404908819
---
=> fix(container-registry): allow Azure config

libs/domains/environments/feature/src/lib/environment-action-toolbar/__snapshots__/environment-action-toolbar.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-action-toolbar/environment-action-toolbar.tsx, libs/domains/services/feature/src/lib/service-action-toolbar/__snapshots__/service-action-toolbar.spec.tsx.snap, libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1747156897707909
---
=> fix(action-toobar): remove logs dropdown for service and environment

libs/pages/cluster/src/lib/ui/page-settings-credentials/page-settings-credentials.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-general/step-general.tsx, libs/shared/console-shared/src/lib/cluster-settings/feature/cluster-credentials-settings-feature/cluster-credentials-settings-feature.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-credentials-settings/cluster-credentials-settings.tsx
https://qovery.atlassian.net/jira/software/c/projects/QOV/boards/56?selectedIssue=QOV-845
---
=> fix(cluster-credential): remove warning creation flow

libs/domains/cloud-providers/data-access/src/lib/domains-cloud-providers-data-access.ts
Typage issue
https://qovery.slack.com/archives/C038JMN9GUE/p1747911637014949
---
=> fix(cluster): creation flow karpenter request type

libs/domains/clusters/feature/src/lib/cluster-card/__snapshots__/cluster-card.spec.tsx.snap, libs/domains/clusters/feature/src/lib/cluster-card/cluster-card.tsx, libs/pages/services/src/lib/feature/page-new-feature/page-new-feature.tsx
https://www.figma.com/design/ceStC4e4ma81E1rrUxvKNH?node-id=29494-660569#1269883514
- Feedback by Yael for border-color and box-shadow
---
=> fix(cards): border-color box-shadow for cluster service

libs/domains/service-logs/feature/src/lib/sidebar-pod-statuses/sidebar-pod-statuses.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1747747421612189
---
=> fix(sidebar-pod-statuses): pods filtered inconsistency

apps/console/src/app/app.tsx, libs/shared/util-web-sockets/src/lib/use-status-web-sockets/use-status-web-sockets.ts, package.json, yarn.lock
- https://qovery.atlassian.net/browse/QOV-840
- https://qovery.slack.com/archives/C038JMN9GUE/p1747636200136999?thread_ts=1747424079.918969&cid=C038JMN9GUE
---
=> chore: capture message service running status ws

libs/shared/console-shared/src/lib/flow-create-port/ui/crud-modal/crud-modal.tsx
https://qovery.atlassian.net/jira/software/c/projects/QOV/boards/56?selectedIssue=QOV-856
---
=> fix(port-modal): add default value HTTP for protocol

libs/domains/services/feature/src/lib/pod-details/__snapshots__/pod-details.spec.tsx.snap, libs/domains/services/feature/src/lib/pod-details/pod-details.tsx
- Align design with new timeline
- Remove timestamp and seperate status reason and status message
https://qovery.atlassian.net/jira/software/c/projects/QOV/boards/56?selectedIssue=QOV-620
---
=> fix(service-metrics): events and timeline UI

libs/domains/environments/feature/src/lib/environment-list/__snapshots__/environment-list.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-list/environment-list.tsx, libs/domains/environments/feature/src/lib/environment-state-chip/__snapshots__/environment-state-chip.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-state-chip/environment-state-chip.tsx, libs/domains/environments/feature/src/lib/hooks/use-environments/use-environments.ts, libs/domains/services/feature/src/lib/hooks/use-services/use-services.ts, libs/domains/services/feature/src/lib/service-list/__snapshots__/service-list.spec.tsx.snap, libs/domains/services/feature/src/lib/service-list/service-list.tsx
https://qovery.atlassian.net/browse/QOV-840
https://qovery.slack.com/archives/C02P2JB4SEM/p1749028045455169
Use real loading state for statuses
---
=> fix(statuses): remove default stopped state

libs/domains/environments/feature/src/lib/environment-action-toolbar/__snapshots__/environment-action-toolbar.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-action-toolbar/environment-action-toolbar.tsx, libs/domains/services/feature/src/lib/hooks/use-uninstall-service/use-uninstall-service.ts, libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx, libs/domains/services/feature/src/lib/service-list/service-list-action-bar.tsx, libs/pages/events/src/lib/ui/row-event/row-event.tsx, package.json, yarn.lock
Support toaster with correct link when triggering an uninstallation
---
=> feat(uninstall): support toaster for action

libs/shared/util-web-sockets/src/lib/use-status-web-sockets/use-status-web-sockets.ts
https://qovery.slack.com/archives/C02P2JB4SEM/p1750433075107109
---
=> chore: remove status web socket Sentry message

libs/pages/settings/src/lib/ui/page-organization-roles-edit/row-project/row-project.tsx, libs/pages/settings/src/lib/ui/page-organization-roles-edit/table-clusters/table-clusters.tsx
https://qovery.slack.com/archives/C0910KW2NCA/p1750848474777469?thread_ts=1750848303.343189&cid=C0910KW2NCA
---
=> fix(table-roles): reverse head project and cluster

libs/shared/devops-copilot/feature/src/lib/devops-copilot-panel/devops-copilot-panel.tsx
Fix conversation slowdown by caching already rendered Mermaid diagrams
=> fix(devops-copilot): caching Mermaid rendering

libs/domains/observability/feature/src/lib/hooks/use-metrics/use-metrics.ts, libs/domains/observability/feature/src/lib/service-overview/card-instance/card-instance.tsx, libs/domains/observability/feature/src/lib/service-overview/instance-autoscaling-chart/instance-autoscaling-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/instance-status-chart/instance-status-chart.tsx
=> feat: add autoscaling limit reached chart

libs/domains/observability/feature/src/lib/service-overview/card-http-errors/card-http-errors.tsx, libs/domains/observability/feature/src/lib/service-overview/card-instance-status/card-instance-status.tsx, libs/domains/observability/feature/src/lib/service-overview/card-log-errors/card-log-errors.tsx, libs/domains/observability/feature/src/lib/service-overview/card-metric/card-metric.tsx, libs/domains/observability/feature/src/lib/service-overview/card-storage/card-storage.tsx, libs/domains/observability/feature/src/lib/service-overview/disk-chart/disk-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/local-chart/local-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/local-chart/tooltip.tsx, libs/domains/observability/feature/src/lib/service-overview/persistent-storage-chart/persistent-storage-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/service-overview.tsx
=> feat: improve disk io chart

libs/domains/observability/feature/src/lib/service-overview/card-instance/card-instance.tsx, libs/domains/observability/feature/src/lib/service-overview/instance-autoscaling-chart/instance-autoscaling-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/instance-status-chart/instance-status-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/local-chart/local-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/network-request-duration-chart/network-request-duration-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/network-request-size-chart/network-request-size-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/network-request-status-chart/network-request-status-chart.tsx
=> fix: color and icon for events

libs/domains/observability/feature/src/lib/service-overview/persistent-storage-chart/persistent-storage-chart.tsx
=> feat: rename path in storage chart

libs/domains/observability/feature/src/lib/service-overview/card-storage/card-storage.spec.tsx, libs/domains/observability/feature/src/lib/service-overview/card-storage/card-storage.tsx, libs/domains/services/feature/src/lib/pods-metrics/pods-metrics.tsx, libs/pages/application/src/lib/feature/page-monitoring-feature/page-monitoring-feature.tsx
=> fix(monitoring): add no monitoring placeholder

libs/domains/observability/feature/src/lib/service-overview/local-chart/local-chart.tsx
https://qovery.slack.com/archives/C090XR4CA69/p1753943846026419
---
=> fix(monitoring) display placeholder if no events in the list

libs/domains/observability/feature/src/lib/service-overview/local-chart/local-chart.tsx
This pull request enhances the alignment and rendering of event reference lines in the `LocalChart` component to improve user experience and visual accuracy. The main changes focus on aligning event timestamps with chart data points, refactoring rendering logic for better maintainability, and improving the interactivity and appearance of reference lines.
Event timestamps are now aligned to the closest chart data point timestamp, ensuring reference lines match the actual data on the chart for more accurate visualization. 
https://qovery.slack.com/archives/C090XR4CA69/p1754315071114949
---
=> fix(monitoring): aligning event timestamps with reference line 

libs/pages/login/src/lib/ui/login/login.tsx
=> fix(login): update link size

libs/domains/observability/feature/src/lib/service-overview/card-http-errors/card-http-errors.spec.tsx, libs/domains/observability/feature/src/lib/service-overview/card-http-errors/card-http-errors.tsx, libs/domains/observability/feature/src/lib/service-overview/card-instance-status/card-instance-status.spec.tsx, libs/domains/observability/feature/src/lib/service-overview/card-instance-status/card-instance-status.tsx, libs/domains/observability/feature/src/lib/service-overview/card-log-errors/card-log-errors.spec.tsx, libs/domains/observability/feature/src/lib/service-overview/card-log-errors/card-log-errors.tsx, libs/domains/observability/feature/src/lib/service-overview/card-percentile-99/card-percentile-99.spec.tsx, libs/domains/observability/feature/src/lib/service-overview/card-percentile-99/card-percentile-99.tsx, libs/domains/observability/feature/src/lib/service-overview/card-storage/card-storage.spec.tsx, libs/domains/observability/feature/src/lib/service-overview/card-storage/card-storage.tsx, libs/domains/observability/feature/src/lib/service-overview/util-filter/service-overview-context.spec.tsx, libs/domains/observability/feature/src/lib/service-overview/util-filter/service-overview-context.tsx
Apply zoom's time range on cards.
---
=> fix(service-monitoring): apply zoom's time range on cards 

package.json, yarn.lock
This PR simply updates the Posthog SDK to its latest version
---
=> fix: update Posthog

libs/shared/ui/src/lib/components/warning-screen-mobile/warning-screen-mobile.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1755710403888239
---
=> feat(warning-screen-mobile): allow deprecated experience

libs/domains/organizations/feature/src/index.ts, libs/domains/organizations/feature/src/lib/invoice-banner/invoice-banner.tsx, libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx, libs/shared/iam/feature/src/lib/use-user-role/use-user-role.ts
[QOV-1093](https://qovery.atlassian.net/browse/QOV-1093)
This PR adds a banner informing users when they have overdue invoices.
https://github.com/user-attachments/assets/ef2450cd-93a1-463d-8e74-3c05622cb158
---
[QOV-1090]: https://qovery.atlassian.net/browse/QOV-1090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[QOV-1093]: https://qovery.atlassian.net/browse/QOV-1093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add banner for overdue invoices

libs/domains/observability/feature/src/lib/hooks/use-metrics/use-metrics.spec.ts, libs/domains/observability/feature/src/lib/hooks/use-metrics/use-metrics.ts, libs/domains/observability/feature/src/lib/service-overview/card-http-errors/card-http-errors.tsx, libs/domains/observability/feature/src/lib/service-overview/card-instance-status/card-instance-status.tsx, libs/domains/observability/feature/src/lib/service-overview/card-percentile-99/card-percentile-99.tsx, libs/domains/observability/feature/src/lib/service-overview/instance-autoscaling-chart/instance-autoscaling-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/instance-http-errors-chart/instance-http-errors-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/instance-status-chart/instance-status-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/local-chart/local-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/local-chart/tooltip.tsx, libs/domains/observability/feature/src/lib/service-overview/network-request-duration-chart/network-request-duration-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/network-request-size-chart/network-request-size-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/network-request-status-chart/network-request-status-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/service-overview.tsx, libs/domains/observability/feature/src/lib/service-overview/util-filter/service-overview-context.tsx
- Improve performance 
- Update some minor elements
---
=> fix(service-monitoring): performance and remove infinite loop

libs/domains/observability/feature/src/lib/service-overview/cpu-chart/cpu-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/instance-status-chart/instance-status-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/local-chart/local-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/memory-chart/memory-chart.tsx, libs/shared/ui/src/lib/components/chart/chart.stories.tsx, libs/shared/ui/src/lib/components/chart/chart.tsx
https://qovery.slack.com/archives/C090XR4CA69/p1756274260069089
- Update tooltip animation
- Remove dash line for limit and request
---
=> fix(chart-tooltip): default animation

libs/domains/observability/feature/src/lib/service-overview/instance-http-errors-chart/instance-http-errors-chart.tsx, libs/pages/cluster/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-general-settings/cluster-general-settings.tsx, libs/shared/interfaces/src/lib/domain/cluster-creation-flow.interface.ts
=> feat(cluster): enable metrics for Qovery admin only

libs/pages/cluster/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
- Allow disabled metrics feature for Qovery admin
---
=> fix(cluster): authorize disable metrics for Qovery admin

libs/domains/observability/feature/src/lib/service-overview/cpu-chart/cpu-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/local-chart/local-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/local-chart/tooltip.tsx, libs/domains/observability/feature/src/lib/service-overview/memory-chart/memory-chart.tsx, libs/domains/observability/feature/src/lib/service-overview/service-overview.tsx, libs/shared/ui/src/lib/components/chart/chart.tsx
=> fix(service-monitoring): tooltip cropped and responsive

libs/domains/service-terraform/feature/src/lib/terraform-configuration-settings/terraform-configuration-settings.tsx, libs/pages/services/src/lib/feature/page-terraform-create-feature/page-terraform-create-feature.tsx, libs/pages/services/src/lib/feature/page-terraform-create-feature/step-configuration-feature/step-configuration-feature.spec.tsx
=> fix(terraform): execution timeout is in seconds and add validation

libs/domains/services/feature/src/lib/select-commit-modal/__snapshots__/select-commit-modal.spec.tsx.snap, libs/domains/services/feature/src/lib/select-commit-modal/select-commit-modal.tsx, libs/shared/ui/src/lib/components/modal/modal.tsx
- Fix buttons position for small screens
https://qovery.slack.com/archives/C02P2JB4SEM/p1759311111442229
---
=> fix(select-commit-modal): add sticky button for small screen

libs/pages/onboarding/src/lib/feature/onboarding-more/onboarding-more.tsx
Just a personal preference, but I think you can  drop "easily" in front of every phrase and also capitalize the first character.
---
=> chore: cleanup onboarding wording
