Qovery/console

apps/console/src/app/app.tsx, libs/domains/environment/src/index.ts, libs/domains/environment/src/lib/slices/environments.slice.spec.ts, libs/domains/environment/src/lib/slices/environments.slice.ts, libs/domains/organization/src/lib/provider/organization-provider.tsx, libs/domains/organization/src/lib/slices/organization.slice.ts, libs/domains/projects/src/index.ts, libs/domains/projects/src/lib/provider/environments-provider.spec.ts, libs/domains/projects/src/lib/provider/environments-provider.ts, libs/domains/projects/src/lib/provider/projects-provider.tsx, libs/domains/projects/src/lib/slices/projects.slice.spec.ts, libs/domains/projects/src/lib/slices/projects.slice.ts, libs/pages/application/feature/src/lib/application-page.tsx, libs/pages/applications/feature/src/lib/applications-page.tsx, libs/pages/environments/feature/src/lib/components/general/general.tsx, libs/shared/layout/src/lib/layout.tsx, libs/store/data/src/lib/root.ts
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-370
This PR remove set the one-to-many redux relationship for the existing entities and move the slices definition in the correct libs. Before this PR, the slices where following the api-doc (for example environment slice was declared in project lib) which was not super trivial for our project. Now environment slice is declared in environment lib.
---
=> Rewrite store selector by id and moving slices

libs/pages/application/src/lib/feature/page-general-feature/page-general-feature.tsx, libs/pages/application/src/lib/ui/instances-table/instances-table.tsx, libs/pages/application/src/lib/ui/page-general/page-general.tsx
- Stability: https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-436
- Rounding: https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-417
This pr implement the rounding of the percentage in the application overview and display the stability but for this point, I think that it's super weird to display `Service Stability: 0` and this means that application is alright there is no problem. It means that there were no reboot. But I read it that the score of my stability is 0. Could we not change the wording to fix that? 
---
=> Application overview improved

apps/console/src/app/app.tsx, libs/pages/application/src/lib/ui/container/container.spec.tsx, libs/pages/database/src/lib/ui/container/container.spec.tsx, libs/pages/layout/src/lib/feature/layout/layout.tsx, libs/pages/layout/src/lib/ui/layout-page/layout-page.spec.tsx, libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx, libs/pages/layout/src/lib/ui/navigation/navigation.spec.tsx, libs/pages/layout/src/lib/ui/navigation/navigation.tsx, libs/pages/login/src/index.ts, libs/pages/login/src/lib/feature/page-logout-feature/page-logout-feature.spec.tsx, libs/pages/login/src/lib/feature/page-logout-feature/page-logout-feature.tsx, libs/shared/router/src/lib/beta-route/beta-route.tsx, libs/shared/router/src/lib/pages/no-beta-access.tsx, libs/shared/router/src/lib/sub-router/login.router.ts, libs/shared/ui/src/lib/components/layouts/navigation/navigation.tsx, libs/shared/ui/src/lib/components/modals/modal-user/modal-user.tsx
- Added a proper /logout URL that pass through a component so that we can call extra method (`posthog.reset()`)
- posthog.reset() that was need to fix inconsistency with different session / cache / proxy
- posthog identify that was no longer triggered but was hard to detect because of cache inconsistencies
- Added a beta state to re-render the page so that the flag overridden does not requires us to manually refresh the page or put an setInterval
---
=> fix(beta-access): fix restricted access and identification

libs/shared/ui/src/index.ts, libs/shared/ui/src/lib/components/navigation-left/navigation-left-sub-link/navigation-left-sub-link.spec.tsx, libs/shared/ui/src/lib/components/navigation-left/navigation-left-sub-link/navigation-left-sub-link.tsx, libs/shared/ui/src/lib/components/navigation-left/navigation-left.spec.tsx, libs/shared/ui/src/lib/components/navigation-left/navigation-left.stories.tsx, libs/shared/ui/src/lib/components/navigation-left/navigation-left.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-351)
- Add the navigation left with react-router logic
- I didn't add an animation when we opened the sub links, it was too much
[Link](http://localhost:4400/?path=/story/navigationleft--primary)
---
=> feat(navigation-left): add component 

libs/pages/layout/src/lib/feature/layout/layout.spec.tsx, libs/pages/layout/src/lib/feature/layout/layout.tsx, libs/pages/layout/src/lib/utils/utils.tsx, libs/pages/login/src/lib/hooks/use-redirect-if-logged/use-redirect-if-logged.spec.tsx
Fix redirection to the previous orgnization/project
---
=> fix(redirection): save orgId and projectId on localStorage

libs/shared/interfaces/src/lib/domain/application.entity.ts, libs/shared/utils/src/lib/tools/refacto-payload.spec.ts, libs/shared/utils/src/lib/tools/refacto-payload.ts
Because the `put` method is a little bit strange backend side, we can't have any information outside of the one accepted by the API.
If we send our application object with additional properties, backend will reject our `put`.
So everytime we were adding some stuff for development purpose on the application or everytime the backend was adding properties on the application object that we fetch with get, we had to manually suppress the extra properties. Which was not super safe and could break at any API changes if the response of the get was changed.
With this fix, we pass only what is asked by the Payload Interface.
=> chore(api): safer way to prepare api payload

apps/console/src/main.tsx, tailwind-workspace-preset.js
- The css file was imported twice in two different files with the same exact huge content (2,8mo unminified)
- Removing safelist from tailwind config that was keeping way too much CSS properties. From 2,8mo to 200kb unmodified
In the end, with the minified version the prod comes from 2x1,8mb to 1x100kb.
We can already file the first loading of the pages much responsive and fast.
=> chore(css-size): cut size from 4mo to 100kb

apps/console/src/app/components/redirect-overview.tsx, libs/pages/login/src/lib/hooks/use-redirect-if-logged/use-redirect-if-logged.tsx
Redirect on this screen when the first organization available does not have any project to propose.
Fixing an infinite loop that was boring on every new preview env
=> fix(initialisation): infinite loader after loading

libs/pages/services/src/lib/ui/page-deployments/page-deployments.tsx
> [Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-568)
As long as we have the same values, we don't loose the filter
=> page deployments filter stays

libs/shared/ui/src/lib/components/inputs/input-select/input-select.tsx, libs/shared/ui/src/lib/styles/components/select.scss
- Fixed bug when we have long value on the Input Select
- Added tooltip and truncate
---
=> fix(input-select): add tooltip and truncate for long value

libs/domains/application/src/lib/slices/application.actions.ts, libs/domains/database/src/lib/slices/database.actions.ts
[> Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-564)
The error message was empty, now it displays what we know.
---
=> fix(error): add info in database error messages

libs/pages/application/src/lib/ui/page-settings-ports/crud-modal/crud-modal.tsx, libs/pages/services/src/lib/ui/page-application-create/page-application-create-port/port-row/port-row.tsx, libs/shared/ui/src/lib/components/buttons/button-icon/button-icon.tsx, libs/shared/ui/src/lib/components/funnel-flow-body/funnel-flow-body.tsx, libs/shared/ui/src/lib/components/inputs/input-text/input-text.tsx
[> Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-587)
Reset the value when toggle public and adding a tooltip on both places we have a port creation.
---
=> fix(ports): adding info tooltip and reset the value

libs/shared/ui/src/lib/components/layouts/breadcrumb/breadcrumb.tsx
- Bind escape touch to close Application and Deployment logs
---
=> feat(logs): bind escape to close logs

libs/shared/console-shared/src/lib/application-buttons-actions/application-buttons-actions.tsx, libs/shared/console-shared/src/lib/database-buttons-actions/database-buttons-actions.tsx, libs/shared/console-shared/src/lib/environment-buttons-actions/environment-buttons-actions.tsx, libs/shared/ui/src/lib/components/buttons/button-icon-action/button-icon-action-element/button-icon-action-element.tsx, libs/shared/ui/src/lib/components/buttons/button-icon-action/button-icon-action.stories.tsx, libs/shared/ui/src/lib/components/menu/menu.tsx
- Add tooltip for buttons actions 
---
=> feat(buttons-actions): add tooltip

__tests__/utils/setup-jest.tsx, jest.config.ts, jest.preset.js, libs/pages/application/src/lib/ui/crud-environment-variable-modal/crud-environment-variable-modal.spec.tsx, libs/pages/application/src/lib/ui/import-environment-variable-modal/import-environment-variable-modal.spec.tsx, libs/pages/application/src/lib/ui/page-settings-advanced/page-settings-advanced.spec.tsx, package.json
=> fix(jest): fix jest config and removing faulty useless server wrapper

libs/domains/environment-variable/src/lib/slices/environment-variables.slice.ts, libs/domains/environment-variable/src/lib/slices/secret-environment-variables.slice.ts, libs/pages/application/src/lib/feature/crud-environment-variable-modal-feature/crud-environment-variable-modal-feature.tsx, libs/pages/application/src/lib/feature/import-environment-variable-modal-feature/import-environment-variable-modal-feature.tsx, libs/pages/application/src/lib/feature/import-environment-variable-modal-feature/utils/form-check.tsx, libs/pages/application/src/lib/ui/crud-environment-variable-modal/crud-environment-variable-modal.tsx, libs/pages/application/src/lib/ui/import-environment-variable-modal/import-environment-variable-modal.tsx, libs/pages/application/src/lib/utils/compute-available-environment-variable-scope.tsx, libs/shared/ui/src/lib/components/table/table-row-deployment/table-row-deployment.tsx, package.json, yarn.lock
- Fix environments variables for Jobs and Container
- Fix row deployments for Database
---
=> fix(jobs): environments variables

libs/domains/application/src/lib/slices/applications.slice.ts, libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.spec.tsx, libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx, libs/pages/application/src/lib/ui/page-settings-general/page-settings-general.spec.tsx, libs/pages/application/src/lib/ui/page-settings-general/page-settings-general.tsx, libs/pages/clusters/src/lib/ui/card-cluster/card-cluster.spec.tsx, libs/pages/clusters/src/lib/ui/card-cluster/card-cluster.tsx, libs/pages/database/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx, libs/pages/database/src/lib/ui/page-settings-general/page-settings-general.tsx, libs/pages/services/src/lib/feature/page-application-create-feature/page-application-post-feature/page-application-install-post.spec.tsx, libs/pages/services/src/lib/feature/page-application-create-feature/page-application-post-feature/page-application-post-feature.tsx, libs/pages/services/src/lib/feature/page-database-create-feature/database-creation-flow.interface.ts, libs/pages/services/src/lib/feature/page-database-create-feature/page-database-create-post-feature/page-database-create-post-feature.spec.tsx, libs/pages/services/src/lib/feature/page-database-create-feature/page-database-create-post-feature/page-database-create-post-feature.tsx, libs/pages/services/src/lib/ui/page-application-create/page-application-create-general/page-application-create-general.spec.tsx, libs/pages/services/src/lib/ui/page-application-create/page-application-create-general/page-application-create-general.tsx, libs/pages/services/src/lib/ui/page-database-create/page-database-create-general/page-database-create-general.tsx, libs/pages/services/src/lib/ui/page-job-create/step-general/step-general.tsx, libs/shared/console-shared/src/lib/general-container-settings/ui/general-container-settings.tsx, libs/shared/interfaces/src/lib/domain/application-creation-flow.interface.ts, libs/shared/utils/src/lib/tools/refacto-payload.spec.ts, libs/shared/utils/src/lib/tools/refacto-payload.ts, package.json, yarn.lock
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-625)
- Fix Job general settings
- Add field description for Application and Containers 
---
=> fix(settings-description): field description 

libs/shared/console-shared/src/lib/create-clone-environment-modal/feature/create-clone-environment-modal-feature.tsx
- Redirection to the Services page after cloning or creating Environment
---
=> fix(create-clone-environment-modal): redirect after request

libs/shared/utils/src/lib/hooks/use-running-status-websocket/use-running-status-websocket.tsx, libs/shared/websockets/src/lib/components/websocket-container/websocket-container.tsx
Fixing an annoying cyclic dependency in the websocket lib.
---
=> fix(cyclic-dep): removing the cyclic dep from websocket lib

libs/shared/ui/src/lib/components/layouts/breadcrumb/breadcrumb.tsx
- Add Breadcrumb menu for Clusters 
---
=> feat(breadcrumb): add cluster

libs/pages/cluster/src/lib/feature/page-settings-danger-zone-feature/page-settings-danger-zone-feature.spec.tsx, libs/pages/cluster/src/lib/feature/page-settings-danger-zone-feature/page-settings-danger-zone-feature.tsx, libs/pages/cluster/src/lib/router/router.tsx, libs/pages/cluster/src/lib/ui/page-settings-danger-zone/page-settings-danger-zone.spec.tsx, libs/pages/cluster/src/lib/ui/page-settings-danger-zone/page-settings-danger-zone.tsx
- Add cluster settings section for Danger Zone
---
=> feat(page-cluster): settings danger zone

libs/domains/organization/src/lib/slices/cluster.slice.spec.ts, libs/domains/organization/src/lib/slices/cluster.slice.ts, libs/pages/cluster/src/lib/feature/page-settings-advanced-feature/init-form-values/init-form-values.spec.ts, libs/pages/cluster/src/lib/feature/page-settings-advanced-feature/init-form-values/init-form-values.ts, libs/pages/cluster/src/lib/feature/page-settings-advanced-feature/page-settings-advanced-feature.spec.tsx, libs/pages/cluster/src/lib/feature/page-settings-advanced-feature/page-settings-advanced-feature.tsx, libs/pages/cluster/src/lib/router/router.tsx, libs/pages/cluster/src/lib/ui/page-settings-advanced/page-settings-advanced.spec.tsx, libs/pages/cluster/src/lib/ui/page-settings-advanced/page-settings-advanced.tsx, libs/shared/interfaces/src/lib/domain/advanced-settings.interface.ts, libs/shared/interfaces/src/lib/domain/cluster.entity.ts, libs/shared/interfaces/src/lib/states/clusters.interface.ts, libs/shared/ui/src/lib/components/table-edition/table-edition.tsx, package.json, yarn.lock
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-499)
- Add advanced settings for Clusters
- For clusters, we can now add "object" for some value
---
=> feat(cluster-advanced-settings): add page

libs/domains/environment/src/lib/slices/environments.slice.ts, libs/pages/environments/src/lib/feature/page-general-feature/page-general-feature.tsx, libs/pages/environments/src/lib/ui/page-general/page-general.tsx, libs/pages/environments/src/lib/ui/table-row-environments/table-row-environments.tsx, libs/pages/services/src/lib/feature/page-general-feature/page-general-feature.tsx
This PR makes better use of the store and prevent from flashing placeholder when we already have the data in the store. Environments list was showing again the placeholder anytime we were going back to it. Even though we had all the necessary information in store.
Before:
https://user-images.githubusercontent.com/6163954/214322095-2db4d87e-eab8-44f2-8a7a-104b210be9d6.mp4
After:
https://user-images.githubusercontent.com/6163954/214322133-d2c5e415-a36f-4b9c-b856-ab29d6fb2727.mp4
---
=> feat(navigation): more fluid navigation and remove blinking elements

libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx
- Hide this banner when cluster is deployed
---
=> fix(cluster-banner): hide when cluster is deployed

libs/pages/layout/src/lib/feature/layout/layout.tsx
We had a two API calls that was triggered every time we were changing URL on the app. 
The navigate in the useEffect deps was triggering that. After some research about how to deal with that trying to avoid adding an eslint comment to disable the check here, I found this issue on react-router repo:
https://github.com/remix-run/react-router/discussions/8465
where the owner of the repo was suggesting that we use redirect over navigate in this kind of case. We remove the dependence need to navigate and it fixes the problem.
---
=> fix(api-calls): remove unnecessary api calls on each URL changes

libs/shared/console-shared/src/lib/job-configure-settings/ui/job-configure-settings.tsx
Just update the wording on the hint for the start event on lifecycle job
---
- [ x] I made sure the code is type safe (no any)
=> fix(job-configure-settings): updated the hint for start event

libs/pages/application/src/lib/feature/crud-environment-variable-modal-feature/crud-environment-variable-modal-feature.tsx
Creation of normal environment variable was broken because mount_path was '' instead of null
---
=> fix(env-variable): fix environment variable creation without mount_file

libs/domains/environment-variable/src/lib/slices/environment-variables.slice.ts, libs/domains/environment-variable/src/lib/slices/secret-environment-variables.slice.ts, libs/pages/application/src/lib/feature/crud-environment-variable-modal-feature/handle-submit/handle-submit.tsx
[NB board - Agile board - Qovery Jira](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-653)
if the scope of the new/edited env var / alias / override is “application” we should change the message and the redeploy should only trigger the redeploy of this service.
---
=> feat(environment-variable): toaster message and action different if scope application

libs/shared/console-shared/src/lib/buttons-actions/ui/application-buttons-actions/application-buttons-actions.spec.tsx, libs/shared/console-shared/src/lib/buttons-actions/ui/application-buttons-actions/application-buttons-actions.tsx, libs/shared/console-shared/src/lib/buttons-actions/ui/database-buttons-actions/database-buttons-actions.spec.tsx, libs/shared/console-shared/src/lib/buttons-actions/ui/database-buttons-actions/database-buttons-actions.tsx, libs/shared/console-shared/src/lib/environment-buttons-actions/ui/environment-buttons-actions.spec.tsx, libs/shared/console-shared/src/lib/environment-buttons-actions/ui/environment-buttons-actions.tsx, libs/shared/utils/src/lib/tools/status-actions-available.tsx
- Cancel deployment after deleting action available
- [Romain's request](https://qovery.slack.com/archives/C02P2JB4SEM/p1677230799228619)
---
=> fix(application-buttons-actions): cancel action after deleting

libs/shared/console-shared/src/lib/setting-resources/ui/setting-resources.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1677678320092069
Until api allow us to fetch the maximum allowed memory, we hardcoded the maximum value to a super large one. If it's not possible, backend will return an error but at least clients are not blocked.
---
=> fix(service): lifting the maximum hardcoded allowed value for memory

libs/pages/application/src/lib/feature/page-settings-feature/page-settings-feature.tsx, libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx, libs/pages/application/src/lib/page-application.tsx
Remove useless multiple rendering
- For all application pages with Environment selector
- For application settings page with Application selector
---
=> fix(page-application): remove useless application rendering

libs/domains/environment/src/lib/slices/environments.slice.ts
- Disabled environment status request for Cluster logs
---
=> fix(cluster-logs): disabled request environment status

libs/shared/enums/src/lib/running-status.enum.ts, libs/shared/ui/src/lib/components/status-chip/status-chip.tsx
Fix missing live service status icon since last change.
=> fix: missing icon for live status

libs/shared/utils/src/lib/tools/status-actions-available.tsx
Restart action is not available anymore, due to runningStatus being in 'RUNNING' state.
Should fix this file, because RunningStatus is used for live status returned from agents and does not condition the availability of some actions.
Also isRedeployAvailable contains "in progress" deployment status, which is not going to allow a redeploy
=> fix unavailable restart action

libs/pages/settings/src/lib/ui/page-organization-api/page-organization-api.tsx, libs/pages/settings/src/lib/ui/page-organization-container-registries/page-organization-container-registries.tsx, libs/pages/settings/src/lib/ui/page-organization-github-repository-access/page-organization-github-repository-access.tsx, libs/pages/settings/src/lib/ui/page-organization-members/page-organization-members.tsx, libs/pages/settings/src/lib/ui/page-organization-roles/page-organization-roles.tsx
it updates the links to the doc following the structure update. see https://github.com/Qovery/documentation/pull/295
---
=> chore: update links in orga settings following doc structure update

libs/pages/application/src/lib/ui/page-variables/page-variables.tsx, libs/pages/logs/environment/src/lib/ui/sidebar-status/sidebar-status.tsx, libs/pages/settings/src/lib/ui/page-organization-roles-edit/page-organization-roles-edit.tsx, libs/pages/settings/src/lib/ui/page-organization-roles/page-organization-roles.tsx
add link to doc on env variables page
---
=> fix: add link to doc on env variables page

libs/shared/console-shared/src/lib/deploy-other-commit-modal/feature/deploy-other-commit-modal-feature.tsx
https://qovery.slack.com/archives/C02NPSG2HBL/p1683703783833349
For job, the `Current Version` label was missing
---
=> fix(service): current label on deploy other commit for job

libs/pages/services/src/lib/feature/page-settings-preview-environments-feature/page-settings-preview-environments-feature.tsx, libs/pages/services/src/lib/ui/page-settings-preview-environments/page-settings-preview-environments.spec.tsx, libs/pages/services/src/lib/ui/page-settings-preview-environments/page-settings-preview-environments.tsx
The PR introduces a new flag on environment deployment rule. This flag disable automatic preview environment and enable instead a new git flow, to let user select which and when a preview should be created.
https://qovery.atlassian.net/browse/COR-614
add trigger to create preview environments (activation mode)
---
=> feat(preview-environments): add on demand preview flag to environment deployment rule

libs/pages/cluster/src/lib/ui/page-settings-resources/page-settings-resources.spec.tsx, libs/pages/clusters/src/lib/feature/page-clusters-create-feature/page-clusters-create-feature.tsx, libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-resources-feature/step-resources-feature.spec.tsx, libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-summary-feature/step-summary-feature.spec.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-resources/step-resources.spec.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-summary/step-summary.spec.tsx, libs/shared/console-shared/src/lib/cluster-settings/feature/cluster-resources-settings-feature/cluster-resources-settings-feature.spec.tsx, libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.spec.tsx, libs/shared/factories/src/lib/cluster-factory.mock.ts
This PR changes the minimum default disk_size from 20 to 50 Gib.
---
=> chore(cluster-settings): change default disk_size from 20 to 50

libs/shared/console-shared/src/lib/entrypoint-cmd-inputs/ui/entrypoint-cmd-inputs.tsx
Remove confusion in an example, where we expect args and a binary name is set
=> fix: remove binary name in the args cmd example

libs/pages/application/src/lib/feature/crud-environment-variable-modal-feature/crud-environment-variable-modal-feature.tsx, libs/pages/application/src/lib/ui/crud-environment-variable-modal/crud-environment-variable-modal.spec.tsx, libs/pages/application/src/lib/ui/crud-environment-variable-modal/crud-environment-variable-modal.tsx
Allow empty value for variable (was forbidden until now)
---
=> feat(variables): allow empty value for variable

libs/pages/application/src/lib/ui/about/about-update/about-update.tsx, libs/pages/environments/src/lib/ui/table-row-environments/table-row-environments.tsx, libs/pages/services/src/lib/ui/table-row-services/table-row-services.tsx
I have added tooltips on the updated at info available in:
- the service list
- the environment list
- the service overview
what is missing for now:
- tooltip on the deployment tab
---
=> feat: added tooltips to display full date on updated_at info

libs/pages/application/src/lib/ui/about/about-container/about-container.tsx, libs/pages/application/src/lib/ui/page-settings-advanced/page-settings-advanced.tsx, libs/pages/cluster/src/lib/ui/page-settings-advanced/page-settings-advanced.tsx, libs/pages/events/src/lib/ui/row-event/row-event.spec.tsx, libs/shared/ui/src/lib/components/tooltip/tooltip.tsx
- Add truncate by default for all tooltip
---
=> feat(tooltip): add truncate by default

libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.tsx, libs/pages/services/src/lib/feature/page-application-create-feature/step-healthchecks-feature/step-healthchecks-feature.tsx, libs/shared/interfaces/src/lib/common/flow-port-data.interface.ts
- Add default TCP healtchecks when we create a new port
---
=> fix(port): add default healtchecks

libs/pages/application/src/lib/feature/page-settings-domains-feature/page-settings-domains-feature.tsx, libs/pages/application/src/lib/feature/page-settings-ports-feature/page-settings-ports-feature.tsx, libs/pages/application/src/lib/feature/page-settings-storage-feature/page-settings-storage-feature.tsx, libs/pages/application/src/lib/feature/table-row-environment-variable-feature/table-row-environment-variable-feature.tsx, libs/pages/application/src/lib/ui/page-settings-danger-zone/page-settings-danger-zone.tsx, libs/pages/cluster/src/lib/feature/page-settings-network-feature/page-settings-network-feature.tsx, libs/pages/cluster/src/lib/ui/page-settings-danger-zone/page-settings-danger-zone.tsx, libs/pages/database/src/lib/ui/page-settings-danger-zone/page-settings-danger-zone.tsx, libs/pages/services/src/lib/feature/page-settings-deployment-pipeline-feature/page-settings-deployment-pipeline-feature.tsx, libs/pages/services/src/lib/ui/page-settings-danger-zone/page-settings-danger-zone.tsx, libs/pages/settings/src/lib/feature/page-organization-api-feature/page-organization-api-feature.tsx, libs/pages/settings/src/lib/feature/page-organization-billing-feature/page-organization-billing-feature.tsx, libs/pages/settings/src/lib/feature/page-organization-container-registries-feature/page-organization-container-registries-feature.tsx, libs/pages/settings/src/lib/feature/page-organization-roles-edit-feature/page-organization-roles-edit-feature.tsx, libs/pages/settings/src/lib/feature/page-organization-webhooks-feature/page-organization-webhooks-feature.tsx, libs/pages/settings/src/lib/ui/page-organization-danger-zone/page-organization-danger-zone.tsx, libs/pages/settings/src/lib/ui/page-organization-members/row-member/row-member.tsx, libs/pages/settings/src/lib/ui/page-project-danger-zone/page-project-danger-zone.tsx, libs/shared/console-shared/src/lib/buttons-actions/ui/application-buttons-actions/application-buttons-actions.tsx, libs/shared/console-shared/src/lib/buttons-actions/ui/cluster-buttons-actions/cluster-buttons-actions.tsx, libs/shared/console-shared/src/lib/buttons-actions/ui/database-buttons-actions/database-buttons-actions.tsx, libs/shared/console-shared/src/lib/environment-buttons-actions/ui/environment-buttons-actions.tsx, libs/shared/ui/src/lib/components/block-content-delete/block-content-delete.tsx, libs/shared/ui/src/lib/components/modals/modal-confirmation/__snapshots__/modal-confirmation.spec.tsx.snap, libs/shared/ui/src/lib/components/modals/modal-confirmation/modal-confirmation.spec.tsx, libs/shared/ui/src/lib/components/modals/modal-confirmation/modal-confirmation.stories.tsx, libs/shared/ui/src/lib/components/modals/modal-confirmation/modal-confirmation.tsx, libs/shared/ui/src/lib/components/modals/modal-confirmation/use-modal-confirmation/use-modal-confirmation.tsx
https://qovery.atlassian.net/browse/FRT-736
Change the behavior of the confirm deletion modal.
- You must now type "delete" (instead of the name of the resource)
- The CTA button is now red when it's a deletion
**Impacts**
- Delete Storage
- Delete Custom Domains
- Delete API tokens
- Delete Custom Roles
- Delete Network
- Delete Pipeline stage
- Delete Organization Member
- Delete Organization Invite
- Delete Container registry
- Delete Webhook
- Delete Credit card
- Delete Network Port
- Delete Project
- Delete Service
- Delete Cluster
- Delete Application
- Delete Database
---
=> feat(modal-confirmation-delete): change confirm deletion modal

nginx.conf
GZIP compression wasn' t enabled.
We need compression to optimize web app loading.
After:
=> chore: enable nginx compression

libs/domains/environment/src/index.ts, libs/domains/environment/src/lib/slices/environments.queries.ts, libs/pages/application/src/lib/feature/page-settings-danger-zone-feature/page-settings-danger-zone-feature.tsx, libs/pages/application/src/lib/feature/page-settings-healthchecks-feature/page-settings-healthchecks-feature.tsx, libs/pages/application/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx, libs/pages/application/src/lib/page-application.tsx, libs/pages/application/src/lib/ui/page-settings-healthchecks/page-settings-healthchecks.tsx, libs/pages/application/src/lib/ui/page-settings-resources/page-settings-resources.tsx, libs/pages/database/src/lib/feature/page-settings-danger-zone-feature/page-settings-danger-zone-feature.tsx, libs/pages/database/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx, libs/pages/database/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx, libs/pages/database/src/lib/page-database.tsx, libs/pages/logs/environment/src/lib/page-environment-logs.tsx, libs/pages/services/src/lib/feature/page-application-create-feature/step-resources-feature/step-resources-feature.tsx, libs/pages/services/src/lib/feature/page-database-create-feature/step-general-feature/step-general-feature.tsx, libs/pages/services/src/lib/feature/page-deployments-feature/page-deployments-feature.tsx, libs/pages/services/src/lib/feature/page-general-feature/page-general-feature.tsx, libs/pages/services/src/lib/feature/page-job-create-feature/step-resources-feature/step-resources-feature.tsx, libs/pages/services/src/lib/feature/page-settings-danger-zone-feature/page-settings-danger-zone-feature.tsx, libs/pages/services/src/lib/feature/page-settings-deployment-pipeline-feature/page-settings-deployment-pipeline-feature.tsx, libs/pages/services/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx, libs/pages/services/src/lib/page-services.tsx, libs/pages/services/src/lib/ui/page-application-create/step-resources/step-resources.tsx, libs/pages/services/src/lib/ui/page-job-create/step-resources/step-resources.tsx, libs/shared/console-shared/src/lib/application-settings/ui/application-settings-resources/application-settings-resources.tsx, libs/shared/console-shared/src/lib/database-settings-resources/feature/settings-resources-instance-types-feature/setting-resources-instance-types-feature.tsx, libs/shared/console-shared/src/lib/update-all-modal/feature/update-all-modal-feature.tsx
- Update environmentById query with select 
- Rename file environments.slice.ts => environment.queries.ts
- Fix Healtchecks query on UI file for environment mode
- Need to do for environmentStatusById
- I didn't separate the fetch `environmentsApi.listEnvironment` with an external function (like getEnvironments), don't know if it's really necessary on our case because we use an external package and not a simple fetch or other
```
export const useFetchEnvironments = <TData = Environment[]>(
projectId: string,
select?: (data: Environment[]) => TData
) => {
const queryClient = useQueryClient()
return useQuery(
['project', projectId, 'environments'],
async () => {
const response = await environmentsApi.listEnvironment(projectId)
return response.data.results as Environment[]
},
{
onSuccess: () …
```
=> chore(environments-queries): update environment by id query

libs/pages/application/src/lib/feature/page-settings-healthchecks-feature/page-settings-healthchecks-feature.tsx, libs/pages/application/src/lib/ui/page-settings-healthchecks/page-settings-healthchecks.tsx, libs/shared/console-shared/src/lib/application-settings/ui/application-settings-resources/application-settings-resources.tsx
Fix #680
Warning should be based on min running instances only
=> fix(warn-instance-number): fix warning condition

apps/console/project.json, apps/console/src/polyfills.ts, package.json, yarn.lock
https://qovery.atlassian.net/browse/FRT-755
Manually include regenerator-runtime and core-js as polyfill isn't necessary anymore.
This is not part of a freshly generated nx workspace (eg. `npx create-nx-workspace@latest --preset=react-monorepo --bundler=webpack`) and this is done by babel plugins
```
ctjhoa@SKYNET ~/qovery/console (git)-[staging] % rg polyfill
yarn.lock
41:    abortcontroller-polyfill: ^1.7.3
46:    promise-polyfill: ^8.2.3
225:"@babel/helper-define-polyfill-provider@npm:^0.3.3":
227:  resolution: "@babel/helper-define-polyfill-provider@npm:0.3.3"
1300:    babel-plugin-polyfill-corejs2: ^0.3.3
1301:    babel-plugin-polyfill-corejs3: ^0.6.0
1302:    babel-plugin-polyfill-regenerator: ^0.4.1
1477:    babel-plugin-polyfill-corejs2: ^0.3.3
1478: …
```
=> refactor: remove useless polyfills

libs/pages/application/src/lib/feature/page-settings-healthchecks-feature/page-settings-healthchecks-feature.spec.tsx, libs/pages/application/src/lib/feature/page-settings-healthchecks-feature/page-settings-healthchecks-feature.tsx, libs/pages/application/src/lib/ui/page-settings-healthchecks/page-settings-healthchecks.spec.tsx, libs/pages/application/src/lib/ui/page-settings-healthchecks/page-settings-healthchecks.tsx, libs/pages/services/src/lib/feature/page-application-create-feature/step-healthchecks-feature/step-healthchecks-feature.spec.tsx, libs/pages/services/src/lib/feature/page-application-create-feature/step-healthchecks-feature/step-healthchecks-feature.tsx, libs/pages/services/src/lib/ui/page-application-create/step-healthchecks/step-healthchecks.tsx, libs/shared/console-shared/src/lib/application-settings/ui/application-settings-healthchecks/application-settings-healthchecks.tsx, package.json, yarn.lock
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-737)
- Fix Healthchecks page settings with real save button
- Clean, remove useless type state for Liveness and Readiness (we use the state of react-hook-form)
---
=> fix(page-settings-healthchecks): update to avoid not available save btn 

libs/shared/console-shared/src/lib/flow-create-port/ui/crud-modal/crud-modal.tsx
Just update the text of the how to on Port modal after the release of the TCP/UDP port
---
=> fix: updated message after TCP/UDP feature release

libs/pages/application/src/lib/feature/page-settings-advanced-feature/init-form-values/init-form-values.ts, libs/pages/application/src/lib/feature/page-settings-advanced-feature/page-settings-advanced-feature.tsx, libs/pages/application/src/lib/ui/page-settings-advanced/page-settings-advanced.tsx
- Allow "object" for services advanced settings (add similar logic with Cluster advanced settings)
---
=> fix(services): allow object for advanced settings

libs/domains/organization/src/lib/slices/organization/auth-provider.slice.spec.ts, libs/domains/organization/src/lib/slices/organization/auth-provider.slice.ts
- Override ids return by API for auth provider to avoid error for Github App (before our store had only the first element because we have same ids)
---
=> fix(github-app): override auth provider ids returned by API

libs/pages/settings/src/lib/feature/page-organization-github-repository-access-feature/page-organization-github-repository-access-feature.tsx
Related to https://qovery.atlassian.net/browse/FRT-746
`error.name` was `undefined` so I changed the condition to match the current error.
=> fix(github-app): fix disconnection modal

libs/pages/logs/environment/src/lib/feature/deployment-logs-feature/deployment-logs-feature.spec.tsx, libs/pages/logs/environment/src/lib/feature/deployment-logs-feature/deployment-logs-feature.tsx, libs/pages/logs/environment/src/lib/feature/pod-logs-feature/pod-logs-feature.tsx, libs/pages/logs/environment/src/lib/feature/service-stage-ids-context/service-stage-ids-context.spec.tsx, libs/pages/logs/environment/src/lib/feature/service-stage-ids-context/service-stage-ids-context.tsx, libs/pages/logs/environment/src/lib/feature/sidebar-history-feature/sidebar-history-feature.spec.tsx, libs/pages/logs/environment/src/lib/feature/sidebar-history-feature/sidebar-history-feature.tsx, libs/pages/logs/environment/src/lib/page-environment-logs.tsx, libs/pages/logs/environment/src/lib/ui/deployment-logs/deployment-logs.spec.tsx, libs/pages/logs/environment/src/lib/ui/deployment-logs/deployment-logs.tsx, libs/pages/logs/environment/src/lib/ui/row-deployment/row-deployment.tsx, libs/pages/logs/environment/src/lib/ui/row-pod/row-pod.tsx, libs/pages/logs/environment/src/lib/ui/sidebar-history/sidebar-history.spec.tsx, libs/pages/logs/environment/src/lib/ui/sidebar-history/sidebar-history.tsx, libs/pages/logs/environment/src/lib/ui/sidebar-pipeline-item/sidebar-pipeline-item.tsx, libs/pages/logs/environment/src/lib/ui/sidebar-pipeline/sidebar-pipeline.tsx, libs/pages/logs/environment/src/lib/ui/sidebar-status/sidebar-status.tsx, libs/pages/logs/environment/src/lib/ui/sidebar/sidebar.tsx, libs/shared/console-shared/src/lib/layout-logs/layout-logs.tsx, libs/shared/routes/src/lib/sub-router/logs.router.ts, libs/shared/ui/src/lib/components/menu/menu.spec.tsx, libs/shared/ui/src/lib/components/menu/menu.tsx, libs/shared/ui/src/lib/styles/components/menu.scss, libs/shared/utils/src/lib/tools/date.spec.ts, libs/shared/utils/src/lib/tools/date.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-690)
- Add deployment history for Deployment logs with a `versionId` on the routing
- Placeholder: service deployed but not on this deployment
- Placeholder: service never deployed
_Minor_
- Update `Menu` component with new dark color
- Fix `Menu` duplicate className
- Update `dateFullFormat` helper and remove by default millisecond
- Refacto context with serviceId and now use URL params  
---
=> feat(environment-logs): add deployment history

nginx.conf
Set HTTP security headers in nginx.
See https://webdock.io/en/docs/how-guides/security-guides/how-to-configure-security-headers-in-nginx-and-apache for more details.
Mainly because we often receive email from security scanners about the X-FRAME-OPTIONS
- [] This PR introduces breaking change(s) and has been labeled as such
=> Add http security headers in nginx

libs/pages/layout/src/lib/feature/layout/layout.tsx
- Remove on the first loading, the double fetch for Organization and UserSignUp
---
=> fix(layout): remove useless double fetch for Organization and UserSignUp

libs/pages/cluster/src/lib/ui/page-settings-network/crud-modal/crud-modal.tsx
It fixes cluster network description field flagged as optional which is required by the API.
**Broken**
**Fixed**
---
=> fix(cluster-network): description field is required

libs/pages/logs/environment/src/lib/ui/sidebar-pipeline-item/sidebar-pipeline-item.tsx, libs/shared/ui/src/lib/components/status-chip/status-chip.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-793
- Fix status for stage pipeline on the sidebar
- Add missing RESTARTED status for StatusChip component
---
=> fix(deployment-history): add status from the history and not the current

libs/pages/environments/src/lib/ui/container/container.tsx, libs/pages/layout/src/lib/feature/layout/layout.tsx, libs/shared/factories/src/lib/container-factory.mock.ts, libs/shared/util-web-sockets/src/lib/use-status-web-sockets/use-status-web-sockets.ts, libs/state/util-queries/src/lib/use-react-query-ws-subscription/use-react-query-ws-subscription.spec.tsx, libs/state/util-queries/src/lib/use-react-query-ws-subscription/use-react-query-ws-subscription.ts
Add `enabled` param to `useReactQueryWsSubscription` to avoid bad WS call.
Here are the corresponding structures
https://gitlab.com/qovery/backend/rust-backend/-/blob/58aca6e768c2d091ec38c6132858e8af6027a196/websocket-gateway/src/deployment/types.rs#L5
https://gitlab.com/qovery/backend/rust-backend/-/blob/58aca6e768c2d091ec38c6132858e8af6027a196/websocket-gateway/src/service_status/types.rs
In addition, we currently have a bug in the recently merged web-socket status feature.
WebSockets require `clusterId` however frontend side environments are listed despite their cluster ownership.
So frontend is forced to create one WS per cluster to listen to all environments statuses.
This is far from ideal and data modeling should be challenged with backend team.
=> fix(services): fix status websocket in corner case.

libs/pages/logs/environment/src/lib/page-environment-logs.tsx, libs/shared/console-shared/src/lib/layout-logs/layout-logs.tsx, libs/shared/ui/src/lib/components/icon/icon.stories.tsx, libs/shared/ui/src/lib/components/icon/icons-status/queued.tsx, libs/shared/ui/src/lib/components/status-chip/__snapshots__/status-chip.spec.tsx.snap
- Display progressing animation by service deployment status and not environment status
- Added a new Queued icon
---
=> fix(layout-logs): display progressing by service deployment status

libs/shared/console-shared/src/lib/create-clone-environment-modal/ui/create-clone-environment-modal.tsx
- updated text for the create/clone modal
- added "how it works" section
---
- [ x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [ x] I made sure the code is type safe (no any)
=> chore(env-modal): updated text and added how it works

libs/shared/console-shared/src/lib/create-clone-environment-modal/ui/create-clone-environment-modal.tsx
fix link to the documentation on the env create/clone modal
=> chore(env-modal): use right documentation link

libs/domains/services/feature/src/lib/last-commit/__snapshots__/last-commit.spec.tsx.snap, libs/domains/services/feature/src/lib/last-commit/last-commit.tsx, libs/domains/services/feature/src/lib/service-details/__snapshots__/service-details.spec.tsx.snap, libs/domains/services/feature/src/lib/service-details/service-details.tsx
- Improved the last commit component
- And should be more ISO with other Badges and Figma
----  
Before:
After:
Before:
After:
Case with double numbers and large characters:
---
=> fix(last-commit): UI padding and width 

package.json, yarn.lock
https://qovery.atlassian.net/browse/FRT-882
Bump qovery-typescript-axios to get this fix https://github.com/Qovery/qovery-openapi-spec/pull/482
=> chore: upgrade qovery-typescript-axios

libs/domains/services/feature/src/lib/pods-metrics/pods-metrics.tsx
https://qovery.atlassian.net/browse/FRT-900
=> fix(ui): truncate container version in pod-metrics

libs/pages/services/src/lib/feature/page-database-create-feature/page-database-create-feature.tsx
Not all DBs have the same instance type, for example Redis doesn't have 'db.t3.medium'. So we chose to remove default instance type and let the user choose.
https://qovery.atlassian.net/browse/FRT-894
=> fix(services): remove default instance_type

libs/pages/logs/environment/src/lib/ui/sidebar-status/sidebar-status.tsx
Fixing parallel deploy counts from 4 to 7.
Fixing parallel deploy counts from 4 to 7 (actual parallel deployments count)
---
=> fix(deployment-logs): update parallel deploys count

libs/domains/services/feature/src/lib/pod-details/__snapshots__/pod-details.spec.tsx.snap, libs/domains/services/feature/src/lib/pod-details/pod-details.tsx
add the last_terminated_state.reason at the beginning of the last_terminated message of a pod
https://qovery.atlassian.net/browse/FRT-951
⚠️ ⚠️ : tests are not passing
---
=> fix: added reason to last_terminated error message

libs/pages/application/src/lib/ui/container/container.tsx
This occurs when you reload an application settings page, the `getServiceType` isn't fully type safe and can lead to this error
=> fix(services): fix react error when reloading page

libs/pages/application/src/lib/feature/page-settings-networking-feature/page-settings-networking-feature.tsx
Add missing helm networking initial values
=> fix(services): fix helm networking settings

libs/domains/services/feature/src/lib/service-details/service-details.tsx
allow to display connection URI for private DB as well
note: design needs to be updated to make it clear that the user can only use this URI if they activate the port forward via the CLI
https://qovery.atlassian.net/browse/FRT-962
---
=> feat(database): display connection uri for private db

libs/pages/application/src/lib/feature/page-settings-deployment-restrictions-feature/page-settings-deployment-restrictions-feature.tsx, libs/pages/application/src/lib/ui/page-settings-deployment-restrictions/crud-modal/crud-modal.tsx
https://qovery.atlassian.net/browse/FRT-964
updated links to point to the new deployment restriction doc
---
=> chore(depl-restriction): updated links

libs/domains/services/feature/src/lib/need-redeploy-flag/need-redeploy-flag.tsx, libs/pages/database/src/lib/feature/page-settings-feature/page-settings-feature.tsx
And, add condition to waiting `database` before displaying settings, because we have a bug when we reload settings we don't see default values.
---
=> fix(need-redeploy-flag): database id

libs/domains/environment/src/lib/slices/environments.queries.ts
- Invalidate the environment query with new data access
---
=> fix(environment): invalidate new environment queries for editing

libs/pages/cluster/src/lib/ui/page-settings-remote/page-settings-remote.tsx
=> fix(cluster-settings): title remote access

libs/domains/clusters/feature/src/lib/cluster-action-toolbar/__snapshots__/cluster-action-toolbar.spec.tsx.snap, libs/domains/clusters/feature/src/lib/cluster-action-toolbar/cluster-action-toolbar.tsx, libs/domains/environments/feature/src/lib/environment-action-toolbar/__snapshots__/environment-action-toolbar.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-action-toolbar/environment-action-toolbar.tsx, libs/domains/environments/feature/src/lib/environment-list/__snapshots__/environment-list.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-list/environment-list-filter.tsx, libs/domains/services/feature/src/lib/service-action-toolbar/__snapshots__/service-action-toolbar.spec.tsx.snap, libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx, libs/domains/services/feature/src/lib/service-list/__snapshots__/service-list.spec.tsx.snap, libs/domains/services/feature/src/lib/service-list/service-list-filter.tsx, libs/shared/ui/src/lib/components/action-toolbar/action-toolbar.stories.tsx
FontAwesome distinguish `angle-down` from `chevron-down` where
`chevron-*` seems to be centered horizontally / vertically
`angle-down`
`chevron-down`
=> fix(ui): fix icons

libs/shared/ui/.storybook/preview.tsx
https://github.com/Qovery/console/pull/1349/files#diff-98b116aa7b1f6ac5f26ea2e8c101af671143eccbbdaa510720584c0fe07d4e78R91
Due to style conflict with log pages and data attribute, we need to use `withThemeByClassName` instead of `withThemeByDataAttribute`
https://github.com/storybookjs/storybook/blob/next/code/addons/themes/docs/api.md
=> chore: fix storybook config

libs/shared/util-web-sockets/src/lib/use-status-web-sockets/use-status-web-sockets.ts, libs/state/util-queries/src/lib/use-react-query-ws-subscription/use-react-query-ws-subscription.ts
During the first deployment, the websocket can timeout because the websocket isn't completely setup.
We must auto-reconnect till connection is setup.
https://qovery.atlassian.net/browse/FRT-1119
=> fix(services): fix running status on first deployment

libs/pages/settings/src/lib/feature/page-organization-container-registries-feature/page-organization-container-registries-feature.tsx, libs/shared/console-shared/src/lib/general-container-settings/ui/general-container-settings.tsx, libs/shared/ui/src/lib/components/modal/modal-root.tsx, libs/shared/ui/src/lib/components/modal/modal.tsx, libs/shared/ui/src/lib/components/modal/use-modal/use-modal.tsx
This is a workaround to avoid radix dialog restriction. Radix use [react-remove-scroll](https://www.npmjs.com/package/react-remove-scroll) to prevent wheel / scroll event directly on `<html>` node in some cases like with Select inside Modal, it causes issues. https://qovery.atlassian.net/browse/FRT-868
https://qovery.atlassian.net/browse/FRT-1134
It worth noting that scroll lock is also important for accessibility reasons This `fakeModal` mode is visually identical than the `modal` mode without the drawback of locking the scroll.
https://github.com/radix-ui/primitives/blob/b32a93318cdfce383c2eec095710d35ffbd33a1c/packages/react/dialog/src/Dialog.tsx#L204
=> fix(ui): add fakeModal to avoid scroll lock in select nested in modal

libs/pages/cluster/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx
Removing the condition to allow editing when the cluster is migrated
---
=> fix(cluster-settings): karpenter remove instance type condition

libs/domains/services/feature/src/lib/service-terminal/service-terminal.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1179
I can't find any cool solution to keep the escape bind. I think the best way is to remove it and hand over control to the terminal
---
=> fix(service-terminal): remove bind escap to close terminal

libs/domains/service-helm/feature/src/lib/deployment-setting/deployment-setting.tsx, libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx, libs/shared/console-shared/src/lib/entrypoint-cmd-inputs/ui/entrypoint-cmd-inputs.spec.tsx, libs/shared/console-shared/src/lib/entrypoint-cmd-inputs/ui/entrypoint-cmd-inputs.tsx, libs/shared/util-js/src/lib/parse-cmd.spec.ts, libs/shared/util-js/src/lib/parse-cmd.ts
We need to keep quote on the UI side but removing it for the back-end
Before
```
["args", "\"arg2 arg3"\"]
```
After 
``` 
["args", "args2 args3"]
```
https://qovery.slack.com/archives/C038JMN9GUE/p1720513590483949
---
=> fix(parser-args): remove quote for back-end and display it for UI only

libs/shared/util-services/src/lib/build-edit-service-payload.spec.ts, libs/shared/util-services/src/lib/build-edit-service-payload.ts
Fix the `buildEditServicePayload` function to handles `icon_uri` param. Otherwise existing service `icon_uri` will be trim from the payload when you goes from service response -> service request
=> fix(services): update service payload to add icon_uri

package.json, yarn.lock
- Update open-api package
https://qovery.slack.com/archives/C02P2JB4SEM/p1721981768208349
---
=> chore(deps): bump qovery-typescript-axios 1.1.457

libs/domains/clusters/feature/src/lib/cluster-card/__snapshots__/cluster-card.spec.tsx.snap, libs/domains/clusters/feature/src/lib/cluster-card/cluster-card.tsx
- Fix alignment between cloud provider icon, name and status
---
=> fix(cluster-card): align name and status

libs/domains/clusters/feature/src/lib/cluster-action-toolbar/__snapshots__/cluster-action-toolbar.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-action-toolbar/__snapshots__/environment-action-toolbar.spec.tsx.snap, libs/domains/environments/feature/src/lib/environment-action-toolbar/environment-action-toolbar.tsx, libs/domains/services/feature/src/lib/service-action-toolbar/__snapshots__/service-action-toolbar.spec.tsx.snap, libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx, libs/shared/ui/src/lib/components/dropdown-menu/dropdown-menu.tsx
- Update default brand icon color from `400` to `500`
- Removed gap for children item with Link asChild, `linkVariants` provides default `gap-1`
**_Before:_**
**_After_**
---
=> fix(action-toolbar): brand color and remove gap for link children

libs/pages/application/src/lib/ui/page-settings-domains/page-settings-domains.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1281
+ Fixed hover bug when the button loads and the Spinner doesn't have the correct size (iso with loading state of btns)
---
=> fix(custom-domain-settings): size tooltip check custom domain

libs/domains/service-helm/feature/src/lib/source-setting/source-setting.tsx, libs/shared/ui/src/lib/components/inputs/input-select/input-select.tsx
- We need to remove it because it's impossible to create an helm chart if we've this param. 
- I prefer to remove it now, I didn't find an solution to fix the validation error when we switch between "Public repo" and "Helm repo" without it 
---
=> fix(helm-source): remove should un register

libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx
The condition was always `ARM64` because the `watchInstanceType` doesn't return `label` but the `id` without this architecture detail.
---
=> fix(cluster-resources-settings): corrected set default architecture after karpenter checked

libs/domains/service-logs/feature/src/lib/list-service-logs/list-service-logs.tsx
- Labels for service logs filter, display `Container` instead of `Container name`
---
=> fix(service-logs): topbar labels

libs/domains/service-logs/feature/src/lib/sidebar-pod-statuses/sidebar-pod-statuses.spec.tsx, libs/domains/service-logs/feature/src/lib/sidebar-pod-statuses/sidebar-pod-statuses.tsx
https://qovery.slack.com/archives/D063URVH85V/p1732795510051319
---
=> fix(sidebar-pod-statuses): update description for starting pods

libs/domains/service-logs/feature/src/lib/list-service-logs/list-service-logs.tsx
- Filter by container or version doesn't if using memorised columnFilters, rollback to `useEffect` to avoid it
---
=> fix(list-service-logs): filter by container and version first rendering

libs/pages/application/src/lib/ui/page-settings-general/page-settings-general.tsx, libs/shared/console-shared/src/lib/general-container-settings/ui/general-container-settings.tsx, libs/shared/console-shared/src/lib/general-container-settings/ui/image-name.tsx, libs/shared/console-shared/src/lib/job-general-settings/ui/job-general-settings.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1387
---
=> fix(input-image-name): default option for settings views

libs/domains/clusters/feature/src/lib/hooks/use-upgrade-cluster/use-upgrade-cluster.ts
- Display error and succes toasts when we upgrade cluster
---
=> feat(cluster-upgrade): display error and success toasts

libs/domains/service-logs/feature/src/lib/header-logs/header-logs.tsx, libs/domains/service-logs/feature/src/lib/sidebar-pod-statuses/sidebar-pod-statuses.tsx
This pull request includes updates to the `header-logs` and `sidebar-pod-statuses` components in the `libs/domains/service-logs/feature` directory. The changes focus on improving the status display logic and handling specific service conditions.
Updates to status display logic:
* [`libs/domains/service-logs/feature/src/lib/header-logs/header-logs.tsx`](diffhunk://#diff-476b9ba8aca95449c76dde0e11538ae8448454669039d5a329b47ef9d8a70b92L83-R83): Modified the `ActionTriggerStatusChip` component to use `serviceStatus?.state` instead of `environmentStatus?.last_deployment_state` for the `status` prop.
Hide sidebar pods status for Database managed
* [`libs/domains/service-logs/feature/src/lib/sidebar-pod-statuses/sidebar-pod-statuses.tsx`](diffhunk://#diff-e608ac2678f8feee5fce87a0e80cd780f1a10667c …
=> fix(deployment-logs): service status and hide pod sidebar for db managed

libs/domains/environment-logs/feature/src/lib/list-pre-check-logs/list-pre-check-logs.tsx, libs/pages/settings/src/lib/ui/page-organization-members/page-organization-members.tsx
https://qovery.slack.com/archives/C02PGRVRMD2/p1733737131205719
---
=> fix(page-members): add member column count

libs/pages/services/src/lib/feature/page-job-create-feature/step-configure-feature/step-configure-feature.tsx, libs/pages/services/src/lib/feature/page-job-create-feature/step-general-feature/step-general-feature.tsx, libs/pages/services/src/lib/ui/page-job-create/step-general/step-general.tsx, libs/shared/console-shared/src/lib/job-general-settings/ui/job-general-settings.tsx, libs/shared/interfaces/src/lib/domain/job-creation-flow.interface.ts
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1371
---
=> fix(creation-flow-cronjob): collapse annotations/labels and remove dockerfile step

libs/pages/services/src/lib/feature/page-database-create-feature/step-general-feature/step-general-feature.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1394
---
=> fix(creation-flow-database): default container value if cloud provider is GCP or SCW

libs/domains/services/feature/src/lib/service-list/service-list.tsx
https://qovery.slack.com/archives/C038JMN9GUE/p1736874206294889
---
=> fix(service-list): display deployment instead of service status for db managed

libs/pages/clusters/src/lib/ui/page-clusters-create/step-general/step-general.tsx, libs/pages/clusters/src/lib/ui/page-clusters-create/step-summary/step-summary.tsx, libs/shared/console-shared/src/lib/job-configure-settings/ui/job-configure-settings.tsx
=> chore: GCP remove beta info

libs/pages/settings/src/lib/feature/page-organization-billing-summary-feature/show-usage-modal-feature/show-usage-modal-feature.tsx
The date selected in the report is shifted by one day and thus it doesn’t match the invoice.
https://qovery.atlassian.net/browse/FRT-1437
---
=> fix(FRT-1437): add one day in selected date to align with invoice

libs/pages/cluster/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.spec.tsx, libs/pages/cluster/src/lib/ui/page-settings-resources/page-settings-resources.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1743234920794219
---
=> fix(cluster-resources): remove disabled button for no Karpenter cluster

libs/domains/organizations/feature/src/lib/container-registry-form/container-registry-form.tsx, libs/domains/services/feature/src/lib/select-commit-modal/__snapshots__/select-commit-modal.spec.tsx.snap
https://qovery.atlassian.net/browse/QOV-102
---
=> fix(container-registry): rename password field for Github/Gilab CRs to personal access token

libs/domains/environments/feature/src/lib/environment-deployment-list/environment-deployment-list.tsx, libs/domains/services/feature/src/lib/service-deployment-list/service-deployment-list.tsx
This pull request includes changes to the `EnvironmentDeploymentList` and `ServiceDeploymentList` components to handle deployment states more effectively. The main improvements involve simplifying the logic for deployment status checks and enhancing the user interface for queued deployments.
Enhancements to deployment status handling:
* [`libs/domains/environments/feature/src/lib/environment-deployment-list/environment-deployment-list.tsx`](diffhunk://#diff-4042721f2bf31d4d996cd64372e7cc36c9a0ff9228e6f77e50eb2e2345d38623L107-R107): Simplified the logic for checking deployment history and added UI elements to display when a deployment is in the queue. [[1]](diffhunk://#diff-4042721f2bf31d4d996cd64372e7cc36c9a0ff9228e6f77e50eb2e2345d38623L107-R107) …
=> fix(environment/service-deployment): display cancel deployment queue

libs/domains/variables/feature/src/lib/create-update-variable-modal/create-update-variable-modal.tsx
update the text to specify that vars can be used in dockerfile with ARGS
---
=> chore: update text for ARGS usage

libs/domains/clusters/feature/src/lib/cluster-update-modal/cluster-update-modal.spec.tsx, libs/domains/clusters/feature/src/lib/cluster-update-modal/cluster-update-modal.tsx
[> Link to the JIRA ticket](https://qovery.atlassian.net/browse/QOV-627)
PR adding a redirection to the cluster's logs when updating a cluster with "dry run" selected:
https://github.com/user-attachments/assets/51eae15e-1ae0-4c8d-8879-0b709dbca465
---
=> feat(cluster): redirect to logs when selecting dry-run

libs/domains/clusters/feature/src/lib/cluster-card/cluster-card.spec.tsx, libs/domains/clusters/feature/src/lib/cluster-card/cluster-card.tsx, libs/domains/clusters/feature/src/lib/hooks/use-edit-cloud-provider-info/use-edit-cloud-provider-info.ts, libs/shared/util-js/src/lib/status-actions-available.ts
https://qovery.atlassian.net/jira/software/c/projects/QOV/boards/56?selectedIssue=QOV-599
- Add `INVALID_CREDENTIALS` status in the cluster card with a link to logs
- Clean-up some deprecated code
- Link to try the feature [remi-test](http://localhost:4200/organization/3d542888-3d2c-474a-b1ad-712556db66da/cluster/dffb9ce6-d3ea-431c-ad09-aa82600e1d5c/settings/general)
---
=> feat(cluster-card): add INVALID_CREDENTIALS status

libs/domains/services/feature/src/lib/service-list/service-list.tsx
[> Link to the JIRA ticket](https://qovery.atlassian.net/browse/QOV-38)
This PR adds a counter for the queued deployments for a given service.
https://github.com/user-attachments/assets/46bd3514-7206-4ee7-94cb-933577764117
---
=> feat(services): add counter for queued deployments

libs/domains/clusters/feature/src/lib/cluster-credentials-modal/cluster-credentials-modal.spec.tsx, libs/domains/clusters/feature/src/lib/cluster-credentials-modal/cluster-credentials-modal.tsx, libs/shared/ui/src/lib/components/modals/modal-crud/modal-crud.tsx
[QOV-782](https://qovery.atlassian.net/browse/QOV-782)
This PR adds a confirmation modal when user attempts to delete a credential.
https://github.com/user-attachments/assets/e40d4973-7c4e-4209-91d6-d1269542fe28
---
[QOV-782]: https://qovery.atlassian.net/browse/QOV-782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(clusters): add confirmation modal when removing a credential

libs/domains/cloud-providers/feature/src/lib/cluster-scw-control-plane-feature/cluster-scw-control-plane-feature.spec.tsx, libs/domains/cloud-providers/feature/src/lib/cluster-scw-control-plane-feature/cluster-scw-control-plane-feature.tsx, libs/pages/services/src/lib/feature/page-job-create-feature/step-dockerfile-feature/__snapshots__/step-dockerfile-feature.spec.tsx.snap, libs/shared/ui/src/lib/components/inputs/input-select/input-select.tsx
https://qovery.atlassian.net/jira/software/c/projects/QOV/boards/56?selectedIssue=QOV-46
- Update `input-select` to support `description` inside label
- Add description for each control plane option
---
=> feat(cluster-scw-control-plane): add description specs for options

libs/domains/variables/feature/src/lib/hooks/use-create-variable/use-create-variable.ts, libs/shared/ui/src/lib/utils/toast-error.spec.tsx, libs/shared/ui/src/lib/utils/toast-error.tsx, libs/shared/utils/src/lib/http/interceptors/auth-interceptor/auth-interceptor.tsx
[Link to the JIRA ticket](https://qovery.atlassian.net/browse/QOV-76)
This PR improves how we deal with conflicts when updating or creating an env variable by allowing the user to directly go to the conflicting variable from the warning toast.
https://github.com/user-attachments/assets/0fad037c-379f-4670-b2e4-f7d38ecb03c5
---
=> feat(services): improve toast for env variable creation or update in case of conflict

libs/domains/services/feature/src/lib/select-commit-modal/__snapshots__/select-commit-modal.spec.tsx.snap, package.json, yarn.lock
Replace Azure external container registry fields `azure_client_id` and `azure_client_secret` to `azure_tenant_id` and `azure_subscription_id`.
---
=> chore(azure): update container credentials fields

libs/domains/environments/data-access/src/lib/domains-environments-data-access.ts, libs/domains/environments/feature/src/lib/environment-list/environment-list.tsx, libs/domains/environments/feature/src/lib/environment-state-chip/environment-state-chip.tsx, libs/domains/environments/feature/src/lib/hooks/use-check-running-status-closed/use-check-running-status-closed.ts, libs/domains/services/data-access/src/lib/domains-services-data-access.ts, libs/domains/services/feature/src/lib/hooks/use-check-running-status-closed/use-check-running-status-closed.ts, libs/domains/services/feature/src/lib/service-list/service-list.tsx, libs/shared/util-web-sockets/src/lib/use-status-web-sockets/use-status-web-sockets.ts
- Added new hook `useCheckRunningStatusClosed` to have the possibility to add a custom message when the service running status is closed/unavailable
- For now, I used it only for displaying `status unavailable` when we don't have a status for running status in the service and environment list
https://qovery.slack.com/archives/C02P2JB4SEM/p1750664192989659
---
=> fix(service-running-status): display unavailable if agent error

libs/shared/devops-copilot/feature/src/lib/devops-copilot-panel/devops-copilot-panel.tsx
- Detection of a replanning
- Display of a message for the user
- Replacement of the plan
---
=> feat(devops-copilot): add handling and display for the replanning

libs/shared/ui/src/lib/components/chart/chart.tsx, libs/shared/ui/src/lib/styles/main.scss, package.json, yarn.lock
Fix React DOM warnings for reverseDirection and useTranslate3d props. The issue was in the ChartTooltip component which was directly aliasing the recharts Tooltip without filtering out these internal recharts props that shouldn't reach DOM elements.
The fix involved creating a wrapper component that filters out these problematic props before passing them to the recharts Tooltip component:
```
function ChartTooltip(props: ComponentProps<typeof RechartsPrimitive.Tooltip>) {
// Filter out non-DOM props that cause React warnings when passed to div elements
const { reverseDirection, useTranslate3d, ...validProps } = props
return <RechartsPrimitive.Tooltip {...validProps} />
}
```
---
=> chore(chart): update Recharts 3.1.2

libs/domains/services/feature/src/lib/need-redeploy-flag/need-redeploy-flag.tsx, libs/pages/logs/environment/src/lib/page-environment-logs.tsx
[QOV-1090](https://qovery.atlassian.net/browse/QOV-1090)
This PR fixes an issue where the "Deploy now" button was redirecting to the previous deployment and not the ongoing one.
Seeing as it not possible from the back-end to be aware of the `execution_id` when the deployment is triggered, this PR implements a workaround on the front-end side, where the clicking on "Deploy now" will not redirect to a specific `execution_id` but to `/latest` instead. The component will wait for the data of the ongoing deployment to be received to then redirect to its logs.
https://github.com/user-attachments/assets/3ac40221-8989-47fe-ba3b-b1f0c1566a5f
https://github.com/user-attachments/assets/7133f76a-199f-4246-8b9d-c5f048c9d231
---
[QOV-1090]: https://qovery.atlassian.net/browse/QOV-1090?atlOrigin=eyJpIjoi …
=> fix: redirection to latest logs when clicking on "Deploy now"

libs/domains/services/feature/src/lib/service-list/service-list-action-bar.tsx
[QOV-1145](https://qovery.atlassian.net/browse/QOV-1145)
This PR adds support for bulk delete/uninstall/stop of Terraform services.
---
[QOV-1145]: https://qovery.atlassian.net/browse/QOV-1145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(terraform): bulk delete/uninstall/stop of services

libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx, libs/shared/util-js/src/lib/status-actions-available.ts
[QOV-1146](https://qovery.atlassian.net/browse/QOV-1146)
This PR fixes an issue where the "run plan" action was present even though it shouldn't be (for instance when a service is already deploying)
https://github.com/user-attachments/assets/1585c624-78db-49ac-b7b6-ebf32102a624
https://github.com/user-attachments/assets/b4381aaf-9fa8-44e7-b92d-8b8056f280a4
---
[QOV-1146]: https://qovery.atlassian.net/browse/QOV-1146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(terraform): hide "run plan" action when it cannot be performed

libs/pages/services/src/lib/feature/page-new-feature/page-new-feature.spec.tsx, libs/pages/services/src/lib/feature/page-new-feature/page-new-feature.tsx
[QOV-1157](https://qovery.atlassian.net/browse/QOV-1157)
PR adding a "contact us" button to the Terraform card in the services creation page when FF is disabled, allowing users to request access to the feature by filling out a Pylon form.
---
[QOV-1157]: https://qovery.atlassian.net/browse/QOV-1157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(terraform): add "contact us" to Terraform card

libs/domains/service-logs/feature/src/lib/list-deployment-logs/filters-stage-step/filters-stage-step.spec.tsx, libs/domains/service-logs/feature/src/lib/list-deployment-logs/filters-stage-step/filters-stage-step.tsx, libs/domains/service-logs/feature/src/lib/list-deployment-logs/list-deployment-logs.tsx, package.json, yarn.lock
[QOV-1148](https://qovery.atlassian.net/browse/QOV-1148)
PR implementing a new "executing" step in the logs of Terraform services.
[Example](http://localhost:4200/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/566f48ec-bc41-4b5d-9209-2e6dbb381995/environment/bca1baa4-79f9-4574-930b-5eaaec91b583/logs/649a71c4-3202-43b8-b360-114036941de4/deployment-logs/bca1baa4-79f9-4574-930b-5eaaec91b583-82)
---
[QOV-1148]: https://qovery.atlassian.net/browse/QOV-1148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(terraform): add "executing" step in logs

libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.spec.tsx, libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.tsx, libs/pages/services/src/lib/feature/page-application-create-feature/step-port-feature/crud-modal-feature/crud-modal-feature.tsx, libs/pages/services/src/lib/feature/page-terraform-create-feature/step-general-feature/step-general-feature.tsx, libs/pages/services/src/lib/feature/page-terraform-create-feature/step-summary-feature/step-summary-feature.tsx, libs/shared/factories/src/lib/terraform-factory.mock.ts, libs/shared/interfaces/src/lib/common/flow-port-data.interface.ts, package.json, yarn.lock
This PR does
* Update qovery-lib and fix breaking changes
* Forward the field public_path & public_path_rewrite of port when set by the API
It does not change anything in the UI for now. Will discuss how to integrate it properly.
=> feat(port): foward public_path and public_path_rewrite values

libs/pages/services/src/lib/feature/page-new-feature/service-templates.ts
This reverts commit 7e1948d9b4667d7af907087180f4157ab3798acc.
Brings back the Terraform card of the IAC section. This section will need to be removed once the new Terraform feature will be finished.
---
=> Revert "fix(terraform): remove Terraform entry from IAC section (#2036)"

libs/domains/organizations/feature/src/lib/container-registry-form/container-registry-form.tsx, libs/shared/util-js/src/lib/container-registry-kind-to-icon.ts, package.json, yarn.lock
[QOV-1189](https://qovery.atlassian.net/browse/QOV-1189)
PR adding the missing TS checks for Github Enterprise
---
[QOV-1189]: https://qovery.atlassian.net/browse/QOV-1189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(github-enterprise): add missing support for Github Enterprise

libs/domains/organizations/feature/src/lib/container-registry-create-edit-modal/container-registry-create-edit-modal.tsx, libs/domains/organizations/feature/src/lib/container-registry-form/container-registry-form.tsx, libs/domains/organizations/feature/src/lib/git-token-create-edit-modal/git-token-create-edit-modal.tsx, libs/domains/organizations/feature/src/lib/hooks/use-available-container-registries/use-available-container-registries.ts, libs/domains/organizations/feature/src/lib/hooks/use-container-images/use-container-images.ts, libs/shared/console-shared/src/lib/general-container-settings/ui/image-name.tsx
[JIRA ticket](https://qovery.atlassian.net/browse/QOV-1189)
PR implementing the support for GitHub Enterprise. 
Changes include:
- Adding a dropdown to the "git token" update/creation modal so users can choose between GitHub and Github Enterprise. If GitHub Enterprise is selected, a new text input is displayed, asking users to enter the URL to their GHE instance.
- Adding support for the new `GITHUB_ENTERPRISE_CR` container registry type in the Container Registry creation/update modal. _Please note that GHE does not support anonymous sign in and users will thus need to specify some credentials._
- Getting rid of the `gitlab-self-hosted` feature flag.
--- 
🎥  [Demo here](https://qovery.slack.com/archives/C0910JC1N9G/p1759242823163199)
---
=> feat(github-enterprise): support GitHub Enterprise
