Qovery/console

- libs/pages/onboarding/ui/src/lib/components/benefits-card/benefits-card.spec.tsx
- libs/pages/onboarding/ui/src/lib/components/benefits-card/benefits-card.tsx
- libs/pages/onboarding/ui/src/lib/components/layout-onboarding/layout-onboarding.tsx
- libs/shared/ui/src/lib/components/icon/icon.tsx
- libs/shared/ui/src/lib/styles/base/icons.scss
- libs/shared/ui/src/lib/styles/object/link.scss
- Create benefits blocs (for project step on onboardin)
- Update link css with icon size
- Update Icon component with className on FontAwesome icons
> feat(onboarding-storybook): benefits bloc

- apps/onboarding/src/app/app.tsx
- apps/onboarding/src/environments/environment.prod.ts
- apps/onboarding/src/environments/environment.ts
- package.json
- yarn.lock
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-293
- Adding Google Analytics after a request from the DX team.
___
> Adding Google Analytics

- libs/pages/onboarding/ui/src/lib/components/step-pricing/step-pricing.spec.tsx
- libs/pages/onboarding/ui/src/lib/components/step-pricing/step-pricing.tsx
- libs/shared/ui/src/lib/components/layouts/layout-page/layout-page.spec.tsx
- libs/shared/ui/src/lib/components/layouts/navigation/navigation.spec.tsx
- libs/shared/ui/src/lib/components/layouts/navigation/navigation.tsx
Fix tests for the onboarding pricing page
___
> fix(onboarding-pricing): tests

- apps/console/src/app/app.tsx
- libs/domains/organization/src/lib/mocks/factories/organizations-factory.mock.ts
- libs/domains/user/src/index.ts
- libs/domains/user/src/lib/mocks/factories/user-signup-factory.mock.ts
- libs/domains/user/src/lib/slices/user-sign-up.slice.ts
- libs/domains/user/src/lib/slices/user.slice.ts
- libs/pages/overview/feature/src/lib/overview.tsx
- libs/pages/overview/ui/src/lib/components/overview/overview.spec.tsx
- libs/pages/overview/ui/src/lib/components/overview/overview.tsx
- libs/shared/ui/src/lib/components/avatar/avatar.spec.tsx
- libs/shared/ui/src/lib/components/avatar/avatar.stories.tsx
- libs/shared/ui/src/lib/components/avatar/avatar.tsx
- libs/shared/ui/src/lib/components/layouts/layout-page/layout-page.spec.tsx
- libs/shared/ui/src/lib/components/layouts/layout-page/layout-page.tsx
- libs/shared/ui/src/lib/components/layouts/navigation/navigation.spec.tsx
- libs/shared/ui/src/lib/components/layouts/navigation/navigation.tsx
- libs/shared/utils/src/lib/http/interceptors/auth-interceptor/auth-interceptor.tsx
- Update avatar component, adding placeholder
- Update layout with logout behavior on the avatar
___
> Update avatar layout page

- .github/workflows/deploy-staging.yml
- .github/workflows/pull-request.yml
- .github/workflows/test-build-and-deploy.yml
Adds a pull request worflow to run test and does not deploy yo qovery as it is handled by preview env
___
> feat(ci): added pull request flow and condition to not deploy on qovery

- pull_request_template.md
Just cleaned up the PR template to demonstrate review environment flow
___
> fix(ci): updated pull request template

- .github/workflows/deploy-production.yml
Just updating production worflow name
> fix(ci): deploy production name

- libs/pages/environments/ui/src/lib/components/general/general.tsx
- libs/pages/environments/ui/src/lib/components/table-row-environments/table-row-environments.tsx
- libs/shared/ui/src/index.ts
- libs/shared/ui/src/lib/components/icon/icon.stories.tsx
- libs/shared/ui/src/lib/components/table/table-head-sort/table-head-sort.spec.tsx
- libs/shared/ui/src/lib/components/table/table-head-sort/table-head-sort.tsx
- libs/shared/ui/src/lib/components/table/table.stories.tsx
- libs/shared/ui/src/lib/components/table/table.tsx
- libs/shared/ui/src/lib/styles/base/icons.scss
- https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-317
Adding table sort update by key
---
> Adding table sort by key

- libs/domains/application/src/lib/provider/applications-provider.tsx
- libs/domains/application/src/lib/slices/applications.slice.ts
- libs/domains/projects/src/lib/provider/environments-provider.ts
- libs/domains/projects/src/lib/slices/environments.slice.ts
- libs/pages/application/feature/src/lib/application-page.tsx
- libs/pages/application/ui/src/lib/components/container/container.tsx
- libs/pages/applications/feature/src/lib/applications-page.tsx
- libs/pages/applications/ui/src/lib/components/container/container.tsx
- libs/pages/environments/feature/src/lib/components/general/general.tsx
- libs/pages/environments/ui/src/lib/components/table-row-environments/table-row-environments.tsx
- libs/shared/layout/src/lib/layout.tsx
- libs/shared/ui/src/lib/components/buttons/button-action/button-action.tsx
- libs/shared/ui/src/lib/components/buttons/button-icon-action/button-icon-action-element/button-icon-action-element.tsx
- libs/shared/ui/src/lib/components/buttons/button-icon-action/button-icon-action.tsx
- libs/shared/ui/src/lib/components/header/header.tsx
- libs/shared/ui/src/lib/components/status-menu-action/status-menu-action.tsx
- libs/shared/ui/src/lib/components/status-menu/status-menu.spec.tsx
- libs/shared/ui/src/lib/components/status-menu/status-menu.tsx
- libs/shared/ui/src/lib/styles/components/menu.scss
- libs/shared/ui/src/lib/styles/components/status-menu.scss
[> Link to the JIRA ticket](https://qovery.atlassian.net/browse/FRT-339)
Add dynamic data on header (Environments, Applications and Application pages)
> Header data

- libs/pages/application/ui/src/lib/components/container/container.tsx
- libs/pages/applications/ui/src/lib/components/container/container.tsx
- libs/pages/environments/ui/src/lib/components/container/container.tsx
- libs/shared/ui/src/lib/components/header/header.tsx
- libs/shared/ui/src/lib/components/skeleton/skeleton.tsx
- libs/shared/ui/src/lib/styles/components/skeleton.scss
Fix some UI elements on the header : 
- Skeleton position on status menu
- Hide the elements who don't retrieve data at this moment
> Fix header

- apps/console/project.json
[> Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-360)
In development mode, compilation between each changes were super slow, like 6 to 10s. Totally unsustainable at this moment of the project with a quite short codebase.
Takes less that 1s now.
FRT-360
---
> Fix long building time in development

- libs/domains/application/src/lib/slices/applications.slice.ts
- libs/pages/application/feature/src/lib/application-page.tsx
- libs/pages/application/feature/src/lib/components/general/general.tsx
- libs/pages/application/ui/src/lib/components/about/about.spec.tsx
- libs/pages/application/ui/src/lib/components/about/about.tsx
- libs/pages/application/ui/src/lib/components/general/general.tsx
- libs/pages/application/ui/src/lib/components/last-commit/last-commit.spec.tsx
- libs/pages/application/ui/src/lib/components/last-commit/last-commit.tsx
- libs/shared/interfaces/src/lib/domain/application.entity.ts
- libs/shared/layout/src/lib/layout.tsx
- libs/shared/ui/src/lib/components/header/header.tsx
- libs/shared/ui/src/lib/components/tabs/tabs.tsx
- libs/shared/ui/src/lib/components/tag-commit/tag-commit.tsx
- yarn.lock
[> Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-349)
- Actual ticket
- Scrolling behavior + doc about it https://www.notion.so/qovery/Make-only-the-main-block-scrollable-not-the-whole-page-2eea05b77b3846918572587f344c9a94
- First example of a memoized createSelector with a strong impact on the project (it tooks me 4h and many weeks of maturation to finally implement this `getCountNewCommitsToDeploy`). Wrote doc about it https://www.notion.so/qovery/Use-a-CreateSelector-with-a-parameter-b963feec6fd14298b99a39e7c752edd4
---
> Application last commit

- libs/pages/application/ui/src/lib/components/container/container.tsx
- libs/shared/ui/src/lib/components/menu/menu-group/menu-group.tsx
- libs/shared/ui/src/lib/components/menu/menu-item/menu-item.tsx
- libs/shared/ui/src/lib/components/menu/menu.stories.tsx
- yarn.lock
Add the possibility to have a button to copy on the clipboard a string on a menu item
---
> Copy menu item

- libs/domains/environment/src/lib/mocks/factories/environment-factory.mock.ts
- libs/pages/applications/feature/src/lib/components/general/general.tsx
- libs/pages/applications/ui/src/lib/components/table-row-applications/table-row-applications.tsx
- libs/pages/environments/feature/src/lib/components/general/general.tsx
- libs/pages/environments/ui/src/lib/components/general/general.tsx
- libs/pages/environments/ui/src/lib/components/table-row-environments/table-row-environments.tsx
- libs/shared/ui/src/lib/components/layouts/breadcrumb/breadcrumb.tsx
- libs/shared/ui/src/lib/components/table/table-head-filter/table-head-filter.tsx
- libs/shared/ui/src/lib/components/table/table-row/table-row.tsx
Fix for table filters, Environments and Applications, bugs identified with the update for the Store
---
> Adding fix for Table filters (Environments and Applications)

- libs/domains/environment/src/lib/slices/environments.slice.ts
- libs/pages/environments/feature/src/lib/components/general/general.tsx
- libs/pages/environments/ui/src/lib/components/container/container.tsx
- libs/pages/services/feature/src/lib/components/general/general.tsx
- libs/shared/ui/src/lib/components/status-chip/status-chip.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-389)
- Add auto refetch for Environments and Services
- Fix status-chip, added CANCELED status  
---
> Add auto-refetch for Environments and Services

- libs/domains/projects/src/lib/slices/deployment-rules.slice.ts
- libs/pages/application/ui/src/lib/components/container/container.tsx
- libs/pages/services/ui/src/lib/components/general/general.tsx
- libs/pages/services/ui/src/lib/components/table-row-services/table-row-services.spec.tsx
- libs/pages/services/ui/src/lib/components/table-row-services/table-row-services.tsx
- libs/shared/enums/src/index.ts
- libs/shared/enums/src/lib/services.enum.ts
- libs/shared/ui/src/index.ts
- libs/shared/ui/src/lib/components/header/header.tsx
- libs/shared/ui/src/lib/components/layouts/breadcrumb-item/breadcrumb-item.tsx
- libs/shared/ui/src/lib/components/layouts/breadcrumb/breadcrumb.tsx
- libs/shared/ui/src/lib/components/menu/menu-group/menu-group.tsx
- libs/shared/ui/src/lib/components/menu/menu-item/menu-item.tsx
- libs/shared/ui/src/lib/components/truncate/truncate.spec.tsx
- libs/shared/ui/src/lib/components/truncate/truncate.stories.tsx
- libs/shared/ui/src/lib/components/truncate/truncate.tsx
- libs/shared/ui/src/lib/styles/components/menu.scss
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-367)
- Adding feedback breadcrumb
- Adding truncate on the MenuItem
- Adding truncate on the Header component
---
> Add feedback Breadcrumb

- libs/pages/application/feature/src/lib/components/general/general.tsx
- libs/pages/environments/feature/src/lib/components/deployment-rules/create-deployment-rule/create-deployment-rule.tsx
- libs/pages/environments/feature/src/lib/components/deployment-rules/deployment-rules.tsx
- libs/pages/environments/feature/src/lib/components/deployment-rules/edit-deployment-rule/edit-deployment-rule.tsx
- libs/pages/environments/feature/src/lib/components/general/general.tsx
- libs/pages/services/feature/src/lib/components/deployments/deployments.tsx
- libs/pages/services/feature/src/lib/components/general/general.tsx
Updates wording and links on the footer element
---
- [x ] This PR does not introduce any breaking change
> changed wording and links on footer

- apps/console/src/main.tsx
- libs/domains/application/src/lib/slices/applications.slice.spec.ts
- libs/domains/application/src/lib/slices/applications.slice.ts
- libs/domains/database/src/lib/slices/databases.slice.spec.ts
- libs/domains/database/src/lib/slices/databases.slice.ts
- libs/pages/environments/ui/src/lib/components/general/general.tsx
- libs/pages/services/ui/src/lib/components/general/general.tsx
- libs/shared/interfaces/src/lib/states/applications.interface.ts
- libs/shared/interfaces/src/lib/states/databases.interface.ts
- libs/shared/layout/src/lib/layout.tsx
[> Link to the JIRA ticket](https://qovery.atlassian.net/browse/FRT-430)
- Fixing a services table and environment table not updating the running status value when the websocket update.
It was due to the condition in the React.memo
- Fixing also some performances issue with the cohabitation of pulling deployment status and the running status websockets
- Fixing a react 18 warning about createRoot
---
> fix(websocket): fix websocket and memo

- apps/console/src/app/app.tsx
- libs/shared/router/src/index.ts
- libs/shared/router/src/lib/beta-route/beta-route.spec.tsx
- libs/shared/router/src/lib/beta-route/beta-route.tsx
- libs/shared/router/src/lib/pages/no-beta-access.spec.tsx
- libs/shared/router/src/lib/pages/no-beta-access.tsx
- libs/shared/router/src/lib/router.ts
- libs/shared/ui/src/lib/components/link/link.tsx
- yarn.lock
[> Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23/backlog?assignee=5f4932289a0131004115f0b4&selectedIssue=FRT-399)
- Correctly identify User in Posthog. (todo with Intercom too)
- Add a `BetaRoute` Wrapper like `ProtectedRoute`
- Add some route that are always available even if the guy does not have beta access (eg: Infra log)
- TODO: For now tests are broken like I have never seen (infinite loop and other weird error)
---
> feat(feature-flag): beta access accessible through feature flag

- libs/shared/router/src/lib/beta-route/beta-route.tsx
> fix(beta): restricted access render component instead of navigate

- .github/workflows/semantic-release.yml
- libs/domains/application/src/lib/slices/applications.slice.ts
- libs/domains/environment/src/lib/slices/environments.slice.ts
- libs/pages/application/src/lib/feature/page-deployments-feature/page-deployments-feature.tsx
- libs/pages/services/src/lib/feature/page-deployments-feature/page-deployments-feature.tsx
- libs/shared/router/src/lib/beta-route/beta-route.tsx
- package.json
> Implementing Semantic Release

- libs/domains/application/src/lib/slices/application.actions.ts
- libs/pages/application/src/lib/ui/container/container.tsx
- libs/pages/environments/src/lib/ui/table-row-environments/table-row-environments.tsx
- libs/pages/services/src/lib/ui/container/container.tsx
- libs/pages/services/src/lib/ui/table-row-services/table-row-services.tsx
- libs/shared/ui/src/lib/components/icon/icon.tsx
- libs/shared/ui/src/lib/components/skeleton/skeleton.stories.tsx
- libs/shared/ui/src/lib/components/status-chip/status-chip.stories.tsx
- libs/shared/ui/src/lib/components/status-chip/status-chip.tsx
- tailwind-workspace-preset.js
[> Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-423)
- Add flex-shrink on all icones
- Add stopping, starting, unknown
---
> Chore/status tabs chips FRT-423

- libs/pages/application/src/lib/ui/container/container.tsx
- libs/pages/application/src/lib/ui/page-deployments/page-deployments.tsx
- libs/pages/application/src/lib/ui/page-general/page-general.tsx
- libs/pages/environments/src/lib/ui/container/container.tsx
- libs/pages/environments/src/lib/ui/page-deployment-rules/page-deployment-rules.tsx
- libs/pages/environments/src/lib/ui/page-general/page-general.tsx
- libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx
- libs/pages/services/src/lib/ui/container/container.tsx
- libs/pages/services/src/lib/ui/page-deployments/page-deployments.tsx
- libs/pages/services/src/lib/ui/page-general/page-general.tsx
- libs/shared/ui/src/lib/components/menu/menu-group/menu-group.tsx
- libs/shared/ui/src/lib/components/menu/menu-item/menu-item.tsx
- libs/shared/ui/src/lib/components/menu/menu.spec.tsx
- libs/shared/ui/src/lib/components/table/table-row/table-row.tsx
- libs/shared/ui/src/lib/components/tag-mode/tag-mode.tsx
- libs/shared/ui/src/lib/components/tag/tag.spec.tsx
- libs/shared/ui/src/lib/components/tag/tag.tsx
- yarn.lock
> [Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-440)
Change the design of header buttons and tags
---
> Fix/ Header buttons

- libs/shared/router/src/lib/pages/no-beta-access.tsx
Prevent user from being stuck forever on the restricted access beta page.
> fix(beta-access): fix user stuck on beta access page

- libs/pages/application/src/lib/ui/page-deployments/page-deployments.tsx
- libs/pages/application/src/lib/ui/page-general/page-general.tsx
- libs/pages/environments/src/lib/ui/page-deployment-rules/page-deployment-rules.tsx
- libs/pages/environments/src/lib/ui/page-general/page-general.tsx
- libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx
- libs/pages/services/src/lib/ui/page-deployments/page-deployments.tsx
- libs/pages/services/src/lib/ui/page-general/page-general.tsx
- libs/shared/router/src/lib/pages/no-beta-access.tsx
- nx.json
- tailwind-workspace-preset.js
- yarn.lock
> Merge staging into main

- libs/pages/application/src/lib/feature/page-deployments-feature/page-deployments-feature.tsx
- libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx
- libs/pages/services/src/lib/feature/page-deployments-feature/page-deployments-feature.tsx
- libs/shared/ui/src/index.ts
- libs/shared/ui/src/lib/components/icon/icon.tsx
- libs/shared/ui/src/lib/components/status-chip/status-chip.tsx
- libs/shared/ui/src/lib/components/warning-screen-mobile/warning-screen-mobile.spec.tsx
- libs/shared/ui/src/lib/components/warning-screen-mobile/warning-screen-mobile.stories.tsx
- libs/shared/ui/src/lib/components/warning-screen-mobile/warning-screen-mobile.tsx
> [Link to the JIRA ticket](https://qovery.atlassian.net/browse/FRT-441?atlOrigin=eyJpIjoiNzdhODg5MDgxYjdhNDdlNjhhMWI0YWU3NDAwYjRiYTkiLCJwIjoiaiJ9)
Add warning screen when the window is less than 1024px wide
---
> Feat/Warning screen on mobile 

- apps/console/src/app/app.tsx
- libs/pages/login/src/lib/hooks/use-redirect-if-logged/use-redirect-if-logged.tsx
> fix(use-redirect): remove log

- libs/domains/application/src/lib/slices/application.actions.ts
- libs/domains/environment/src/lib/slices/environment.actions.ts
- libs/pages/application/src/lib/feature/page-deployments-feature/page-deployments-feature.tsx
- libs/pages/application/src/lib/page-application.tsx
- libs/pages/services/src/lib/feature/page-deployments-feature/page-deployments-feature.tsx
- libs/pages/services/src/lib/page-services.tsx
- libs/shared/ui/src/lib/components/icon/icon.tsx
- libs/shared/ui/src/lib/components/status-chip/status-chip.tsx
- Fix deployments refresh when action is launch on environment
- Change progress icon
---
> Fix / Deployments pulling on status update

- __tests__/server.ts
- __tests__/utils/setup-jest.tsx
- libs/domains/application/src/lib/slices/applications.slice.spec.ts
- libs/domains/database/src/lib/slices/databases.slice.spec.ts
- libs/domains/environment/src/lib/slices/environments.slice.spec.ts
- libs/domains/organization/src/lib/slices/cluster.slice.spec.ts
- libs/domains/organization/src/lib/slices/organization.slice.spec.ts
- libs/domains/organization/src/lib/slices/organization.slice.ts
- libs/domains/projects/src/lib/slices/deployment-rules.slice.spec.ts
- libs/domains/projects/src/lib/slices/projects.slice.spec.ts
- libs/domains/user/src/lib/slices/user-sign-up.slice.spec.ts
- libs/pages/login/src/lib/feature/page-login/page-login.tsx
- libs/pages/login/src/lib/hooks/use-redirect-if-logged/use-redirect-if-logged.tsx
- libs/shared/auth/src/lib/use-auth/use-auth.spec.ts
- libs/shared/ui/src/lib/components/slider/slider.spec.tsx
> feat(tests): remove warning and broken tests

- README.md
- package.json
- s.sh
- Update README
- Add script
---
> feat(contributing): indications

- libs/pages/layout/src/lib/feature/layout/layout.tsx
- libs/pages/login/src/lib/hooks/use-redirect-if-logged/use-redirect-if-logged.spec.tsx
- libs/pages/login/src/lib/hooks/use-redirect-if-logged/use-redirect-if-logged.tsx
- libs/pages/login/src/lib/hooks/use-redirect-if-logged/utils/utils.tsx
- libs/shared/router/src/lib/protected-route/protected-route.tsx
- yarn.lock
Store the current organizationId and projectId on the localStorage to redirect the user on it on the next session/login
---
> Add redirect on the previous project

- libs/domains/application/src/lib/slices/application.actions.ts
- libs/domains/database/src/lib/slices/database.actions.ts
- libs/domains/database/src/lib/slices/databases.slice.ts
- libs/domains/environment/src/lib/slices/environment.actions.ts
- libs/pages/application/src/lib/page-application.tsx
- libs/pages/application/src/lib/ui/container/container.tsx
- libs/pages/database/src/lib/page-database.tsx
- libs/pages/database/src/lib/ui/container/container.tsx
- libs/pages/environments/src/lib/feature/page-general-feature/page-general-feature.tsx
- libs/pages/services/src/lib/feature/table-row-services-feature/table-row-services-feature.tsx
- libs/pages/services/src/lib/page-services.tsx
- libs/pages/services/src/lib/ui/container/container.tsx
- libs/pages/services/src/lib/ui/table-row-services/table-row-services.tsx
- libs/shared/ui/src/lib/components/buttons/button-icon-action/button-icon-action-element/button-icon-action-element.tsx
- libs/shared/ui/src/lib/components/buttons/button-icon-action/button-icon-action.tsx
- libs/shared/ui/src/lib/components/status-menu-action/status-menu-action.tsx
> [Link to the JIRA ticket](https://qovery.atlassian.net/browse/FRT-405?atlOrigin=eyJpIjoiNWUxODAwYzk1NmE3NDJkZTk0YzVjMjkxYjVlOGI0OWUiLCJwIjoiaiJ9)
Move remove button from status menu to a side menu
---
- x ] This PR does not introduce any breaking change
> feat(delete-action): move button and add action

- libs/domains/application/src/lib/slices/application.actions.ts
- libs/domains/database/src/lib/slices/database.actions.ts
- libs/domains/environment/src/lib/slices/environment.actions.ts
- libs/pages/application/src/lib/page-application.tsx
- libs/pages/application/src/lib/ui/container/container.tsx
- libs/pages/database/src/lib/page-database.tsx
- libs/pages/database/src/lib/ui/container/container.tsx
- libs/pages/environments/src/lib/feature/page-general-feature/page-general-feature.tsx
- libs/pages/layout/src/lib/feature/layout/layout.tsx
- libs/pages/logs/infra/src/lib/ui/row/row.tsx
- libs/pages/services/src/lib/feature/table-row-services-feature/table-row-services-feature.tsx
- libs/pages/services/src/lib/page-services.tsx
- libs/pages/services/src/lib/ui/container/container.tsx
- libs/pages/services/src/lib/ui/table-row-services/table-row-services.tsx
- libs/shared/ui/src/index.ts
- libs/shared/ui/src/lib/components/buttons/button-icon-action/button-icon-action-element/button-icon-action-element.tsx
- libs/shared/ui/src/lib/components/buttons/button-icon-action/button-icon-action.tsx
- libs/shared/ui/src/lib/components/copy-to-clipboard/copy-to-clipboard.spec.tsx
- libs/shared/ui/src/lib/components/copy-to-clipboard/copy-to-clipboard.stories.tsx
- libs/shared/ui/src/lib/components/copy-to-clipboard/copy-to-clipboard.tsx
- libs/shared/ui/src/lib/components/copy-to-clipboard/utils/copy-to-clipboard.tsx
- libs/shared/ui/src/lib/components/header/header.tsx
- libs/shared/ui/src/lib/components/layouts/layout-logs/tabs-logs/card-cluster/card-cluster.tsx
- libs/shared/ui/src/lib/components/status-menu-action/status-menu-action.tsx
- libs/shared/ui/src/lib/styles/main.scss
- libs/shared/ui/src/lib/styles/utils/bigger-click-zone.scss
> Merge Stagin in Main

- libs/domains/environment/src/lib/slices/environment.actions.ts
- libs/domains/environment/src/lib/slices/environments.slice.ts
- libs/pages/environments/src/lib/feature/page-general-feature/page-general-feature.tsx
- libs/pages/environments/src/lib/ui/page-general/page-general.tsx
- libs/pages/environments/src/lib/ui/table-row-environments/table-row-environments.tsx
- libs/pages/services/src/lib/page-services.tsx
- libs/shared/ui/src/lib/components/buttons/button-icon-action/button-icon-action.tsx
- Adding delete Environments on list
- Improvement delete behavior with redirection and update store
---
> feat(environments): add remove action

- libs/domains/projects/src/lib/slices/deployment-rules.slice.ts
- libs/pages/environments/src/lib/ui/deployment-rule-item/deployment-rule-item.tsx
- libs/pages/environments/src/lib/ui/page-deployment-rules/page-deployment-rules.tsx
- yarn.lock
Change the UI of deployment rules list according to the Figma
---
> feat(dep-rules): change the UI of the list

- libs/pages/layout/src/lib/ui/navigation/navigation.tsx
- libs/shared/router/src/lib/beta-route/beta-route.tsx
- libs/shared/ui/src/lib/components/layouts/breadcrumb-item/breadcrumb-item.tsx
- libs/shared/ui/src/lib/components/layouts/breadcrumb/breadcrumb.tsx
- Infra logs page, remove the internal redirect
- Activate beta route
---
> feat(infra-logs): remove internal links

- libs/domains/database/src/lib/slices/databases.slice.ts
- libs/pages/application/src/lib/feature/page-deployments-feature/page-deployments-feature.tsx
- libs/pages/application/src/lib/ui/instances-table/instances-table.tsx
- libs/pages/application/src/lib/ui/page-deployments/page-deployments.tsx
- libs/pages/application/src/lib/ui/page-general/page-general.tsx
- libs/pages/database/src/lib/feature/page-deployments-feature/page-deployments-feature.tsx
- libs/pages/database/src/lib/ui/container/container.tsx
- libs/pages/database/src/lib/ui/instances-table/instances-table.tsx
- libs/pages/database/src/lib/ui/page-deployments/page-deployments.tsx
- libs/pages/database/src/lib/ui/page-general/page-general.tsx
- libs/pages/layout/src/lib/feature/breadcrumb/breadcrumb.tsx
- libs/pages/services/src/lib/ui/page-deployments/page-deployments.tsx
- libs/shared/ui/src/lib/components/buttons/button-icon-action/button-icon-action.tsx
- libs/shared/ui/src/lib/components/table/table-row-deployment/table-row-deployment.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-392
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-395
- Added Database deployments page
- Fixed logs links for Database, Applications, and Services deployments page
- Updated UI detail for Database and Application
- Warning: I need to update the API Doc because deployments database results are mistyped (I added todo)
---
> feat(database): add deployments list and update UI details

- libs/pages/environments/src/lib/ui/table-row-environments/table-row-environments.tsx
- libs/pages/services/src/lib/feature/page-general-feature/page-general-feature.tsx
- libs/pages/services/src/lib/ui/table-row-services/table-row-services.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-433)
- Remove glitch page services when we have Databases and Applications
- Add a placeholder for status
https://www.loom.com/share/3215517d1e9f4bd689326310d21c0768
---
> fix(page-services): placeholders glitching

- libs/pages/application/src/lib/ui/last-commit/last-commit.tsx
- libs/pages/layout/src/lib/ui/navigation/navigation.tsx
- libs/shared/ui/src/lib/components/avatar/avatar.spec.tsx
- libs/shared/ui/src/lib/components/avatar/avatar.tsx
- libs/shared/ui/src/lib/components/table/table-row-deployment/table-row-deployment.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-404)
- Add tooltip for Avatar
- Fix commit first name last on Application page
---
> fix(avatar): add tooltip

- libs/shared/ui/src/lib/components/buttons/button-action/button-action.stories.tsx
- libs/shared/ui/src/lib/components/buttons/button-action/button-action.tsx
- libs/shared/ui/src/lib/styles/components/button-action.scss
Add a large size on the component ButtonAction
---
> feat(button-action): add large size

- libs/pages/application/src/lib/feature/crud-environment-variable-modal-feature/crud-environment-variable-modal-feature.spec.tsx
- libs/pages/application/src/lib/feature/crud-environment-variable-modal-feature/handle-submit/handle-submit.spec.tsx
> test(environment-variable): polishing test for environment variable

- __tests__/utils/wrap-with-react-hook-form.tsx
- libs/pages/application/src/lib/feature/crud-environment-variable-modal-feature/crud-environment-variable-modal-feature.spec.tsx
- libs/pages/application/src/lib/feature/import-environment-variable-modal-feature/import-environment-variable-modal-feature.spec.tsx
- libs/pages/application/src/lib/feature/import-environment-variable-modal-feature/import-environment-variable-modal-feature.tsx
- libs/shared/interfaces/src/lib/domain/cluster.entity.ts
- libs/shared/ui/src/lib/components/layouts/layout-logs/tabs-logs/card-cluster/card-cluster.tsx
- package.json
- yarn.lock
> chore: api update

- libs/pages/environments/src/lib/ui/table-row-environments/table-row-environments.tsx
- package.json
- yarn.lock
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-450)
- Update open-api
- Add cluster name for Environments list
---
> feat(environments): add cluster name

- libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.spec.tsx
- libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
- libs/pages/application/src/lib/feature/tabs-feature/tabs-feature.tsx
- libs/pages/application/src/lib/router/router.tsx
- libs/pages/application/src/lib/ui/page-settings-danger-zone/page-settings-danger-zone.tsx
- libs/pages/application/src/lib/ui/page-settings-general/page-settings-general.spec.tsx
- libs/pages/application/src/lib/ui/page-settings-general/page-settings-general.tsx
- libs/pages/application/src/lib/ui/page-settings-storage/page-settings-storage.spec.tsx
- libs/pages/application/src/lib/ui/page-settings-storage/page-settings-storage.tsx
- libs/pages/database/src/lib/ui/page-settings-danger-zone/page-settings-danger-zone.tsx
- libs/pages/environments/src/lib/ui/page-create-edit-deployment-rule/page-create-edit-deployment-rule.tsx
- libs/pages/services/src/lib/ui/page-settings-danger-zone/page-settings-danger-zone.tsx
- libs/pages/services/src/lib/ui/page-settings-general/page-settings-general.tsx
- libs/pages/services/src/lib/ui/page-settings-preview-environments/page-settings-preview-environments.tsx
- libs/shared/ui/src/lib/components/block-content-delete/block-content-delete.tsx
- libs/shared/ui/src/lib/components/buttons/button/button.spec.tsx
- libs/shared/ui/src/lib/components/buttons/button/button.tsx
- libs/shared/ui/src/lib/components/inputs/input-select-small/input-select-small.tsx
- libs/shared/ui/src/lib/components/inputs/input-select/input-select.tsx
- libs/shared/ui/src/lib/components/inputs/input-text/input-text.tsx
- libs/shared/utils/src/lib/tools/refacto-payload.spec.ts
- libs/shared/utils/src/lib/tools/refacto-payload.ts
- tailwind-workspace-preset.js
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-458)
- First part of General settings with General information and Build mode
- Update max-width for all Settings pages
---
> feat(application-settings): add general section

- libs/domains/environment/src/lib/mocks/factories/environment-factory.mock.ts
- libs/pages/environments/src/lib/feature/page-create-deployment-rule-feature/page-create-deployment-rule-feature.tsx
- libs/pages/environments/src/lib/ui/page-create-edit-deployment-rule/page-create-edit-deployment-rule.tsx
- libs/pages/services/src/lib/feature/page-settings-deployment-feature/page-settings-deployment-feature.spec.tsx
- libs/pages/services/src/lib/feature/page-settings-deployment-feature/page-settings-deployment-feature.tsx
- libs/pages/services/src/lib/feature/page-settings-preview-environments-feature/page-settings-preview-environments-feature.tsx
- libs/pages/services/src/lib/router/router.tsx
- libs/pages/services/src/lib/ui/page-settings-deployment/page-settings-deployment.spec.tsx
- libs/pages/services/src/lib/ui/page-settings-deployment/page-settings-deployment.tsx
- libs/pages/services/src/lib/ui/page-settings-general/page-settings-general.tsx
- libs/pages/services/src/lib/ui/page-settings-preview-environments/page-settings-preview-environments.tsx
- libs/pages/services/src/lib/ui/page-settings/page-settings.tsx
- libs/shared/ui/src/lib/components/inputs/input-select-multiple/input-select-multiple.tsx
- libs/shared/ui/src/lib/components/inputs/input-select/input-select.tsx
- libs/shared/ui/src/lib/styles/components/select-multiple.scss
- libs/shared/utils/src/index.ts
- libs/shared/utils/src/lib/constants/environment-mode-values.ts
- libs/shared/utils/src/lib/constants/timezone-values.ts
- libs/shared/utils/src/lib/constants/weekdays-values.ts
- tailwind-workspace-preset.js
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-383)
- Added Deployment rules for Environment
- Added loading for Preview env
- Added section title for all Environment settings
---
> feat(environment-settings): deployment

- libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.spec.tsx
- libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-ports-feature/page-settings-ports-feature.spec.tsx
- libs/pages/application/src/lib/feature/page-settings-ports-feature/page-settings-ports-feature.tsx
- libs/pages/application/src/lib/router/router.tsx
- libs/pages/application/src/lib/ui/page-settings-ports/crud-modal/crud-modal.spec.tsx
- libs/pages/application/src/lib/ui/page-settings-ports/crud-modal/crud-modal.tsx
- libs/pages/application/src/lib/ui/page-settings-ports/page-settings-ports.spec.tsx
- libs/pages/application/src/lib/ui/page-settings-ports/page-settings-ports.tsx
- libs/shared/ui/src/lib/components/inputs/input-toggle/input-toggle.tsx
- tailwind-workspace-preset.js
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-461)
- Added Ports settings section
- Fixed min-height settings Tailwind variable 
---
> feat(application-settings): add port section 

- libs/domains/database/src/lib/slices/databases.slice.ts
- libs/pages/application/src/lib/feature/page-deployments-feature/page-deployments-feature.tsx
- libs/pages/application/src/lib/ui/page-deployments/page-deployments.tsx
- libs/pages/application/src/lib/ui/page-general/page-general.tsx
- libs/pages/database/src/lib/feature/page-deployments-feature/page-deployments-feature.tsx
- libs/pages/database/src/lib/ui/page-deployments/page-deployments.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-507
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-512
> fix(deployments): database and application fetching deployments

- libs/pages/application/src/lib/feature/crud-environment-variable-modal-feature/handle-submit/handle-submit.tsx
- libs/pages/application/src/lib/ui/import-environment-variable-modal/import-environment-variable-modal.spec.tsx
Fixing bug reported by Melvin:
https://qovery.atlassian.net/browse/COR-467?focusedCommentId=12599
> fix(secret-environment): fix updating alias secret COR-467

- libs/domains/database/src/lib/slices/databases.slice.ts
- libs/pages/database/src/lib/feature/page-settings-general-feature/page-settings-general-feature.spec.tsx
- libs/pages/database/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
- libs/pages/database/src/lib/router/router.tsx
- libs/pages/database/src/lib/ui/page-settings-general/page-settings-general.spec.tsx
- libs/pages/database/src/lib/ui/page-settings-general/page-settings-general.tsx
- libs/pages/database/src/lib/ui/page-settings/page-settings.tsx
- libs/shared/utils/src/lib/tools/refacto-payload.spec.ts
- libs/shared/utils/src/lib/tools/refacto-payload.ts
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-520)
- Add general section for Database settings
---
> feat(database-settings): add general section

- libs/pages/application/src/lib/ui/container/container.tsx
- libs/pages/services/src/lib/ui/table-row-services/table-row-services.tsx
- libs/shared/ui/src/lib/components/buttons/button-icon-action/button-icon-action-element/button-icon-action-element.tsx
- libs/shared/ui/src/lib/components/icon/icon-awesome.enum.tsx
- libs/shared/ui/src/lib/components/menu/menu-item/menu-item.tsx
- libs/shared/ui/src/lib/styles/base/icons.scss
- libs/shared/utils/src/index.ts
- libs/shared/utils/src/lib/tools/url-code-editor.spec.ts
- libs/shared/utils/src/lib/tools/url-code-editor.ts
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-511)
- Add button for Edit code
---
> feat(sub-menu): add edit code link

- libs/domains/database/src/lib/mocks/factories/database-factory.mock.ts
- libs/pages/application/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.spec.tsx
- libs/pages/application/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx
- libs/pages/application/src/lib/ui/page-settings-resources/page-settings-resources.spec.tsx
- libs/pages/application/src/lib/ui/page-settings-resources/page-settings-resources.tsx
- libs/pages/database/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.spec.tsx
- libs/pages/database/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx
- libs/pages/database/src/lib/router/router.tsx
- libs/pages/database/src/lib/ui/page-settings-resources/page-settings-resources.spec.tsx
- libs/pages/database/src/lib/ui/page-settings-resources/page-settings-resources.tsx
- libs/shared/ui/src/index.ts
- libs/shared/ui/src/lib/components/inputs/input-size-unit/input-size-unit.spec.tsx
- libs/shared/ui/src/lib/components/inputs/input-size-unit/input-size-unit.stories.tsx
- libs/shared/ui/src/lib/components/inputs/input-size-unit/input-size-unit.tsx
- libs/shared/ui/src/lib/components/inputs/input-size-unit/utils.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-520)
- Add section Resources for Database
- Add a shared component to manage Units (add it for the Resources General section too)
---
> feat(database-settings): add resources section

- libs/pages/application/src/lib/page-application.tsx
- libs/pages/application/src/lib/ui/page-deployments/page-deployments.tsx
- libs/pages/services/src/lib/feature/page-deployments-feature/page-deployments-feature.tsx
- libs/pages/services/src/lib/feature/table-row-services-feature/table-row-services-feature.spec.tsx
- libs/pages/services/src/lib/ui/page-deployments/page-deployments.tsx
- libs/shared/ui/src/lib/components/table/table-row-deployment/table-row-deployment.spec.tsx
- libs/shared/ui/src/lib/components/table/table-row-deployment/table-row-deployment.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-517)
- Adding Deployment list for Containers (services and detail page)
---
> feat(container): add deployment

- libs/domains/application/src/lib/slices/applications.slice.ts
- libs/domains/application/src/lib/slices/custom-domain.slice.ts
- libs/pages/application/src/lib/feature/page-settings-advanced-feature/page-settings-advanced-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-danger-zone-feature/page-settings-danger-zone-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-domains-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-domains-feature/page-settings-domains-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-ports-feature/page-settings-ports-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-storage-feature/page-settings-storage-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-storage-feature/storage-modal-feature/storage-modal-feature.tsx
- libs/pages/application/src/lib/page-application.tsx
- libs/pages/application/src/lib/ui/about/about.spec.tsx
- libs/pages/application/src/lib/ui/container/container.tsx
- libs/pages/application/src/lib/ui/page-settings-general/page-settings-general.spec.tsx
- libs/pages/application/src/lib/ui/page-settings-general/page-settings-general.tsx
- libs/pages/services/src/lib/feature/page-settings-preview-environments-feature/page-settings-preview-environments-feature.tsx
- libs/shared/ui/src/lib/components/table/table-row-deployment/table-row-deployment.tsx
- libs/shared/utils/src/lib/tools/refacto-payload.spec.ts
- libs/shared/utils/src/lib/tools/refacto-payload.ts
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-525)
- Add settings for Containers
---
- [ x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
> feat(container): add settings

- libs/domains/organization/src/lib/slices/organization.slice.ts
- libs/pages/settings/src/lib/feature/page-organization-danger-zone-feature/page-organization-danger-zone-feature.spec.tsx
- libs/pages/settings/src/lib/feature/page-organization-danger-zone-feature/page-organization-danger-zone-feature.tsx
- libs/pages/settings/src/lib/router/router.tsx
- libs/pages/settings/src/lib/ui/page-organization-danger-zone/page-organization-danger-zone.spec.tsx
- libs/pages/settings/src/lib/ui/page-organization-danger-zone/page-organization-danger-zone.tsx
- libs/shared/ui/src/lib/components/block-content-delete/block-content-delete.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-494)
---
> feat(organization): danger zone settings

- libs/shared/ui/src/lib/components/inputs/input-select/input-select.tsx
- libs/shared/ui/src/lib/styles/components/select.scss
- Clean classNames
- Refactoring code (more simple)
- Remove icon translate
- Fix isMulti (selected values on the options list)
---
> fix(input-select): icon and isMulti

- libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx
- libs/pages/layout/src/lib/ui/navigation/navigation.tsx
- libs/pages/layout/src/lib/ui/top-bar/top-bar.tsx
- libs/pages/services/src/lib/feature/page-application-create-feature/page-application-create-feature.tsx
- libs/shared/ui/src/lib/components/funnel-flow/funnel-flow.spec.tsx
- libs/shared/ui/src/lib/components/funnel-flow/funnel-flow.tsx
- tailwind-workspace-preset.js
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-504)
- Remove fixed element for Intercom banner
---
> fix(layout): replace fixed element to stick

- libs/domains/application/src/lib/slices/applications.slice.ts
- libs/domains/environment/src/lib/slices/environment.actions.ts
- libs/pages/application/src/lib/feature/page-settings-domains-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-ports-feature/page-settings-ports-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-storage-feature/page-settings-storage-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-storage-feature/storage-modal-feature/storage-modal-feature.tsx
- libs/pages/services/src/lib/feature/page-settings-preview-environments-feature/page-settings-preview-environments-feature.tsx
- libs/shared/ui/src/lib/components/table/table-row-deployment/table-row-deployment.tsx
- libs/shared/utils/src/lib/tools/refacto-payload.spec.ts
- libs/shared/utils/src/lib/tools/refacto-payload.ts
fixes: 
- https://qovery.slack.com/archives/C02P2JB4SEM/p1664790373657569
- https://qovery.slack.com/archives/C02P2JB4SEM/p1664790484709759
- https://qovery.slack.com/archives/C02P2JB4SEM/p1664793297709109
> fix(global): action message error + toaster actions issue

- libs/pages/services/src/lib/feature/page-database-create-feature/page-database-create-general-feature/page-database-create-general-feature.tsx
> fix(create-database): updated link on database flow

- libs/domains/organization/src/lib/mocks/organizations-factory.mock.ts
- libs/domains/organization/src/lib/slices/organization.slice.ts
- libs/pages/settings/src/lib/feature/page-organization-general-feature/page-organization-general-feature.tsx
- libs/pages/settings/src/lib/feature/page-organization-members-feature/page-organization-members-feature.spec.tsx
- libs/pages/settings/src/lib/feature/page-organization-members-feature/page-organization-members-feature.tsx
- libs/pages/settings/src/lib/feature/page-organization-roles-feature/page-organization-roles-feature.spec.tsx
- libs/pages/settings/src/lib/feature/page-organization-roles-feature/page-organization-roles-feature.tsx
- libs/pages/settings/src/lib/router/router.tsx
- libs/pages/settings/src/lib/ui/page-organization-members/page-organization-members.spec.tsx
- libs/pages/settings/src/lib/ui/page-organization-members/page-organization-members.tsx
- libs/pages/settings/src/lib/ui/page-organization-members/row-member/row-member.spec.tsx
- libs/pages/settings/src/lib/ui/page-organization-members/row-member/row-member.tsx
- libs/pages/settings/src/lib/ui/page-organization-roles/page-organization-roles.spec.tsx
- libs/pages/settings/src/lib/ui/page-organization-roles/page-organization-roles.tsx
- libs/shared/interfaces/src/lib/domain/organization.entity.ts
- libs/shared/ui/src/lib/components/icon/icon-awesome.enum.tsx
- libs/shared/ui/src/lib/components/menu/menu.tsx
- libs/shared/ui/src/lib/components/table/table-head-filter/table-head-filter.tsx
- libs/shared/ui/src/lib/components/table/table-head-sort/table-head-sort.tsx
- libs/shared/ui/src/lib/components/table/table.stories.tsx
- libs/shared/ui/src/lib/components/table/table.tsx
- libs/shared/ui/src/lib/styles/base/icons.scss
- libs/shared/ui/src/lib/styles/components/button.scss
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-492)
---
> feat(organizations): members settings

- libs/domains/organization/src/lib/mocks/organizations-factory.mock.ts
- libs/domains/organization/src/lib/slices/organization.slice.ts
- libs/pages/onboarding/src/lib/feature/onboarding-pricing/onboarding-pricing.tsx
- libs/pages/onboarding/src/lib/ui/step-pricing/step-pricing.spec.tsx
- libs/pages/onboarding/src/lib/ui/step-pricing/step-pricing.tsx
- libs/pages/settings/src/lib/feature/page-organization-members-feature/page-organization-members-feature.spec.tsx
- libs/pages/settings/src/lib/feature/page-organization-members-feature/page-organization-members-feature.tsx
- libs/pages/settings/src/lib/ui/page-organization-members/page-organization-members.spec.tsx
- libs/pages/settings/src/lib/ui/page-organization-members/page-organization-members.tsx
- libs/pages/settings/src/lib/ui/page-organization-members/row-member/row-member.spec.tsx
- libs/pages/settings/src/lib/ui/page-organization-members/row-member/row-member.tsx
- libs/shared/ui/src/lib/components/icon/icon-awesome.enum.tsx
- libs/shared/ui/src/lib/components/menu/menu-group/menu-group.tsx
- libs/shared/ui/src/lib/components/menu/menu-item/menu-item.tsx
- libs/shared/ui/src/lib/styles/base/icons.scss
- libs/shared/ui/src/lib/styles/components/menu.scss
- package.json
- yarn.lock
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-492)
- Add a delete action
- Add transfer ownership action
---
> feat(members-settings): delete and transfer ownership actions

- .github/workflows/nx-cloud-main.yml
- .github/workflows/test-build-and-deploy.yml
- yarn.lock
This pr clean the github actions that was a little bit too complex and out-to-date by using latest nx recommendations.
It makes a better usage of nx agents, parallelized more actions, making a better usage of nx cache, and restore colors in logs.
It's also a good prep work for coming image registry deployment if we want to implement it. 
Before
After
> chore(ci): simplifying github actions

- .github/workflows/test-build-and-deploy.yml
- libs/shared/ui/src/lib/components/inputs/input-select-small/input-select-small.spec.tsx
- libs/shared/ui/src/lib/components/inputs/input-select-small/input-select-small.tsx
Silent the jest warning to reduce noise in the ci logs
> chore(ci): silent jest warning

- libs/pages/application/src/lib/feature/crud-environment-variable-modal-feature/crud-environment-variable-modal-feature.tsx
- libs/pages/application/src/lib/feature/import-environment-variable-modal-feature/import-environment-variable-modal-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-advanced-feature/page-settings-advanced-feature.spec.tsx
- libs/pages/application/src/lib/feature/page-settings-domains-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/application/src/lib/ui/page-settings-storage/storage-modal/storage-modal.tsx
- libs/pages/environments/src/lib/feature/create-clone-environment-modal-feature/create-clone-environment-modal-feature.spec.tsx
- libs/pages/environments/src/lib/feature/create-clone-environment-modal-feature/create-clone-environment-modal-feature.tsx
- libs/pages/environments/src/lib/ui/container/container.tsx
- libs/shared/ui/src/index.ts
- libs/shared/ui/src/lib/components/modal-alert/modal-alert.spec.tsx
- libs/shared/ui/src/lib/components/modal-alert/modal-alert.tsx
- libs/shared/ui/src/lib/components/modal-alert/use-modal-alert/use-modal-alert.spec.tsx
- libs/shared/ui/src/lib/components/modal-alert/use-modal-alert/use-modal-alert.tsx
- libs/shared/ui/src/lib/components/modal/modal-root.spec.tsx
- libs/shared/ui/src/lib/components/modal/modal-root.tsx
- libs/shared/ui/src/lib/components/modal/modal.spec.tsx
- libs/shared/ui/src/lib/components/modal/modal.tsx
- libs/shared/ui/src/lib/components/modal/use-modal/use-modal.tsx
- libs/shared/ui/src/lib/components/modals/modal-confirmation/use-modal-confirmation/use-modal-confirmation.spec.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-554
> feat(modal): confirm on click outside

- libs/domains/application/src/lib/slices/application.actions.ts
- libs/domains/application/src/lib/slices/applications.slice.ts
- libs/pages/application/src/lib/ui/container/container.tsx
- libs/pages/services/src/lib/ui/table-row-services/table-row-services.tsx
- libs/shared/console-shared/src/lib/deploy-other-commit-modal/feature/deploy-other-commit-modal-feature.spec.tsx
- libs/shared/console-shared/src/lib/deploy-other-commit-modal/feature/deploy-other-commit-modal-feature.tsx
- libs/shared/console-shared/src/lib/deploy-other-commit-modal/ui/deploy-other-commit-modal.spec.tsx
- libs/shared/console-shared/src/lib/deploy-other-commit-modal/ui/deploy-other-commit-modal.tsx
- libs/shared/ui/src/lib/components/inputs/input-search/input-search.tsx
- libs/shared/utils/src/lib/tools/date.tsx
[> Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-510)
Allow to deploy a certain commit id for an application
---
- [ x] I made sure the code is type safe (no any)
> feat(deploy): deploy different commits

- .github/workflows/semantic-release.yml
- package.json
- yarn.lock
Create a new action that you can trigger via a button in action menu
> feat(semantic-release): github action trigger by button

- libs/pages/services/src/lib/ui/page-database-create/page-database-create-general/page-database-create-general.tsx
A simple typo fix in the database creation configuration modal.
> fix(database-create): typo fix, snapshots

- libs/pages/services/src/lib/ui/page-database-create/page-database-create-general/page-database-create-general.tsx
- libs/pages/settings/src/lib/ui/page-organization-general/page-organization-general.tsx
I fix small typos from the web ui
---
> fix(text): fix small typos

- libs/pages/logs/application/src/lib/page-application-logs.tsx
- libs/shared/ui/src/lib/components/icon/icon-awesome.enum.tsx
- libs/shared/ui/src/lib/components/layouts/layout-logs/layout-logs.tsx
- libs/shared/ui/src/lib/components/menu/menu-item/menu-item.tsx
- libs/shared/ui/src/lib/components/menu/menu.spec.tsx
- libs/shared/ui/src/lib/components/table/table-head-filter/table-head-filter.spec.tsx
- libs/shared/ui/src/lib/components/table/table-head-filter/table-head-filter.tsx
- libs/shared/ui/src/lib/components/table/table.stories.tsx
- libs/shared/ui/src/lib/components/table/table.tsx
- libs/shared/ui/src/lib/styles/base/icons.scss
- libs/shared/ui/src/lib/styles/components/button.scss
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-595)
- Add props `itemContentCustom` for Menu
- Add props `menuWidth` for Menu
- Add filter by pod name for Application logs
---
> feat(application-logs): pod name filter

- libs/pages/application/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-594)
- Fix resources warning CPU with the cluster CPU
---
> fix(application): resources warning cpu

- libs/shared/console-shared/src/lib/application-buttons-actions/application-buttons-actions.tsx
- libs/shared/utils/src/lib/tools/status-actions-available.tsx
[> Link to the JIRA ticket](https://qovery.atlassian.net/browse/FRT-573?focusedCommentId=12718)
Adding cancel deployment on service (triggering the environment cancel deployment)
---
> feat(deployment): cancel deployment on services

- libs/pages/application/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.spec.tsx
- libs/pages/application/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx
- libs/pages/application/src/lib/ui/page-settings-resources/page-settings-resources.spec.tsx
- libs/pages/application/src/lib/ui/page-settings-resources/page-settings-resources.tsx
- libs/pages/database/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.spec.tsx
- libs/pages/database/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx
- libs/pages/database/src/lib/ui/page-settings-resources/page-settings-resources.spec.tsx
- libs/pages/database/src/lib/ui/page-settings-resources/page-settings-resources.tsx
- libs/pages/services/src/lib/feature/page-application-create-feature/application-creation-flow.interface.ts
- libs/pages/services/src/lib/feature/page-application-create-feature/page-application-create-feature.tsx
- libs/pages/services/src/lib/feature/page-application-create-feature/page-application-create-resources-feature/page-application-create-resources-feature.spec.tsx
- libs/pages/services/src/lib/feature/page-application-create-feature/page-application-post-feature/page-application-install-post.spec.tsx
- libs/pages/services/src/lib/feature/page-application-create-feature/page-application-post-feature/page-application-post-feature.tsx
- libs/pages/services/src/lib/feature/page-database-create-feature/database-creation-flow.interface.ts
- libs/pages/services/src/lib/feature/page-database-create-feature/page-database-create-feature.tsx
- libs/pages/services/src/lib/feature/page-database-create-feature/page-database-create-post-feature/page-database-create-post-feature.spec.tsx
- libs/pages/services/src/lib/feature/page-database-create-feature/page-database-create-post-feature/page-database-create-post-feature.tsx
- libs/pages/services/src/lib/feature/page-database-create-feature/page-database-create-resources-feature/page-database-create-resources-feature.spec.tsx
- libs/pages/services/src/lib/ui/page-application-create/page-application-create-resources/page-application-create-resources.tsx
- libs/pages/services/src/lib/ui/page-application-create/page-application-post/page-application-post.spec.tsx
- libs/pages/services/src/lib/ui/page-application-create/page-application-post/page-application-post.tsx
- libs/pages/services/src/lib/ui/page-database-create/page-database-create-post/page-database-create-post.spec.tsx
- libs/pages/services/src/lib/ui/page-database-create/page-database-create-post/page-database-create-post.tsx
- libs/pages/services/src/lib/ui/page-database-create/page-database-create-resources/page-database-create-resources.tsx
- libs/shared/console-shared/src/lib/setting-resources/ui/setting-resources.spec.tsx
- libs/shared/console-shared/src/lib/setting-resources/ui/setting-resources.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-600)
- Remove input unit
- Add input number for Memory
- Clean input number for Storage (remove useless props and state)
---
> fix(resources): change input unit to input number

- libs/pages/logs/deployment/src/lib/ui/row/row.spec.tsx
- libs/pages/logs/deployment/src/lib/ui/row/row.tsx
- Remove ANSI characters for deployments logs
---
> feat(deployment-logs): rows remove ANSI characters

- libs/domains/application/src/lib/slices/application.actions.ts
- libs/domains/application/src/lib/slices/applications.slice.ts
- libs/domains/environment-variable/src/lib/slices/environment-variables.slice.ts
- libs/pages/application/src/lib/ui/container/container.tsx
- libs/pages/application/src/lib/ui/page-general/page-general.tsx
- libs/pages/services/src/lib/ui/table-row-services/table-row-services.tsx
- libs/shared/console-shared/src/lib/application-buttons-actions/application-buttons-actions.tsx
- libs/shared/console-shared/src/lib/environment-buttons-actions/environment-buttons-actions.tsx
- libs/shared/enums/src/lib/utils/get-service-type.ts
- package.json
- yarn.lock
- Add Job deployment page
- Add Job status request
- Add Job about section (image information) for Overview
- Add Job variables 
- Add Job actions
---
> feat(pages-job): about + deployments + variables + actions and status

- libs/domains/projects/src/lib/slices/projects.slice.ts
- libs/pages/settings/src/lib/feature/page-project-danger-zone-feature/page-project-danger-zone-feature.spec.tsx
- libs/pages/settings/src/lib/feature/page-project-danger-zone-feature/page-project-danger-zone-feature.tsx
- libs/pages/settings/src/lib/feature/page-project-general-feature/page-project-general-feature.spec.tsx
- libs/pages/settings/src/lib/feature/page-project-general-feature/page-project-general-feature.tsx
- libs/pages/settings/src/lib/page-settings.tsx
- libs/pages/settings/src/lib/router/router.tsx
- libs/pages/settings/src/lib/ui/page-project-danger-zone/page-project-danger-zone.spec.tsx
- libs/pages/settings/src/lib/ui/page-project-danger-zone/page-project-danger-zone.tsx
- libs/pages/settings/src/lib/ui/page-project-general/page-project-general.spec.tsx
- libs/pages/settings/src/lib/ui/page-project-general/page-project-general.tsx
- libs/shared/router/src/lib/sub-router/settings.router.ts
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-582)
- Add Project General settings
- Add Project Danger Zone settings
---
> feat(settings-project): add general and danger zone

- libs/pages/logs/application/src/lib/page-application-logs.tsx
- libs/pages/logs/application/src/lib/ui/row/row.spec.tsx
- libs/pages/logs/application/src/lib/ui/row/row.tsx
> fix(logs): pod version

- libs/shared/ui/src/lib/styles/components/input.scss
> feat(input): update focus outline

- libs/pages/logs/deployment/src/lib/ui/row/row.tsx
- libs/shared/ui/src/index.ts
- libs/shared/ui/src/lib/components/buttons/button/button.tsx
- libs/shared/ui/src/lib/components/layouts/layout-logs/layout-logs.tsx
- libs/shared/ui/src/lib/components/layouts/layout-logs/update-time-context/update-time-context.spec.tsx
- libs/shared/ui/src/lib/components/layouts/layout-logs/update-time-context/update-time-context.tsx
- libs/shared/ui/src/lib/components/modal/modal-root.spec.tsx
- libs/shared/ui/src/lib/styles/components/button.scss
- libs/shared/utils/src/lib/tools/date.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-608)
- Add time format dropdown for Deployment logs
---
> feat(logs): button update time format

- libs/pages/environments/src/lib/feature/page-general-feature/page-general-feature.tsx
- libs/pages/environments/src/lib/page-environments.tsx
- libs/pages/environments/src/lib/ui/container/container.tsx
- libs/pages/environments/src/lib/ui/page-general/page-general.tsx
- libs/pages/layout/src/lib/feature/layout/layout.tsx
- libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx
- libs/shared/ui/src/lib/components/banner/banner.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-592)
- Add a placeholder to create a cluster
- Add a placeholder to create an environment
- Add a banner to indicate cluster installation is ongoing
---
> feat(page-environment): placeholder to create a cluster and environment

- libs/pages/application/src/lib/ui/container/container.tsx
- libs/pages/database/src/lib/ui/container/container.tsx
- libs/pages/services/src/lib/ui/container/container.tsx
- libs/shared/console-shared/src/lib/deploy-other-commit-modal/ui/deploy-other-commit-modal.tsx
- libs/shared/ui/src/lib/components/avatar/avatar.tsx
- libs/shared/ui/src/lib/components/scroll-shadow-wrapper/scroll-shadow-wrapper.tsx
- libs/shared/ui/src/lib/components/tag-commit/tag-commit.tsx
- libs/shared/ui/src/lib/components/tag/tag.tsx
- libs/shared/utils/src/lib/tools/status-actions-available.tsx
> fix: cluster name visible, missing stop action and git avatar

- libs/pages/login/src/lib/ui/login/login.tsx
> chore(login): change messaging on the login page

- libs/domains/environment/src/lib/slices/environment.actions.ts
- libs/shared/console-shared/src/index.ts
- libs/shared/console-shared/src/lib/environment-buttons-actions/ui/environment-buttons-actions.tsx
- libs/shared/console-shared/src/lib/update-all-modal/feature/update-all-modal-feature.spec.tsx
- libs/shared/console-shared/src/lib/update-all-modal/feature/update-all-modal-feature.tsx
- libs/shared/console-shared/src/lib/update-all-modal/ui/update-all-modal.spec.tsx
- libs/shared/console-shared/src/lib/update-all-modal/ui/update-all-modal.tsx
- libs/shared/ui/src/lib/components/scroll-shadow-wrapper/scroll-shadow-wrapper.tsx
- libs/shared/ui/src/lib/components/tag-commit/tag-commit.tsx
[> Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-634)
---
> feat(services): update all modal

- libs/domains/application/src/lib/slices/application.actions.ts
- libs/domains/database/src/lib/slices/database.actions.ts
- libs/shared/console-shared/src/lib/buttons-actions/ui/application-buttons-actions/application-buttons-actions.spec.tsx
- libs/shared/console-shared/src/lib/buttons-actions/ui/application-buttons-actions/application-buttons-actions.tsx
- libs/shared/console-shared/src/lib/buttons-actions/ui/cluster-buttons-actions/cluster-buttons-actions.tsx
- libs/shared/console-shared/src/lib/buttons-actions/ui/database-buttons-actions/database-buttons-actions.spec.tsx
- libs/shared/console-shared/src/lib/buttons-actions/ui/database-buttons-actions/database-buttons-actions.tsx
- libs/shared/console-shared/src/lib/environment-buttons-actions/ui/environment-buttons-actions.tsx
- libs/shared/utils/src/lib/tools/status-actions-available.tsx
- package.json
- yarn.lock
[> Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-614)
> We should add the “Restart” option in the deployment action menu for any service except managed db , lifecycle job , cronjob
> 
> The option should be available only if the service is deployed. 
---
> feat(services): restart button for deployed services

- libs/pages/application/src/lib/feature/crud-environment-variable-modal-feature/crud-environment-variable-modal-feature.tsx
- libs/pages/application/src/lib/ui/crud-environment-variable-modal/crud-environment-variable-modal.spec.tsx
- libs/pages/application/src/lib/ui/crud-environment-variable-modal/crud-environment-variable-modal.tsx
[> Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-650)
Revamping the modal to edit alias and override.
---
> feat(env-variable): better modal for alias and overrides FRT-650

- libs/pages/cluster/src/lib/feature/page-settings-features-feature/page-settings-features-feature.spec.tsx
- libs/pages/cluster/src/lib/feature/page-settings-features-feature/page-settings-features-feature.tsx
- libs/pages/cluster/src/lib/router/router.tsx
- libs/pages/cluster/src/lib/ui/page-settings-features/page-settings-features.spec.tsx
- libs/pages/cluster/src/lib/ui/page-settings-features/page-settings-features.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-499)
- Add settings section for Cluster
---
> feat(cluster-settings): features section

- libs/domains/application/src/lib/slices/applications.slice.ts
- libs/pages/logs/application/src/lib/page-application-logs.tsx
- libs/pages/logs/deployment/src/lib/page-deployment-logs.tsx
- libs/pages/services/src/lib/ui/container/container.tsx
- libs/shared/ui/src/lib/components/layouts/layout-logs/layout-logs.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-648)
- Fetch environment status for Deployments and Application logs
- Removed 3 requests for status (Jobs, Container, and Application) to use only one endpoint
---
> fix(deployment-logs): status

- libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-general-feature/step-general-feature.tsx
- libs/pages/clusters/src/lib/ui/page-clusters-create/step-general/step-general.spec.tsx
- libs/pages/clusters/src/lib/ui/page-clusters-create/step-general/step-general.tsx
- libs/shared/console-shared/src/lib/cluster-settings/feature/cluster-credentials-settings-feature/cluster-credentials-settings-feature.tsx
- Fixe to fetch credentials after changing cloud providers
- Clean code
---
> fix(cluster-credentials): behavior switch between providers

- libs/pages/settings/src/lib/ui/page-organization-roles-edit/row-project/row-project.tsx
- Fix bug when we select all environments for a custom role 
- History available [here](https://qovery.slack.com/archives/C038JMN9GUE/p1675243671064499) 
---
> fix(custom-role-edit): select all environments

- libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx
[> Link to the JIRA ticket](https://qovery.slack.com/archives/C02P2JB4SEM/p1675443332320449)
---
> fix(cluster): increase the max node limit

- libs/domains/application/src/lib/slices/applications.slice.ts
- libs/pages/services/src/lib/feature/table-row-services-feature/table-row-services-feature.tsx
- libs/pages/services/src/lib/ui/page-general/page-general.tsx
- Fix link for database overview
- Fix actions for container stays empty (status where missing)
---
> fix(container): empty actions for containers

- libs/domains/organization/src/lib/slices/cluster/cluster.slice.ts
- libs/pages/cluster/src/lib/feature/page-settings-feature/page-settings-feature.tsx
- libs/pages/clusters/src/lib/feature/page-clusters-create-feature/page-clusters-create-feature.tsx
- libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-features-feature/step-features-feature.spec.tsx
- libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-features-feature/step-features-feature.tsx
- libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-general-feature/step-general-feature.tsx
- libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-resources-feature/step-resources-feature.tsx
- libs/pages/clusters/src/lib/router/router.tsx
- libs/pages/clusters/src/lib/ui/page-clusters-create/step-features/step-features.spec.tsx
- libs/pages/clusters/src/lib/ui/page-clusters-create/step-features/step-features.tsx
- libs/pages/clusters/src/lib/ui/page-clusters-create/step-general/step-general.tsx
- libs/shared/console-shared/src/lib/cluster-settings/feature/cluster-resources-settings-feature/cluster-resources-settings-feature.tsx
- libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.spec.tsx
- libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx
- libs/shared/interfaces/src/lib/domain/cluster-creation-flow.interface.ts
- libs/shared/routes/src/lib/sub-router/clusters.router.ts
- libs/shared/ui/src/lib/components/inputs/input-radio-box/input-radio-box.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-580)
- Add a step to setup features for creating cluster flow
- Fix UI for resources step
- Fix bug on the general step (appear when we back from resources)
- Hide Features for Scaleway
---
> feat(create-cluster): features step

- libs/pages/application/src/lib/feature/page-general-feature/page-general-feature.tsx
- libs/pages/application/src/lib/ui/about/about-container/about-container.spec.tsx
- libs/pages/application/src/lib/ui/about/about-container/about-container.tsx
- libs/pages/application/src/lib/ui/about/about-git/about-git.spec.tsx
- libs/pages/application/src/lib/ui/about/about-git/about-git.tsx
- libs/pages/application/src/lib/ui/about/about-update/about-update.spec.tsx
- libs/pages/application/src/lib/ui/about/about-update/about-update.tsx
- libs/pages/application/src/lib/ui/about/about.tsx
- libs/pages/application/src/lib/ui/last-commit/last-commit.tsx
- libs/pages/application/src/lib/ui/page-general/page-general.tsx
- libs/shared/factories/src/index.ts
- libs/shared/factories/src/lib/container-factory.mock.ts
- libs/shared/ui/src/lib/components/tag-commit/tag-commit.tsx
[> Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-635)
---
> feat(services): about section revamped with container and git info

- libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-general-feature/step-general-feature.spec.tsx
- libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-general-feature/step-general-feature.tsx
- libs/shared/ui/src/lib/components/navigation-left/navigation-left-sub-link/navigation-left-sub-link.tsx
- Icon alignment for navigation-left component
---
> fix(navigation-left): alignment of icon

- libs/pages/cluster/src/lib/ui/page-settings-features/page-settings-features.tsx
- libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-features-feature/step-features-feature.spec.tsx
- libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-features-feature/step-features-feature.tsx
- libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-summary-feature/step-summary-feature.tsx
- libs/pages/clusters/src/lib/ui/page-clusters-create/step-features/step-features.tsx
- libs/pages/clusters/src/lib/ui/page-clusters-create/step-summary/step-summary.tsx
- libs/shared/console-shared/src/index.ts
- libs/shared/console-shared/src/lib/cluster-settings/ui/card-cluster-feature/card-cluster-feature.spec.tsx
- libs/shared/console-shared/src/lib/cluster-settings/ui/card-cluster-feature/card-cluster-feature.tsx
- libs/shared/interfaces/src/lib/domain/cluster-creation-flow.interface.ts
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-580)
- Updated summary with a real name for instance_type
- Updated features to disabled input select
- Fixed features settings with select
---
> fix(cluster-create): features and resources

- libs/shared/ui/src/lib/components/link/link.spec.tsx
- libs/shared/ui/src/lib/components/link/link.tsx
- Fix routing for link component
---
> fix(link): add real navigation with react-router

- libs/pages/application/src/lib/ui/page-settings-general/page-settings-general.tsx
- libs/pages/cluster/src/lib/ui/page-settings-general/page-settings-general.tsx
- libs/pages/clusters/src/lib/ui/page-clusters-create/step-general/step-general.tsx
- libs/pages/clusters/src/lib/ui/page-clusters-create/step-summary/step-summary.tsx
- libs/pages/database/src/lib/ui/page-settings-general/page-settings-general.tsx
- libs/pages/services/src/lib/ui/page-application-create/step-general/step-general.tsx
- libs/pages/services/src/lib/ui/page-application-create/step-summary/step-summary.tsx
- libs/pages/services/src/lib/ui/page-database-create/step-general/step-general.tsx
- libs/pages/services/src/lib/ui/page-database-create/step-summary/step-summary.tsx
- libs/pages/services/src/lib/ui/page-job-create/step-general/step-general.tsx
- libs/pages/services/src/lib/ui/page-job-create/step-summary/step-summary.tsx
- libs/pages/services/src/lib/ui/page-settings-general/page-settings-general.tsx
- libs/pages/settings/src/lib/ui/page-organization-roles-edit/page-organization-roles-edit.tsx
fixing "information" typos around the repo
---
> fix(wording): fixed wording for information

- libs/pages/services/src/lib/feature/page-settings-preview-environments-feature/page-settings-preview-environments-feature.tsx
- libs/pages/services/src/lib/ui/page-settings-preview-environments/page-settings-preview-environments.spec.tsx
- libs/pages/services/src/lib/ui/page-settings-preview-environments/page-settings-preview-environments.tsx
- libs/shared/ui/src/lib/components/inputs/input-toggle/input-toggle.tsx
[Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-656)
- Remove the animation on the initialisation of the toggle input
- Fix the bugs described in FRT-656 about preview environment page toggles
---
> feat(toggle): toggle input initialisation without animation

- libs/domains/user/src/lib/slices/user.slice.ts
Fix the build of the project after independabot bump
---
> fix(build): project build broken after bump of redux-toolkit

- libs/pages/services/src/lib/feature/page-settings-deployment-pipeline-feature/page-settings-deployment-pipeline-feature.tsx
- libs/pages/services/src/lib/ui/page-settings-deployment-pipeline/draggable-item/draggable-item.spec.tsx
- libs/pages/services/src/lib/ui/page-settings-deployment-pipeline/draggable-item/draggable-item.tsx
- libs/pages/services/src/lib/ui/page-settings-deployment-pipeline/page-settings-deployment-pipeline.spec.tsx
- libs/pages/services/src/lib/ui/page-settings-deployment-pipeline/page-settings-deployment-pipeline.tsx
- libs/shared/enums/src/lib/utils/get-service-type.ts
- libs/shared/ui/src/index.ts
- libs/shared/ui/src/lib/components/badge-service/badge-service.spec.tsx
- libs/shared/ui/src/lib/components/badge-service/badge-service.stories.tsx
- libs/shared/ui/src/lib/components/badge-service/badge-service.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-655)
- Add component BadgeService
- Add item design for the deployment stage
---
> feat(deployment-stage-item): add integration

- libs/pages/logs/application/src/lib/page-application-logs.tsx
- libs/pages/logs/application/src/lib/ui/row/row.tsx
- libs/shared/ui/src/lib/components/inputs/input-checkbox/input-checkbox.tsx
- libs/shared/ui/src/lib/components/layouts/layout-logs/layout-logs.spec.tsx
- libs/shared/ui/src/lib/components/layouts/layout-logs/layout-logs.tsx
- libs/shared/ui/src/lib/styles/components/input.scss
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-663)
- Add debug checkbox to display Nginx logs
---
> feat(layout-logs): add debug view

- apps/console/src/app/app.tsx
- Removed useless key that provide unnecessary re-fetch of all queries from Layout.tsx
---
> fix(dark-mode-enabler): remove re-render layout with key

- libs/shared/ui/src/lib/components/layouts/layout-logs/layout-logs.tsx
> fix(layout-log): wording nginx log

- libs/domains/organization/src/lib/slices/billing/billing-info.ts
- libs/pages/settings/src/lib/feature/page-organization-billing-summary-feature/invoices-list-feature/invoices-list-feature.spec.tsx
- libs/pages/settings/src/lib/feature/page-organization-billing-summary-feature/invoices-list-feature/invoices-list-feature.tsx
- libs/pages/settings/src/lib/ui/page-organization-billing-summary/invoices-list/invoices-list.spec.tsx
- libs/pages/settings/src/lib/ui/page-organization-billing-summary/invoices-list/invoices-list.tsx
- libs/pages/settings/src/lib/ui/page-organization-billing-summary/invoices-list/table-row-invoice/table-row-invoice.spec.tsx
- libs/pages/settings/src/lib/ui/page-organization-billing-summary/invoices-list/table-row-invoice/table-row-invoice.tsx
- libs/pages/settings/src/lib/ui/page-organization-billing-summary/page-organization-billing-summary.tsx
- libs/pages/settings/src/lib/ui/page-organization-billing/page-organization-billing.tsx
- libs/shared/interfaces/src/lib/domain/organization.entity.ts
- libs/shared/ui/src/lib/components/buttons/button-icon/button-icon.tsx
- libs/shared/ui/src/lib/components/icon/icon-awesome.enum.tsx
- libs/shared/ui/src/lib/components/inputs/input-select-small/input-select-small.tsx
- libs/shared/ui/src/lib/components/tag/tag.tsx
- libs/shared/ui/src/lib/styles/base/icons.scss
- Invoices list
- Filtering by year
- Download one
- Download many
- tests
https://user-images.githubusercontent.com/6163954/224091449-ba7fab82-1057-42aa-b76b-87277d0f8d3e.mp4
---
> feat(billing): invoice list

- libs/pages/logs/application/src/lib/page-application-logs.tsx
- Change the URL for NGINX logs
---
> fix(nginx-logs): new url

- libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx
- libs/pages/logs/application/src/lib/page-application-logs.tsx
- libs/shared/ui/src/lib/components/layouts/layout-logs/layout-logs.tsx
- Added number of NGINX logs
- Fixed bug with cluster banner
---
> fix(nginx-log): add number of logs

- libs/pages/clusters/src/lib/ui/page-clusters-create/step-summary/step-summary.tsx
- libs/pages/logs/application/src/lib/page-application-logs.spec.tsx
- libs/pages/logs/application/src/lib/page-application-logs.tsx
- libs/pages/logs/application/src/lib/ui/row/row.tsx
- libs/pages/settings/src/lib/page-settings.tsx
- libs/pages/settings/src/lib/ui/container/container.tsx
- libs/shared/ui/src/lib/components/banner-box/banner-box.tsx
- Remove useless account settings
- Fix NGINX log websocket connexion
- Add message for Kubernetes update
---
> fix(create-cluster): warning message for Kubernetes update

- libs/pages/services/src/lib/feature/page-general-feature/page-general-feature.tsx
- libs/pages/services/src/lib/ui/page-general/page-general.tsx
- libs/pages/services/src/lib/ui/table-row-services/table-row-services.tsx
Fixing a bug found by Mevlin about list in table that sometimes wait for status update to update the orderering.
---
> feat(table): idempotent list glitch fixed

- libs/pages/onboarding/src/lib/feature/onboarding-pricing/onboarding-pricing.tsx
I changed the Team plan pricing (49 > 99 / month) and plans subtitles.
---
> chore: change team plan price and plan subtitles

- libs/pages/layout/src/lib/ui/menu-account/menu-account.tsx
Remove useless user settings link
---
> fix(menu-account): remove settings user

- libs/domains/environment/src/lib/slices/environments.slice.ts
- libs/pages/environments/src/lib/ui/table-row-environments/table-row-environments.tsx
- libs/pages/services/src/lib/ui/page-settings-deployment-pipeline/draggable-item/draggable-item.tsx
- Enabled request when isn't mock, it removed error on the console
---
> fix(running-status-store): enabled request when is not mock

- libs/domains/application/src/lib/slices/applications.slice.ts
- libs/shared/console-shared/src/lib/cluster-settings/feature/cluster-resources-settings-feature/utils/list-instance-type-formatter.spec.ts
- libs/shared/console-shared/src/lib/cluster-settings/feature/cluster-resources-settings-feature/utils/list-instance-type-formatter.ts
- libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.spec.tsx
- libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx
- libs/shared/factories/src/lib/database-deployments-factory.mock.ts
- libs/shared/factories/src/lib/environment-factory.mock.ts
- libs/shared/ui/src/lib/components/banner-box/banner-box.tsx
- package.json
- yarn.lock
[> Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-675)
---
> feat(cluster): instance architecture in name

- libs/pages/cluster/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.spec.tsx
- libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-resources-feature/step-resources-feature.spec.tsx
- libs/pages/clusters/src/lib/ui/page-clusters-create/step-summary/step-summary.tsx
- Fix test for architecture field
---
> test(cluster-flow): architecture test

- libs/shared/ui/src/lib/components/status-chip/status-chip.tsx
> fix(status-chip): add canceling status

- libs/pages/settings/src/lib/feature/page-organization-general-feature/page-organization-general-feature.tsx
- Fixed request to update website for organization settings
---
> fix(organization-settings): website request

- libs/domains/application/src/lib/slices/application.actions.ts
- libs/domains/application/src/lib/slices/applications.slice.ts
- libs/domains/database/src/lib/slices/database.actions.ts
- libs/domains/database/src/lib/slices/databases.slice.ts
- libs/domains/environment/src/lib/slices/environment.actions.ts
- libs/domains/environment/src/lib/slices/environments.slice.ts
- libs/pages/application/src/lib/feature/page-variables-feature/page-variables-feature.tsx
- libs/pages/application/src/lib/ui/crud-environment-variable-modal/crud-environment-variable-modal.tsx
- libs/pages/application/src/lib/ui/import-environment-variable-modal/import-environment-variable-modal.tsx
- libs/pages/environments/src/lib/ui/page-general/page-general.tsx
- libs/pages/services/src/lib/feature/page-settings-danger-zone-feature/page-settings-danger-zone-feature.tsx
- libs/pages/services/src/lib/ui/page-general/page-general.tsx
- libs/shared/console-shared/src/lib/buttons-actions/ui/application-buttons-actions/application-buttons-actions.tsx
- libs/shared/console-shared/src/lib/buttons-actions/ui/database-buttons-actions/database-buttons-actions.tsx
- libs/shared/console-shared/src/lib/environment-buttons-actions/ui/environment-buttons-actions.tsx
- libs/shared/console-shared/src/lib/flow-create-variable/ui/variable-row/variable-row.tsx
- libs/shared/utils/src/lib/tools/compute-available-environment-variable-scope.tsx
This PR deals with deletions in service list and environment list. If the status is READY, then we delete the item and remove it from the list. If it's any other status, we don't remove it from the list.
We do that because a READY item will never update its status after deletion. If the status is anything else than READY, then when we delete, we see the status going through the different step of deletion until showing the status `DELETED`
- https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-617
- https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-685 
- https://qovery.slack.com/archives/C02P2JB4SEM/p1680594287437329 : Removing the wrong count indication on table loading
- https://qovery.atlassian.net/browse/FRT-683 : …
> feat(services): improve deletion in list

- libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
- libs/pages/application/src/lib/ui/page-settings-general/page-settings-general.tsx
- libs/pages/services/src/lib/feature/page-application-create-feature/step-general-feature/step-general-feature.tsx
- libs/pages/services/src/lib/feature/page-application-create-feature/step-summary-feature/step-summary-feature.spec.tsx
- libs/pages/services/src/lib/feature/page-application-create-feature/step-summary-feature/step-summary-feature.tsx
- libs/pages/services/src/lib/ui/page-application-create/step-general/step-general.tsx
- libs/pages/services/src/lib/ui/page-application-create/step-summary/step-summary.tsx
- libs/shared/utils/src/lib/tools/refacto-payload.ts
[> Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-616)
---
> feat(application): adding argument and entrypoint to git applications creation and edit flow

- libs/pages/application/src/lib/ui/page-settings-general/page-settings-general.tsx
- libs/pages/services/src/lib/ui/page-application-create/step-general/step-general.tsx
Fix many feedbacks from Romaric in the #product channel.
---
> fix(application): arguments and entrypoints adjustments

- libs/pages/settings/src/lib/ui/page-organization-billing-summary/invoices-list/invoices-list.tsx
- libs/pages/settings/src/lib/ui/page-organization-billing-summary/invoices-list/table-row-invoice/table-row-invoice.spec.tsx
- libs/pages/settings/src/lib/ui/page-organization-billing-summary/invoices-list/table-row-invoice/table-row-invoice.tsx
[> Link to the JIRA ticket](https://qovery.slack.com/archives/C02NPSG2HBL/p1681308514679099)
Removing PLAN column since it's not provided by the api.
---
> fix(invoice): remove plan column

- libs/pages/logs/environment/src/lib/ui/row-deployment/row-deployment.tsx
- libs/pages/logs/environment/src/lib/ui/row-pod/row-pod.tsx
- libs/pages/logs/infra/src/lib/ui/row/row.tsx
[> Link to the JIRA ticket](https://qovery.slack.com/archives/C02P2JB4SEM/p1681805283129109)
- Request from Romaric and Romain
https://user-images.githubusercontent.com/6163954/232787953-ec97c091-9e01-4745-a6c4-3c9feca8a5fd.mp4
---
> feat(log): select multiline only messages

- libs/pages/application/src/lib/feature/page-settings-domains-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-domains-feature/page-settings-domains-feature.tsx
- libs/pages/application/src/lib/ui/container/container.tsx
- libs/shared/ui/src/lib/components/status-chip/status-chip.tsx
[> Link to the JIRA ticket](https://qovery.slack.com/archives/C02P2JB4SEM/p1681826256651019)
---
> fix(status): removed a glitch where we could see a spinner and an icon

- libs/shared/ui/src/lib/components/inputs/input-text/input-text.stories.tsx
- libs/shared/ui/src/lib/styles/components/input.scss
[> Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-692)
---
> fix(input): fixing ui glitch on time input FRT-692

- libs/pages/logs/environment/src/lib/ui/row-pod/row-pod.tsx
- libs/shared/console-shared/src/lib/buttons-actions/ui/database-buttons-actions/database-buttons-actions.tsx
- [NB board - Agile board - Qovery Jira](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-699)
- [NB board - Agile board - Qovery Jira](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-695)
---
> feat(logs): UTC and button on contained databases.

- .github/workflows/test-build-and-deploy.yml
- libs/pages/clusters/src/lib/ui/page-clusters-create/step-remote/step-remote.tsx
- libs/pages/clusters/src/lib/ui/page-clusters-create/step-summary/step-summary.tsx
- libs/pages/database/src/lib/ui/page-settings-resources/page-settings-resources.tsx
- libs/pages/services/src/lib/ui/page-database-create/step-summary/step-summary.tsx
- libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.spec.tsx
- libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx
- updated text on cluster flow and as well fixed links
- added warning bannerBox on managed db creation flow +  in resources section for both managed db and clusters
---
> chore(doc): updating links text

- libs/pages/database/src/lib/ui/page-settings-resources/page-settings-resources.tsx
- libs/shared/console-shared/src/lib/setting-resources/ui/setting-resources.tsx
Fix minimum memory limit as it's wrong
> fix: update wrong min memory usage

- libs/pages/settings/src/lib/feature/page-organization-members-feature/page-organization-members-feature.tsx
- libs/pages/settings/src/lib/ui/page-organization-members/page-organization-members.tsx
- libs/pages/settings/src/lib/ui/page-organization-members/row-member/row-member.tsx
[> Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-701)
---
> feat(member): transfer ownership with confirmation

- libs/pages/logs/environment/src/lib/ui/deployment-logs/deployment-logs.tsx
Just update the text for the placeholder
---
> fix: update wording on placeholder when no deployment logs are available

- libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
https://qovery.slack.com/archives/C038JMN9GUE/p1682597243644849?thread_ts=1682596845.474399&cid=C038JMN9GUE
Editing a container was ignoring changes on registry_id
---
> fix(container): container registry id was ignored

- libs/pages/settings/src/lib/feature/page-organization-roles-edit-feature/page-organization-roles-edit-feature.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-707)
- Fix submit new description and name for custom roles
---
> fix(roles-edit-feature): submit new name and description

- libs/pages/logs/environment/src/lib/ui/sidebar-pipeline-item/sidebar-pipeline-item.tsx
- libs/pages/services/src/lib/ui/page-settings-deployment-pipeline/page-settings-deployment-pipeline.tsx
- libs/pages/services/src/lib/ui/page-settings-deployment-pipeline/stage-order-modal/stage-order-modal.tsx
- libs/shared/ui/src/lib/components/badge-deployment-order/badge-deployment-order.spec.tsx
- libs/shared/ui/src/lib/components/badge-deployment-order/badge-deployment-order.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-704)
- Remove random colors for badge deployment order
---
> fix(badge-deployment-order): remove color by id

- libs/pages/application/src/lib/ui/page-settings-domains/crud-modal/crud-modal.tsx
- libs/shared/ui/src/lib/components/banner-box/banner-box.spec.tsx
- libs/shared/ui/src/lib/components/banner-box/banner-box.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-688)
- Add banner message for create/edit domain modal
---
> feat(modal-domain): add banner info

- libs/domains/organization/src/lib/slices/organization/organization.slice.ts
- libs/pages/settings/src/lib/feature/page-organization-roles-feature/page-organization-roles-feature.tsx
- libs/shared/ui/src/lib/components/modals/modal-confirmation/modal-confirmation.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-708)
- Need to refetch the list because we don't have response on the requests to remove it on the store
---
> fix(delete-roles): remove on the roles list

- libs/domains/application/src/lib/slices/application.actions.ts
- libs/domains/database/src/lib/slices/database.actions.ts
- libs/domains/environment/src/lib/slices/environment.actions.ts
- libs/pages/application/src/lib/feature/crud-environment-variable-modal-feature/crud-environment-variable-modal-feature.tsx
- libs/pages/application/src/lib/feature/crud-environment-variable-modal-feature/handle-submit/handle-submit.tsx
- libs/pages/application/src/lib/feature/page-settings-advanced-feature/page-settings-advanced-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-configure-job-feature/page-settings-configure-job-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-domains-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-ports-feature/page-settings-ports-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-storage-feature/page-settings-storage-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-storage-feature/storage-modal-feature/storage-modal-feature.tsx
- libs/pages/application/src/lib/ui/container/container.tsx
- libs/pages/database/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
- libs/pages/database/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx
- libs/pages/database/src/lib/ui/container/container.tsx
- libs/shared/console-shared/src/lib/buttons-actions/ui/application-buttons-actions/application-buttons-actions.tsx
- libs/shared/console-shared/src/lib/buttons-actions/ui/database-buttons-actions/database-buttons-actions.tsx
- libs/shared/console-shared/src/lib/environment-buttons-actions/ui/environment-buttons-actions.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-712)
- Replace restart to redeploy actions for DB, Apps, Jobs, Container and Env
---
> chore(restart-actions): replace with redeploy actions

- libs/pages/onboarding/src/lib/feature/onboarding-project/onboarding-project.tsx
- libs/pages/onboarding/src/lib/ui/step-project/step-project.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-709)
- Add back button if we have already created organizations
---
> fix(onboarding-project): add back button if organizations available

- libs/pages/settings/src/lib/feature/page-organization-billing-feature/billing-details-feature/billing-details-feature.tsx
- libs/shared/ui/src/lib/components/status-chip/status-chip.tsx
- libs/shared/ui/src/lib/components/status-label/status-label.tsx
- libs/shared/utils/src/lib/tools/status-actions-available.tsx
- package.json
- yarn.lock
Bump qovery axios typescript librairy to last version.
BillingInfo and BillingInfoRequest are the same object.
> chore(package): bump qovery axios typescript

- libs/pages/application/src/lib/feature/page-settings-domains-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-domains-feature/page-settings-domains-feature.tsx
- libs/pages/application/src/lib/ui/page-settings-domains/crud-modal/crud-modal.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-688)
---
> feat(new-domain-modal): add default type and value

- libs/domains/database/src/lib/slices/databases.slice.ts
- libs/pages/database/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
- libs/pages/database/src/lib/page-database.tsx
- libs/pages/database/src/lib/ui/page-settings-general/page-settings-general.tsx
- libs/pages/services/src/lib/feature/page-database-create-feature/step-general-feature/step-general-feature.tsx
- libs/pages/services/src/lib/ui/page-database-create/step-general/step-general.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-457)
- Hide public accessibility when the database is container on EC2 cluster
---
> feat(database): hide public accessibility for ec2 container

- libs/pages/application/src/lib/feature/tabs-feature/tabs-feature.tsx
- libs/pages/application/src/lib/ui/import-environment-variable-modal/import-environment-variable-modal.tsx
Renaming "Import variables" into "Import from .env file"
---
> chore: rename import variables into import from .env file

- apps/console/src/app/router/main.router.tsx
- libs/pages/application/src/lib/feature/tabs-feature/tabs-feature.tsx
- libs/pages/events/src/lib/feature/page-general-feature/page-general-feature.tsx
- libs/pages/events/src/lib/page-events.tsx
- libs/pages/events/src/lib/router/router.tsx
- libs/pages/events/src/lib/ui/page-general/page-general.tsx
- libs/pages/layout/src/lib/ui/navigation/navigation.tsx
- libs/shared/routes/src/lib/router.ts
- libs/shared/routes/src/lib/sub-router/audit-logs.router.ts
- libs/shared/routes/src/lib/sub-router/events.router.ts
- Rename Events to Audit Logs
---
> chore(audit-logs): update wording

- libs/shared/ui/src/lib/styles/components/input.scss
> fix(input-time): remove indicator

- libs/pages/logs/environment/src/lib/ui/sidebar-status/sidebar-status.tsx
since they are not dynamic and we have already them in the logs
---
> fix(logs): removed build resources info

- libs/pages/environments/src/lib/ui/page-create-edit-deployment-rule/page-create-edit-deployment-rule.tsx
- libs/pages/services/src/lib/ui/page-general/page-general.tsx
- libs/pages/services/src/lib/ui/page-settings-deployment-pipeline/page-settings-deployment-pipeline.tsx
- libs/pages/services/src/lib/ui/page-settings-deployment-rules/page-settings-deployment-rules.tsx
- libs/pages/services/src/lib/ui/page-settings-general/page-settings-general.tsx
- libs/pages/services/src/lib/ui/page-settings-preview-environments/page-settings-preview-environments.tsx
- libs/pages/settings/src/lib/feature/page-organization-billing-feature/page-organization-billing-feature.tsx
- libs/pages/settings/src/lib/ui/page-organization-billing-summary/page-organization-billing-summary.tsx
- libs/pages/settings/src/lib/ui/page-organization-container-registries/page-organization-container-registries.tsx
- libs/pages/settings/src/lib/ui/page-organization-members/page-organization-members.tsx
- libs/pages/settings/src/lib/ui/page-organization-roles-edit/page-organization-roles-edit.tsx
- libs/shared/console-shared/src/lib/create-clone-environment-modal/ui/create-clone-environment-modal.tsx
- libs/shared/ui/src/lib/components/block-content-delete/block-content-delete.tsx
- libs/shared/ui/src/lib/components/modals/modal-confirmation/use-modal-confirmation/use-modal-confirmation.tsx
- reviewed the wording in a few sections
- added the configuration of the placeholder for the confirmation modal and updated it for credit cards
- removed manage members link from the billing page since it was more confusing than anything
---
> chore(general): update wording

- libs/shared/console-shared/src/lib/application-settings/ui/application-settings-healthchecks/application-settings-healthchecks.tsx
- fixed tooltip wordings
- added missing tooltips for exec and service fields
---
> fix(liveness-readiness): fixed wording and added missing tooltips

- libs/pages/events/src/lib/feature/page-general-feature/page-general-feature.tsx
- libs/pages/events/src/lib/ui/page-general/page-general.spec.tsx
- libs/pages/events/src/lib/ui/page-general/page-general.tsx
- libs/pages/events/src/lib/ui/row-event/row-event.tsx
- libs/shared/ui/src/lib/components/buttons/button/button.tsx
- libs/shared/ui/src/lib/components/table/table-head-filter/table-head-filter.spec.tsx
- libs/shared/ui/src/lib/components/table/table-head-filter/table-head-filter.tsx
- libs/shared/ui/src/lib/components/table/table.tsx
- libs/shared/ui/src/lib/styles/components/button.scss
- Update Table component to add custom field
- Add filter for Tools
---
> feat(audit-logs): add filter for tools

- libs/pages/login/src/lib/hooks/use-redirect-if-logged/use-redirect-if-logged.tsx
- libs/shared/auth/src/lib/use-auth/use-auth.tsx
> chore(use-auth): user GTM

- libs/pages/login/src/lib/hooks/use-redirect-if-logged/use-redirect-if-logged.spec.tsx
- libs/pages/login/src/lib/hooks/use-redirect-if-logged/use-redirect-if-logged.tsx
- libs/shared/auth/src/lib/use-auth/use-auth.tsx
> test(use-redirect-if-logged): GTM

- libs/pages/services/src/lib/ui/page-application-create/step-summary/step-summary.tsx
- libs/shared/console-shared/src/lib/application-settings/ui/application-settings-healthchecks/application-settings-healthchecks.tsx
- Replace liveness before readiness
---
> chore(healthchecks): replace liveness before readiness

- libs/pages/logs/environment/src/lib/ui/sidebar-status/sidebar-status.tsx
- libs/shared/ui/src/lib/components/table/table-head-filter/table-head-filter.tsx
- Add dark mode for Buttons
---
> fix(table-filter): dark mode for buttons

- libs/domains/application/src/lib/slices/applications.slice.ts
- libs/pages/application/src/lib/ui/page-settings-ports/crud-modal/crud-modal.tsx
- libs/pages/services/src/lib/feature/page-general-feature/page-general-feature.tsx
- Fix error with the service list when application's updated
---
> fix(edit-application): don't set error state status on the store

- libs/pages/events/src/lib/feature/page-general-feature/page-general-feature.tsx
- libs/pages/events/src/lib/ui/custom-filter/custom-filter.spec.tsx
- libs/pages/events/src/lib/ui/custom-filter/custom-filter.tsx
- libs/pages/events/src/lib/ui/page-general/page-general.spec.tsx
- libs/pages/events/src/lib/ui/page-general/page-general.tsx
- libs/shared/ui/src/index.ts
- libs/shared/ui/src/lib/components/inputs/input-filter/input-filter.spec.tsx
- libs/shared/ui/src/lib/components/inputs/input-filter/input-filter.stories.tsx
- libs/shared/ui/src/lib/components/inputs/input-filter/input-filter.tsx
- libs/shared/ui/src/lib/components/inputs/input-select/input-select.spec.tsx
- libs/shared/ui/src/lib/components/inputs/input-select/input-select.tsx
- libs/shared/ui/src/lib/styles/components/input.scss
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-713)
- Filter by type
- Clear all filter
---
> feat(audit-logs): add filter by type and clear filter btn

- libs/pages/application/src/lib/feature/import-environment-variable-modal-feature/utils/file-to-form.spec.tsx
- libs/pages/application/src/lib/feature/import-environment-variable-modal-feature/utils/file-to-form.tsx
- libs/pages/application/src/lib/ui/import-environment-variable-modal/import-environment-variable-modal.spec.tsx
- libs/pages/application/src/lib/ui/import-environment-variable-modal/import-environment-variable-modal.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-729)
- Add Environment for default scope value
---
> fix(import-env-var): add environment default value

- libs/domains/application/src/lib/slices/applications.slice.ts
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-732)
- Remove Qovery links by default
---
> fix(link): remove qovery links by default

- libs/pages/application/src/lib/ui/page-settings-general/page-settings-general.tsx
- libs/pages/services/src/lib/ui/page-application-create/step-general/step-general.tsx
- libs/shared/console-shared/src/lib/entrypoint-cmd-inputs/ui/entrypoint-cmd-inputs.spec.tsx
- libs/shared/console-shared/src/lib/entrypoint-cmd-inputs/ui/entrypoint-cmd-inputs.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-722)
---
> feat(container-settings): add docker cmd example

- libs/pages/application/src/lib/ui/crud-environment-variable-modal/crud-environment-variable-modal.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-694)
- Add disable scope for edit mode
---
> fix(environment-variable-modal): disable scope field when editing

- libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/services/src/lib/feature/page-application-create-feature/step-port-feature/crud-modal-feature/crud-modal-feature.spec.tsx
- libs/pages/services/src/lib/feature/page-application-create-feature/step-port-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/services/src/lib/feature/page-application-create-feature/step-summary-feature/step-summary-feature.spec.tsx
- libs/pages/services/src/lib/feature/page-application-create-feature/step-summary-feature/step-summary-feature.tsx
- libs/pages/services/src/lib/ui/page-application-create/step-summary/step-summary.tsx
- libs/shared/console-shared/src/lib/flow-create-port/ui/crud-modal/crud-modal.spec.tsx
- libs/shared/console-shared/src/lib/flow-create-port/ui/crud-modal/crud-modal.tsx
- libs/shared/console-shared/src/lib/flow-create-port/ui/flow-create-port/flow-create-port.tsx
- libs/shared/interfaces/src/lib/common/flow-port-data.interface.ts
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-717)
- Add input select protocol 
---
> feat(port): add protocol field

- libs/domains/environment/src/lib/slices/environments.slice.ts
- libs/pages/database/src/lib/feature/page-settings-general-feature/page-settings-general-feature.spec.tsx
- libs/pages/database/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
- libs/pages/database/src/lib/ui/page-settings-general/page-settings-general.tsx
- libs/shared/utils/src/lib/tools/refacto-payload.ts
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-715)
---
> feat(edit-db): update version for db managed and containered

- libs/pages/application/src/lib/ui/page-settings-general/page-settings-general.spec.tsx
- libs/pages/application/src/lib/ui/page-settings-general/page-settings-general.tsx
- Fix container settings sectons
---
> fix(container-settings): entrypoint and arguments

- libs/pages/environments/src/lib/feature/page-create-deployment-rule-feature/page-create-deployment-rule-feature.tsx
- libs/pages/environments/src/lib/feature/page-edit-deployment-rule-feature/page-edit-deployment-rule-feature.tsx
- libs/pages/environments/src/lib/ui/page-create-edit-deployment-rule/page-create-edit-deployment-rule.spec.tsx
- libs/pages/environments/src/lib/ui/page-create-edit-deployment-rule/page-create-edit-deployment-rule.tsx
- libs/pages/services/src/lib/feature/page-settings-deployment-rules-feature/page-settings-deployment-rules-feature.spec.tsx
- libs/pages/services/src/lib/feature/page-settings-deployment-rules-feature/page-settings-deployment-rules-feature.tsx
- libs/pages/services/src/lib/feature/page-settings-preview-environments-feature/page-settings-preview-environments-feature.tsx
- libs/pages/services/src/lib/ui/page-settings-preview-environments/page-settings-preview-environments.spec.tsx
- libs/pages/services/src/lib/ui/page-settings-preview-environments/page-settings-preview-environments.tsx
- libs/shared/factories/src/lib/deployment-rules-factory.mock.ts
- libs/shared/factories/src/lib/environment-factory.mock.ts
remove the auto-delete feature from:
- the project deployment rules
- the environment deployment rules
https://qovery.atlassian.net/browse/COR-682
---
> chore(auto-delete): remove auto-delete feature

- apps/console/src/app/app.spec.tsx
- package.json
- Update `yarn test` command with the real test cmd
---
> chore(package.json): update yarn test command

- libs/domains/environment-variable/src/lib/slices/environment-variables.slice.ts
- libs/domains/environment-variable/src/lib/slices/secret-environment-variables.slice.ts
- libs/domains/event/src/lib/event.queries.ts
- libs/pages/events/src/lib/feature/custom-filter-feature/custom-filter-feature.spec.tsx
- libs/pages/events/src/lib/feature/custom-filter-feature/custom-filter-feature.tsx
- libs/pages/events/src/lib/feature/page-general-feature/page-general-feature.tsx
- libs/pages/events/src/lib/ui/custom-filter/custom-filter.spec.tsx
- libs/pages/events/src/lib/ui/custom-filter/custom-filter.tsx
- libs/pages/events/src/lib/ui/page-general/page-general.spec.tsx
- libs/pages/events/src/lib/ui/page-general/page-general.tsx
- libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx
- libs/shared/ui/src/lib/components/inputs/input-filter/__snapshots__/input-filter.spec.tsx.snap
- libs/shared/ui/src/lib/components/inputs/input-filter/input-filter.spec.tsx
- libs/shared/ui/src/lib/components/inputs/input-filter/input-filter.tsx
- package.json
- yarn.lock
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-713)
- Add filter with context
- Update API doc package
- Refactoring custom filter with outside feature component
- Rename Tools column to Source
---
> feat(audit-logs): add filter with context

- libs/pages/application/src/lib/feature/page-settings-healthchecks-feature/page-settings-healthchecks-feature.tsx
- libs/pages/application/src/lib/ui/page-settings-healthchecks/page-settings-healthchecks.spec.tsx
- libs/pages/application/src/lib/ui/page-settings-healthchecks/page-settings-healthchecks.tsx
- libs/shared/console-shared/src/lib/application-settings/ui/application-settings-resources/application-settings-resources.tsx
https://qovery.atlassian.net/browse/FRT-735
---
> feat(warn-instance-number): add warning on instance number

- .vscode/extensions.json
- .vscode/settings.json
Add VSCode recommended extensions and settings
> chore: add vscode settings & extensions

- .github/workflows/test-build-and-deploy.yml
- Disable Codecov fail ci if error because flacky codecov feedback can block the CI
---
> chore(ci): disabled fail ci error with codecov

- package.json
Add helpful NPM scripts related to NX
> chore: add more npm scripts

- libs/shared/factories/src/lib/application-deployment-factory.mock.ts
- libs/shared/factories/src/lib/application-factory.mock.ts
- libs/shared/factories/src/lib/auth-provider.mock.ts
- libs/shared/factories/src/lib/cluster-factory.mock.ts
- libs/shared/factories/src/lib/cluster-log-factory.mock.ts
- libs/shared/factories/src/lib/container-factory.mock.ts
- libs/shared/factories/src/lib/database-deployments-factory.mock.ts
- libs/shared/factories/src/lib/database-factory.mock.ts
- libs/shared/factories/src/lib/database-master-credentials-factory.mock.ts
- libs/shared/factories/src/lib/database-status.mock.ts
- libs/shared/factories/src/lib/deployment-log-factory.mock.ts
- libs/shared/factories/src/lib/deployment-rules-factory.mock.ts
- libs/shared/factories/src/lib/deployment-stages-factory.mock.ts
- libs/shared/factories/src/lib/environment-factory.mock.ts
- libs/shared/factories/src/lib/environment-variable-factory.mock.ts
- libs/shared/factories/src/lib/events.mock.ts
- libs/shared/factories/src/lib/job-factory.mock.ts
- libs/shared/factories/src/lib/organizations-factory.mock.ts
- libs/shared/factories/src/lib/projects-factory.mock.ts
- libs/shared/factories/src/lib/user-signup-factory.mock.ts
- libs/shared/factories/src/lib/webhook-factory.mock.ts
- libs/shared/ui/src/lib/components/buttons/button-icon/button-icon.spec.tsx
- libs/shared/ui/src/lib/components/buttons/button/button.spec.tsx
We must initialize Chance with a seed to prevent different result in test
https://chancejs.com/usage/seed.html
> fix(random): use static seed to avoid randomness

- libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-features-feature/step-features-feature.spec.tsx
- libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-resources-feature/step-resources-feature.spec.tsx
- libs/pages/database/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.spec.tsx
- libs/pages/login/src/lib/hooks/use-redirect-if-logged/use-redirect-if-logged.spec.tsx
- libs/pages/services/src/lib/feature/page-database-create-feature/step-resources-feature/step-resources-feature.spec.tsx
- libs/pages/settings/src/lib/feature/page-organization-container-registries-feature/crud-modal-feature/crud-modal-feature.spec.tsx
- libs/pages/settings/src/lib/feature/page-organization-webhooks-feature/webhook-crud-modal-feature/webhook-crud-modal-feature.spec.tsx
- libs/shared/auth/src/lib/use-auth/use-auth.spec.ts
- libs/shared/auth/src/lib/use-invite-member/use-invite-member.spec.tsx
- libs/shared/console-shared/src/lib/cluster-settings/feature/cluster-credentials-settings-feature/cluster-credentials-settings-feature.spec.tsx
- libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-credentials-settings/cluster-credentials-settings.spec.tsx
- libs/shared/console-shared/src/lib/create-clone-environment-modal/feature/create-clone-environment-modal-feature.spec.tsx
- libs/shared/ui/src/lib/components/inputs/input-select/input-select.spec.tsx
- libs/shared/utils/src/lib/hooks/use-document-title/use-document-title.spec.tsx
- libs/shared/utils/src/lib/hooks/use-running-status-websocket/use-running-status-websocket.spec.tsx
- libs/shared/utils/src/lib/http/interceptors/auth-interceptor/auth-interceptor.spec.ts
- package.json
- yarn.lock
https://github.com/testing-library/react-hooks-testing-library#a-note-about-react-18-support
> chore: fix render hook import

- package.json
- Fix `yarn start` with correct target  
---
> chore: fix run project with console target

- libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-ports-feature/page-settings-ports-feature.tsx
- libs/pages/services/src/lib/feature/page-application-create-feature/step-port-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/services/src/lib/feature/page-application-create-feature/step-port-feature/step-port-feature.tsx
- libs/pages/services/src/lib/ui/page-application-create/step-summary/step-summary.tsx
- libs/shared/console-shared/src/lib/flow-create-port/ui/crud-modal/crud-modal.spec.tsx
- libs/shared/console-shared/src/lib/flow-create-port/ui/crud-modal/crud-modal.tsx
- libs/shared/console-shared/src/lib/flow-create-port/ui/flow-create-port/flow-create-port.tsx
- libs/shared/interfaces/src/lib/domain/advanced-settings.interface.ts
- package.json
- yarn.lock
](https://qovery.atlassian.net/browse/FRT-742)
- Add TCP and UDP protocols for port modal
- Peer programming with @ctjhoa 
---
> feat(port-modal): add TCP and UDP protocols

- libs/shared/console-shared/src/lib/clone-service-modal/feature/clone-service-modal-feature.tsx
- libs/shared/console-shared/src/lib/clone-service-modal/ui/clone-service-modal.spec.tsx
- libs/shared/console-shared/src/lib/clone-service-modal/ui/clone-service-modal.tsx
https://qovery.atlassian.net/browse/FRT-759
> feat(clone-service): add project selection

- libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.spec.tsx
- libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-ports-feature/page-settings-ports-feature.tsx
- libs/pages/application/src/lib/ui/page-settings-ports/page-settings-ports.tsx
- libs/shared/console-shared/src/index.ts
- libs/shared/console-shared/src/lib/flow-create-port/ui/crud-modal/crud-modal.spec.tsx
- libs/shared/console-shared/src/lib/flow-create-port/ui/crud-modal/crud-modal.tsx
- libs/shared/console-shared/src/lib/flow-create-port/ui/flow-create-port/flow-create-port.spec.tsx
- libs/shared/console-shared/src/lib/flow-create-port/ui/flow-create-port/flow-create-port.tsx
- libs/shared/console-shared/src/lib/flow-create-port/utils/port-healthcheck.spec.ts
- libs/shared/console-shared/src/lib/flow-create-port/utils/port-healthcheck.ts
- libs/shared/factories/src/lib/application-factory.mock.ts
- libs/shared/interfaces/src/lib/common/flow-port-data.interface.ts
- libs/shared/ui/src/lib/components/banner-box/banner-box.tsx
- libs/shared/ui/src/lib/components/inputs/input-select/input-select.spec.tsx
- libs/shared/ui/src/lib/components/inputs/input-select/input-select.tsx
https://qovery.atlassian.net/browse/FRT-740
> feat(port-healthcheck): update on port settings for health checks

- libs/pages/application/src/lib/feature/crud-environment-variable-modal-feature/crud-environment-variable-modal-feature.tsx
- libs/pages/application/src/lib/feature/table-row-environment-variable-feature/table-row-environment-variable-feature.tsx
- libs/shared/ui/src/lib/components/menu/menu-item/menu-item.tsx
- libs/shared/utils/src/lib/tools/compute-available-environment-variable-scope.spec.tsx
- libs/shared/utils/src/lib/tools/compute-available-environment-variable-scope.tsx
https://qovery.atlassian.net/browse/FRT-667
Note: I've not done the requested scope select tooltip because currently select doesn’t support tooltip for option.
> feat(override-var): dynamic override option depending on current scope

- libs/pages/settings/src/lib/ui/page-organization-github-repository-access/disconnection-confirm-modal/disconnection-confirm-modal.tsx
https://qovery.atlassian.net/browse/FRT-746
> refactor(github-app): reword disconnection confirm modal

- .codecov.yml
> chore: codecov update target for patch/project

- libs/pages/database/src/lib/page-database.tsx
- libs/pages/database/src/lib/ui/instances-table/instances-table.tsx
- libs/pages/database/src/lib/ui/page-general/page-general.tsx
> https://qovery.atlassian.net/browse/FRT-741
In addition to the linked ticket, I also fix:
- The running instance metric (which was hard coded)
- The display of metrics when metric equals 0
> fix(database): fix database metrics

- libs/shared/console-shared/src/lib/clone-service-modal/ui/clone-service-modal.spec.tsx
- libs/shared/console-shared/src/lib/clone-service-modal/ui/clone-service-modal.tsx
https://qovery.atlassian.net/browse/FRT-765
> fix(clone-service): remove name transformations

- libs/pages/onboarding/src/lib/feature/container/container.tsx
- libs/pages/onboarding/src/lib/feature/form-user/form-user.tsx
- libs/pages/onboarding/src/lib/feature/onboarding-pricing/onboarding-pricing.tsx
- libs/pages/onboarding/src/lib/feature/onboarding-project/onboarding-project.tsx
https://qovery.atlassian.net/browse/FRT-435
> feat(signup): create admin_email from user email

- libs/shared/ui/src/lib/components/menu/menu.tsx
https://qovery.atlassian.net/browse/FRT-778
> perf(ui): fix Menu rendering

- libs/state/util-queries/src/lib/use-react-query-ws-subscription/use-react-query-ws-subscription.spec.tsx
- libs/state/util-queries/src/lib/use-react-query-ws-subscription/use-react-query-ws-subscription.ts
- Update `urlSearchParams` to authorized empty and undefined values
---
> chore: update urlSearchParams type for WS suscription

- libs/pages/application/src/lib/ui/page-deployments/page-deployments.tsx
- libs/pages/database/src/lib/ui/page-deployments/page-deployments.tsx
- libs/pages/services/src/lib/ui/page-deployments/page-deployments.tsx
- libs/shared/ui/src/lib/components/table/table-row-deployment/table-row-deployment.spec.tsx
- libs/shared/ui/src/lib/components/table/table-row-deployment/table-row-deployment.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-781)
- Add link to deployment history for deployments rows
- Plan for next sprint but quick win for users
- ButtonIcon should be clean (UI like button-action component)
---
> feat(deployment-row): add link to history logs

- libs/shared/ui/src/lib/components/modals/modal-confirmation/modal-confirmation.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-783
---
> fix(modal-confirmation): modal disappear after actions

- libs/pages/application/src/lib/feature/crud-environment-variable-modal-feature/crud-environment-variable-modal-feature.tsx
https://qovery.atlassian.net/browse/FRT-784
> fix(override-var): fix missing scope in unwanted cases

- libs/domains/services/data-access/src/lib/domains-services-data-access.ts
- package.json
- yarn.lock
- bump qovery-typescript-axios
- remove type aliasing
> refactor(services): remove type alias

- libs/pages/events/src/lib/ui/row-event/row-event.spec.tsx
- libs/pages/events/src/lib/ui/row-event/row-event.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-748)
- Add target link for Audit logs
---
> feat(audit-logs): target link

- libs/pages/layout/src/lib/feature/layout/layout.tsx
- libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx
- libs/pages/layout/src/lib/ui/navigation/navigation.spec.tsx
- libs/pages/layout/src/lib/ui/navigation/navigation.tsx
- Add default organization id when we can't found the organizationId on the URL
---
> fix(layout): add default organization id

- libs/pages/application/src/lib/ui/page-settings-domains/input-approval-badge/input-approval-badge.tsx
- libs/pages/logs/environment/src/lib/ui/pod-logs/pod-logs.tsx
- libs/pages/logs/infra/src/lib/ui/row/row.spec.tsx
- libs/pages/logs/infra/src/lib/ui/row/row.tsx
- libs/pages/settings/src/lib/ui/page-organization-billing-summary/invoices-list/table-row-invoice/table-row-invoice.tsx
- libs/shared/console-shared/src/lib/git-repository-settings/ui/confirmation-git-modal/confirmation-git-modal.tsx
- libs/shared/console-shared/src/lib/git-repository-settings/ui/git-repository-settings/git-repository-settings.tsx
- libs/shared/ui/src/lib/components/banner-box/banner-box.spec.tsx
- libs/shared/ui/src/lib/components/banner-box/banner-box.tsx
- libs/shared/ui/src/lib/components/banner/banner.spec.tsx
- libs/shared/ui/src/lib/components/banner/banner.tsx
- libs/shared/ui/src/lib/components/inputs/input-text-small/input-text-small.tsx
- libs/shared/ui/src/lib/components/toast/toast.tsx
- tailwind-workspace-preset.js
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-774)
- Rename warning to yellow color token
---
> refactor(ui): rename warning token color to yellow

- libs/pages/application/src/lib/ui/container/container.tsx
- libs/pages/clusters/src/lib/ui/card-cluster/card-cluster.spec.tsx
- libs/pages/clusters/src/lib/ui/card-cluster/card-cluster.tsx
- libs/pages/database/src/lib/ui/container/container.tsx
- libs/pages/services/src/lib/ui/container/container.tsx
- libs/shared/ui/src/lib/components/header/header.stories.tsx
- libs/shared/ui/src/lib/components/tag-commit/tag-commit.tsx
- libs/shared/ui/src/lib/styles/components/status-menu.scss
- tailwind-workspace-preset.js
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-774)
- Rename progressing to orange color token
---
> refactor(ui): rename progressing token color to orange

- apps/console/src/app/app.tsx
- apps/console/src/app/router/main.router.tsx
- libs/pages/database/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.spec.tsx
- libs/pages/layout/src/lib/feature/menu-account-feature/menu-account-feature.tsx
- libs/pages/layout/src/lib/ui/menu-account/menu-account.tsx
- libs/pages/user/.babelrc
- libs/pages/user/.eslintrc.json
- libs/pages/user/README.md
- libs/pages/user/jest.config.ts
- libs/pages/user/project.json
- libs/pages/user/src/index.ts
- libs/pages/user/src/lib/feature/page-user-general-feature/page-user-general-feature.spec.tsx
- libs/pages/user/src/lib/feature/page-user-general-feature/page-user-general-feature.tsx
- libs/pages/user/src/lib/page-user.spec.tsx
- libs/pages/user/src/lib/page-user.tsx
- libs/pages/user/src/lib/router/router.tsx
- libs/pages/user/src/lib/ui/container/container.spec.tsx
- libs/pages/user/src/lib/ui/container/container.tsx
- libs/pages/user/src/lib/ui/page-user-general/page-user-general.spec.tsx
- libs/pages/user/src/lib/ui/page-user-general/page-user-general.tsx
- libs/pages/user/tsconfig.json
- libs/pages/user/tsconfig.lib.json
- libs/pages/user/tsconfig.spec.json
- libs/shared/routes/src/lib/router.ts
- libs/shared/routes/src/lib/sub-router/user.router.ts
- tsconfig.base.json
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-718)
---
> feat(page-user): add user page with general settings

- libs/pages/application/src/lib/ui/container/container.tsx
- libs/pages/application/src/lib/ui/crud-environment-variable-modal/crud-environment-variable-modal.tsx
- libs/pages/application/src/lib/ui/page-settings-healthchecks/page-settings-healthchecks.tsx
- libs/pages/application/src/lib/ui/table-row-environment-variable/table-row-environment-variable.tsx
- libs/pages/cluster/src/lib/ui/container/container.tsx
- libs/pages/clusters/src/lib/ui/card-cluster/card-cluster.tsx
- libs/pages/database/src/lib/ui/container/container.tsx
- libs/pages/environments/src/lib/ui/help-sidebar/help-sidebar.tsx
- libs/pages/layout/src/lib/ui/breadcrumb/breadcrumb.tsx
- libs/pages/login/src/lib/ui/login/login.tsx
- libs/pages/onboarding/src/lib/ui/benefits-card/benefits-card.tsx
- libs/pages/onboarding/src/lib/ui/step-pricing/step-pricing.tsx
- libs/pages/onboarding/src/lib/ui/step-thanks/step-thanks.tsx
- libs/pages/overview/ui/src/lib/components/overview/overview.tsx
- libs/pages/services/src/lib/ui/container/container.tsx
- libs/pages/settings/src/lib/ui/page-organization-container-registries/crud-modal/crud-modal.tsx
- libs/shared/console-shared/src/lib/cluster-settings/ui/create-edit-credentials-modal/create-edit-credentials-modal.tsx
- libs/shared/console-shared/src/lib/layout-logs/card-cluster/card-cluster.tsx
- libs/shared/console-shared/src/lib/layout-logs/tabs-cluster-logs/tabs-cluster-logs.tsx
- libs/shared/ui/src/lib/components/banner-box/banner-box.spec.tsx
- libs/shared/ui/src/lib/components/banner-box/banner-box.tsx
- libs/shared/ui/src/lib/components/header/header.stories.tsx
- libs/shared/ui/src/lib/components/link/link.tsx
- libs/shared/ui/src/lib/components/modals/modal-confirmation/__snapshots__/modal-confirmation.spec.tsx.snap
- libs/shared/ui/src/lib/components/modals/modal-confirmation/modal-confirmation.tsx
- libs/shared/ui/src/lib/components/tag-event/tag-event.tsx
- libs/shared/ui/src/lib/components/tag-mode/tag-mode.tsx
- libs/shared/ui/src/lib/styles/object/code-ansi.scss
- libs/shared/ui/src/lib/styles/object/link.scss
- tailwind-workspace-preset.js
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-774)
- Rename accent colors token
---
> refactor(ui): rename accent colors to new name

- libs/pages/logs/environment/src/lib/feature/deployment-logs-feature/deployment-logs-feature.tsx
- libs/pages/logs/environment/src/lib/feature/pod-logs-feature/pod-logs-feature.tsx
https://qovery.atlassian.net/browse/FRT-745
> perf: improve logs performances

- libs/domains/environment/src/lib/slices/deployment-stage.ts
- https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-791
- https://qovery.slack.com/archives/C02P2JB4SEM/p1692439342647849
---
> fix(deployment-stage): remove optimistic id for mutate

- .vscode/extensions.json
https://qovery.slack.com/archives/C02NF49B0TF/p1682437832073609
> chore: add github vscode extensions suggestions

- libs/pages/logs/environment/src/lib/ui/pod-logs/pod-logs.spec.tsx
- libs/pages/logs/environment/src/lib/ui/pod-logs/pod-logs.tsx
- libs/shared/console-shared/src/lib/layout-logs/layout-logs.tsx
- libs/shared/ui/src/lib/components/inputs/input-checkbox/input-checkbox.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-676
---
> feat(nginx-logs): some improvements

- libs/shared/ui/src/lib/components/table-primitives/table-primitives.stories.tsx
- libs/shared/ui/src/lib/components/table-primitives/table-primitives.tsx
- libs/shared/ui/src/lib/components/table/table-head-filter/table-head-filter.tsx
- libs/shared/ui/src/lib/components/table/table-head-sort/table-head-sort.tsx
- libs/shared/ui/src/lib/components/table/table-row-deployment/table-row-deployment.tsx
- libs/shared/ui/src/lib/components/table/table-row-filter/table-row-filter.tsx
- libs/shared/ui/src/lib/components/table/table-row/table-row.tsx
- libs/shared/ui/src/lib/components/table/table.tsx
- package.json
- yarn.lock
https://qovery.atlassian.net/browse/FRT-801
```jsx
<Table.Root>
<Table.Header>
<Table.Row>
<Table.ColumnHeaderCell>Full name</Table.ColumnHeaderCell>
<Table.ColumnHeaderCell>Email</Table.ColumnHeaderCell>
<Table.ColumnHeaderCell>Group</Table.ColumnHeaderCell>
</Table.Row>
</Table.Header>
<Table.Body>
<Table.Row>
<Table.RowHeaderCell>Danilo Sousa</Table.RowHeaderCell>
<Table.Cell>danilo@example.com</Table.Cell>
<Table.Cell>Developer</Table.Cell>
</Table.Row>
<Table.Row>
<Table.RowHeaderCell>Zahra Ambessa</Table.RowHeaderCell>
<Table.Cell>zahra@example.com</Table.Cell>
<Table.Cell>Admin</Table.Cell>
</Table.Row>
<Table.Row>
<Table.RowHeaderCell>Jasper Eriksson</Table.RowHeaderCell>
<Table.Cell>jasper@example.com</Table.Cell>
<Table.Cell>Developer</Table.Cell>
</Table.Row>
</Table.Body> …
```
> feat(ui): add table primitives

- libs/pages/logs/environment/src/lib/ui/pod-logs/pod-logs.tsx
https://app.logrocket.com/msuoxn/console-v3/issue/473623516?issueType=EXCEPTION&referrer=slack
---
> fix(pod-logs): error if empty service

- libs/shared/ui/src/lib/components/menu/menu-group/menu-group.tsx
- libs/shared/ui/src/lib/components/tooltip/tooltip.tsx
- tailwind-workspace-preset.js
- Replace element dark 400 by neutral 600
---
> refactor(ui): remove element dark color

- libs/pages/layout/src/lib/feature/layout/layout.tsx
- libs/pages/layout/src/lib/feature/menu-account-feature/menu-account-feature.spec.tsx
- libs/pages/login/src/lib/hooks/use-redirect-if-logged/use-redirect-if-logged.tsx
- Remove useless UserSignUp request
---
> fix(layout): remove user sign up request

- libs/pages/logs/environment/src/lib/feature/deployment-logs-feature/deployment-logs-feature.tsx
- libs/pages/logs/environment/src/lib/feature/pod-logs-feature/pod-logs-feature.tsx
- libs/pages/logs/environment/src/lib/ui/deployment-logs/deployment-logs.spec.tsx
- libs/pages/logs/environment/src/lib/ui/deployment-logs/deployment-logs.tsx
- libs/pages/logs/environment/src/lib/ui/pod-logs/pod-logs.tsx
- libs/pages/logs/infra/src/lib/page-infra-logs.tsx
- libs/shared/console-shared/src/lib/layout-logs/layout-logs.spec.tsx
- libs/shared/console-shared/src/lib/layout-logs/layout-logs.tsx
- libs/shared/console-shared/src/lib/layout-logs/placeholder-logs/placeholder-logs.spec.tsx
- libs/shared/console-shared/src/lib/layout-logs/placeholder-logs/placeholder-logs.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-797
- Add placeholder for DB Managed on the Live logs
- Refacto placeholders and using only one component for all Logs 
- Don't hesitate to re-test different case because the placeholders logics are modified 
---
> feat(logs-placeholder): update placeholder for Logs

- libs/shared/console-shared/src/lib/layout-logs/layout-logs.tsx
> chore(logs-nginx): wording

- libs/pages/settings/src/lib/feature/page-organization-members-feature/create-modal-feature/create-modal-feature.tsx
https://app.logrocket.com/msuoxn/console-v3/issue/478267410?issueType=EXCEPTION&referrer=slack
---
> fix(invite-member-modal): default custom roles

- libs/shared/ui/src/lib/components/table/table-row-deployment/table-row-deployment.spec.tsx
- libs/shared/ui/src/lib/components/table/table-row-deployment/table-row-deployment.tsx
- Fixed link to live logs with correct serviceId
---
> fix(row-deployment): link to pod logs

- libs/pages/events/src/lib/feature/custom-filter-feature/custom-filter-feature.tsx
- libs/pages/events/src/lib/feature/page-general-feature/page-general-feature.tsx
- libs/pages/events/src/lib/ui/custom-filter/custom-filter.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-794
---
> fix(audit-logs): environment custom filter

- apps/console/src/app/components/redirect-overview.tsx
- apps/console/src/app/router/main.router.tsx
- libs/pages/layout/src/lib/ui/breadcrumb/breadcrumb.tsx
- Remove hard reload for Environments page
- Improve UI loader
https://www.loom.com/share/5549b2134f944adba8084383bfcb5eba
---
> fix(organization): remove hard reload to redirect environments page

- libs/pages/layout/src/lib/ui/navigation/navigation.tsx
https://qovery.atlassian.net/browse/FRT-810
> fix(navigation): keep same project when clicking on the "Environment"

- .eslintrc.json
- libs/pages/settings/src/lib/ui/page-organization-roles-edit/row-project/row-project.tsx
> chore: add no-redeclare eslint rule

- libs/shared/console-shared/src/lib/layout-logs/layout-logs.tsx
https://qovery.atlassian.net/browse/FRT-809
> fix(logs): prevent pauseLogs if no scrollbar

- libs/pages/application/src/lib/ui/page-settings-advanced/page-settings-advanced.spec.tsx
- libs/pages/application/src/lib/ui/page-settings-advanced/page-settings-advanced.tsx
- libs/pages/cluster/src/lib/ui/page-settings-advanced/page-settings-advanced.spec.tsx
- libs/pages/cluster/src/lib/ui/page-settings-advanced/page-settings-advanced.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-764
---
> fix(advanced-settings): allow show overriden settings for object

- libs/shared/util-web-sockets/src/lib/use-status-web-sockets/use-status-web-sockets.ts
> fix(ws): require projectId for service status WS

- libs/pages/layout/src/lib/ui/breadcrumb/breadcrumb.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-818
---
> fix(breadcrumb-environments): remove statuses

- libs/pages/layout/src/lib/feature/layout/layout.tsx
https://qovery.atlassian.net/browse/FRT-818
> fix(ws): limit open WS in service list view

- libs/shared/ui/src/lib/components/inputs/input-select/input-select.tsx
https://qovery.atlassian.net/browse/FRT-813
You can test it with the following `index.html`
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Qovery</title>
<base href="/" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="icon" type="image/x-icon" href="favicon.ico" />
</head>
<body style="padding-top: 0; margin-top: 50px; max-height: calc(100% - 50px)">
<div id="root"></div>
<iframe style="height: 50px; width: 100vw; position: fixed; top: 0px; left: 0px; z-index: 2147483001"></iframe>
</body>
</html>
```
> fix(ui): Prevent select options misplacement with intercom banner

- libs/pages/application/src/lib/ui/page-settings-deployment-restrictions/crud-modal/crud-modal.tsx
- libs/pages/application/src/lib/ui/page-settings-domains/crud-modal/crud-modal.tsx
- libs/shared/console-shared/src/lib/clone-service-modal/feature/clone-service-modal-feature.tsx
- libs/shared/console-shared/src/lib/clone-service-modal/ui/clone-service-modal.tsx
- libs/shared/console-shared/src/lib/flow-create-port/ui/crud-modal/crud-modal.tsx
- libs/shared/ui/src/index.ts
- libs/shared/ui/src/lib/components/help-section/help-section.tsx
- libs/shared/ui/src/lib/components/icon/icon-awesome.enum.tsx
- libs/shared/ui/src/lib/components/modals/modal-crud/modal-crud.tsx
- libs/shared/ui/src/lib/components/popover/popover.stories.tsx
- libs/shared/ui/src/lib/components/popover/popover.tsx
- libs/shared/ui/src/lib/components/table-primitives/table-primitives.tsx
- libs/shared/ui/src/lib/styles/animations.stories.tsx
- libs/shared/ui/src/lib/styles/base/icons.scss
- package.json
- tailwind-workspace-preset.js
- yarn.lock
https://qovery.atlassian.net/browse/FRT-763
> feat(services): add how it works info on clone service

- libs/domains/services/feature/src/lib/hooks/use-metrics/use-metrics.ts
https://qovery.atlassian.net/browse/FRT-826
> fix(metrics): preserve order

- libs/pages/application/src/lib/feature/table-row-environment-variable-feature/table-row-environment-variable-feature.tsx
https://qovery.atlassian.net/browse/FRT-785
> fix(env-var): disable variable override for job and container

- libs/pages/logs/environment/src/lib/feature/sidebar-history-feature/sidebar-history-feature.tsx
- libs/pages/logs/environment/src/lib/ui/sidebar-history/sidebar-history.spec.tsx
- libs/pages/logs/environment/src/lib/ui/sidebar-history/sidebar-history.tsx
- libs/pages/logs/environment/src/lib/ui/sidebar/sidebar.tsx
- libs/shared/ui/.storybook/preview.tsx
- libs/shared/ui/src/lib/components/buttons/button-icon/button-icon.tsx
- libs/shared/ui/src/lib/components/buttons/button/button.tsx
- libs/shared/ui/src/lib/components/icon/icon-awesome.enum.tsx
- libs/shared/ui/src/lib/components/inputs/input-filter/__snapshots__/input-filter.spec.tsx.snap
- libs/shared/ui/src/lib/components/inputs/input-filter/input-filter.spec.tsx
- libs/shared/ui/src/lib/components/modals/modal-confirmation/__snapshots__/modal-confirmation.spec.tsx.snap
- libs/shared/ui/src/lib/components/tooltip/tooltip.spec.tsx
- libs/shared/ui/src/lib/components/tooltip/tooltip.stories.tsx
- libs/shared/ui/src/lib/components/tooltip/tooltip.tsx
- libs/shared/ui/src/lib/styles/base/icons.scss
- package.json
- yarn.lock
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-776
- Update deployment history with new UI
- Add CVA
- Add Tooltip orange color
---
> feat(sidebar-history): actions improvements

- libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx
- libs/pages/layout/src/lib/ui/navigation/navigation.tsx
- Add cluster notification if failed
---
> feat(navigation): add cluster notification if failed

- libs/pages/application/src/lib/ui/container/container.tsx
- libs/pages/database/src/lib/ui/container/container.tsx
- libs/pages/services/src/lib/ui/container/container.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-803
I didn't add a tooltip because we have space to have full name (you can see [here](http://localhost:4200/organization/460616f0-94da-4d35-b631-6fa4ed08eb9a/project/61acd49c-41d9-4354-8e8c-9ae502273a0c/environment/df9ce8df-7f22-456e-a558-967d9d7f270d/application/0c896b65-6205-400b-8659-a9c95660f870/general)).
---
> fix(page-details): remove truncate cluster name

- package.json
- yarn.lock
- Update some packages without dependabot 
---
> chore: packages (eslint, css-loader, msw, postcss)

- libs/pages/settings/src/lib/feature/page-organization-container-registries-feature/crud-modal-feature/crud-modal-feature.spec.tsx
- libs/pages/settings/src/lib/ui/page-organization-container-registries/crud-modal/crud-modal.spec.tsx
- libs/pages/settings/src/lib/ui/page-organization-container-registries/crud-modal/crud-modal.tsx
- https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-711
---
> feat(container-registry): add github gitlab and generic support

- libs/pages/logs/environment/src/lib/feature/deployment-logs-feature/deployment-logs-feature.tsx
- libs/pages/logs/environment/src/lib/feature/sidebar-history-feature/sidebar-history-feature.tsx
- libs/pages/logs/environment/src/lib/page-environment-logs.spec.tsx
- libs/pages/logs/environment/src/lib/page-environment-logs.tsx
- libs/pages/logs/environment/src/lib/ui/sidebar-history/sidebar-history.spec.tsx
- libs/pages/logs/environment/src/lib/ui/sidebar-history/sidebar-history.tsx
- libs/pages/logs/environment/src/lib/ui/sidebar/sidebar.spec.tsx
- libs/pages/logs/environment/src/lib/ui/sidebar/sidebar.tsx
- libs/pages/settings/src/lib/ui/page-organization-container-registries/crud-modal/crud-modal.tsx
- Display TaskManager logs  
- Fix label "new"
---
> fix(deployment-logs): new label and displaying TaskManager logs

- libs/pages/services/src/lib/ui/table-row-services/table-row-services.tsx
- Add the Git branch name next to the service version.
- Limits the branch name display to 20 characters using the Truncate method
---
> feat(page-services): add the git branch name next to the service version

- libs/shared/util-web-sockets/src/lib/use-status-web-sockets/use-status-web-sockets.ts
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-832
---
> fix(page-environments): WS deployment status request

- libs/pages/settings/src/lib/ui/page-organization-container-registries/crud-modal/crud-modal.tsx
- moved dockerhub info message at the bottom
---
> fix(container-registry): move dockerhub info message

- libs/pages/services/src/lib/feature/page-application-create-feature/step-summary-feature/step-summary-feature.spec.tsx
- libs/pages/services/src/lib/feature/page-application-create-feature/step-summary-feature/step-summary-feature.tsx
- libs/pages/services/src/lib/feature/page-job-create-feature/step-summary-feature/step-summary-feature.tsx
- Add default healthchecks for Application/Container/Jobs
---
> fix(create-flow): defined healthchecks

- libs/shared/util-js/src/lib/refacto-payload.spec.ts
- libs/shared/util-js/src/lib/refacto-payload.ts
- https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-839
---
> fix(jobs-healthchecks): return values

- libs/shared/factories/src/lib/container-factory.mock.ts
- libs/shared/factories/src/lib/job-factory.mock.ts
- libs/shared/util-js/src/lib/refacto-payload.spec.ts
- libs/shared/util-js/src/lib/refacto-payload.ts
- package.json
- yarn.lock
`healthchecks` property is now mandatory since https://github.com/Qovery/console/pull/833
> fix(services): add missing healthchecks property

- libs/shared/console-shared/src/lib/update-all-modal/feature/update-all-modal-feature.tsx
- libs/shared/console-shared/src/lib/update-all-modal/ui/update-all-modal.tsx
https://qovery.atlassian.net/browse/FRT-804
> fix(services): fix deploy latest version modal

- .eslintrc.json
- apps/console/src/main.tsx
- libs/pages/logs/environment/src/lib/ui/pod-logs/pod-logs.tsx
- libs/pages/settings/src/lib/ui/page-organization-billing-summary/invoices-list/table-row-invoice/table-row-invoice.tsx
- libs/pages/settings/src/lib/ui/page-organization-billing/billing-details/billing-details.tsx
- libs/shared/console-shared/src/lib/create-general-git-application/ui/create-general-git-application.tsx
- libs/shared/console-shared/src/lib/credit-card-form/ui/credit-card-form.tsx
- libs/shared/console-shared/src/lib/flow-create-variable/ui/variable-row/variable-row.tsx
- libs/shared/console-shared/src/lib/git-repository-settings/ui/git-repository-settings/git-repository-settings.tsx
- libs/shared/console-shared/src/lib/job-general-settings/ui/job-general-settings.tsx
- libs/shared/console-shared/src/lib/update-all-modal/ui/update-all-modal.tsx
- libs/shared/ui/src/lib/components/modal-alert/modal-alert.tsx
- libs/shared/ui/src/lib/components/modal/modal.tsx
- libs/shared/ui/src/lib/components/password-show-hide/password-show-hide.tsx
- libs/shared/ui/src/lib/components/sticky-action-form-toaster/sticky-action-form-toaster.tsx
https://qovery.atlassian.net/browse/FRT-841
> chore: add react/jsx-curly-brace-presence eslint rule

- .eslintrc.json
- To avoid forgetting some missing keys
---
> chore: add react/jsx-key eslint rule

- libs/pages/logs/environment/src/lib/feature/deployment-logs-feature/deployment-logs-feature.tsx
- libs/pages/logs/environment/src/lib/feature/pod-logs-feature/pod-logs-feature.tsx
- libs/pages/logs/environment/src/lib/page-environment-logs.tsx
- libs/pages/logs/environment/src/lib/ui/deployment-logs/deployment-logs.tsx
- libs/pages/logs/environment/src/lib/ui/pod-logs/pod-logs.tsx
- libs/shared/console-shared/src/lib/layout-logs/layout-logs.spec.tsx
- libs/shared/console-shared/src/lib/layout-logs/layout-logs.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-790
- `Progressbar` for Lives and Deployment logs
https://www.loom.com/share/6eebcec9ff8f4d0c9dfd98f368ee1d32 (we use now the brand color for the component)
---
> feat(layout-logs): add running animation

- libs/pages/logs/environment/src/lib/ui/sidebar-pipeline/sidebar-pipeline.spec.tsx
- libs/pages/logs/environment/src/lib/ui/sidebar-pipeline/sidebar-pipeline.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-842
---
> fix(sidebar-pipeline): spinner if stages undefined

- libs/domains/environment-variable/src/lib/slices/environment-variables.slice.ts
- libs/domains/environment-variable/src/lib/slices/secret-environment-variables.slice.ts
- libs/pages/application/src/lib/feature/crud-environment-variable-modal-feature/crud-environment-variable-modal-feature.tsx
- libs/pages/application/src/lib/feature/table-row-environment-variable-feature/table-row-environment-variable-feature.tsx
- libs/pages/application/src/lib/feature/tabs-feature/tabs-feature.tsx
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-835)
- Add redeploy action in a Toast when we delete a variable
- Fix create variable file modal (didn't work impossible to submit change)
---
> fix(environment-variable): add redeploy delete action in toast

- apps/console/src/main.tsx
https://react.dev/reference/react/StrictMode
---
> chore: add strict mode

- libs/domains/organization/src/lib/slices/cluster/cluster.actions.ts
- libs/pages/cluster/src/lib/page-cluster.tsx
- libs/pages/cluster/src/lib/ui/container/container.tsx
- libs/pages/cluster/src/lib/ui/need-redeploy-flag/need-redeploy-flag.spec.tsx
- libs/pages/cluster/src/lib/ui/need-redeploy-flag/need-redeploy-flag.tsx
- libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx
- libs/shared/console-shared/src/lib/need-redeploy-flag/ui/need-redeploy-flag.tsx
- libs/shared/ui/src/lib/components/banner/__snapshots__/banner.spec.tsx.snap
- libs/shared/ui/src/lib/components/banner/banner.spec.tsx
- libs/shared/ui/src/lib/components/banner/banner.stories.tsx
- libs/shared/ui/src/lib/components/banner/banner.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-747
+ And update Banner component with CVA
---
> feat(cluster): add redeploy banner

- libs/domains/services/data-access/src/lib/domains-services-data-access.ts
- libs/pages/application/src/lib/ui/container/container.tsx
- libs/pages/cluster/src/lib/ui/container/container.tsx
- libs/pages/database/src/lib/ui/container/container.tsx
- libs/pages/environments/src/lib/ui/container/container.tsx
- libs/pages/services/src/lib/ui/container/container.tsx
- libs/shared/ui/src/index.ts
- libs/shared/ui/src/lib/components/description-list/description-list.stories.tsx
- libs/shared/ui/src/lib/components/description-list/description-list.tsx
- libs/shared/ui/src/lib/components/header/header.spec.tsx
- libs/shared/ui/src/lib/components/header/header.tsx
- libs/shared/ui/src/lib/components/heading/__snapshots__/heading.spec.tsx.snap
- libs/shared/ui/src/lib/components/heading/heading.spec.tsx
- libs/shared/ui/src/lib/components/heading/heading.tsx
- libs/shared/ui/src/lib/components/heading/level-context.ts
- libs/shared/ui/src/lib/components/section/__snapshots__/section.spec.tsx.snap
- libs/shared/ui/src/lib/components/section/section.spec.tsx
- libs/shared/ui/src/lib/components/section/section.stories.tsx
- libs/shared/ui/src/lib/components/section/section.tsx
https://qovery.atlassian.net/browse/FRT-768
> feat(ui): add components for the next service right section

- libs/pages/application/src/lib/ui/page-settings-general/page-settings-general.tsx
- libs/pages/services/src/lib/feature/page-application-create-feature/step-general-feature/step-general-feature.tsx
- libs/pages/services/src/lib/feature/page-application-create-feature/step-summary-feature/step-summary-feature.spec.tsx
- libs/pages/services/src/lib/feature/page-application-create-feature/step-summary-feature/step-summary-feature.tsx
- libs/pages/services/src/lib/feature/page-job-create-feature/step-general-feature/step-general-feature.tsx
- libs/pages/services/src/lib/feature/page-job-create-feature/step-summary-feature/step-summary-feature.tsx
- libs/pages/services/src/lib/ui/page-application-create/step-general/step-general.tsx
- libs/pages/services/src/lib/ui/page-job-create/step-general/step-general.tsx
- libs/shared/console-shared/src/lib/job-general-settings/ui/job-general-settings.spec.tsx
- libs/shared/console-shared/src/lib/job-general-settings/ui/job-general-settings.tsx
https://qovery.atlassian.net/browse/FRT-668
> fix(services): fix autodeploy

- libs/shared/ui/src/lib/components/buttons/button-action/button-action.stories.tsx
- libs/shared/ui/src/lib/components/buttons/button-icon/button-icon.stories.tsx
- libs/shared/ui/src/lib/components/buttons/button-legacy/button-legacy.spec.tsx
- libs/shared/ui/src/lib/components/buttons/button-legacy/button-legacy.stories.tsx
- libs/shared/ui/src/lib/components/buttons/button-legacy/button-legacy.tsx
Follows https://github.com/Qovery/console/pull/862 and https://github.com/Qovery/console/pull/858
> refactor(ui): rename legacy button props

- libs/shared/ui/src/lib/components/status-chip/__snapshots__/status-chip.spec.tsx.snap
- libs/shared/ui/src/lib/components/status-chip/status-chip.spec.tsx
- libs/shared/ui/src/lib/components/status-chip/status-chip.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23
---
> fix(status-chip): new icon READY status

- libs/pages/services/src/lib/ui/table-row-services/table-row-services.tsx
> fix(ui): truncate service badges

- libs/pages/logs/environment/src/lib/feature/deployment-logs-feature/deployment-logs-feature.tsx
- libs/pages/logs/environment/src/lib/feature/pod-logs-feature/pod-logs-feature.tsx
- libs/pages/logs/environment/src/lib/page-environment-logs.tsx
- libs/pages/logs/environment/src/lib/ui/deployment-logs/deployment-logs.tsx
- libs/pages/logs/environment/src/lib/ui/pod-logs/pod-logs.tsx
- libs/shared/console-shared/src/lib/layout-logs/layout-logs.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-850
---
> fix(layout-logs): update progressing animation

- libs/domains/application/src/lib/slices/custom-domain.slice.ts
- libs/pages/application/src/lib/feature/page-settings-domains-feature/crud-modal-feature/crud-modal-feature.spec.tsx
- libs/pages/application/src/lib/feature/page-settings-domains-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/application/src/lib/ui/page-settings-domains/crud-modal/crud-modal.spec.tsx
- libs/pages/application/src/lib/ui/page-settings-domains/crud-modal/crud-modal.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-852
---
> feat(modal-domain): add generate certificate toggle

- libs/domains/services/data-access/src/lib/domains-services-data-access.ts
- libs/domains/services/feature/src/lib/last-commit/last-commit.tsx
https://qovery.atlassian.net/browse/FRT-768
> fix(services): fix service details

- libs/domains/services/data-access/src/lib/domains-services-data-access.ts
- libs/domains/services/feature/src/lib/service-state-chip/service-state-chip.tsx
- libs/pages/logs/environment/src/lib/feature/pod-logs-feature/pod-logs-feature.tsx
- libs/shared/util-js/src/lib/status-actions-available.ts
- libs/shared/util-web-sockets/src/lib/use-status-web-sockets/use-status-web-sockets.ts
- package.json
- yarn.lock
> https://qovery.atlassian.net/browse/FRT-823
> fix(types): improve WS typing

- libs/shared/ui/src/lib/components/help-section/__snapshots__/help-section.spec.tsx.snap
- libs/shared/ui/src/lib/components/help-section/help-section.tsx
- Add URL for ExternalLinks
---
> fix(help-section): add url for external links

- libs/pages/settings/src/lib/feature/page-organization-api-feature/crud-modal-feature/crud-modal-feature.spec.tsx
- libs/pages/settings/src/lib/feature/page-organization-api-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/settings/src/lib/ui/page-organization-api/crud-modal/crud-modal.spec.tsx
- libs/pages/settings/src/lib/ui/page-organization-api/crud-modal/crud-modal.tsx
- libs/pages/settings/src/lib/ui/page-organization-api/page-organization-api.spec.tsx
- libs/pages/settings/src/lib/ui/page-organization-api/page-organization-api.tsx
- libs/pages/settings/src/lib/ui/page-organization-members/create-modal/create-modal.tsx
- libs/shared/ui/src/lib/components/modals/modal-crud/modal-crud.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-848
---
> feat(api-token): add role

- libs/pages/settings/src/lib/ui/page-organization-container-registries/crud-modal/crud-modal.tsx
- libs/pages/settings/src/lib/ui/page-organization-container-registries/page-organization-container-registries.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-840
---
> fix(modal-container-registry): clean config payload

- libs/domains/services/feature/src/lib/service-details/service-details.tsx
https://qovery.atlassian.net/browse/FRT-860
> feat(services): handle bitbucket icon

- libs/pages/services/src/lib/ui/page-application-create/step-general/step-general.tsx
https://qovery.atlassian.net/browse/FRT-862
> fix(applications): fix entrypoint / args on container creation flow

- libs/domains/services/feature/src/lib/service-details/__snapshots__/service-details.spec.tsx.snap
- libs/pages/application/src/lib/ui/container/container.tsx
- libs/pages/application/src/lib/ui/page-settings/page-settings.tsx
- libs/pages/cluster/src/lib/ui/container/container.tsx
- libs/pages/cluster/src/lib/ui/page-settings/page-settings.tsx
- libs/pages/database/src/lib/ui/container/container.tsx
- libs/pages/database/src/lib/ui/page-settings/page-settings.tsx
- libs/pages/environments/src/lib/ui/container/container.tsx
- libs/pages/services/src/lib/ui/container/container.tsx
- libs/pages/services/src/lib/ui/page-settings/page-settings.tsx
- libs/shared/ui/src/lib/components/heading/__snapshots__/heading.spec.tsx.snap
- libs/shared/ui/src/lib/components/section/__snapshots__/section.spec.tsx.snap
- libs/shared/ui/src/lib/components/section/section.tsx
- tailwind-workspace-preset.js
https://qovery.atlassian.net/browse/FRT-863
Simplify layout and remove some hardcoded values
> fix(ui): improve container flex layout

- libs/pages/application/src/lib/feature/tabs-feature/tabs-feature.tsx
- libs/pages/application/src/lib/ui/container/container.tsx
- libs/pages/cluster/src/lib/ui/container/container.tsx
- libs/pages/database/src/lib/ui/container/container.tsx
- libs/pages/services/src/lib/ui/container/container.tsx
- Avoid the glitch after reloading caused by skeleton height
---
> fix(header): ui reload glitch

- libs/domains/clusters/data-access/.eslintrc.json
- libs/domains/clusters/data-access/README.md
- libs/domains/clusters/data-access/jest.config.ts
- libs/domains/clusters/data-access/package.json
- libs/domains/clusters/data-access/project.json
- libs/domains/clusters/data-access/src/index.ts
- libs/domains/clusters/data-access/src/lib/domains-clusters-data-access.ts
- libs/domains/clusters/data-access/tsconfig.json
- libs/domains/clusters/data-access/tsconfig.lib.json
- libs/domains/clusters/data-access/tsconfig.spec.json
- libs/domains/clusters/feature/src/index.ts
- libs/domains/clusters/feature/src/lib/cluster-delete-modal/__snapshots__/cluster-delete-modal.spec.tsx.snap
- libs/domains/clusters/feature/src/lib/cluster-delete-modal/cluster-delete-modal.spec.tsx
- libs/domains/clusters/feature/src/lib/cluster-delete-modal/cluster-delete-modal.tsx
- libs/domains/clusters/feature/src/lib/hooks/use-delete-cluster/use-delete-cluster.ts
- libs/shared/console-shared/src/lib/buttons-actions/ui/cluster-buttons-actions/cluster-buttons-actions.tsx
- libs/shared/ui/src/lib/components/modals/modal-confirmation/__snapshots__/modal-confirmation.spec.tsx.snap
- libs/shared/ui/src/lib/components/modals/modal-confirmation/modal-confirmation.tsx
- tsconfig.base.json
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-854
---
> feat(cluster-delete-modal): add delete option

- libs/shared/console-shared/src/lib/general-container-settings/ui/general-container-settings.tsx
add hint on the image tag field
---
- [ x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x ] I made sure the code is type safe (no any)
> chore: added hint for image tag field

- libs/domains/clusters/feature/src/lib/cluster-delete-modal/__snapshots__/cluster-delete-modal.spec.tsx.snap
- libs/domains/clusters/feature/src/lib/cluster-delete-modal/cluster-delete-modal.tsx
> chore(delete-cluster): duplicate typo

- libs/pages/application/src/lib/ui/job-overview/job-overview.tsx
- libs/pages/application/src/lib/ui/page-settings-storage/page-settings-storage.tsx
- libs/pages/application/src/lib/ui/page-settings-storage/storage-modal/storage-modal.spec.tsx
- libs/pages/application/src/lib/ui/page-settings-storage/storage-modal/storage-modal.tsx
- libs/shared/console-shared/src/lib/application-settings/ui/application-settings-resources/application-settings-resources.tsx
- libs/shared/console-shared/src/lib/database-settings-resources/ui/database-settings-resources/database-settings-resources.tsx
https://qovery.atlassian.net/browse/FRT-866
> fix: moved all units to MiB/GiB

- libs/pages/settings/src/lib/ui/page-organization-api/crud-modal/crud-modal.tsx
- libs/shared/ui/src/lib/components/inputs/input-select/input-select.tsx
This is an upstream bug due to radix + react-select https://github.com/radix-ui/primitives/issues/2125
> fix(ui): fix scrollable issue with select inside modal

- libs/pages/layout/src/lib/ui/navigation/navigation.tsx
Update the UI in navigation component to fix typos around incorrect pluralization.
- `Helps` -> `Help`
- `See Documentations` -> `See Documentation`
---
> Fix typos on pluralization

- libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
- libs/shared/util-js/src/lib/build-git-repo-url.ts
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-861
---
> fix(build-git-url): includes http

- libs/domains/organizations/data-access/.eslintrc.json
- libs/domains/organizations/data-access/README.md
- libs/domains/organizations/data-access/jest.config.ts
- libs/domains/organizations/data-access/project.json
- libs/domains/organizations/data-access/src/index.ts
- libs/domains/organizations/data-access/src/lib/domains-organizations-data-access.ts
- libs/domains/organizations/data-access/tsconfig.json
- libs/domains/organizations/data-access/tsconfig.lib.json
- libs/domains/organizations/data-access/tsconfig.spec.json
https://qovery.atlassian.net/browse/FRT-844
> chore: add domains-organizations-data-access

- libs/domains/services/data-access/src/lib/domains-services-data-access.ts
- libs/domains/services/feature/src/lib/hooks/use-master-credentials/use-master-credentials.ts
- libs/domains/services/feature/src/lib/service-details/service-details.tsx
https://qovery.atlassian.net/browse/FRT-870
> feat(services): add access button for databases

- libs/domains/services/data-access/src/lib/domains-services-data-access.ts
- libs/shared/console-shared/src/lib/clone-service-modal/ui/clone-service-modal.spec.tsx
- libs/shared/console-shared/src/lib/clone-service-modal/ui/clone-service-modal.tsx
- libs/shared/enums/src/lib/service-type.enum.ts
Add data-access Helm endpoints and add `HELM` service type
> feat(services): add Helm services basic support

- libs/domains/services/feature/src/lib/pod-details/__snapshots__/pod-details.spec.tsx.snap
- libs/domains/services/feature/src/lib/pod-details/pod-details.tsx
- libs/domains/services/feature/src/lib/pods-metrics/__snapshots__/pods-metrics.spec.tsx.snap
- libs/domains/services/feature/src/lib/pods-metrics/pods-metrics.tsx
- https://qovery.atlassian.net/browse/FRT-886
> feat(services): pods metrics feedbacks

- libs/pages/logs/environment/src/lib/feature/pod-logs-feature/pod-logs-feature.tsx
- libs/pages/logs/environment/src/lib/ui/pod-logs/pod-logs.tsx
https://qovery.atlassian.net/browse/FRT-829
> feat(logs): add load previous logs button

- libs/pages/layout/src/lib/feature/layout/layout.tsx
- libs/pages/layout/src/lib/ui/layout-page/layout-page.spec.tsx
- libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx
- libs/pages/logs/infra/src/lib/page-infra-logs.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-847
You can test with this [Cluster](http://localhost:4200/organization/460616f0-94da-4d35-b631-6fa4ed08eb9a/cluster/be9e22b0-d05a-4330-b5b5-547667d380fd/settings/general) 
---
> feat(cluster): add deployment error banner

- libs/domains/organization/src/lib/slices/organization/auth-provider.slice.ts
- libs/domains/organization/src/lib/slices/organization/repository.slice.ts
- libs/domains/organizations/data-access/src/lib/domains-organizations-data-access.ts
- libs/domains/organizations/feature/src/lib/git-provider-setting/git-provider-setting.tsx
> chore: update git queries

- libs/pages/application/src/lib/ui/page-general/page-general.tsx
Update the cronjob alert text and add the TTL info
> chore(cronjob-overview): updated text for cronjob alert

- libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx
- Fix cluster error notification
---
> fix: cluster error notification

- libs/domains/organization/src/lib/slices/organization/auth-provider.slice.ts
- libs/domains/organization/src/lib/slices/organization/repository.slice.ts
- libs/domains/organizations/data-access/src/lib/domains-organizations-data-access.ts
- package.json
- yarn.lock
> chore: remove temp git api

- libs/domains/application/src/lib/slices/applications.slice.ts
- libs/pages/application/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx
- libs/pages/application/src/lib/page-application.tsx
- libs/shared/console-shared/src/lib/application-settings/ui/application-settings-resources/application-settings-resources.tsx
- libs/shared/interfaces/src/lib/domain/container-application.entity.ts
- libs/shared/interfaces/src/lib/domain/git-application.entity.ts
- libs/shared/interfaces/src/lib/domain/job-application.entity.ts
> feat(services): remove legacy instances props

- libs/domains/organization/src/lib/slices/cluster/cluster.actions.ts
- libs/pages/cluster/src/lib/feature/page-settings-danger-zone-feature/page-settings-danger-zone-feature.tsx
- libs/pages/cluster/src/lib/ui/page-settings-danger-zone/page-settings-danger-zone.tsx
- libs/shared/ui/src/lib/components/block-content-delete/block-content-delete.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1698656371868059
---
> fix(cluster-danger-zone): add new delete modal

- libs/domains/application/src/lib/slices/applications.slice.ts
- libs/domains/services/data-access/src/lib/domains-services-data-access.ts
- libs/domains/services/feature/src/index.ts
- libs/domains/services/feature/src/lib/hooks/use-commits/use-commits.ts
- libs/domains/services/feature/src/lib/hooks/use-outdated-services/use-outdated-services.ts
- libs/pages/application/src/lib/feature/page-settings-deployment-restrictions-feature/page-settings-deployment-restrictions-feature.tsx
- libs/pages/application/src/lib/page-application.tsx
- libs/shared/console-shared/src/lib/deploy-other-commit-modal/feature/deploy-other-commit-modal-feature.spec.tsx
- libs/shared/console-shared/src/lib/deploy-other-commit-modal/feature/deploy-other-commit-modal-feature.tsx
- libs/shared/console-shared/src/lib/deploy-other-commit-modal/ui/deploy-other-commit-modal.spec.tsx
- libs/shared/console-shared/src/lib/update-all-modal/feature/update-all-modal-feature.spec.tsx
- libs/shared/console-shared/src/lib/update-all-modal/feature/update-all-modal-feature.tsx
- libs/shared/console-shared/src/lib/update-all-modal/ui/update-all-modal.spec.tsx
- libs/shared/console-shared/src/lib/update-all-modal/ui/update-all-modal.tsx
- libs/shared/interfaces/src/lib/domain/git-application.entity.ts
- libs/shared/interfaces/src/lib/domain/job-application.entity.ts
- libs/shared/util-tests/src/lib/shared-util-tests.tsx
- libs/shared/util-types/.eslintrc.json
- libs/shared/util-types/README.md
- libs/shared/util-types/jest.config.ts
- libs/shared/util-types/project.json
- libs/shared/util-types/src/index.ts
- libs/shared/util-types/src/lib/shared-util-types.ts
- libs/shared/util-types/tsconfig.json
- libs/shared/util-types/tsconfig.lib.json
- libs/shared/util-types/tsconfig.spec.json
- tsconfig.base.json
https://qovery.atlassian.net/browse/FRT-891
> feat(services): migrate service commits to react query

- libs/domains/database/src/lib/slices/databases.slice.ts
- libs/pages/database/src/lib/page-database.tsx
- libs/shared/interfaces/src/lib/domain/database.entity.ts
> refactor(services): clean legacy services entity props

- libs/pages/layout/src/lib/ui/layout-page/layout-page.spec.tsx
- libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx
- Add good status to display credential banner
---
> fix(cluster): display banner cluster credential status

- libs/shared/console-shared/src/lib/deploy-other-commit-modal/feature/deploy-other-commit-modal-feature.tsx
> fix(services): fix deploy other commit modal

- libs/pages/database/src/lib/ui/page-settings-general/page-settings-general.tsx
- libs/pages/database/src/lib/ui/page-settings-resources/page-settings-resources.tsx
- libs/shared/console-shared/src/lib/database-settings-resources/ui/database-settings-resources/database-settings-resources.tsx
- libs/shared/console-shared/src/lib/database-settings-resources/ui/settings-resources-instance-types/setting-resources-instance-types.spec.tsx
- libs/shared/console-shared/src/lib/database-settings-resources/ui/settings-resources-instance-types/setting-resources-instance-types.tsx
- updated text when modifying version, storage and instance types
- added alert when changing disk size for managed db
note: we could use the same structure for the instance type and storage field (With a separate file) but I didn't do it, let me know
---
> feat(database): warning for maintenance window

- libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.spec.tsx
- libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-881
---
> feat(cluster-resources): add warning cluster nodes edit

- libs/pages/events/src/lib/ui/custom-filter/custom-filter.tsx
- libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx
- libs/pages/layout/src/lib/ui/top-bar/top-bar.tsx
- libs/pages/login/src/lib/ui/layout-login/layout-login.tsx
- libs/pages/login/src/lib/ui/login/login.tsx
- libs/shared/console-shared/src/lib/deploy-other-commit-modal/ui/deploy-other-commit-modal.tsx
- libs/shared/console-shared/src/lib/layout-logs/layout-logs.tsx
- libs/shared/ui/src/lib/components/date-picker/date-picker.tsx
- libs/shared/ui/src/lib/components/menu/menu.tsx
- libs/shared/ui/src/lib/components/modal/modal.tsx
- libs/shared/ui/src/lib/components/modals/modal-crud/modal-crud.tsx
- libs/shared/ui/src/lib/components/table/table.tsx
- libs/shared/ui/src/lib/components/tooltip/tooltip.tsx
https://qovery.atlassian.net/browse/FRT-895
Use natural DOM order to avoid z-index escalation
> fix(ui): avoid z-index war

- libs/pages/application/src/lib/feature/tabs-feature/tabs-feature.tsx
https://qovery.atlassian.net/browse/FRT-895
Note: The upload seems to work the first time.
Here is my repro case:
http://localhost:4200/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a021261e-4318-4f2f-b480-169ab62efc28/environment/c1567d73-b9cd-4664-8aa0-5c71e2bfd74a/application/49af5ad3-8966-4046-a77e-1f11749fa039/variables
Explanation:
This `serviceType` can be resolve as undefined, even if the one in upper scope is properly evaluated
https://github.com/Qovery/console/blob/66cacbfcbe802e243f05d7248baa4aef912ca091/libs/pages/application/src/lib/feature/tabs-feature/tabs-feature.tsx#L108
So my goal was to prevent untimely re-render by splitting the component in 2.
This prevent issue.
> fix(env-variables): fix untimely re-render / fix ImportEnvironmentVariableModalFeature

- libs/shared/console-shared/src/lib/flow-create-port/ui/crud-modal/crud-modal.spec.tsx
- libs/shared/console-shared/src/lib/flow-create-port/ui/crud-modal/crud-modal.tsx
- Added portal for the select protocol
---
> fix(select-protocol): add portal

- libs/pages/cluster/src/lib/feature/page-settings-credentials-feature/page-settings-credentials-feature.tsx
- libs/shared/ui/src/lib/components/inputs/input-select/input-select.tsx
- libs/shared/ui/src/lib/components/modal/modal.tsx
- libs/shared/util-js/src/lib/status-actions-available.ts
- Fix cluster credential update
---
> fix(cluster-credentials): select new credential after error

- libs/domains/services/feature/src/lib/service-list/service-list-filter.tsx
https://qovery.atlassian.net/browse/FRT-613
> fix(services): fix undefined facet entries

- libs/domains/services/feature/src/lib/service-details/service-details.tsx
- libs/domains/services/feature/src/lib/service-list/service-list.spec.tsx
- libs/pages/application/src/lib/feature/page-settings-configure-job-feature/page-settings-configure-job-feature.tsx
- libs/shared/console-shared/src/lib/force-run-modal/feature/force-run-modal-feature.tsx
- libs/shared/console-shared/src/lib/force-run-modal/ui/force-run-modal.tsx
- libs/shared/enums/src/lib/utils/get-service-type.ts
- libs/shared/factories/src/lib/job-factory.mock.ts
- libs/shared/interfaces/src/lib/domain/application.entity.ts
- libs/shared/interfaces/src/lib/domain/job-application.entity.ts
- package.json
- yarn.lock
https://qovery.atlassian.net/browse/FRT-902
> fix(types): fix job types after qovery-typescript-axios upgrade

- libs/domains/services/feature/src/lib/hooks/use-services/use-services.ts
https://qovery.atlassian.net/browse/FRT-907
> fix(services): handle managed db running status

- libs/domains/organizations/feature/src/lib/hooks/use-create-organization/use-create-organization.tsx
- libs/domains/projects/data-access/src/lib/domains-projects-data-access.ts
- libs/domains/projects/feature/src/lib/hooks/use-create-project/use-create-project.ts
- libs/domains/projects/feature/src/lib/hooks/use-delete-project/use-delete-project.ts
- libs/domains/projects/feature/src/lib/hooks/use-edit-project/use-edit-project.ts
- libs/domains/services/feature/src/lib/hooks/use-create-deployment-restriction/use-create-deployment-restriction.ts
- libs/domains/services/feature/src/lib/hooks/use-delete-deployment-restriction/use-delete-deployment-restriction.ts
- libs/domains/services/feature/src/lib/hooks/use-edit-deployment-restriction/use-edit-deployment-restriction.ts
- libs/pages/application/src/lib/feature/page-settings-deployment-restrictions-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-deployment-restrictions-feature/page-settings-deployment-restrictions-feature.tsx
- libs/pages/onboarding/src/lib/feature/onboarding-pricing/onboarding-pricing.tsx
- libs/pages/settings/src/lib/feature/page-project-danger-zone-feature/page-project-danger-zone-feature.tsx
- libs/pages/settings/src/lib/feature/page-project-general-feature/page-project-general-feature.tsx
- libs/shared/console-shared/src/lib/create-project-modal/feature/create-project-modal-feature.tsx
> refactor(hooks): use variables to invalidate queries

- libs/domains/services/data-access/src/lib/domains-services-data-access.ts
- libs/pages/application/src/lib/feature/page-general-feature/page-general-feature.tsx
- libs/pages/application/src/lib/page-application.tsx
- libs/pages/application/src/lib/ui/container/container.tsx
- libs/pages/application/src/lib/ui/page-general/page-general.tsx
- libs/pages/database/src/lib/feature/page-general-feature/page-general-feature.tsx
- libs/pages/database/src/lib/page-database.tsx
- libs/pages/database/src/lib/ui/container/container.tsx
- libs/pages/database/src/lib/ui/page-general/page-general.tsx
- libs/pages/layout/src/lib/feature/breadcrumb/breadcrumb.tsx
- libs/pages/layout/src/lib/ui/breadcrumb/breadcrumb.tsx
https://qovery.atlassian.net/browse/FRT-874
> refactor(services): simplify service pages

- libs/shared/util-js/src/lib/container-registry-kind-to-icon.ts
- package.json
- yarn.lock
> fix: upgrade openapi to handle GCP

- libs/pages/application/src/lib/feature/crud-environment-variable-modal-feature/crud-environment-variable-modal-feature.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-908
---
> fix(edit-variable): data values

- libs/shared/ui/src/lib/components/inputs/input-select/input-select.tsx
- libs/shared/ui/src/lib/components/modal/modal.tsx
Prevent z-index war
Related to:
https://github.com/Qovery/console/pull/969/files
https://github.com/Qovery/console/pull/965
> fix(ui): fix z-index conflicts

- libs/domains/services/feature/src/lib/service-details/service-details.tsx
https://qovery.atlassian.net/browse/FRT-912
> fix(services): hide connection URI if DB is private

- libs/pages/events/src/lib/ui/page-general/page-general.spec.tsx
- libs/pages/layout/src/lib/ui/menu-account/menu-account.spec.tsx
- libs/pages/layout/src/lib/ui/menu-account/menu-account.tsx
- libs/pages/services/src/lib/ui/page-settings-deployment-pipeline/page-settings-deployment-pipeline.spec.tsx
- libs/pages/services/src/lib/ui/page-settings-deployment-pipeline/page-settings-deployment-pipeline.tsx
- libs/pages/settings/src/lib/feature/page-organization-members-feature/page-organization-members-feature.spec.tsx
- libs/pages/settings/src/lib/ui/page-organization-members/row-member/row-member.spec.tsx
- libs/shared/console-shared/src/lib/buttons-actions/ui/application-buttons-actions/application-buttons-actions.spec.tsx
- libs/shared/console-shared/src/lib/buttons-actions/ui/cluster-buttons-actions/cluster-buttons-actions.spec.tsx
- libs/shared/console-shared/src/lib/buttons-actions/ui/database-buttons-actions/database-buttons-actions.spec.tsx
- libs/shared/console-shared/src/lib/buttons-actions/ui/environment-buttons-actions/environment-buttons-actions.spec.tsx
- libs/shared/console-shared/src/lib/layout-logs/menu-time-format/menu-time-format.spec.tsx
- libs/shared/ui/src/lib/components/menu/menu.spec.tsx
- libs/shared/ui/src/lib/components/menu/menu.tsx
- libs/shared/ui/src/lib/styles/components/menu.scss
Prevent this issue
And fix corner case like
> fix(ui): remove initial szh-menu z-index

- libs/pages/logs/environment/src/lib/feature/pod-logs-feature/pod-logs-feature.tsx
https://qovery.atlassian.net/browse/FRT-923
---
> fix(pod-logs): allow db container logs

- libs/shared/console-shared/src/lib/layout-logs/placeholder-logs/placeholder-logs.spec.tsx
- libs/shared/console-shared/src/lib/layout-logs/placeholder-logs/placeholder-logs.tsx
update the wording in the placeholder "no live logs available" for managed db
> fix(logs): update wording no logs

- libs/domains/organizations/feature/src/lib/git-token-list/__snapshots__/git-token-list.spec.tsx.snap
- libs/domains/services/feature/src/lib/last-commit/__snapshots__/last-commit.spec.tsx.snap
- libs/domains/services/feature/src/lib/pod-details/__snapshots__/pod-details.spec.tsx.snap
- libs/domains/services/feature/src/lib/service-list/__snapshots__/service-list.spec.tsx.snap
- libs/pages/services/src/lib/feature/page-helm-create-feature/step-general-feature/__snapshots__/step-general-feature.spec.tsx.snap
- libs/shared/ui/src/lib/components/button-primitive/button-primitive.tsx
- libs/shared/ui/src/lib/components/button/__snapshots__/button.spec.tsx.snap
- libs/shared/ui/src/lib/components/button/button.tsx
- Remove `span` and using `text-transparent` 
---
> fix(button):  update loading behavior

- libs/domains/service-helm/feature/src/lib/deployment-setting/__snapshots__/deployment-setting.spec.tsx.snap
- libs/domains/services/feature/src/lib/pod-details/__snapshots__/pod-details.spec.tsx.snap
- libs/domains/services/feature/src/lib/pods-metrics/empty-state.tsx
- libs/domains/services/feature/src/lib/pods-metrics/pods-metrics.spec.tsx
- libs/domains/services/feature/src/lib/pods-metrics/pods-metrics.tsx
- libs/domains/services/feature/src/lib/service-links-popover/__snapshots__/service-links-popover.spec.tsx.snap
- libs/domains/services/feature/src/lib/service-links-popover/service-links-popover.tsx
- libs/pages/application/src/lib/ui/page-general/page-general.tsx
- libs/pages/database/src/lib/ui/page-general/page-general.tsx
- libs/pages/services/src/lib/feature/page-helm-create-feature/step-general-feature/__snapshots__/step-general-feature.spec.tsx.snap
- libs/shared/ui/src/lib/components/help-section/__snapshots__/help-section.spec.tsx.snap
- libs/shared/ui/src/lib/components/link/__snapshots__/link.spec.tsx.snap
- libs/shared/ui/src/lib/components/link/link.tsx
https://qovery.atlassian.net/browse/FRT-921
Prefer "Hide whitespace" for review
> fix(services): fix empty state for jobs

- libs/domains/clusters/data-access/src/lib/domains-clusters-data-access.ts
- libs/domains/clusters/feature/src/index.ts
- libs/domains/clusters/feature/src/lib/hooks/use-cluster-status/use-cluster-status.ts
- libs/domains/clusters/feature/src/lib/hooks/use-cluster-statuses/use-cluster-statuses.ts
- libs/domains/clusters/feature/src/lib/hooks/use-cluster/use-cluster.ts
- libs/domains/clusters/feature/src/lib/hooks/use-clusters/use-clusters.ts
- libs/pages/clusters/src/lib/feature/page-clusters-general-feature/page-clusters-general-feature.tsx
- libs/pages/clusters/src/lib/ui/card-cluster/card-cluster.spec.tsx
- libs/pages/clusters/src/lib/ui/card-cluster/card-cluster.tsx
- libs/pages/clusters/src/lib/ui/page-clusters-general/page-clusters-general.spec.tsx
- libs/pages/clusters/src/lib/ui/page-clusters-general/page-clusters-general.tsx
- libs/pages/environments/src/lib/feature/page-edit-deployment-rule-feature/page-edit-deployment-rule-feature.tsx
- libs/pages/environments/src/lib/feature/page-general-feature/page-general-feature.tsx
- libs/pages/environments/src/lib/page-environments.tsx
- libs/pages/logs/infra/src/lib/feature/card-cluster-feature/card-cluster-feature.tsx
- libs/shared/console-shared/src/lib/layout-logs/card-cluster/card-cluster.spec.tsx
- libs/shared/console-shared/src/lib/layout-logs/card-cluster/card-cluster.tsx
- libs/state/util-queries/src/lib/queries/queries.ts
https://qovery.atlassian.net/browse/FRT-919
> feat(clusters): refactor clusters to use react-query (part 1)

- libs/pages/layout/src/lib/ui/breadcrumb-item/breadcrumb-item.tsx
- libs/shared/ui/src/lib/components/menu/menu.tsx
Fix bug which require 2 click to open a menu
> fix(ui): fix menu opening

- libs/domains/organizations/data-access/src/lib/domains-organizations-data-access.ts
- libs/shared/console-shared/src/lib/cluster-settings/feature/create-edit-credentials-modal-feature/create-edit-credentials-modal-feature.spec.tsx
- libs/shared/console-shared/src/lib/cluster-settings/feature/create-edit-credentials-modal-feature/create-edit-credentials-modal-feature.tsx
- libs/shared/console-shared/src/lib/cluster-settings/ui/create-edit-credentials-modal/create-edit-credentials-modal.spec.tsx
- libs/shared/console-shared/src/lib/cluster-settings/ui/create-edit-credentials-modal/create-edit-credentials-modal.tsx
- package.json
- yarn.lock
https://qovery.atlassian.net/browse/FRT-926
> fix(clusters): add organization id to scaleway auth

- libs/pages/services/src/lib/ui/page-deployments/page-deployments.tsx
- libs/shared/ui/src/lib/components/table/table-row-deployment/table-row-deployment.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1701429563727549
---
> fix(services-deployments): background color

- libs/shared/console-shared/src/lib/buttons-actions/ui/cluster-buttons-actions/cluster-buttons-actions.spec.tsx
- libs/shared/console-shared/src/lib/buttons-actions/ui/cluster-buttons-actions/cluster-buttons-actions.tsx
https://qovery.atlassian.net/browse/FRT-919
https://qovery.slack.com/archives/C02P2JB4SEM/p1701463733783139
> fix(clusters): fix cluster button actions

- apps/console/src/main.tsx
Current `notifyOnSuccess` implementation doesn't forward `onSuccess` parameters so we can't build a notification based on those args. Here is an example where we need that:
```ts
export function useEditClusterAdvancedSettings() {
const queryClient = useQueryClient()
const { mutateAsync: deployCluster } = useDeployCluster()
return useMutation(mutations.editAdvancedSettings, {
onSuccess(_, { organizationId, clusterId }) {
queryClient.invalidateQueries({
queryKey: queries.clusters.advancedSettings({ organizationId, clusterId }).queryKey,
})
},
meta: {
notifyOnSuccess(_: unknown, { organizationId, clusterId }: { organizationId: string; clusterId: string }) {
return {
title: 'Cluster update',
description: 'You must update to apply the settings',
callback() {
deployCluster({ organizationId, …
```
> feat: add support for args in react-query meta

- libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.spec.tsx
- libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/shared/console-shared/src/lib/flow-create-port/utils/port-healthcheck.spec.ts
- libs/shared/console-shared/src/lib/flow-create-port/utils/port-healthcheck.ts
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-913
- Health checks and port can have different protocol (confirmed with Romain)
---
> fix(edit-port): allow health checks editing 

- libs/pages/services/src/lib/ui/page-settings-deployment-pipeline/draggable-item/draggable-item.tsx
https://qovery.atlassian.net/browse/FRT-929
> fix(environments): fix blank deployment pipeline page

- libs/pages/services/src/lib/feature/page-settings-feature/page-settings-feature.tsx
> chore(pipeline-settings): remove "new" badge

- libs/shared/console-shared/src/lib/create-clone-environment-modal/feature/create-clone-environment-modal-feature.spec.tsx
- libs/shared/console-shared/src/lib/create-clone-environment-modal/feature/create-clone-environment-modal-feature.tsx
- libs/shared/console-shared/src/lib/create-clone-environment-modal/ui/create-clone-environment-modal.tsx
https://qovery.atlassian.net/browse/FRT-938
> feat(environments): remove automatic option from environment creation clone modal

- libs/pages/services/src/lib/ui/page-application-create/step-summary/step-summary.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1702319153855609
---
> fix(application-summary): truncate long arguments

- libs/domains/services/feature/src/lib/pod-details/__snapshots__/pod-details.spec.tsx.snap
- libs/domains/services/feature/src/lib/pod-details/pod-details.spec.tsx
- libs/domains/services/feature/src/lib/pod-details/pod-details.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1702371266996299
https://qovery.slack.com/archives/C02P2JB4SEM/p1702371758272569
---
> fix(pod-details): displaying name

- libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.spec.tsx
- libs/pages/logs/environment/src/lib/feature/deployment-logs-feature/deployment-logs-feature.tsx
- libs/pages/logs/environment/src/lib/feature/pod-logs-feature/pod-logs-feature.tsx
- libs/pages/logs/environment/src/lib/page-environment-logs.tsx
- libs/pages/logs/environment/src/lib/ui/deployment-logs/deployment-logs.tsx
- libs/pages/logs/environment/src/lib/ui/pod-logs/pod-logs.tsx
- libs/pages/logs/environment/src/lib/ui/sidebar-pipeline-item/sidebar-pipeline-item.tsx
- libs/pages/logs/environment/src/lib/ui/sidebar-pipeline/sidebar-pipeline.tsx
- libs/pages/logs/environment/src/lib/ui/sidebar/sidebar.tsx
- libs/pages/services/src/lib/feature/page-settings-deployment-pipeline-feature/page-settings-deployment-pipeline-feature.tsx
- libs/pages/services/src/lib/ui/page-settings-deployment-pipeline/draggable-item/draggable-item.spec.tsx
- libs/pages/services/src/lib/ui/page-settings-deployment-pipeline/draggable-item/draggable-item.tsx
- libs/pages/services/src/lib/ui/page-settings-deployment-pipeline/page-settings-deployment-pipeline.tsx
- libs/shared/console-shared/src/lib/layout-logs/layout-logs.tsx
- libs/shared/factories/src/lib/application-factory.mock.ts
- libs/shared/factories/src/lib/database-factory.mock.ts
- libs/shared/ui/src/lib/components/icon/icon.stories.tsx
- libs/shared/ui/src/lib/components/service-icon/service-icon.spec.tsx
- libs/shared/ui/src/lib/components/service-icon/service-icon.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-945
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-946
- Added React Query services for Logs and Deployment pipeline
- Missing HELM dark icon (waiting Yael) I'll made another PR for this change
---
> feat(helm): add logs and deployment pipeline

- libs/domains/cloud-providers/data-access/src/lib/domains-cloud-providers-data-access.ts
- libs/domains/clusters/feature/src/lib/cluster-type/cluster-type.tsx
- package.json
- yarn.lock
Add support of AWS self-managed cloud provider
> fix(cloud-providers): fix AWS self managed

- libs/pages/logs/environment/src/lib/feature/pod-logs-feature/pod-logs-feature.tsx
https://qovery.slack.com/archives/C038JMN9GUE/p1702570672709349
---
> fix(pod-logs): enabled ws logs

- libs/shared/ui/src/lib/components/dropdown-menu/dropdown-menu.stories.tsx
- libs/shared/ui/src/lib/components/dropdown-menu/dropdown-menu.tsx
- libs/shared/ui/src/lib/components/menu/menu.tsx
- tailwind-workspace-preset.js
> feat(dropdown-menu): add new component

- libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
- libs/pages/application/src/lib/ui/page-settings-general/page-settings-general.tsx
- Fix Job container general settings
---
> fix(job-general-settings): container settings

- libs/pages/services/src/lib/feature/page-helm-create-feature/step-summary-feature/step-summary-feature.spec.tsx
- libs/pages/services/src/lib/feature/page-helm-create-feature/step-summary-feature/step-summary-feature.tsx
https://qovery.atlassian.net/browse/FRT-950
> fix(helm): fix summary step

- libs/shared/console-shared/src/lib/cluster-settings/ui/cluster-resources-settings/cluster-resources-settings.tsx
https://qovery.atlassian.net/browse/FRT-948
> fix(clusters): fix warning display

- libs/shared/ui/src/lib/components/table/table-row-deployment/table-row-deployment.tsx
https://qovery.atlassian.net/browse/FRT-943
> fix(logs): fix environment deployment logs links

- libs/shared/console-shared/src/lib/create-clone-environment-modal/feature/create-clone-environment-modal-feature.tsx
https://qovery.atlassian.net/browse/FRT-944
> feat(env): add default values for create-clone env modal

- libs/domains/services/feature/src/lib/service-links-popover/service-links-popover.tsx
> fix(helm): service links popover hide customize

- libs/pages/services/src/lib/ui/container/container.tsx
- Available environment actions with React Query for services
---
> fix(services): environment actions with react query

- libs/shared/ui/src/lib/components/table/table-row-deployment/table-row-deployment.tsx
- libs/shared/util-js/src/lib/merge-deployment-services.spec.ts
- libs/shared/util-js/src/lib/merge-deployment-services.ts
- package.json
- yarn.lock
> feat(helm): add deployment history with chart version

- libs/pages/services/src/lib/feature/page-helm-create-feature/step-summary-feature/step-summary-feature.tsx
- Add create and deploy action
---
> feat(helm): creation flow add create and deploy

- libs/pages/application/src/lib/feature/crud-environment-variable-modal-feature/crud-environment-variable-modal-feature.tsx
- libs/pages/application/src/lib/feature/import-environment-variable-modal-feature/import-environment-variable-modal-feature.tsx
- libs/pages/application/src/lib/feature/page-variables-feature/page-variables-feature.tsx
- libs/pages/application/src/lib/feature/table-row-environment-variable-feature/table-row-environment-variable-feature.tsx
- libs/pages/application/src/lib/feature/tabs-feature/tabs-feature.tsx
- libs/pages/application/src/lib/ui/import-environment-variable-modal/import-environment-variable-modal.tsx
- libs/pages/application/src/lib/ui/page-variables/page-variables.tsx
- libs/shared/util-js/src/lib/compute-available-environment-variable-scope.ts
> feat(helm): add variables

- libs/domains/service-helm/feature/src/lib/networking-setting/networking-setting.tsx
- libs/domains/service-helm/feature/src/lib/values-override-files-setting/__snapshots__/values-override-files-setting.spec.tsx.snap
- libs/domains/service-helm/feature/src/lib/values-override-files-setting/values-override-files-setting.tsx
- libs/pages/services/src/lib/feature/page-helm-create-feature/step-general-feature/__snapshots__/step-general-feature.spec.tsx.snap
- libs/pages/services/src/lib/feature/page-helm-create-feature/step-general-feature/step-general-feature.tsx
- libs/pages/services/src/lib/feature/page-helm-create-feature/step-networking-feature/step-networking-feature.tsx
- libs/pages/services/src/lib/feature/page-helm-create-feature/step-values-override-files-feature/__snapshots__/step-values-override-files-feature.spec.tsx.snap
- libs/pages/services/src/lib/feature/page-helm-create-feature/step-values-override-files-feature/step-values-override-files-feature.tsx
- update the text to reflect what's in figma
- fix some link
---
> chore(helm): update text and links for helm

- libs/pages/application/src/lib/feature/page-general-feature/page-general-feature.tsx
- libs/pages/application/src/lib/ui/page-settings-general/page-settings-general.tsx
- Overview
- General settings
---
> chore(helm): update documentation links

- libs/domains/service-helm/feature/src/lib/values-override-files-setting/values-override-files-setting.tsx
- libs/pages/application/src/lib/feature/page-settings-values-override-file-feature/page-settings-values-override-file-feature.tsx
- libs/shared/ui/src/lib/components/inputs/input-select/input-select.tsx
- package.json
- yarn.lock
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-959
---
> fix(helm-values-override): default git repository value

- .github/workflows/test-build-and-deploy-to-qovery.yml
- .github/workflows/test-build-and-deploy-to-s3.yml
> ci: improve upload artifact speed

- libs/pages/application/src/lib/feature/page-settings-values-override-arguments-feature/page-settings-values-override-arguments-feature.tsx
- Fix override when we update values as arguments
---
> fix(helm-values-override): remove override file values

- libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-966
---
> feat(service-action-toolbar): add cancel deployment

- libs/domains/services/data-access/src/lib/domains-services-data-access.ts
- libs/domains/services/feature/src/lib/advanced-settings/advanced-settings.spec.tsx
- libs/domains/services/feature/src/lib/hooks/use-last-deployed-commit/use-last-deployed-commit.tsx
- libs/shared/enums/src/lib/utils/get-service-type.ts
- libs/shared/util-services/src/lib/build-edit-service-payload.ts
- package.json
- yarn.lock
https://qovery.atlassian.net/browse/FRT-954
> feat(service): prepare helm deploy other version

- libs/pages/application/src/lib/feature/import-environment-variable-modal-feature/utils/handle-submit.tsx
https://qovery.atlassian.net/browse/FRT-971
Boolean value aren't "trimable" so we must add fallback
> fix(services): fix .env file import with secret

- libs/domains/services/feature/src/lib/service-action-toolbar/__snapshots__/service-action-toolbar.spec.tsx.snap
- libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1704295126373399
---
> fix(service-action-toolbar): copy identifier

- libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.spec.tsx
- libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-ports-feature/page-settings-ports-feature.tsx
- libs/shared/console-shared/src/lib/flow-create-port/ui/flow-create-port/flow-create-port.tsx
> feat(services): migrate ports react query

- libs/domains/services/feature/src/lib/hooks/use-edit-service/use-edit-service.ts
- libs/pages/services/src/lib/feature/page-settings-preview-environments-feature/page-settings-preview-environments-feature.spec.tsx
- libs/pages/services/src/lib/feature/page-settings-preview-environments-feature/page-settings-preview-environments-feature.tsx
- libs/pages/services/src/lib/ui/page-settings-preview-environments/page-settings-preview-environments.spec.tsx
- libs/pages/services/src/lib/ui/page-settings-preview-environments/page-settings-preview-environments.tsx
> feat(services): migrate preview env react query 

- libs/shared/ui/src/lib/components/service-icon/service-icon.stories.tsx
> fix(ui): fix service icon stories

- libs/shared/ui/src/lib/components/action-toolbar/action-toolbar.stories.tsx
> fix(ui): fix action-toolbar stories

- libs/shared/ui/src/lib/components/action-toolbar/action-toolbar.stories.tsx
- libs/shared/ui/src/lib/components/header/header.stories.tsx
- libs/shared/ui/src/lib/components/service-icon/service-icon.stories.tsx
> fix(ui): fix header stories

- libs/domains/service-helm/feature/src/lib/networking-setting/networking-setting.spec.tsx
- libs/domains/service-helm/feature/src/lib/networking-setting/networking-setting.tsx
https://qovery.atlassian.net/browse/FRT-956
> fix(services): add helm remove port confirmation

- libs/pages/application/src/lib/feature/page-settings-healthchecks-feature/page-settings-healthchecks-feature.spec.tsx
- libs/pages/application/src/lib/feature/page-settings-healthchecks-feature/page-settings-healthchecks-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-ports-feature/page-settings-ports-feature.tsx
- libs/pages/application/src/lib/ui/page-settings-healthchecks/page-settings-healthchecks.tsx
> feat(services): migrate healthchecks react query

- Storybook
Update node version for yarn 2.0
---
> chore: storybook update node version dockerfile

- libs/pages/application/src/lib/feature/page-settings-configure-job-feature/page-settings-configure-job-feature.spec.tsx
- libs/pages/application/src/lib/feature/page-settings-configure-job-feature/page-settings-configure-job-feature.tsx
- libs/pages/application/src/lib/ui/page-settings-configure-job/page-settings-configure-job.spec.tsx
- libs/pages/application/src/lib/ui/page-settings-configure-job/page-settings-configure-job.tsx
- libs/shared/factories/src/lib/job-factory.mock.ts
> feat(services): migrate configure job setting react query

- libs/pages/application/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.spec.tsx
- libs/pages/application/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx
- libs/pages/application/src/lib/ui/page-settings-resources/page-settings-resources.spec.tsx
- libs/pages/application/src/lib/ui/page-settings-resources/page-settings-resources.tsx
- libs/pages/services/src/lib/feature/page-application-create-feature/step-resources-feature/step-resources-feature.tsx
- libs/pages/services/src/lib/feature/page-job-create-feature/step-resources-feature/step-resources-feature.tsx
- libs/pages/services/src/lib/ui/page-application-create/step-resources/step-resources.tsx
- libs/pages/services/src/lib/ui/page-job-create/step-resources/step-resources.tsx
- libs/shared/console-shared/src/lib/application-settings/ui/application-settings-resources/application-settings-resources.spec.tsx
- libs/shared/console-shared/src/lib/application-settings/ui/application-settings-resources/application-settings-resources.tsx
> feat(services): migrate resources setting react query

- libs/pages/application/src/lib/feature/page-settings-storage-feature/page-settings-storage-feature.spec.tsx
- libs/pages/application/src/lib/feature/page-settings-storage-feature/page-settings-storage-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-storage-feature/storage-modal-feature/storage-modal-feature.spec.tsx
- libs/pages/application/src/lib/feature/page-settings-storage-feature/storage-modal-feature/storage-modal-feature.tsx
- libs/shared/util-services/src/lib/build-edit-service-payload.ts
> feat(services): migrate storage setting react query

- libs/domains/services/data-access/src/lib/domains-services-data-access.ts
- libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx
- libs/shared/console-shared/src/lib/force-run-modal/feature/force-run-modal-feature.spec.tsx
- libs/shared/console-shared/src/lib/force-run-modal/feature/force-run-modal-feature.tsx
- libs/shared/console-shared/src/lib/force-run-modal/ui/force-run-modal.spec.tsx
- libs/shared/console-shared/src/lib/force-run-modal/ui/force-run-modal.tsx
- libs/shared/ui/src/lib/components/modals/modal-crud/modal-crud.tsx
> feat(services): migrate force run job react query

- libs/pages/clusters/src/lib/ui/page-clusters-create/step-general/step-general.tsx
> feat(cluster): enable GCP

- libs/pages/clusters/src/lib/feature/page-clusters-create-feature/page-clusters-create-feature.tsx
- libs/pages/clusters/src/lib/ui/page-clusters-create/step-general/step-general.tsx
> feat(GCP): add warning in the creation flow

- libs/domains/services/data-access/src/lib/domains-services-data-access.ts
- libs/domains/services/feature/src/lib/hooks/use-custom-domains/use-custom-domains.ts
- libs/domains/services/feature/src/lib/pod-statuses-callout/pod-statuses-callout.tsx
- libs/pages/application/src/lib/feature/page-settings-domains-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-domains-feature/page-settings-domains-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-feature/page-settings-feature.tsx
- package.json
- yarn.lock
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-936
---
> feat(helm): add custom domain setting

- libs/shared/console-shared/src/lib/cluster-settings/feature/create-edit-credentials-modal-feature/create-edit-credentials-modal-feature.spec.tsx
- libs/shared/console-shared/src/lib/cluster-settings/ui/create-edit-credentials-modal/create-edit-credentials-modal.spec.tsx
- libs/shared/console-shared/src/lib/cluster-settings/ui/create-edit-credentials-modal/create-edit-credentials-modal.tsx
- libs/shared/ui/src/lib/components/dropzone/dropzone.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-965
---
> feat(cluster-credential): upload file field for GCP

- libs/domains/service-helm/feature/src/lib/values-override-arguments-setting/__snapshots__/values-override-arguments-setting.spec.tsx.snap
- libs/domains/service-helm/feature/src/lib/values-override-arguments-setting/values-override-arguments-setting.tsx
- libs/domains/service-helm/feature/src/lib/values-override-files-setting/__snapshots__/values-override-files-setting.spec.tsx.snap
- libs/domains/service-helm/feature/src/lib/values-override-files-setting/values-override-files-setting.tsx
- libs/pages/application/src/lib/feature/page-settings-values-override-arguments-feature/page-settings-values-override-arguments-feature.tsx
- libs/pages/services/src/lib/feature/page-helm-create-feature/step-values-override-arguments-feature/step-values-override-arguments-feature.tsx
- libs/pages/services/src/lib/feature/page-helm-create-feature/step-values-override-files-feature/__snapshots__/step-values-override-files-feature.spec.tsx.snap
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-967
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-980
---
> feat(helm): update default button for values override

- libs/pages/database/src/lib/ui/page-settings-general/page-settings-general.tsx
- libs/pages/services/src/lib/feature/page-database-create-feature/step-general-feature/step-general-feature.tsx
- libs/pages/services/src/lib/ui/page-database-create/step-general/step-general.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-955
---
> feat(database-mode): default select for SCW and GCP

- libs/pages/services/src/lib/feature/page-job-create-feature/step-summary-feature/step-summary-feature.tsx
https://qovery.atlassian.net/browse/FRT-984
> fix(services): fix wrong service type

- libs/domains/service-helm/feature/src/lib/values-override-files-setting/values-override-files-setting.tsx
- libs/pages/application/src/lib/feature/page-settings-values-override-file-feature/page-settings-values-override-file-feature.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-979
---
> fix(helm-override-yaml): setting submit directly on the modal

- libs/pages/application/src/lib/feature/page-settings-ports-feature/crud-modal-feature/crud-modal-feature.tsx
- libs/pages/application/src/lib/feature/page-settings-ports-feature/page-settings-ports-feature.tsx
https://discuss.qovery.com/t/cannot-modify-application-port-settings/2317/2
---
> fix(setting-ports): add buildEditServicePayload edit service request

- libs/pages/application/src/lib/ui/page-deployments/page-deployments.spec.tsx
- libs/pages/application/src/lib/ui/page-deployments/page-deployments.tsx
- libs/pages/services/src/lib/feature/page-deployments-feature/page-deployments-feature.tsx
- libs/pages/services/src/lib/ui/page-deployments/page-deployments.spec.tsx
- libs/pages/services/src/lib/ui/page-deployments/page-deployments.tsx
> fix(deployment): add empty state

- libs/domains/services/feature/src/lib/advanced-settings/advanced-settings.spec.tsx
- libs/domains/services/feature/src/lib/pod-details/__snapshots__/pod-details.spec.tsx.snap
- libs/domains/services/feature/src/lib/pod-details/pod-details.tsx
https://qovery.atlassian.net/browse/FRT-875
> feat(services): add icons to pod details

- libs/shared/console-shared/src/lib/cluster-settings/ui/create-edit-credentials-modal/create-edit-credentials-modal.tsx
https://qovery.slack.com/archives/C05D9LSFRRQ/p1705256902827929
---
> fix(cluster-credential): GCP upload file

- libs/pages/logs/environment/src/lib/feature/deployment-logs-feature/deployment-logs-feature.tsx
- libs/pages/logs/environment/src/lib/ui/deployment-logs/deployment-logs.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-974
---
> feat(deployment-logs): add load previous logs button

- libs/domains/services/data-access/src/lib/domains-services-data-access.ts
- libs/domains/services/feature/src/lib/hooks/use-commits/use-commits.ts
- libs/domains/services/feature/src/lib/hooks/use-last-deployed-commit/use-last-deployed-commit.tsx
- libs/domains/services/feature/src/lib/select-commit-modal/select-commit-modal.tsx
- libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx
https://qovery.atlassian.net/browse/FRT-986
> fix(helm): fix helm deploy another version values

- libs/domains/services/feature/src/lib/pods-metrics/__snapshots__/pods-metrics.spec.tsx.snap
- libs/domains/services/feature/src/lib/pods-metrics/pods-metrics.tsx
https://qovery.atlassian.net/browse/FRT-963
> feat(services): add copytoclipboard to pod name

- libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx
https://app.logrocket.com/msuoxn/console-v3/issue/624708290?issueType=EXCEPTION
> fix: add optionnal chaining when no clusters

- libs/domains/services/feature/src/lib/service-links-popover/__snapshots__/service-links-popover.spec.tsx.snap
- libs/domains/services/feature/src/lib/service-links-popover/service-links-popover.tsx
- libs/domains/services/feature/src/lib/service-list/__snapshots__/service-list.spec.tsx.snap
- libs/domains/services/feature/src/lib/service-list/service-list.tsx
https://qovery.atlassian.net/browse/FRT-906
> feat(services): improve service link popover behavior

- libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1705496761998019
---
> fix(service-action-toolbar): open settings for database

- libs/pages/services/src/lib/feature/page-helm-create-feature/step-general-feature/step-general-feature.tsx
- libs/pages/services/src/lib/ui/page-application-create/step-general/step-general.tsx
- libs/pages/services/src/lib/ui/page-job-create/step-general/step-general.tsx
https://qovery.atlassian.net/browse/FRT-989
> fix(services): prevent exception when git settings aren't completed

- libs/shared/console-shared/src/lib/flow-create-port/ui/crud-modal/crud-modal.tsx
https://qovery.atlassian.net/browse/FRT-988
> feat(services): enable TCP/UDP port for GCP

- libs/domains/clusters/feature/src/lib/cluster-installation-guide-modal/cluster-installation-guide-modal.tsx
https://qovery.atlassian.net/browse/FRT-992
> feat(clusters): revamp installation guide modal

- libs/pages/cluster/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.spec.tsx
- libs/pages/database/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.spec.tsx
- libs/pages/database/src/lib/ui/page-settings-general/page-settings-general.spec.tsx
- libs/pages/services/src/lib/ui/page-application-create/step-resources/step-resources.spec.tsx
- libs/shared/console-shared/src/lib/application-settings/ui/application-settings-resources/application-settings-resources.tsx
- libs/shared/console-shared/src/lib/database-settings-resources/ui/database-settings-resources/database-settings-resources.tsx
https://qovery.atlassian.net/browse/FRT-982
> feat(services): add checks on vCPU/Memory

- libs/pages/application/src/lib/feature/page-settings-storage-feature/storage-modal-feature/storage-modal-feature.tsx
https://qovery.atlassian.net/browse/FRT-994
> fix(services): fix missing onClose modal

- libs/domains/services/feature/src/lib/select-commit-modal/__snapshots__/select-commit-modal.spec.tsx.snap
- libs/pages/cluster/src/lib/feature/page-settings-feature/page-settings-feature.tsx
- libs/pages/cluster/src/lib/feature/page-settings-general-feature/page-settings-general-feature.spec.tsx
- libs/pages/cluster/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
- libs/pages/cluster/src/lib/ui/page-settings-general/page-settings-general.spec.tsx
- libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-general-feature/step-general-feature.tsx
- libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-summary-feature/step-summary-feature.spec.tsx
- libs/pages/clusters/src/lib/feature/page-clusters-create-feature/step-summary-feature/step-summary-feature.tsx
- libs/pages/clusters/src/lib/ui/page-clusters-create/step-general/step-general.tsx
- libs/pages/clusters/src/lib/ui/page-clusters-create/step-kubeconfig/__snapshots__/step-kubeconfig.spec.tsx.snap
- libs/pages/clusters/src/lib/ui/page-clusters-create/step-kubeconfig/step-kubeconfig.tsx
- libs/shared/ui/src/lib/components/radio-group/radio-group.stories.tsx
- libs/shared/ui/src/lib/components/radio-group/radio-group.tsx
https://qovery.atlassian.net/browse/FRT-961
> feat(clusters): enable self-managed creation flow

- libs/domains/clusters/feature/src/lib/hooks/use-clusters/use-clusters.ts
- libs/domains/environments/feature/src/lib/hooks/use-environments/use-environments.ts
- libs/domains/services/feature/src/lib/hooks/use-services/use-services.ts
https://qovery.atlassian.net/browse/FRT-1005
> feat: improve listing order

- libs/pages/logs/environment/src/lib/ui/sidebar-pipeline-item/sidebar-pipeline-item.tsx
https://qovery.atlassian.net/browse/FRT-1006
> fix(ui): fix sidebar pipeline alignment

- libs/pages/clusters/src/lib/ui/card-cluster/card-cluster.tsx
https://qovery.atlassian.net/browse/FRT-997
> feat(clusters): hide instance type if undefined

- libs/domains/cloud-providers/feature/src/lib/hooks/use-cloud-provider-features/use-cloud-provider-features.ts
- libs/pages/clusters/src/lib/ui/page-clusters-create/step-general/step-general.tsx
https://qovery.atlassian.net/browse/FRT-1008
> fix(clusters): fix creation flow issues

- libs/pages/settings/src/lib/feature/page-organization-github-repository-access-feature/page-organization-github-repository-access-feature.tsx
- libs/pages/settings/src/lib/ui/page-organization-github-repository-access/page-organization-github-repository-access.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-995
---
> chore: git token title wording

- libs/domains/clusters/feature/src/lib/cluster-action-toolbar/cluster-action-toolbar.tsx
- libs/domains/clusters/feature/src/lib/cluster-delete-modal/cluster-delete-modal.spec.tsx
- libs/domains/clusters/feature/src/lib/cluster-delete-modal/cluster-delete-modal.tsx
- libs/pages/cluster/src/lib/feature/page-settings-danger-zone-feature/page-settings-danger-zone-feature.tsx
https://qovery.atlassian.net/browse/FRT-996
> feat(clusters): update self-managed delete options

- libs/shared/ui/src/lib/components/buttons/button-icon/button-icon.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-857
---
> feat(navigation): cluster error indicator position

- libs/domains/clusters/feature/src/lib/cluster-action-toolbar/cluster-action-toolbar.tsx
- libs/domains/environments/feature/src/lib/environment-action-toolbar/environment-action-toolbar.tsx
- libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx
- libs/pages/layout/src/lib/ui/breadcrumb/breadcrumb.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1707905388089919
---
> fix(layout-logs): close logs behavior with state routing

- libs/domains/environments/feature/src/lib/hooks/use-environments/use-environments.ts
- libs/domains/projects/feature/src/lib/hooks/use-projects/use-projects.ts
- libs/pages/layout/src/lib/feature/breadcrumb/breadcrumb.tsx
https://qovery.slack.com/archives/C02P2JB4SEM/p1707993040787149
---
> fix(cluster): remove project and environment requests

- libs/domains/services/feature/src/lib/pod-details/__snapshots__/pod-details.spec.tsx.snap
- libs/domains/services/feature/src/lib/pod-details/pod-details.tsx
- libs/pages/logs/environment/src/lib/feature/pod-logs-feature/pod-logs-feature.tsx
- libs/pages/logs/environment/src/lib/ui/pod-logs/pod-logs.spec.tsx
- libs/pages/logs/environment/src/lib/ui/pod-logs/pod-logs.tsx
- libs/shared/routes/src/lib/sub-router/logs.router.ts
- libs/shared/ui/src/lib/components/table/table-head-filter/table-head-filter.tsx
https://qovery.atlassian.net/browse/FRT-865
> feat(logs): add filter by pod in logs url

- package.json
https://qovery.slack.com/archives/C02P2JB4SEM/p1708504766592759
---
> chore: update setup cmd

- libs/pages/cluster/src/lib/ui/page-settings-features/page-settings-features.tsx
https://qovery.atlassian.net/browse/FRT-1025
Follows https://github.com/Qovery/console/pull/1160
> feat(clusters): hide vpc settings for now

- libs/domains/services/feature/src/lib/service-details/service-details.tsx
- libs/domains/services/feature/src/lib/service-list/__snapshots__/service-list.spec.tsx.snap
- libs/domains/services/feature/src/lib/service-list/service-list.tsx
https://qovery.atlassian.net/browse/FRT-1020
> feat(services): reword version and commit

- libs/domains/services/feature/src/lib/select-commit-modal/__snapshots__/select-commit-modal.spec.tsx.snap
- libs/domains/services/feature/src/lib/select-commit-modal/select-commit-modal.tsx
https://qovery.atlassian.net/browse/FRT-640
> feat(services): apply latest design on deploy other version

- libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx
https://qovery.atlassian.net/browse/FRT-1022
> fix(clusters): fix installation banner

- libs/domains/services/feature/src/lib/service-links-popover/__snapshots__/service-links-popover.spec.tsx.snap
- libs/domains/services/feature/src/lib/service-links-popover/service-links-popover.tsx
https://qovery.atlassian.net/browse/FRT-1023
> fix(ui): add overflow scroll with too many links

- libs/pages/application/src/lib/ui/table-row-environment-variable/table-row-environment-variable.tsx
https://qovery.atlassian.net/browse/FRT-739
> feat(services): hide variable value if alias

- .github/workflows/test-build-and-deploy.yml
- apps/console/src/app/app.tsx
https://qovery.atlassian.net/browse/FRT-1026
> chore: add logrocket release

- libs/pages/clusters/src/lib/ui/page-clusters-create/step-general/step-general.tsx
https://qovery.atlassian.net/browse/FRT-1012
> feat(clusters): add "Which should I chose"

- libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
https://qovery.atlassian.net/browse/FRT-1027
> fix(services): add missing git_token_id param

- libs/pages/application/src/lib/feature/page-settings-general-feature/page-settings-general-feature.tsx
- libs/pages/services/src/lib/feature/page-helm-create-feature/step-general-feature/step-general-feature.tsx
https://qovery.atlassian.net/browse/FRT-1030
> fix(helm): handle invalid arguments gracefully

- libs/pages/cluster/src/lib/ui/page-settings-features/page-settings-features.spec.tsx
- libs/pages/cluster/src/lib/ui/page-settings-features/page-settings-features.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1002
---
> feat(cluster-detail): feature VPC

- libs/domains/service-helm/feature/src/lib/values-override-arguments-setting/__snapshots__/values-override-arguments-setting.spec.tsx.snap
- libs/domains/service-helm/feature/src/lib/values-override-arguments-setting/values-override-arguments-setting.spec.tsx
- libs/domains/service-helm/feature/src/lib/values-override-arguments-setting/values-override-arguments-setting.tsx
- libs/domains/service-helm/feature/src/lib/values-override-files-setting/__snapshots__/values-override-files-setting.spec.tsx.snap
- libs/domains/service-helm/feature/src/lib/values-override-files-setting/values-override-files-setting.tsx
- libs/pages/application/src/lib/feature/page-settings-values-override-arguments-feature/page-settings-values-override-arguments-feature.tsx
- libs/pages/services/src/lib/feature/page-helm-create-feature/step-summary-feature/step-summary-feature.spec.tsx
- libs/pages/services/src/lib/feature/page-helm-create-feature/step-summary-feature/step-summary-feature.tsx
- libs/pages/services/src/lib/feature/page-helm-create-feature/step-values-override-files-feature/__snapshots__/step-values-override-files-feature.spec.tsx.snap
Updated the wording on both the help section and the field naming (use helm naming convention)
---
> chore: update text on helm override params section

- libs/pages/settings/src/lib/ui/page-organization-billing-summary/page-organization-billing-summary.spec.tsx
- libs/pages/settings/src/lib/ui/page-organization-billing-summary/page-organization-billing-summary.tsx
- libs/shared/ui/src/lib/components/status-chip/status-chip.tsx
- package.json
- yarn.lock
https://qovery.atlassian.net/browse/FRT-1032
> feat(services): add missing RECAP deployment status

- libs/pages/services/src/lib/feature/page-database-create-feature/step-general-feature/step-general-feature.spec.tsx
- libs/pages/services/src/lib/feature/page-database-create-feature/step-general-feature/step-general-feature.tsx
- libs/pages/services/src/lib/ui/page-database-create/step-general/step-general.tsx
- libs/shared/util-types/src/lib/shared-util-types.ts
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1002
---
> feat(database): filter db type by cluster vpc setup

- libs/domains/variables/feature/src/lib/output-variables/__snapshots__/output-variables.spec.tsx.snap
- libs/domains/variables/feature/src/lib/output-variables/output-variables.tsx
- libs/pages/application/src/lib/ui/table-row-environment-variable/table-row-environment-variable.tsx
- libs/shared/ui/src/lib/components/password-show-hide/password-show-hide.spec.tsx
- libs/shared/ui/src/lib/components/password-show-hide/password-show-hide.tsx
https://qovery.atlassian.net/browse/FRT-1021
> refactor(variables): align variables design with figma

- libs/domains/clusters/feature/src/lib/cluster-action-toolbar/__snapshots__/cluster-action-toolbar.spec.tsx.snap
- libs/domains/clusters/feature/src/lib/cluster-action-toolbar/cluster-action-toolbar.tsx
- libs/domains/environments/feature/src/lib/environment-action-toolbar/__snapshots__/environment-action-toolbar.spec.tsx.snap
- libs/domains/environments/feature/src/lib/environment-action-toolbar/environment-action-toolbar.tsx
- libs/domains/services/feature/src/lib/service-action-toolbar/__snapshots__/service-action-toolbar.spec.tsx.snap
- libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx
- libs/shared/ui/src/lib/components/action-toolbar/action-toolbar.stories.tsx
- libs/shared/ui/src/lib/components/action-toolbar/action-toolbar.tsx
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1029
---
> fix(toolbar-actions): update ui size
